### ISSUE TITLE
Contact Form: add validator for email field

### ISSUE THREAD

**Issue by ksuess** [plone/volto#1005]
![Contact_form](https://user-images.githubusercontent.com/1144737/68596724-f8de9480-049b-11ea-9066-0e9f762198bf.jpg)

**Comment by sumukhah** [comment]
Hello <b>@ksuess</b>
I am not able to reproduce the error,
Can you give me some brief information regarding the error?
thank you :smiley:

**Comment by ksuess** [comment]
That's old stuff.
You cannot reproduce the error? Fine. I close this issue.
