### ISSUE TITLE
ON creation of a page the behavior for volto editor needs to be added

### ISSUE THREAD

**Issue by bloodbare** [plone/volto#1019]
On guillotina_cms at POST creation the behavior that is used to store the blocks editor information (layout and blocks) was added by default on the page as a default Behavior. We are changing it so there is no default Editor behavior applied to the document. In order to maintain the same behavior you need to send on the creation call:

```
POST 
{
  "@type": "Document",
  "id": "id1",
  "@behaviors": ["guillotina_cms.interfaces.blocks.IBlocks"],
  "guillotina_cms.interfaces.blocks.IBlocks": {
    ...
  }
}
```

**Comment by sneridagh** [comment]
@robgietema is time for make Volto Guillotina/Plone aware for this kind of things. Let's talk it at the sprint.

**Comment by sneridagh** [comment]
@bloodbare fixed in master.

**Comment by bloodbare** [comment]
@sneridagh fixed or skiped ?

**Comment by sneridagh** [comment]
@bloodbare https://github.com/plone/volto/blob/master/g-api/docker-compose.yml#L10

using the old docker image build for now, waiting for the sprint to know what we do.

**Comment by bloodbare** [comment]
Yups I mean the issue is not fixed in master, the solution is skipped until sprint!

**Comment by sneridagh** [comment]
Closing, since solved in master which is using already G6 thanks to https://github.com/plone/guillotina-volto
