### ISSUE TITLE
video block: typing in a "wrong" URL leads to error

### ISSUE THREAD

**Issue by steffenri** [plone/volto#1021]
steps to reproduce:
1) go to your local volto build (or https://volto.kitconcept.com/)
2) create a new video block
3) type in an URL which does not lead to a video (can also type in anything you want which is not a correct link)
-> error message:
-> expected: some message that the link you typed in does not refer to a video or does not exist.

Sorry, something went wrong with your request 
Cannot read property '1' of null

    in t
    in InjectIntl(t)
    in div
    in t
    in DragSource(t)
    in DropTarget(DragSource(t))
    in div
    in t
    in InjectIntl(t)
    in div
    in t
    in p
    in InjectIntl(Connect(t))
    in DragDropContext(InjectIntl(Connect(t)))
    in t
    in t
    in main
    in div
    in v
    in n
    in p
    in p
    in t
    in t
    in t
    in r
    in Y
    in p
    in t
    in withRouter(Connect(Y))
    in t
    in t
    in withRouter(t)
    in t
    in n
    in r
    in p
    in IntlProvider
    in p
    in t
    in s

**Comment by wkbkhard** [comment]
WIP while working on #1037
