### ISSUE TITLE
changing listing preferences has no effect in the content menu

### ISSUE THREAD

**Issue by steffenri** [plone/volto#1035]
steps to reproduce
1) go to your local volto build content menu (or volto.kitconcept.com/contents
sort elements by creation date or any other setting
-> has no impact on the listing
-> expected: elements should get reordered depended on your settings
![listingorder](https://user-images.githubusercontent.com/54619639/70127978-638a8680-167c-11ea-8b7f-9dbe8c938fb9.png)

**Comment by tisto** [comment]
@iFlameing pls check the functionality and write a Cypress test for it.

**Comment by iFlameing** [comment]
@steffenri @tisto I tested in my current local environment and it is working fine :)
