### ISSUE TITLE
File content type

### ISSUE THREAD

**Issue by tisto** [plone/volto#1036]
Standard Plone behavior for file types (similar to the Link type functionality, see #877):

1) File opens directly for anonymous users
2) Editors see the file view to being able to edit an existing file

This should also work if a file content object is linked within the body text of an existing Volto page.

**Comment by sneridagh** [comment]
@tisto The file feature requires some addition in p.restapi which @csenger was working with Rob during the last sprint, and is still in progress.

**Comment by sneridagh** [comment]
https://github.com/plone/volto/pull/1050
