### ISSUE TITLE
Listing Tile - relative path

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#1059]
if i set a 'Location' criteria as 'relative path' in listing block, nothing changes in results, and the cypress test fails

**Comment by steffenri** [comment]
the results dont change in 'absolute path' and 'navigation path' either. the whole path criteria is not working properly.

**Comment by pnicolli** [comment]
This is still valid for relative path search with latest commit in #747 ('listing-tile' branch). Absolute path works now.

**Comment by pnicolli** [comment]
Fixed in branch 'listing-tile' (see #747 )
