### ISSUE TITLE
ToHTML: unstyled error in view for multiline-filed

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#1061]
There's a 'unique key' error in view when  rendering multiline textfield. 
The correct code for return of unstyled blocks in TOHTML.jsx is:

 return processedChildren.map(
      (chunk, index) => chunk && <p key={keys[index]}>{chunk}</p>,
    );

**Comment by tisto** [comment]
@giuliaghisini thanks! Could you imagine to write a pull request with a fix for this?
