### ISSUE TITLE
TextEditBlock error: blockNode is note defined

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#1062]
in handleClickOutside, the prop this.props.blockNode is not defined and the error is fired each time you click outside the block.

**Comment by mayursamnani36** [comment]
I am new to this project, can you tell me in which file is this error is located.

**Comment by giuliaghisini** [comment]
in TextEdit block. When you click outside the block a console error is fired with the description "prop this.props.blockNode is not defined". This is because the component not have the blockNode property and no other component pass this prop to it..

**Comment by tisto** [comment]
@giuliaghisini would you mind creating some "steps to reproduce" to make it easier for other devs to reproduce the problem?

**Comment by giuliaghisini** [comment]
@tisto i verified this problem in the latest volto version, and i didn't find this error anymore. Maybe some fix have resolved this problem. If you agree i would like to close this bug
