### ISSUE TITLE
Add i18n improvements

### ISSUE THREAD

**Issue by macagua** [plone/volto#1073]
- Many elements for UI don't have support for translation.
- No exits a clear documentation for add more language to Volto.

**Comment by macagua** [comment]
For this moments these changes are committed at "[i18n-improvements](https://github.com/plone/volto/tree/i18n-improvements)" branch.

**Comment by sneridagh** [comment]
Closing this, since it was merged weeks ago!
@macagua reopen if you want to maintain it open for some reason.
