### ISSUE TITLE
Export unconnected classes

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1076]
To be able to extend component classes (for example widgets) they have to be also exported as individual classes, in addition to the already default export as redux connected classes.

**Comment by tiberiuichim** [comment]
An example of how this can be useful: I want to reuse the QuerystringWidget, to filter the indexes it receives. I can't do that now because the only export of that module is already connected, but if the class was individually exported, I could write:
```
export default connect(
    state => ({
          indexes: filterIndexes(state.querystring.indexes),
    }),
    { getQuerystring },
)(QuerystringWidget);
```
Also, the QuerystringWidget needs to be exported by ``@plone/volto/components``.

**Comment by sneridagh** [comment]
@robgietema I need your feedback here and in #1078

**Comment by ichim-david** [comment]
We moved from class components and the pull request that provided this change was not accepted as such we can close this ticket, if ever we need something similar another issue and pull request can be opened
