### ISSUE TITLE
Rendering richtext draft-js atomic block loses children

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1084]
```
const getAtomic = (children, { data, keys }) =>
  data.map((item, i) => <div key={keys[i]} {...data[i]} />);
```

Rendering the children here is important, when redraft attempts to group the atomic group with the next group, the children are lost. I don't know enough of draft-js, but for my case it worked something like this:

```
const getAtomic = (children, { data, keys}) => (<div>{children}</div>);
```

As far as I understand, atomic blocks are meant to signal, in draft-js, that some content "belongs together", so that it would be deleted completely on backspace key. So it makes sense to rewrite it as above.

**Comment by tisto** [comment]
I guess that's something that @robgietema or @sneridagh need to look into.

**Comment by ichim-david** [comment]
This issue can be closed since draft js editor has been dropped in favor of Slate editor.
