### ISSUE TITLE
[React Intl] Missing locale data for locale: "de". Using default locale: "en" as fallback.

### ISSUE THREAD

**Issue by tisto** [plone/volto#1087]
0) Set language of your browser to "DE" (German)
1) Checkout Volto master branch
2) Start Volto and Backend
3) Go to localhost:3000
-> Check console: [React Intl] Missing locale data for locale: "de". Using default locale: "en" as fallback.

**Comment by nileshgulia1** [comment]
@tisto I cannot able to reproduce the issue. The console shows empty when opening homepage.

**Comment by tisto** [comment]
@nileshgulia1 you don't see this message when you are using the English language. I forgot to add that to the ticket. :)

**Comment by sneridagh** [comment]
That's annoying, but if there's any translation on the current used components on screen and the translation is missing (=empty) then it shows the message :(

**Comment by sneridagh** [comment]
We ended up removing the message because there was a problem in `react-intl` itself.
