### ISSUE TITLE
add customStyleMap for DraftJs Editor

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#1094]
in order to add new styles in draft js, the property customStyleMap is missing when including <Editor/> element in Edit component. 
This will be usefull to add new inline styles that are not yet implemented. 
For Example, I wold like to add a style to center text of an h2 block type..

**Comment by tiberiuichim** [comment]
As a fallback, there's also the option of registering a new drafts-plugin-editor plugin that has the styles. See https://github.com/draft-js-plugins/draft-js-plugins/blob/master/HOW_TO_CREATE_A_PLUGIN.md#basics

```

**Comment by tisto** [comment]
@giuliaghisini this sounds like a useful addition. Would you feel comfortable looking into this or do you need help/pointers?

**Comment by giuliaghisini** [comment]
@tisto sure! in next days i will try to this. ill'create a branch named "custom-style-map"

**Comment by sneridagh** [comment]
Addressed in https://github.com/plone/volto/pull/1096
