### ISSUE TITLE
Draftjs: blockquote style render error: unique key

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#1097]
- create a new page
- add new text block
- write some text
- select all text
- apply the style 'blockquote' 
- save

in view mode there's an error in console:
"Each child in a list should have a unique "key" prop"

**Comment by nileshgulia1** [comment]
@giuliaghisini That warning comes up when key prop to <list /> is not supplied.

**Comment by iFlameing** [comment]
Fixed by #1456
