### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by tisto** [plone/volto#1104]
Plone has a "table of contents" feature that extracts the H1-H3 headlines from the body text and creates a "table of contents" with links to the headlines used in the body text.
![demo kitconcept com](https://user-images.githubusercontent.com/632105/72219302-f30d3a00-3544-11ea-8011-fbb35926a3c2.png)
![Page — demo kitconcept com](https://user-images.githubusercontent.com/632105/72219306-f4d6fd80-3544-11ea-87fe-15566ba00f26.png)

**Comment by aryamanpuri** [comment]
@tisto Can I work on this ?

**Comment by aryamanpuri** [comment]
Actually I am willing to contribute to this project, but didn't get any replied message, to where and how to start from. Is there any channel where I can communicate with others.

**Comment by tisto** [comment]
@aryamanpuri we have a Slack channel. Join:

http://plone.slack.com/

Channel: "#volto"

**Comment by tisto** [comment]
@aryamanpuri the best way to start contributing to Volto is to start using it, report bugs, and start to fix smaller issues.

We have a label to mark easier and newbie-friendly tasks:

https://github.com/plone/volto/issues?q=is%3Aissue+is%3Aopen+label%3A%2241+lvl%3A+easy%22

**Comment by aryamanpuri** [comment]
@tisto okay, I will start from there.



> http://plone.slack.com/

I don't have any  credentials

**Comment by tisto** [comment]
@aryamanpuri I sent you an invitation.

**Comment by aryamanpuri** [comment]
Got it

**Comment by tiberiuichim** [comment]
@tiso: can I also get an invite? Thanks!

**Comment by sneridagh** [comment]
Implemented already.
