### ISSUE TITLE
Search Bar in Contents menu get on size change and excedes the table on Resizing the Page

### ISSUE THREAD

**Issue by aryamanpuri** [plone/volto#1105]
**Describe the bug**
The Search Bar in the Content Menu is exceeding the table menu on resizing the page.

**Expected behavior**
The Search Bar shouldn't exceed in size when the window width changes, whereas it should adjust.

![Screenshot from 2020-01-13 14-33-01](https://user-images.githubusercontent.com/43513114/72243451-04704800-3612-11ea-9409-0c9bb2b84d26.png)

**Additional Context**
I am working on this.

**Comment by aryamanpuri** [comment]
@tisto Should I add custom CSS?

**Comment by tisto** [comment]
@aryamanpuri yes. please.

**Comment by aryamanpuri** [comment]
@tisto Since we are using Semantic-UI, so changing in the props would be better, as it would be similar to the codebase.

**Comment by aryamanpuri** [comment]
I tried with different props to add up in both menu.menu and input with it does not give the required result .

**Comment by aryamanpuri** [comment]
Hi @tisto , I found out there is problem due to Mozilla Browser and as such there is no bug in code .
There is some bug in the semantic-UI for mozilla Browser .
