### ISSUE TITLE
DraftJS Footnotes

### ISSUE THREAD

**Issue by tisto** [plone/volto#1106]
DraftJS in Volto should support footnotes. I guess this is a non-trivial task since we need to allow editors to set the name of a footnote and create an anchor link to that footnote. Maybe there is a DraftJS plugin we can build upon.

**Comment by tiberiuichim** [comment]
idea: have the footnotes automatically generated by scanning all draftjs text blocks, either in a separate "footnotes" block, or automatically inserted in DefaultView.jsx.

For the footnote entities themselves, the LinkPlugin can serve as rough example. Footnote name can be saved in the entity data, just like the link target.
