### ISSUE TITLE
Unable to login from /logout page

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1147]
There's an error in the Javascript error console when trying to login from the /logout page

> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

This happens with Volto 4.0.0-alpha.34 on https://volto.kitconcept.com/

**Comment by tiberiuichim** [comment]
I think this happens because ``unsafe_componentWillReceiveProps`` in Login.jsx only handles the case where the auth token exists, there seems to be no code handling what happens further with the logout page if I try to login.

**Comment by sneridagh** [comment]
Fixed in #1147
