### ISSUE TITLE
Optimize produced bundles for Anonymous users

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1149]
There are some opportunities to further shrink the generated bundle with the techniques described here: https://webpack.js.org/guides/lazy-loading/

We've been using this technique for a custom implementation that uses ckeditor:
```
  componentDidMount() {
    import(/* webpackChunkName: 'ckeditor' */ '@ckeditor/ckeditor5-react').then(
      module => this.setState({ CKEditor: module.default }),
    );
    import(
      /* webpackChunkName: 'classiCk' */ '@ckeditor/ckeditor5-build-classic'
    ).then(module => this.setState({ ClassicEditor: module.default }));
  }
```

And then in component rendering we use ``this.state.ClassicEditor`` and such to render the CKEditor component. This causes Webpack to split those resources in a separate chunk that's loaded on demand when the parent components is first mounted.

As the bigger candidates in Volto's case, I see the draftjs editor (which will also include immutable.js) and the DND support, I think it's react-dnd.

**Comment by pnicolli** [comment]
See also #967. In that PR we integrated ``loadable-components`` and most of the work is done. I am working on the tests of that PR in these days. For sure separating editor and dnd makes sense.

**Comment by tiberiuichim** [comment]
@pnicolli Does this make the chunk load on demand or is every chunk loaded from the generated HTML?

**Comment by pnicolli** [comment]
@tiberiuichim the chunks are loaded on-demand with ``loadable-components``. It is based on the same dynamic imports you suggested above.

**Comment by sneridagh** [comment]
I will leave here for the record, the bundle sizes and improvements we are making in our lazy load story.

This is the bundle analysis for master, Volto 4.6.0 April 7th (Baseline)
<img width="1917" alt="VoltoModuleAnalyzerBaseline" src="https://user-images.githubusercontent.com/486927/78641477-973b1e80-78b1-11ea-8779-b0032689ec74.png">

and the current sizes

<img width="324" alt="image" src="https://user-images.githubusercontent.com/486927/78641443-88ed0280-78b1-11ea-91dc-8539db00077e.png">

**Comment by sneridagh** [comment]
These are the ones after the basic boilerplate: #1342

**Comment by sneridagh** [comment]
Merged #1342

**Comment by sneridagh** [comment]
Merged #1145 

Current status:
<img width="1916" alt="Screenshot 2020-04-10 at 12 52 26" src="https://user-images.githubusercontent.com/486927/78985944-5ef24500-7b2a-11ea-800c-7304eac2afdf.png">

<img width="591" alt="Screenshot 2020-04-10 at 12 52 38" src="https://user-images.githubusercontent.com/486927/78985959-67e31680-7b2a-11ea-8c81-412079a02bf0.png">

<img width="586" alt="Screenshot 2020-04-10 at 12 52 45" src="https://user-images.githubusercontent.com/486927/78985965-6d406100-7b2a-11ea-83df-01af3ce0acf8.png">

**Comment by sneridagh** [comment]
After #1362:

<img width="1916" alt="Screenshot 2020-04-11 at 12 09 45" src="https://user-images.githubusercontent.com/486927/79041315-1fd9f780-7bef-11ea-964f-c9f24146a020.png">
<img width="584" alt="Screenshot 2020-04-11 at 12 09 54" src="https://user-images.githubusercontent.com/486927/79041320-28cac900-7bef-11ea-9a59-29980e691433.png">
<img width="582" alt="Screenshot 2020-04-11 at 12 10 00" src="https://user-images.githubusercontent.com/486927/79041322-2a948c80-7bef-11ea-92e9-dd0ae41032c9.png">

**Comment by sneridagh** [comment]
After #1364

<img width="1911" alt="Screenshot 2020-04-11 at 16 42 31" src="https://user-images.githubusercontent.com/486927/79046846-7f49fe80-7c13-11ea-8803-a92d01500d69.png">
<img width="580" alt="Screenshot 2020-04-11 at 16 42 38" src="https://user-images.githubusercontent.com/486927/79046848-807b2b80-7c13-11ea-934c-2b7a8a57e332.png">
<img width="584" alt="Screenshot 2020-04-11 at 16 42 43" src="https://user-images.githubusercontent.com/486927/79046850-8244ef00-7c13-11ea-802e-21465326c868.png">

**Comment by sneridagh** [comment]
After #1365

<img width="1919" alt="Screenshot 2020-04-11 at 16 44 23" src="https://user-images.githubusercontent.com/486927/79046903-c932e480-7c13-11ea-936b-dcc5073a98cc.png">
<img width="589" alt="Screenshot 2020-04-11 at 16 44 29" src="https://user-images.githubusercontent.com/486927/79046904-c9cb7b00-7c13-11ea-9f9e-d372d3749599.png">
<img width="586" alt="Screenshot 2020-04-11 at 16 44 35" src="https://user-images.githubusercontent.com/486927/79046906-cb953e80-7c13-11ea-848b-e230ebf4cee7.png">
