### ISSUE TITLE
sitemap.xml.gz generates listing of a batch of results, not the whole website

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1150]
The ``@search`` endpoint uses batching by default, so the resulting sitemap.xml.gz file is not accurate to the actual website content.

So the solution seems to be either to hardcode a certain b_size parameter in the API call (maybe expose this as a setting?), or extend the restapi search service to allow disabling the batching process.

**Comment by sneridagh** [comment]
@tiberiuichim probably the first option.

**Comment by sneridagh** [comment]
Fixed in #1159
