### ISSUE TITLE
Hit Enter in ObjectBrowser search input sends submit and reloads page

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1157]
Tested on Volto 4.0.0-alpha.34.

To reproduce:

- Create an image block, click on the Navtree button.
- In the ObjectBrowser sidebar, go to the search field
- Hit the Enter key on your keyboard.

**Comment by tiberiuichim** [comment]
This still happens in Volto 8

**Comment by tisto** [comment]
Yeah. That's annoying. Maybe @iFlameing can have a look on Monday...
