### ISSUE TITLE
RFC on AlignBlock API

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1162]
A really small nitpick about ``align`` member de-structured in the object passed as parameter, below,
```
const AlignBlock = ({ align, onChangeBlock, data, intl, block }) 
```
In this case, ``align`` is never used in AlignBlock.jsx and instead ``data.align`` is used. ``data`` probably needs to be passed because it's needed to callback ``onChangeBlock``. I think the API would be cleaner if ``onAlignBlock`` is a prop, merging the data is done in the parent component and AlignBlock only gets ``align`` as a property.

So, for example, in ImageSidebar.jsx, it would become:
```
                    <AlignBlock
                      align={data.align}
                      onAlignBlock={align => onChangeBlock(block, {...data, align})}
                      data={data}
                      block={block}
                    />
```

These changes make sense if, for example, AlignBlock would become a widget and the Sidebar block editing would be formalized with schemas and an autogenerated form.

**Comment by sneridagh** [comment]
I think this was implemented and even probably superseeded and not used anymore since we went full schema based settings, right? @tiberiuichim ?
