### ISSUE TITLE
Listing block: add pagination

### ISSUE THREAD

**Issue by cekk** [plone/volto#1182]
Listing block show only first n results from query, but if we want to use it as a listing_view, we need to implement batch pagination like in classic Plone

**Comment by tisto** [comment]
@cekk that would be a really nice addition. Do you plan to work on this?

**Comment by cekk** [comment]
yes, we **need** to work on this in these days.
someone will come back with a pr ;)

**Comment by tisto** [comment]
@cekk awesome! Let us know if there is anything we can do to help! I'd love to see this feature in Volto asap as well.

**Comment by sneridagh** [comment]
Merged!
