### ISSUE TITLE
RichText widget in a form stopped working.

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#1184]
The draftjs editor don't show the toolbar.

**Comment by pnicolli** [comment]
We noticed the same thing yesterday evening. Actually, the toolbar in shown in the top-left corner of the page. Not sure why yet, but this might help to debug it.

**Comment by tisto** [comment]
I'd highly recommend writing an acceptance test as long as this is broken. This way we can make sure such a regression won't happen again. Writing a Cypress test is a perfect newbie task at a sprint. :)

**Comment by sneridagh** [comment]
Fixed.
