### ISSUE TITLE
Layout navigation and user actions (login, register) overlapping on medium windows

### ISSUE THREAD

**Issue by ksuess** [plone/volto#1186]
![Welcome_to_Volto_](https://user-images.githubusercontent.com/1144737/74336700-17a43e00-4d9f-11ea-8874-e1ac9f9b3ebe.png)

**Comment by tisto** [comment]
What about hiding login/registration for smaller viewports? The navigation could still overlap the search but then maybe we have to hide the search for smaller viewports as well. Or switch to mobile view for smaller viewports.

**Comment by nileshgulia1** [comment]
@ksuess The nav links (login,register) do not overlap in when the i18 is en lang. But I think we can switch to mobile view on smaller screens on other languages as well.

**Comment by ksuess** [comment]
Anontools (login and register), even if not needed on many websites, are IMHO better hidden in custom themes, not in default theme.

As you said @tisto there is still the search that could be overlapped by a long navigation.
So here is my first throw of a flexible responsive header: 
https://github.com/plone/volto/pull/1233

short navigation:

![Gartenplan_-_Mozilla_Firefox](https://user-images.githubusercontent.com/1144737/75140378-12c08200-56ef-11ea-9ca4-b96d579c992b.png)

long navigation:

![Kräuter_-_Mozilla_Firefox](https://user-images.githubusercontent.com/1144737/75140258-cecd7d00-56ee-11ea-8e7d-1b06bc020632.png)
