### ISSUE TITLE
Editing: small windows: button for selecting type of block is missing

### ISSUE THREAD

**Issue by ksuess** [plone/volto#1187]
![image](https://user-images.githubusercontent.com/1144737/74336966-ad3fcd80-4d9f-11ea-98bb-a05369f325ba.png)

**Comment by tisto** [comment]
@ksuess thank you for reporting this. This is kind of a known UX issue. The question is how to fix it. Leaving a space between toolbar and block might be an option. Though, I'd only do that for small screens and this would make the blocks even smaller (which might cause problems with larger and more complex blocks).

We are open for suggestions or a discussion here I guess. :)
