### ISSUE TITLE
Listing View

### ISSUE THREAD

**Issue by wkbkhard** [plone/volto#1188]
Is the indent on the listing view correct? It seems a bit strange that the items move more and more to the left?

![Listing](https://user-images.githubusercontent.com/28622088/74347793-e719cf80-4db1-11ea-8903-bd191655655c.png)

**Comment by tisto** [comment]
@wkbkhard no. the images should be aligned correctly of course.

**Comment by tisto** [comment]
@wkbkhard in case you plan to work on this. We might change the CSS classes for the views: https://github.com/plone/volto/issues/1189

**Comment by wkbkhard** [comment]
I'll work on this later today and will kepp #1189 in mind!

**Comment by wkbkhard** [comment]
Preview:
![ListingView](https://user-images.githubusercontent.com/28622088/74552123-ce95ea80-4f54-11ea-86ef-d89e0fabfc81.png)
