### ISSUE TITLE
Link should be over REST API 

### ISSUE THREAD

**Issue by aryamanpuri** [plone/volto#1197]
In the third line, see at the link of  `REST API`
It should be over REST API whereas it is over the preceding word and `REST`.

![Screenshot from 2020-02-15 15-22-46](https://user-images.githubusercontent.com/43513114/74585896-e0849580-5007-11ea-8022-f4360f8f275d.png)

**Comment by aryamanpuri** [comment]
@sneridagh How can this can be rectified ?

**Comment by sneridagh** [comment]
@aryamanpuri I think this was already fixed!. Someone changed the text and didn't update the offset of the link in the source JSON for this block. It lives here:

https://github.com/kitconcept/kitconcept.voltodemo/blob/master/src/kitconcept/voltodemo/setuphandlers.py#L97
