### ISSUE TITLE
Broken Japanese tag (Subject)

### ISSUE THREAD

**Issue by terapyon** [plone/volto#1207]
We can add Japanese tag (Subject), but we can't re-select same tag, because saved data became like a Unicode number.

![スクリーンショット 2020-02-17 20 33 34](https://user-images.githubusercontent.com/485372/74650341-d65bc600-51c4-11ea-8a8b-1305af6320f4.png)

**Comment by terapyon** [comment]
I found a new release plone.restapi 6.3.0. @sneridagh Did it focus this bug?

**Comment by sneridagh** [comment]
Fixed in k.volto.
