### ISSUE TITLE
Contents view is accessible for anonymous users

### ISSUE THREAD

**Issue by tisto** [plone/volto#1238]
0) As anonymous user
1) go to https://volto.kitconcept.com/contents
-> you will see the full folder contents view with all options (change workflow, delete, edit, etc)
-> you can not do anything and every call will fail

Expected behavior:

-> Show login form for unauthorized, and maybe even for regular users without the editor role (we need to check how standard Plone handles that)

**Comment by demarant** [comment]
Another couple of places to consider:

**1) Accessing an unpublished page, should return 401 and login info**

add a News item "Test news item"  under the news folder and try to access it as anonymous
https://volto.kitconcept.com/news/test-news-item
you will get a 200 OK page with a message on the page  "This page does not seem to exist…" (which is usually for a 404 page).

Expected: return a 401 Unauthorized  as plone api backend does.
and display a user friendly message to the user explaining the need to login.

**2) links to "/edit" should return 401 and login info**
Similar issue when you access the "/edit" of a content item. 

add a News item  under the news folder and try to access it with /edit
https://volto.kitconcept.com/news/test-news-item/edit
you will get an error on the page
![Screenshot_2020-03-02 https volto kitconcept com](https://user-images.githubusercontent.com/320440/75658536-ccc46a80-5c68-11ea-9613-580594e9a1f9.png)

Expected: a 401 Unauthorized status code back and a user friendly message on the page, explaining the need to login.

**Comment by avoinea** [comment]
This seems fixed within latest Volto.
