### ISSUE TITLE
Console error on reload browser.

### ISSUE THREAD

**Issue by terapyon** [plone/volto#1241]
I got an error by browser inspector on reload browser with logged in.
`Warning: Expected server HTML to contain a matching <div> in <div>.` 

![スクリーンショット 2020-02-27 14 45 49](https://user-images.githubusercontent.com/485372/75415809-039c3700-5970-11ea-8936-88a3dd7e4924.png)

**Comment by sneridagh** [comment]
This is know, and it's fixed in the lazy load branch.
