### ISSUE TITLE
tuple field (e.g. creator, contributor) are not editable via volto

### ISSUE THREAD

**Issue by demarant** [plone/volto#1247]
it is not possible to edit the Creators or the Contributors field via Volto.
These are of type tuple.

**How to reproduce**
Add a News item. Try to edit and add another creator or contributor and save.
![add-values-to-creator-contributor](https://user-images.githubusercontent.com/320440/75681053-1c1f9080-5c93-11ea-8faf-ff6e5ad1b550.png)

**Expected**
Same behaviour as when editing via standard Plone UI. It should be possible to add or remove lines to the Creators and Contributors fields.

**Comment by davisagli** [comment]
This is working currently.
