### ISSUE TITLE
show html buttons for text entered in RichText field?

### ISSUE THREAD

**Issue by demarant** [plone/volto#1248]
How should richtext fields be handled by Volto?

I see that they do not get the same editing buttons as the Volto text-block.

e.g try to edit the Text field of a News Item. 

from a user point of view, I would expect same behaviour, meaning no matter where I add text (in blocks or in the metadata richtext field) I should get the same UX and possibility of wysiwyg html formatting.

Of course, the richtext field in my opinion may be totally deprecated in plone6, if volto is standard ui, than richtext field is basically replaced by a volto-blocks behaviour field....

**How to reproduce**
go to https://volto.kitconcept.com/news and login
Add a "News Item", click on the field Text (richtext field)
you should get a text editor toolbar, nothing comes up to let you do some html editing.
see screenshot below
![Add News Item](https://user-images.githubusercontent.com/320440/75769641-d3c1aa80-5d46-11ea-8f38-05cdbc5a5b54.png)

**Comment by tisto** [comment]
@demarant I agree. Would you mind adding some screenshots and some steps-to-reproduce?

**Comment by demarant** [comment]
@tisto I have updated the issue description with steps and a screenshot.

**Comment by demarant** [comment]
I cannot reproduce the issue anymore, we updated 4.0.0 and the editing buttons appears now when selecting some text.
