### ISSUE TITLE
jsconfig.json

### ISSUE THREAD

**Issue by ebrehault** [plone/volto#125]
Hi @robgietema,

I noticed you added recently a `jsconfig.json` file in the package:
https://github.com/plone/plone-react/blob/master/jsconfig.json

What are you using it for? Is it used in your build?

I am asking because it is an equivalent of our `tsconfig.json` in TypeScript which allows us to set custom paths to dependencies and we are currently building a mr.developer-like tool (https://github.com/collective/ng-mr-developer/tree/eric-changes) to improve the developer experience when working with several checkouts in a project.

I would be glad to adapt ng-mr-developer so it can be used in Plone React projects too.

**Comment by tisto** [comment]
@ebrehault that would be awesome! We have a config.json in our large Angular 2 project that is used at build time to pass variables to Webpack to apply custom themes and other stuff. We also have a config.json that our app loads at run-time for customizations that we need at run-time. @sneridagh can tell more about this. 

In any case, a JS mr.developer is definitely what we need. And we should try to keep Angular and React close so we can use tools together.

Just one small recommendation, when we make this a generic tool: can we please get rid of the "ng"? :)

We could also move this to the Plone organization. I think this is essential infrastructure for our future Plone versions.

**Comment by ebrehault** [comment]
I was already considering renaming `ts-mr-developer` (because it works in any TypeScript-based project), but if it even works with ES6-based projects, then we need something else. Maybe `js-mr-developer`.

**Comment by robgietema** [comment]
A `mr-developer` would be awesome! As far as I know the `jsconfig.json` is used only for ide's not in the build system.

**Comment by sneridagh** [comment]
@ebrehault That sounds awesome!!
+1 to standardize it.

jsconfig.json is used by vscode:
https://code.visualstudio.com/docs/languages/jsconfig

If not set, it complains about JS syntax etc... It has the same purpose as the tsconfig.json file (but not used by the build/tooling).

**Comment by ebrehault** [comment]
@sneridagh, our mr-developer https://www.npmjs.com/package/mr-developer is working quite nicely now.

I am wondering if the best way to use it in a React project could be to set the `resolve.alias` property https://webpack.js.org/configuration/resolve/#resolve-alias in `webpack.config.dev.js`.

But I am not super confortable with the idea of changing dynamically a JS file.

Maybe `webpack.config.dev.js` could compute its `alias` value by reading the tsconfig.json's `compilerOptions.paths` attribute? What do you think?

**Comment by ebrehault** [comment]
@sneridagh so let's say you want to use a checkout of draft-js-buttons, you have to create a `mr.developer.json` like this:

```
{
    "draft-js-buttons": {
        "path": "draft-js-buttons/src",
        "url": "https://github.com/draft-js-plugins/draft-js-plugins.git"
    }
}
```

Then you do:

```
$ mrdeveloper --config=jsconfig.json
```

And to override the `draft-js-buttons` package node_modules path, I think you can do something like:

```
const pathsConfig = require('./jsconfig').compilerOptions.paths;
const alias = {};
Object.keys(pathsConfig).forEach(package => {
  alias[package] = pathsConfig[package][0];
});
```

I tried it, but I do not know where it should be done in your webpack jungle :)

**Comment by robgietema** [comment]
Implemented
