### ISSUE TITLE
In Text field in CT apostrophe breaks saving

### ISSUE THREAD

**Issue by nzambello** [plone/volto#1250]
Volto 4.0.0, Plone 5.2.0, python3

When editing a NewsItem or an Event, if I type something with apostrophes (') it breaks when trying to save the content.

Example: editing/adding a News Item, I type from lipsum.com:

> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

Clicking Save will do nothing in the UI and Plone will print this in logs:

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 161, in transaction_pubevents
  Module transaction._manager, line 252, in commit
  Module transaction._manager, line 131, in commit
  Module transaction._transaction, line 296, in commit
  Module transaction._transaction, line 367, in _callBeforeCommitHooks
  Module Products.CMFCore.indexing, line 312, in before_commit
  Module Products.CMFCore.indexing, line 222, in process
  Module Products.CMFCore.indexing, line 50, in reindex
  Module Products.CMFCore.CatalogTool, line 367, in _reindexObject
  Module Products.CMFPlone.CatalogTool, line 351, in catalog_object
  Module Products.ZCatalog.ZCatalog, line 499, in catalog_object
  Module Products.ZCatalog.Catalog, line 369, in catalogObject
  Module Products.ZCTextIndex.ZCTextIndex, line 178, in index_object
  Module plone.indexer.wrapper, line 65, in __getattr__
  Module plone.indexer.delegate, line 20, in __call__
  Module plone.app.contenttypes.indexers, line 85, in SearchableText_news
  Module plone.app.contenttypes.indexers, line 67, in SearchableText
  Module Products.PortalTransforms.TransformEngine, line 173, in convertTo
  Module Products.PortalTransforms.Transform, line 202, in convert
  Module Products.PortalTransforms.libtransforms.retransform, line 31, in convert
  Module Products.PortalTransforms.transforms.html_to_text, line 21, in sub_func
ValueError: invalid literal for int() with base 10: 'x27'
```

Clicking a second time Volto breaks.

I edited the same content on Plone without any issue and Volto renders it correctly.

The difference is within the handling of special characters in draftjs (I guess).
It could be the same with other symbols.

While editing a "correct" text with apostrophes in the editor, inspecting, I see the character `'`, in the other case - the one with the error - the editors is trying to save `&#27;` as html entity but Plone trasforms seem to dislike it.
You can see it in the inspector and in net calls.

**Comment by nzambello** [comment]
@sneridagh @tisto @cekk I see this very dangerous and I'd treat it with high priority.
Have anyone else discovered this issue?

**Comment by sneridagh** [comment]
The responsibility for converting from djs to html is left to redraftjs library. We have certain control over it, since is configurable. Maybe  the culprit is there.

**Comment by cekk** [comment]
Update to fix it without changing anything in draftjs: https://github.com/plone/plone.restapi/pull/913
