### ISSUE TITLE
Improve Volto error messages

### ISSUE THREAD

**Issue by tisto** [plone/volto#1252]
I ran across this blogposts about how to write good error messages:

https://uxplanet.org/how-to-write-good-error-messages-858e4551cd4?gi=532c11e13d0

I think we can learn a lot from those advices and significantly improve the user experience on errors in Volto. Any takers?

**Comment by avimishra18** [comment]
> I think we can learn a lot from those advices and significantly improve the user experience on errors in Volto. Any takers?

I would love to contribute to this. Can you please specify more on this issue possibly with some example error scenarios?

**Comment by avimishra18** [comment]
Correct me if I am wrong. This is an error message component, right? 

![Screenshot 2022-03-14 at 07 37 48](https://user-images.githubusercontent.com/48449499/158092677-8c286e29-3a9b-4f7a-80a0-3b17aa28bef5.png)

**Comment by aaryan-verma** [comment]
I would like to work on this error (if it's still open )

**Comment by varun-s22** [comment]
@tisto is this issue still open? i would like to work on it

**Comment by farhanakhtar24** [comment]
@tisto i would like to work on this issue.

**Comment by Programmer-Dost** [comment]
As I am unfamiliar with the current project, can someone please list the error messages that need improvement?

**Comment by MontiRajput** [comment]
please @tisto assign this issue to me I have a great curiosity to solve this issue I love in creating UI. I Definatly give a impressive UI of this error msg
Please @tisto  assign me !

**Comment by stevepiercy** [comment]
@tisto I'm closing this issue. It's 4.5 years old, there is no specific direction in the description, and the original article was deleted. We need to know exactly what is wrong with a specific and current error message to fix it.

@MontiRajput please read and follow [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do), [Contributing to Plone](https://6.docs.plone.org/contributing/index.html), and [Contributing to Volto](https://6.docs.plone.org/contributing/volto.html).
