### ISSUE TITLE
Link inside text for content-type without blocks

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#1267]
This error seams related to this problem https://github.com/plone/volto/pull/1228/files. 
I think the problem is in  WysiwygWidget.
These are the steps to reproduce the problem:

- Add a new Event (or ContentType without blocks)
- in Text field, write some text
- select a word and click on link button to add a link
- type something (f.e. 'Events') to choose an internal link
- view the console: an error is fired. It seems that it cannot find a router. 
A different error is also fired if you write an external link. 

This is blocker because content-types without blocks cannot be used, and migrated contents with links inside text will generate errors on edit. 

Please fix it asap.

**Comment by sneridagh** [comment]
@giuliaghisini @cekk It would be great if we write a Cypress test for normal RichText fileds.
