### ISSUE TITLE
Newly created user is not displayed in the User Control Panel

### ISSUE THREAD

**Issue by raschmoneit** [plone/volto#1271]
After I added a new user via volto, I can not see this user in the volto user control panel. Also a search did not find the user. On the Backend (plone/@@usergroup-userprefs) the user is created correctly

**Comment by pbauer** [comment]
Also: Assignment to groups during user-creation does not work.

**Comment by fredvd** [comment]
First checks yesterday on the sprint in Dresden: actions/redux is still working, but there's an error on the console about the user objects being an Array and an Object is expected. The main users-listing segment is broken, but the add user button and popup still works and users are created in Plone backend. 

I tried to search for obvious changes in volto or plone.restapi, but nothing obvious stands out. What has been changed here recently? Or has the user table been broken much longer already?

**Comment by tisto** [comment]
We should start fixing this by writing a few Cypress tests to prove things aren't working right now. Otherwise we risk to break this in the future again. When we merged this feature I manually tested everything, so those things used to work as far as I know.

**Comment by iFlameing** [comment]
@tisto I am unable to make a post request to /@user plone from the volto app. But when I am doing with Postman it succeeds. 
```javascript
resource: the server responded with a status of 400 (Bad Request)
```
