### ISSUE TITLE
Print CSS

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#1289]
ToDo:

- [ ] do some research on Print CSS

- Show basic header
- Hide Navigation and everything that does not make much sense for a print out (e.g. social media buttons)

Resources:

- https://alistapart.com/article/goingtoprint/
- https://www.smashingmagazine.com/2011/11/how-to-set-up-a-print-style-sheet/

**Comment by iFlameing** [comment]
some research link https://stackoverflow.com/questions/40754394/webpack-style-loader-media-tag-for-printing
