### ISSUE TITLE
Extension point needed in constants/Layouts.jsx

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1296]
For Volto addons to be able to add layout titles, ``constants/Layouts.jsx`` should not be used directly, ``Display/Display.jsx`` should import ``layouts`` from ``~/config``.

**Comment by tiberiuichim** [comment]
Perhaps it woulld also be possible to join the configuration of layouts/components and layouts/layout titles, in a manner as it is done for blocks.

**Comment by sneridagh** [comment]
Transfered to config object in Volto 16. Closing.
