### ISSUE TITLE
Client only code and SSR

### ISSUE THREAD

**Issue by nzambello** [plone/volto#1297]
Related to #760 .

I'm using __CLIENT__ variable to get some code work only in client and not in server rendernig.
But the server spawns me an error when I load a page containing the component with this code.

The error (and the code):
```
ReferenceError: window is not defined

  219 |
  220 |   let isMobile = false;
> 221 |   if (__CLIENT__) isMobile = window && window.innerWidth < 992;
  222 |
  223 |   return (
  224 |     <div className="event-search-template">
```

@sneridagh What am I doing wrong?

**Comment by sneridagh** [comment]
Strange, this uses to work always...Which is the error?

**Comment by nzambello** [comment]
It was "ReferenceError: window is not defined".
And the whole app went broken.

I swear I restarted the server yesterday to test it, but it seems to be not appearing this morning.

This is the magic and mistery of our work, I know, but I don't get how to reproduce it today.
Could the server cache something while reloading the app?

**Comment by sneridagh** [comment]
Might be! I was about to suggest remove the oneliner with a "normal" if syntax. Maybe that the hot reload didn't get well that oneliner.

**Comment by nzambello** [comment]
Ok, I guess something about that, so I'm closing this.
Thank you!

**Comment by sneridagh** [comment]
You're welcome!
