### ISSUE TITLE
Google Analysis js code in Volto app

### ISSUE THREAD

**Issue by terapyon** [plone/volto#1301]
We want to use Google Analysis in a custom Volto app. How can we set it?

**Comment by jackahl** [comment]
hi @terapyon,
we just implemented Google Analysis into one of our projects. This is how to do it: 
First create a useGoogleAnalytics file in your project, in which you create a useGoogleAnalytics hook using the following code: 
useGoogleAnalytics.jsx
```
import { useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import ReactGA from 'react-ga';

if (__CLIENT__) {
  ReactGA.initialize('UA-112268545-1', {
    debug: true,
    gaOptions: {
      anonymizeIp: true,
    },
  });
}

const useGoogleAnalytics = () => {
  let location = useLocation();

  useEffect(() => {
    ReactGA.pageview(location.pathname);
  }, [location]);
};

export default useGoogleAnalytics;
```
Use this hook in a GoogleAnalytics function. We created a separate file for that, but you can for sure also directly declare that function in the place you will be using it.
´´´
import useGoogleAnalytics from './useGoogleAnalytics';

const GoogleAnalytics = () => {
  useGoogleAnalytics();

  return null;
};

export default GoogleAnalytics;
```
Than import that function to your App.jsx ` import GoogleAnalytics from '@package/GoogleAnalytics';`
and render it somewhere in there: `<GoogleAnalytics /> `
Google Analytics should be working now.
If necessary you can also include some kind of Cookie banner component to give people the ability to disable tracking by setting the following cookie:
´´´
 onDisableGA() {
    cookie.save('ga-disable', true, {
      expires: new Date((2 ** 31 - 1) * 1000),
      path: '/',
    });
    this.onHideMessage();
  }
´´´

I hope that helps you. If you have any questions on this feel free to ping either me or @sneridagh.

**Comment by nzambello** [comment]
I put this in an addon: https://github.com/collective/volto-google-analytics/
(work in progress)
Any help/contribution is appreciated

**Comment by sneridagh** [comment]
Several Volto add-ons accomplish this now. 

https://github.com/collective/awesome-volto
