### ISSUE TITLE
Travis started to fail out of nowhere

### ISSUE THREAD

**Issue by tisto** [plone/volto#1305]
This happened quite a few times before. Somehow Travis seems to change their configuration/VMs without notice.

To prove that no code change caused this we created a dummy branch with no real change:

https://travis-ci.org/github/plone/volto/builds/667659803?utm_source=github_status

Travis still fails on Plone and Guillotina. I was able to fix the Plone build by not relying on Python venv. I have no clue why or how Guillotina fails:

https://travis-ci.org/github/plone/volto/jobs/667683243?utm_source=github_status

@bloodbare can you have a look? We are using a fixed Docker image of Guillotina but somehow the frontend build started to fail. As said, we can prove that we did not change any code. No clue how to fix this...

**Comment by bloodbare** [comment]
@tisto I don't see any error on travis log that makes me understand what is happening. Docker-compose doesn't show any info, maybe because of ` > /dev/null` can you remove it ?

**Comment by tisto** [comment]
@bloodbare running: https://travis-ci.org/github/plone/volto/jobs/667721180

**Comment by bloodbare** [comment]
Looks like there is no problem with docker-compose. I've checkout the branch and run the tests with the same failing tests so **its not a Travis problem**.

I have the feeling that https://github.com/plone/volto/blob/travis-fail-test/cypress/support/guillotina.js is not called to create the "Site".

**Comment by bloodbare** [comment]
I've checkout commit https://github.com/plone/volto/commit/8052079f4011fd7bc8dd8d3b32717f294fa19f11 and all works in Guillotina, was the commits after on volto that broke it (and I can reproduce in my laptop)

**Comment by bloodbare** [comment]
Looks like master works on guillotina, its the travis-fail-test branch: This commit https://github.com/plone/volto/commit/3b2355494680d36345a7146fcff0c2484cea7289

**Comment by bloodbare** [comment]
@tisto ^

**Comment by tisto** [comment]
That branch was not created from master. Have to do it again.
