### ISSUE TITLE
Change workflow state of content objects recursively

### ISSUE THREAD

**Issue by tisto** [plone/volto#1318]
There is currently no way to change the workflow state of content objects in Volto recursively.

Proposal: we should add a checkbox "change workflow state for this content object and all contained objects" (whatever Plone currently uses).

Steps to reproduce:

1) go to https://volto.kitconcept.com
2) login as admin
3) create folder with a nested structure and a few documents
4) go to the contents view (https://volto.kitconcept.com/contents)
5) choose the folder and click on the "wf change" icon
6) change the workflow to "publish"
-> only the folder content object itself did change the workflow
-> expected: a checkbox that offers to change the wf recursively

![Inhaltsverzeichnis](https://user-images.githubusercontent.com/632105/78045886-c06e2300-7376-11ea-91c2-6e9bbbe219f5.png)

Nice to have in the future:

a) way to change wf state recursively via the normal wf state toggle in the left toolbar
b) async operation that allows doing time-consuming wf state changes (that happen quite often and is something that is a very common problem in standard Plone on large deployments)

**Comment by tisto** [comment]
@robgietema works like a charm! thanks!

@iFlameing @steffenri maybe one of you could write a Cypress test tomorrow for this:

1) create a document with another document inside, both are in the wf state private
2) go to folder contents in the parent object of the document
3) select the document and publish it via the bulk actions, check the "change workflow state recursively"
-> both the document and the document within the document should be in the workflow state publish


![Contents (1)](https://user-images.githubusercontent.com/632105/79916841-b2696a80-8429-11ea-804f-0012003733c1.png)

**Comment by iFlameing** [comment]
@tisto fixed in https://github.com/plone/volto/pull/1343.
