### ISSUE TITLE
Docker image not persist locally

### ISSUE THREAD

**Issue by iFlameing** [plone/volto#1327]
When I am running docker command for backend I need to have internet connectivity every time before running this command.

**Comment by tisto** [comment]
@iFlameing can you please provide more information and an error trace?

**Comment by iFlameing** [comment]
Steps to reproduce:
1. Run this command first time with network connectivity you successfully start the backend for the Volto project. Now stop the backend server and disconnect from the network and re-run. You will see the below error.
```bash
 docker run -it --rm --name=plone -p 8080:8080 -e SITE=Plone -e ADDONS="kitconcept.volto" -e ZCML="kitconcept.volto.cors" -e PROFILES="kitconcept.volto:default-homepage" plone
```

![Screenshot from 2020-04-02 20-13-53](https://user-images.githubusercontent.com/33936987/78263533-b5a2c200-751f-11ea-8304-cd89c01088c8.png)

**Comment by tisto** [comment]
@iFlameing odd. I don't know much about our docker images. Maybe @sneridagh or @avoinea can help here...

**Comment by avoinea** [comment]
@iFlameing @tisto 

That's because you used `--rm` and the docker container is removed every time you stop it. To fix this, you should run it like:

**First run:**
```
$ docker run -d --name=plone -p 8080:8080 -e SITE=Plone -e ADDONS="kitconcept.volto" -e ZCML="kitconcept.volto.cors" -e PROFILES="kitconcept.volto:default-homepage" plone
```

**Stop**
```
$ docker stop plone
```

**Start**
```
$ docker start plone
```

**Logs**
```
$ docker logs -f plone
```

Also, it requires internet connection because you're using Plone with a custom add-on from pypi.org . If you don't use [kitconcept.volto](https://pypi.org/project/kitconcept.volto/) customization, you can just run it like:

```
docker run -it --rm -p 8080:8080 -e SITE=Plone plone
```

**Comment by iFlameing** [comment]
I think we should update the docker command by just removing --rm because we don't want to pull the Plone image every time and close this issue. Any more thoughts? @tisto

**Comment by sneridagh** [comment]
For development, if using Docker, one should know that the --rm creates an expendable container. The README are for quick start, not for development or for deploying.
