### ISSUE TITLE
The right sidebar should allow full-screen mode

### ISSUE THREAD

**Issue by avoinea** [plone/volto#1345]
For better UX on metadata editing the right sidebar should allow expansion:

![sidebar-fullscreen](https://user-images.githubusercontent.com/323385/78802800-e7f06b80-79c6-11ea-8c0a-b2d8eb150697.gif)

**Comment by tisto** [comment]
@avoinea nice! I would love to hear what @albertcasado thinks about the UX. This is just a detail. Though, when clicking on an "X" icon I'd except to go full screen and not "just" expand to the left.

**Comment by sneridagh** [comment]
Albert said:
Yes, expanding the details may help a lot. The x is not for that. You will need to add a expander icon that calls the expand. The typical < that reverse to > when expanded

Better if you place that left to the title but check it is not perceived as a back

If this icon < > does not work go for a maximise and minimise icons. I will take a look this weekend!

**Comment by tisto** [comment]
"<" and ">" makes sense to me as a user. Though, this is something we can test do user tests on. I am wondering if it would be better to put the icons to the left side of "Document" and "Block". Right now you click on the right side of the sidebar to expand it to the left.

**Comment by avoinea** [comment]
This is how it looks with `<` and `>` on the right:

![icon-on-right](https://user-images.githubusercontent.com/323385/79240137-08626f00-7e7a-11ea-9dc4-c37566818b58.gif)

**Comment by avoinea** [comment]
This is how it looks with < and > on the left:

![icon-on-left](https://user-images.githubusercontent.com/323385/79240243-3182ff80-7e7a-11ea-886a-7178140aaab2.gif)

**Comment by tisto** [comment]
Is it possible to align "Document / Block" on the left even if we place the <> icons on the left?

Visually I kind of like this. Though, I am not sure from the UX perspective if that's an improvement or not. It would be nice to hear @albertcasado opinion. The other option is we merge it and wait for feedback from our users/clients.

**Comment by avoinea** [comment]
Something like this:

![icon-on-left-align](https://user-images.githubusercontent.com/323385/79241099-414f1380-7e7b-11ea-858f-a0a60df1de9e.gif)

**Comment by tisto** [comment]
Yeah. I like it. What do you think @sneridagh?

**Comment by sneridagh** [comment]
@avoinea looks good! Thanks!! Tomorrow evening I've scheduled a talk with Albert. We will review all the latest changes and this one as well. I'll tell you!

**Comment by sneridagh** [comment]
@avoinea he already gave his blessings :) btw, I realised that the PR is not updated with that change, can you update it?

**Comment by avoinea** [comment]
@sneridagh Done!
![icon-final](https://user-images.githubusercontent.com/323385/79330001-6d24d480-7f21-11ea-8a8c-aa797c54c6c0.gif)
