### ISSUE TITLE
Control Panel still use Semantic UI icon font - can't set all icons available

### ISSUE THREAD

**Issue by avoinea** [plone/volto#1349]
![broken-icons](https://user-images.githubusercontent.com/323385/78904531-5ac01c00-7a85-11ea-951d-58cec2390b67.png)

**Comment by sneridagh** [comment]
Yes, we should deprecate the use of semantic UI icon font in favor of the SVG one. The control panel overview are still using them. I will change the name of the issue, if you are fine with that. Any use case where we want to use the font? I think we should move all icons to SVGs.

**Comment by avimishra18** [comment]
I think this issue can be closed. Icons seem to be updated. 🙂
