### ISSUE TITLE
Editor should use large/small "T" to indicate large/small headlines instead of H1/H2

### ISSUE THREAD

**Issue by tisto** [plone/volto#135]
The editor on medium.com uses a large "T" to indicate a large headline and a small "T" to indicate a smaller headline. I think this is more user friendly than using technical definitions like "H1" and "H2" like we currently do.

![medium-style-toolbar](https://user-images.githubusercontent.com/632105/38500719-897500b6-3c0b-11e8-91f1-c71fc1c47a99.png)

I'd recommend that we adapt this. @sneridagh @albertcasado is it possible to add those icons to the Pastanaga icon set?

**Comment by davisagli** [comment]
What about a large "H1" for large headline and a small "H2" for smaller headline? Then it both indicates visually what it does, and means something to the users who are familiar with HTML. I don't feel strongly about it though.

Actually I like tinymce's approach of including the headlines on a Formats menu, formatted with their actual styles. This is tangential to this ticket, but I know that my users will need the ability to apply custom formats.
