### ISSUE TITLE
Hydrating a component with `dangerouslySetInnerHTML` coming from SSR fails and shows empty

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#137]
so basically all richtext fields fail to show coming from SSR.

It seems a React v16 bug that it's still open:

https://github.com/facebook/react/issues/11789

There's a PR to fix it but Dan Abramov didn't like it...
https://github.com/facebook/react/pull/11792

We can use old render method but I guess it's not future proof, and console complains.

/cc @robgietema @tisto

**Comment by Yauheni-blr** [comment]
temporally resolved that problem via internal state.

{
  canShow: false
}

componentDidMount() {
  handleAllow()
}

handleAllow just sets canShow: true

additionally have added loader until component will mounted.

**Comment by sneridagh** [comment]
@Yauheni-blr Workaround:

1. Use the old `render` react-dom method instead of hydrate.
2. Call .toString() in all elements that use `dangerouslySetInnerHTML` which can be tedious.

**Comment by Yauheni-blr** [comment]
@sneridagh 

3. have a pain when render method will be deprecated :)
upd: same story with lifecycle hooks. 

P.S. improvement the quality of the code as usually better than destroyed app.

**Comment by sneridagh** [comment]
Fixed in release 1.5.2
