### ISSUE TITLE
Listing Block: sort by effective date, reverse sort order has no effect

### ISSUE THREAD

**Issue by tisto** [plone/volto#1373]
1) login as admin
2) create a page with a listing block and two pages with effective date set
3) listing block config: sort by effective date, reverse sort order
-> reverse sort order has no effect on listing block results

![Seite bearbeiten (8)](https://user-images.githubusercontent.com/632105/79254024-672ce600-7e84-11ea-8117-a8d09407e147.png)

**Comment by davisagli** [comment]
This was resolved by disabling the sort option when there are no criteria (then the results come from contained `items` rather than the `@querystring-search` endpoint).
