### ISSUE TITLE
Two buttons with the same purpose in new control panels actions

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#1374]
@avoinea when I revised the PR I thought we were removing the "back" button.

<img width="186" alt="image" src="https://user-images.githubusercontent.com/486927/79261989-e1fbfe00-7e90-11ea-80ed-952dca57978f.png">

We can't expose two buttons that do the same (back and cancel).

**Comment by avoinea** [comment]
I know, but how do you go back after save? 

Hitting the Cancel button after Save didn't seem right to me.

**Comment by sneridagh** [comment]
I will ask Albert tomorrow!

**Comment by avoinea** [comment]
Best we can do here is to drop the Cancel button, but this doesn't feel right, either :smile:

**Comment by sneridagh** [comment]
@avoinea After a talk with Albert, he is more in favor of dropping the back button, if we go full consistent with the content forms, then we go full in.

**Comment by sneridagh** [comment]
Fixed in: #1409
