### ISSUE TITLE
Multilingual: navigate to page that's not a default language page

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#1401]
- my defaultLanguage in config.js is 'it', and my availableLanguages in config.js are ['it','en']
- If i'm in anonymous navigation browser mode and i type the url of a page of en language, for example i type http://localhost:3000/en/experiences/visit-to-the-ferrari-vinegar-factory
- i see the right content, but i18n translation are wrong, they are translated in default language (it) and not in resource-language (en). 

I think this is because in this case the cookie 'lang' is not set

**Comment by sneridagh** [comment]
https://github.com/plone/volto/pull/1450 should fix this!
