### ISSUE TITLE
Show maximum number of allowed characters in a Volto form textfield

### ISSUE THREAD

**Issue by tisto** [plone/volto#1412]

**Comment by iFlameing** [comment]
@tisto I have implemented this in current text filed but we don't want this for every field. We need to discuss it tomorrow. Here is the screenshot for that :)
![Screenshot from 2020-04-23 21-06-16](https://user-images.githubusercontent.com/33936987/80118899-a35bf700-85a6-11ea-9c64-e8b81ab873f2.png)

**Comment by tisto** [comment]
@iFlameing nice!
