### ISSUE TITLE
Gallery component

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#1426]
It would be nice to have a gallery component.

I put an eye on: https://www.npmjs.com/package/react-image-gallery

Can we search for some other options, then make a decission?

We will need to load it lazily, of course.

**Comment by tisto** [comment]
ToDo:

- [ ] Create a new view for the listing block
- [ ] Make that view selectable in the listing block
- [ ] Add react-image-gallery as a dependency to Volto
- [ ] Add view that uses react-image-gallery and relies on the listing block
- [ ] Create a Cypress test that creates a page that contains images, adds a listing block with a gallery-view view and displays images
