### ISSUE TITLE
Implement srcset and sizes for images in Volto

### ISSUE THREAD

**Issue by tisto** [plone/volto#1428]
Todo:

- [x] Define new scale formats for Plone (we currently have 200/400/800/1200/1600)
- [x] Implement new scale formats in kitconcept.volto (preliminary until PLIP has been accepted) -> https://github.com/kitconcept/kitconcept.volto/blob/main/src/kitconcept/volto/profiles/default/registry.xml#L23
- [ ] Amend image block to use srcset/sizes
- [ ] Amend hero block to use srcset/sizes
- [x] PLIP new image sizes for Plone 6 https://github.com/plone/Products.CMFPlone/issues/3279
- [ ] PLIP accepted by FWT
- [ ] PLIP merged into Plone 6

@datakurre already did most of the work in this commit: https://github.com/datakurre/my-volto-app/commit/89c86ba93db2ad404f45a7dfc5fc9dde686390e6

Twitter found out that 3x for retina is not worth the effort: https://blog.twitter.com/engineering/en_us/topics/infrastructure/2019/capping-image-fidelity-on-ultra-high-resolution-devices.html

**Comment by datakurre** [comment]
https://ausi.github.io/respimagelint/

**Comment by sneridagh** [comment]
Implemented in https://github.com/plone/volto/pull/3337
