### ISSUE TITLE
IBlockConverter story

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#1432]
Added `IBlockConverter` concept, use named adapters to convert deserialized value
of blocks, this enables an extensible mechanism to transform block values on
add/edit content operations.

Concept and HTML converter (ready to merge):
https://github.com/plone/plone.restapi/pull/915

@tiberiuichim I can't find the one that makes the resolveuid work with this. Didn't you create one? The one that should be merged with @cekk related PR too.

@tiberiuichim I can't also find the one with the deferred image creation! Can you provide the current state? Let's not forget this!

Apply same concept for indexers:
https://github.com/plone/plone.restapi/pull/917

**Comment by cekk** [comment]
@sneridagh i see that there is already a resolveuid converter/transformer.
My pr was about making the old serializer more generic and manage images and all blocks with url/href field too.
I don't remember what we decided about this feature: if it's ok to have a default converter like this, or not

**Comment by tiberiuichim** [comment]
Closing in favour of #2078
