### ISSUE TITLE
Language isn't set properly on html Element

### ISSUE THREAD

**Issue by AlexBueckig** [plone/volto#1434]
I'm not sure if this is a thing that only happens with i18n enabled but the html element gets the language `[object Object]`. 

The issue is related to assigning `this.props.content.language`to the lang tag [here](https://github.com/plone/volto/blob/da5c34aa9d9d56c5c15124dbcae3a15dd009891d/src/components/theme/View/View.jsx#L223) . According to redux `this.props.content.language` is an object with the shape `{title: "Deutsch", token: "de"}` . 

Setting it to `this.props.content.language.token` instead solves the issue.

**Comment by sneridagh** [comment]
Doh, true! I will fix it!
