### ISSUE TITLE
Expose system information in Volto control panel

### ISSUE THREAD

**Issue by tisto** [plone/volto#1457]
Classic Plone exposes system information in the control panel overview:

![demo_kitconcept_com](https://user-images.githubusercontent.com/632105/81375886-ba502c80-9102-11ea-8703-e125375a1183.png)

The new Plone REST API system endpoint allows us to expose this information in Volto as well:

https://github.com/plone/plone.restapi/pull/735

**Comment by sneridagh** [comment]
https://github.com/plone/volto/blob/e210ac522f90ee1fe2ca47a7238ecd43fd7baa1c/src/components/manage/Controlpanels/VersionOverview.jsx#L12
