### ISSUE TITLE
Add cypress test for comments

### ISSUE THREAD

**Issue by jackahl** [plone/volto#1482]
In Volto 5.9.0 comments are broken without it being noticed right away. So it would be great to have a cypress test for them. 
I already created a setregistry function which is usable to globally enable comments in the test setup: https://github.com/plone/volto/pull/1481

**Comment by tisto** [comment]
We need to:

- [ ] Enable comments globally
- [ ] Enable comments on createContent(..., allowDiscussion=True) (this should set allowDiscussion = True on the REST API)
