### ISSUE TITLE
Take the widgets out of the wrappers

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#1500]
to use them in Volto sites, for example in edit blocks.

Now widgets are wrapped into Grid.Row/Grid.Columns with label before. 
If you would like to use them in edit block, you don't always need the label or the structure Grid.Row/Grid.Column, but simply the widget for the field

**Comment by tiberiuichim** [comment]
I'd love to see the widget framework reworked a bit... something like a wrapper function that would set the input into the proper place. This would make it easier also to write new widgets

**Comment by sneridagh** [comment]
+1

**Comment by giuliaghisini** [comment]
Branch: https://github.com/plone/volto/tree/take_widgets_out_from_wrappers_%231500
Pull: https://github.com/plone/volto/pull/1551
