### ISSUE TITLE
Not possible to remove an expiration date

### ISSUE THREAD

**Issue by tisto** [plone/volto#1501]
1) as admin
2) create a page and set an expiration date
3) edit that page and try to delete the expiration date
-> there is no obvious way to delete a date once set (this is a UX problem)
-> if the user selects the date and hits the delete key the date/time is greyed out but after save the old expiration date is still set (this is a bug)

@nzambello did you run into this problem already? Does the datepicker lib support the removal of a date once set?

@iFlameing could you please write a Cypress test for this (that fails right now of course)?

**Comment by sneridagh** [comment]
duplicated of #1422
