### ISSUE TITLE
Bug in Richtext render in DefaultView.jsx

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#1509]
https://github.com/plone/volto/blob/master/src/components/theme/View/DefaultView.jsx#L85-L88

Buggy when a mailto: can be used, then it got replaced too.

Since we are already treating it in:
https://github.com/plone/volto/blob/master/src/config/RichTextEditor/ToHTML.jsx#L173-L197

I think we can assume we can remove it.

**Comment by nileshgulia1** [comment]
closed via #1545
