### ISSUE TITLE
Volto internationalization (i18n) for Romanian

### ISSUE THREAD

**Issue by avoinea** [plone/volto#1521]
Branch: https://github.com/plone/volto/tree/eea-ro-translation

**Comment by macagua** [comment]
@avoinea @alecghica Hi guys please check the Contributing translations for a unsupported language guide for VoltoCMS https://docs.voltocms.com/customizing/i18n/#contributing-translations-for-a-unsupported-language

**Comment by alecghica** [comment]
PR merged.
