### ISSUE TITLE
new block type for FAQ

### ISSUE THREAD

**Issue by ksuess** [plone/volto#1524]
It's a recurrent request to have a helper for adding a faq section in Plone pages. So, I thought it would be nice to have some helper also in Volto. What about an additional block type _faq_ that provides the editor with a widget in sidebar where he can type question and answer and add additional question and answer sets.

What do you think, does it make sense to offer this in Volto or is it something for an add-on?

![faq_sidebar](https://user-images.githubusercontent.com/1144737/82900418-c8a0a400-9f5c-11ea-945a-9ff9b5c20461.png)
 
     
_
      
And a rendering like 

![faq](https://user-images.githubusercontent.com/1144737/82897956-c2a8c400-9f58-11ea-802b-9464c727b15c.png)

**Comment by tiberiuichim** [comment]
I like the interface for the multiple entries list, I'll adopt it for the ObjectListWidget.

**Comment by tisto** [comment]
Our use case for FAQ so far was full FAQ pages and we are using https://pypi.org/project/collective.faq/ together with a custom Volto view.

This blocks FAQ would be a nice addition for Volto. Though, I'd be careful with adding too many blocks to Volto core. Those blocks all need to be maintained over time, require upgrade steps if they change, need proper documentation and testing, etc.

My personal opinion is that this would be a nice Volto add-on product. Of course we need an add-on product architecture first.

**Comment by ksuess** [comment]
Yes, I see. Thought so, that a lot of blocks would be useful, but crowding the menu. So let's postpone it to an add-on.

BTW I like a simple block for FAQ without Instances for every single FAQ item.

**Comment by ksuess** [comment]
A new block type for FAQ could be part of an add-on.
