### ISSUE TITLE
Avoid separate fetching of navigation, breadcrumbs, actions and types

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1527]
There is the argument that 5 separate requests to the backend would result in a faster UI for the end users. 

I'm not convinced and of course we have to setup some plone.restapi benchmark locus tests to be convinced, but traditionally threads have been a limited resource in Zope server and having multiple concurent requests running also increases the chance of DatabaseConflictError. There is an overhead in serializing and publishing 4 additional responses, which also needs to be taken into consideration. 

These four endpoints are also available as expand elements in plone.restapi. My proposal is to include them in getContent action, (also make getContent take query options, also include a setting for default expands to include in the getContent call).

The main problem that this would avoid is that the UI feels disconnected if the backends are slow. For anonymous users this is represented by three components: the Breadcrumb, the global Navigation and the main content represented in the View, but for the authenticated users having the Actions and the available context Types not represent the true context can be a source of frustration in site editing and administration.

**Comment by sneridagh** [comment]
@tiberiuichim @robgietema @tisto we should discuss this one as well.

**Comment by ichim-david** [comment]
Nowadays the requests are done together by default from the apiExpander so this is now solved.
https://github.com/plone/volto/pull/4946
