### ISSUE TITLE
Copied relative link is transformed to absolute link

### ISSUE THREAD

**Issue by tisto** [plone/volto#1529]
When you edit a page and copy a relative link the pasted version is an absolute link that opens in a new tab.

Steps to reproduce:

1) Add a new page with a relative link to say, the "news" section in Plone and save
2) On the page view or on the edit view select and copy the link
3) create a new page and paste the link you copied, hit save
-> the link will not work after pasting

**Comment by iFlameing** [comment]
@tisto can you tell me how I can reproduce it?

**Comment by nileshgulia1** [comment]
@tisto Is this still an issue, cannot able to reproduce it.

**Comment by danalvrz** [comment]
It’s not currently possible to enter a relative link at all, so I proceed to close this issue as not planned.
