### ISSUE TITLE
Workflow states in Volto are not translated

### ISSUE THREAD

**Issue by tisto** [plone/volto#1530]
1) Go to volto.kitconcept.com
2) login as admin
3) create a page
-> workflow state (e.g. private) is not translated (everything else is translated)

Nice to have: Cypress tests that test if the translation works (requires a backend test fixture, so this might be complex)

**Comment by iFlameing** [comment]
@tisto I am unable to reproduce it. Can you attach screenshots?

![Screenshot from 2020-05-29 15-15-32](https://user-images.githubusercontent.com/33936987/83246277-81feb400-a1bf-11ea-9561-21b8134ffba1.png)

**Comment by tisto** [comment]
![](https://cdn.discordapp.com/attachments/714749305612664853/715887136716488734/Screenshot_2020-05-29_at_13.19.47.png)

**Comment by sneridagh** [comment]
This has been fixed in https://github.com/plone/volto/pull/3615
