### ISSUE TITLE
[Addons] Extend razzle.config.js from addons

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#1532]
meta issue: #1433

**Comment by tiberiuichim** [comment]
``razzle.config.js`` in an addon is in the the addon ``src`` folder.

**Comment by tiberiuichim** [comment]
The razzle.config.js from an addon can export both razzle config wrappers but also razzle plugins.
``
module.exports = {
   modify: (config) => config,
   plugins: [list_of_razzle_plugins],
}
```
