### ISSUE TITLE
Upgrade raven-js to @sentry/browser

### ISSUE THREAD

**Issue by pnicolli** [plone/volto#1544]
``raven-js`` is legacy software, sentry has a new browser integration available as ``@sentry/browser``.

I found the upgrade that gitlab did to its own service here https://gitlab.com/gitlab-org/gitlab/-/merge_requests/17715/diffs
It doesn't look like a very complex task.

Would it break existing configurations? This is something I don't know, I assume it could, if custom sites rely on importing ``raven-js``, which wouldn't exist anymore, so this is maybe something for Volto 7.

**Comment by pnicolli** [comment]
Even better, guidelines provided on the sentry forums: https://forum.sentry.io/t/switching-to-sentry-javascript/4732

**Comment by sneridagh** [comment]
If the API is different should be a breaking, yes.

**Comment by pnicolli** [comment]
@sneridagh Is a 7.alpha branch planned already? If this is breaking we need a target for the PR

**Comment by tisto** [comment]
@pnicolli you can create a PR for master. We are not afraid of raising version numbers. :)

If we have a breaking change we need an entry and a howto in our upgrade guide, that's all. Then we can do a 7.0.0 final release. We only do alpha releases if the change is so fundamental that we need an additional testing/evaluation period.
