### ISSUE TITLE
Enhancements to the default bundle analyzer plugin integration

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1548]
In some environments the default bundle analyzer is not directly usable (for example if the razzle process runs in a docker container, etc).

My proposal is to change the bundle analyzer to something like this:

```
{
    name: 'bundle-analyzer',
    options: {
      analyzerHost: '0.0.0.0',
      analyzerMode: 'static',
      generateStatsFile: true,
      statsFilename: 'stats.json',
      reportFilename: 'reports.html',
      openAnalyzer: false,
    },
  },
```

This saves the bundle stats, so it's possible to review them without going through a lengthy build process. Then you can run separately ``webpack-bundle-analyzer bundle/output/path/stats.json``, or even just open the ``reports.html`` in a browser.

**Comment by ichim-david** [comment]
This configuration is set like this issue suggests
https://github.com/plone/volto/blob/main/packages/volto/webpack-plugins/webpack-bundle-analyze-plugin.js#L8
