### ISSUE TITLE
Visible URL used as a link target is not transforme into API URL (nor UID)

### ISSUE THREAD

**Issue by datakurre** [plone/volto#1570]
Something we have seen in production Volto:

1. User creates link in text block by selecting text and clicking linking action
2. Because of huge amount of similarly named pages, user is unable to choose the right page by searching it
3. As a workaround, user pastes visible URL from browser as a link target (e.g. "https://volto.kitconcept.com/a-new-page")
4. User saves the page. Link seems to somewhat work. User is happy.

Unfortunately, the target URL is saved as such and never transformed into the backend API url nor UID at the backend.

A better link target dialog might help to fix this somewhat, but I wonder if there is realiable way to detect published URL and transform it into API URL during save.

**Comment by tisto** [comment]
We saw this happening as well. We should convert those links into UUIDs internally.

**Comment by datakurre** [comment]
I’d guess that either Volto frontend or middleware should detect this and convert the visible URL into API url. As long as the API URL really exists on the backend, REST API (block transforms) ould convert it into UUID.


Timo Stollenwerk <notifications@github.com> kirjoitti 6.6.2020 kello 16.22:

**Comment by davisagli** [comment]
Currently, internal links are converted to UID-based URLs in general. If this still doesn't work, please open a new issue.
