### ISSUE TITLE
Refactor block editing sidebars using InlineForm

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1577]
The proposal is to write schemas for all block sidebar form components and use the ``InlineForm`` component to enable their editing. It would require defining new widgets where they don't exist (for example the AlignWidget, ImageSize Widget, etc.

**Comment by sneridagh** [comment]
This is currently in progress, only a few stock blocks are left to convert to schema.

**Comment by davisagli** [comment]
@sneridagh which ones? Might help to create an issue for each one.

**Comment by ichim-david** [comment]
As Victor mentioned there is only one Sidebar component left without using BlockFormData which is using InlineForm.
I'm closing this ticket as I added a follow through for the one component left.
