### ISSUE TITLE
Blockquote: error when text has some style

### ISSUE THREAD

**Issue by cekk** [plone/volto#1601]
**Short:** If a text inside a blockquote has some styles (bold, italic for example), the view breaks.
**Steps to reproduce:**
- Go to edit mode of a page in Volto
- Add some text in a text block
- Add some more text to that block in a new line using shift+enter keys
- Add some style to some words (for example bold)
- Mark all the text you have just written and select the blockquote option for it
- Save the page

Result: The page breaks.
Expected: we see linebreaks and styles in blockquote

This bug is related to the changes made in #1249

**Comment by cekk** [comment]
@iFlameing any idea on how to fix it? i'm missing some logic on how draftjs data structure works

**Comment by iFlameing** [comment]
@cekk I found the problem. Working on fixing it.

**Comment by sneridagh** [comment]
Closing, since it's a draftJS issue and seems quite outdated.
