### ISSUE TITLE
DateTime Widget: current time is off two hours

### ISSUE THREAD

**Issue by tisto** [plone/volto#1617]
1) as admin
2) go to https://volto.kitconcept.com
3) create a new document (https://volto.kitconcept.com/add?type=Document)
-> the current date placeholder in the effective/expiration date is two hours off (two hours less)

![Add_Document (7)](https://user-images.githubusercontent.com/632105/85370876-b4d26880-b52f-11ea-9084-4c7d532c10c6.png)

**Comment by tiberiuichim** [comment]
Maybe related to #1587

**Comment by mihai-macaneata** [comment]
#1587 will fix this issue by synchronizing the timezones between server and client via config

**Comment by tisto** [comment]
@mihai-macaneata awesome!
