### ISSUE TITLE
It is not possible to click-select "Unknown blocks"

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1621]
If for some reason you have block ``@type`` coming from the backend that's unknown to the current Volto running, it is not possible to focus them with a mouse click, but you can navigate to them with up-down arrows from the other blocks.

**Comment by nileshgulia1** [comment]
Hi @tiberiuichim . Can you please outline ways to reproduce this, It'll be great if you have an example for this.

**Comment by tiberiuichim** [comment]
@nileshgulia1 

1. create some image blocks, save the content
2. Comment the image block declaration here: https://github.com/plone/volto/blob/master/src/config/Blocks.jsx#L164

This would render the image blocks as "Unknown type" in Volto, and you'll see that they're not selectable in Volto visual editor form.

**Comment by nileshgulia1** [comment]
@tiberiuichim Its fixed . Please add your review #1686
