### ISSUE TITLE
Image block: can set size for external images but it's not used in view

### ISSUE THREAD

**Issue by cekk** [plone/volto#1623]
In edit mode, i can select the size of an external image (S, M or L).
The image in the block (in edit mode) is resized based on the selection but when i save, i see the image with his original size.

Probably because in view mode there isn't the proper class set ("medium" for example).

**Comment by nileshgulia1** [comment]
@cekk . I cannot able to reproduce this. Maybe if I'm doing wrong way, If possible can you please outline steps on how to reproduce this?

**Comment by cekk** [comment]
You're right. This should be fixed in v6.5.0
