### ISSUE TITLE
Replace custom Volto LESS loader with razzle-plugin-less

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1646]
Unfortunately, at this moment this plugin is not yet published:

https://github.com/jaredpalmer/razzle/tree/next/packages/razzle-plugin-less

Courtesy of multi-repos and synchronized release cycles. In any case, I'd love to see if we can get rid of Volto's LESS loader in razzle.config.js, it would simplify things.

**Comment by nzambello** [comment]
Good catch, we should keep an eye on that for when it will published

**Comment by tiberiuichim** [comment]
It's not actually possible to replace the custom Volto plugin because of semantic-ui less loading needs. Current volto includes a customized copy of that plugin.
