### ISSUE TITLE
Uploading an image in the Image block replaces the global state.content store

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1654]
CREATE_CONTENT_SUCCESS reducer:

https://github.com/plone/volto/blob/master/src/reducers/content/content.js#L131

Upload of image:

https://github.com/plone/volto/blob/master/src/components/manage/Blocks/Image/Edit.jsx#L180

I propose that we implement my transformer-based approach to the Image upload.

**Comment by tiberiuichim** [comment]
@nzambello Your ideas on this?

**Comment by nzambello** [comment]
I don't know right now the best solution, but can't we manage the creation action using a subrequest or something like that?
That's how getContent works, you can call it in a subrequest and I think this is what we're missing here.
