### ISSUE TITLE
Update react-dropzone to newer version

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1682]
Right now react-dropzone is pinned at a very old 5.1.0 version, while the latest is 11.something. It wouldn't be a problem in itself, except that the API is very different and Volto developers need to be aware of this fact, to research older documentation.

**Comment by tisto** [comment]
@tiberiuichim good point. @iFlameing maybe you can look into this next week.

**Comment by iFlameing** [comment]
@tisto react-dropzone has breaking changes we have to refactor all the dropzone component to newer API. What do you want me to do?
