### ISSUE TITLE
Horizontal overflow of folder contents but no scrollbar available

### ISSUE THREAD

**Issue by zopyx** [plone/volto#1689]
Adding extra columns through "columns to show" causes a horizontal overflow of the table.
There is horizontal scrollbar available in order to reach the right-most columns.

**Comment by nileshgulia1** [comment]
@zopyx  Please review #1697

**Comment by sneridagh** [comment]
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/486927/159439655-3356ad8f-6f8e-4be7-b79f-e1d6431df195.png">

Fixed quite a while.
