### ISSUE TITLE
Pastanaga Editor: Rich text toolbar shows up in multiple lines when text is selected at the edges

### ISSUE THREAD

**Issue by tisto** [plone/volto#169]
Steps to reproduce:

1) Go to https://plone-react.kitconcept.io/front-page/edit
2) login as admin
3) Select "this" (last term on the first paragraph)

![plone-react-draftjs-bug-toolbar](https://user-images.githubusercontent.com/632105/41511299-97d4dccc-7274-11e8-9fec-7d753d9b76d0.png)

![plone-react-editing-toolbar-right](https://user-images.githubusercontent.com/632105/41511404-548ba7d2-7276-11e8-911c-9d524873c96a.png)

-> Expected behavior: toolbar should always show in one line.

**Comment by robgietema** [comment]
Related to #170

**Comment by tisto** [comment]
Discussion at Ploneconf 2018 in Tokyo with @albertcasado @sneridagh @tisto @robgietema:

The toolbar should stay in one line and move to the left / right so that it is always displayed in full.

Albert's design does not contain the arrow at the bottom that could make this more complicated, so we should get rid of it.

**Comment by tiberiuichim** [comment]
The current situation 
![Screenshot_20201120_095546](https://user-images.githubusercontent.com/141568/99774547-98eee500-2b16-11eb-8f4e-8a7072a4cef9.png)

Narrow to the left side is bad also

![Screenshot_20201120_095752](https://user-images.githubusercontent.com/141568/99774745-e2d7cb00-2b16-11eb-9608-86bf62a71679.png)

volto-slate partially solves this problem by detecting the left edge and also zindexing above the sidebar.
Though I think we need better UI for such big toolbars.

![Screenshot_20201120_095846](https://user-images.githubusercontent.com/141568/99774883-10247900-2b17-11eb-803c-c1171276ea2c.png)
