### ISSUE TITLE
Missing next & previous icons in contents view

### ISSUE THREAD

**Issue by robdayz** [plone/volto#1690]
In Volto contents view, with a big list of items (to force pagination), you can see 'next' and 'previous' icons to move through pages, but icons are not displayed/loading  :( 

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/506444/88193531-11639900-cc3e-11ea-806d-e0aee7fd0d47.png">

**Comment by nileshgulia1** [comment]
@robdayz Just noticed that, maybe semantic-ui icons are not loading inside the Menu. We can render using our Icon component.

**Comment by nileshgulia1** [comment]
@robdayz see #1693

**Comment by robdayz** [comment]
Merged! Thanks @nileshgulia1
