### ISSUE TITLE
Make pages folderish and plone site pagish

### ISSUE THREAD

**Issue by robgietema** [plone/volto#17]
The rest api doesn't have support to select an item as the default view. This concept is has long been a discussion and should be removed. For this to work we need the pages to be folderish so we don't need a default view anymore but the page can have rich text and also contain items. The plone site root object also needs to have rich text so we can edit the front page.

**Comment by tisto** [comment]
@robgietema it would be cool if an add-on product together with plone.restapi could provide that out-of-the-box.

**Comment by robgietema** [comment]
@tisto Agree! I'll talk to @jaroel to see if we can implement this.

**Comment by robgietema** [comment]
To make pages (etc) folderish we can use collective.folderishtypes.

The Plone site is missing a schema to add content (like a page). Also the workflow and schema rest api calls won't work. So converting the Plone Site Root object to Dexterity could be an option.
