### ISSUE TITLE
Editing toolbar styling

### ISSUE THREAD

**Issue by tisto** [plone/volto#170]
We currently use an editing toolbar with a white background color. This makes it hard to differentiate the toolbar from the background.

medium.com uses a toolbar with a black background color:

![image](https://user-images.githubusercontent.com/632105/41511366-dbdefa32-7275-11e8-97ab-e769e6c1e255.png)

I am not a designer but maybe this would be a better fit. What do you think @albertcasado @sneridagh @robgietema?

**Comment by robgietema** [comment]
The toolbar is currently implemented using the draft-js-plugins toolbar. We need this to be changed to use Semantic-UI components.
