### ISSUE TITLE
Cypress tests failing

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1704]
There are some current PR where travis fails the Cypress tests.

I've tried locally and I can replicate the fails. They're related to the scaling of images performed in kitconcept.volto.

I've got as far as:

In `cypress/support/commands` there's a sample image, exposed as base64-encoded data. When decoding some of its first characters,  `iVBORw0KGgoAAAANSUhEUgAAANcAAAA4CAMAAABZsZ3QAAAAM1BMVEX29fK42OU`, we get this valid PNG header: `PNG...IHDR8Y3PLTE`. The problem is that the data in kitconcept.volto is missing some of the beginning characters:

```
@(Pdb) xx = data.read()
@(Pdb) p xx[:10]
b'hEUgAAANcA'
```

In the CGI storage of the request, the file data is ok, but base64 encoded: `aVZCT1J3MEtHZ29BQUFBTlNVaEVVZ0FBQU5j
QUFBQTRDQU1BQUFCWnNaM1FBQUFBTTFCTVZFWDI` which decodes to `iVBORw0KGgoAAAANSUhEUgAAANcAAAA4CAMAAABZsZ3QAAAAM1BMVEX2` which decodes to `PNG...IHDR8Y3PLTE`. 

So it looks like there's some bits that are lost in kitconcept.volto. Maybe a file being read without seek(0) ?

**Comment by tisto** [comment]
@tiberiuichim I just started to look into this myself. Maybe we should just add a new base64 encoded png to kitconcept.volto to fix this.

**Comment by tisto** [comment]
@tiberiuichim I accidentally added a new Cypress test in a release commit which started the master branch to fail. I removed it and now master is green again.

**Comment by tiberiuichim** [comment]
Probably closed by https://github.com/plone/volto/pull/1823
