### ISSUE TITLE
Listing Block crashes when switching to Image Gallery Template

### ISSUE THREAD

**Issue by jackahl** [plone/volto#1722]
Steps to reproduce: 

1. add a new listing block to page
2. Choose Image Gallery as template. (Do not add any criteria before!)
-> `TypeError: item[_config__WEBPACK_IMPORTED_MODULE_4__.settings.listingPreviewImageField] is undefined`

It does not happen when a criteria is set.

**Comment by nileshgulia1** [comment]
fixed by #1723
