### ISSUE TITLE
Sidebar labels partially hidden

### ISSUE THREAD

**Issue by ksuess** [plone/volto#1726]
Long labels are partially hidden. 
![grafik](https://user-images.githubusercontent.com/1144737/90238490-5ab29d00-de26-11ea-966e-1f060503692a.png)

Maybe a _hyphens: auto_ to wrap them could be enough.

![grafik](https://user-images.githubusercontent.com/1144737/90238465-51293500-de26-11ea-8090-463d24f4f64d.png)

**Comment by tisto** [comment]
@ksuess sounds like a good plan. PR is welcome :)
