### ISSUE TITLE
Subtle bug in Form.jsx unsafe_componentWillReceiveProps

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1734]
I've merged Volto master in the "form state with context hoc" PR and the tests run into a recursive update caused by https://github.com/plone/volto/pull/1732/files

I think the code is wrong there, as shown by this simple example:
```
> {a:'1'} !== {a: '1'}
true
```

Of course, it could be argued that the form state context should not be so sensitive. In any case, using lodash.isEqual(nextProps.formData, this.state.formData) is better and more true to the original intention.

**Comment by tisto** [comment]
@jackahl can you have a look into this?

**Comment by jackahl** [comment]
should be fixed in here: https://github.com/plone/volto/pull/1736
