### ISSUE TITLE
Compatibility with plone.restapi 7.x

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1739]
There's one incompatibility with plone.restapi 7.x block transformer.

The image transformer yields block URLs as [resolveuids](https://github.com/plone/plone.restapi/blob/900637ce927df69bc6aeddc844b3a25218f1c5b8/src/plone/restapi/deserializer/blocks.py#L149) . This has to be handled in [server.jsx](https://github.com/plone/volto/blob/c4d33c476d816d6fbe9ef0d10dffe10f66e0c970/src/server.jsx#L131)

**Comment by tisto** [comment]
@tiberiuichim could you provide the steps to reproduce this problem?

**Comment by tiberiuichim** [comment]
@tisto 

The obligatory

```
cd api
bin/develop co plone.restapi
bin/develop activate plone.restapi
bin/instance fg
```

Then in Volto, create a new page, save it, then edit it and add a new image block. Save the page. On the view page, you'll see that the images are linked as /resolveuid/uid links instead of the usual @@images/image links

**Comment by tiberiuichim** [comment]
Ah, but the code I've linked above is in the deserializer. It's ok if we store the Image link as a resolve uid. We just need to add the coresponding Serializer transformer for the Image block.
