### ISSUE TITLE
Addon: Let project pick dependencies of addons

### ISSUE THREAD

**Issue by ksuess** [plone/volto#1742]
Dependencies of addon package could be added to projects dependencies. Current Volto 7.7.1 does not.

**Comment by tiberiuichim** [comment]
You're supposed to add the addon as a project dependency. Adding it as an addon only activates its configuration loading and activates "Volto" for it.

**Comment by tiberiuichim** [comment]
Perhaps this could be better explained in documentation, though.

**Comment by tiberiuichim** [comment]
Oh, I now realize that you may not know about the "workspaces" configuration. You can allow the project to automatically pickup dependencies of development addons by adding the addon path in the "workspaces" key. See https://github.com/kitconcept/volto-form-builder/blob/master/package.json or https://github.com/collective/volto-example-project-addons/blob/usingmrsdeveloper/package.json
