### ISSUE TITLE
Addon: speaking error message

### ISSUE THREAD

**Issue by ksuess** [plone/volto#1743]
Creating an addon.
Until I got the export of a configuration function right, I got an error message, that could get a better formulation.
_getAddonsLoaderCode_
```
buf += `
const load = (config) => {
const addonLoaders = [${configsToLoad.join(', ')}];
return addonLoaders.reduce((acc, apply) => apply(acc), config);
};
export default load;
`;
return buf;
}
```
If the addon doesn't export a configuration function:
```
/Users/ksuess/Volto/IGIB/igib/build/webpack:/private/var/folders/8y/vdxyzw395vd28hbxft8rb2zw0000gn/T/tmp-33234qUgowkC6TKkE.js:12
  return addonLoaders.reduce((acc, apply) => apply(acc), config);
^
TypeError: apply is not a function
```

**Comment by tiberiuichim** [comment]
Indeed, you've provided a very nice solution for it.

**Comment by tiberiuichim** [comment]
Closed by https://github.com/plone/volto/commit/b28d1ea4fb1285c3f956c20dc996c39fcc498f17
