### ISSUE TITLE
Exposing project-wide Volto specific configuration

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1748]
Based on feedback from various Volto developers, it seems that it would be a nice thing to have the "addons" setting (now in package.json) also available in a separate file. This would enable easier reproduction of "testing" projects, where one can just create a new create-volto-app repo, drop the new `volto-config.json` file inside the project and have it running.

This would be the library to use: https://github.com/davidtheclark/cosmiconfig

**Comment by sneridagh** [comment]
Now we have a `volto.config.js` available in Volto, where one can define rules for delivering a specific `addon` key programmatically.

https://6.dev-docs.plone.org/volto/configuration/volto-config-js.html?highlight=volto%20config%20js
