### ISSUE TITLE
Can not create listing block with image gallery view

### ISSUE THREAD

**Issue by tisto** [plone/volto#1750]
1) as admin
2) go to https://volto.kitconcept.com
3) create a new document (https://volto.kitconcept.com/add?type=Document)
4) add a new listing block
5) Choose template "Image gallery" in the listing block
-> js error trace
![Add-Document](https://user-images.githubusercontent.com/632105/90862472-c1d3d280-e38d-11ea-933e-839d13f942c2.png)

@iFlameing please create a new PR with a Cypress test that fails and pass it to me for review. Once we proved that there is something wrong, you can start working on a fix.

**Comment by iFlameing** [comment]
Fixes by #1762
