### ISSUE TITLE
Event type should support ICS download

### ISSUE THREAD

**Issue by tisto** [plone/volto#1764]
It would be nice if the Volto event would allow users to download events as ICS. I guess we could just use the existing "ics_view" view of the Plone backend. It would be nicer to hide the backend though and add this link to Volto itself and maybe expose the ICS download link via REST API as well.

@giuliaghisini @nzambello is that something that you did in one of your projects maybe?

**Comment by giuliaghisini** [comment]
Hi @tisto , no we haven't needed it yet. But it would be a great functionality for all users!

**Comment by tisto** [comment]
@giuliaghisini we will look into it. Pointing to the existing ics_view in Plone should be trivial. Hiding the backend call might be more complex but maybe not necessary. Thanks for the feedback!

**Comment by davisagli** [comment]
This was fixed in https://github.com/plone/volto/pull/3358
