### ISSUE TITLE
Can't define custom action to get XML content from the backend

### ISSUE THREAD

**Issue by avoinea** [plone/volto#1771]
Trying to get content other format than `JSON` from the backend will end-up in a `null` response even if the request call is executed and the backend returns the right content:

``` jsx

import { GET_SVG } from './constants';

/**
 * Get SVG function.
 * @function getSVG
 * @param {url} url SVG URL.
 * @returns {Object} SVG Object.
 */
export function getSVG(url) {
  return {
    type: GET_SVG,
    request: {
      op: 'get',
      path: url,
      headers: {
        Accept: 'application/xml',
      },
    },
  };
}
```

![getSVG](https://user-images.githubusercontent.com/323385/91174406-e3172480-e6e7-11ea-96ed-1c4839276669.png)

**Comment by tisto** [comment]
@avoinea isn't that a plone.restapi issue? plone.restapi currently only supports json. Or does Volto somehow force "Application/json" for all requests send to the backend?

**Comment by tiberiuichim** [comment]
@tisto no, it's possible to use the Api for anything:

https://github.com/plone/volto/blob/master/src/helpers/Api/Api.js#L64

**Comment by tiberiuichim** [comment]
@tisto so, from Api.js you can see that Volto's API should be able to handle any any type of request. If the headers are set to a non-application/json Accept, than it's not plone.restapi's job to handle them. The only issue was that Volto wanted to retrieve only the json body from the response. With this change the text is passed as a fallback.
