### ISSUE TITLE
UX: User creates a new page with no title and a block. When hitting save there is no visual indication that the title is required and missing

### ISSUE THREAD

**Issue by tisto** [plone/volto#1776]
1) as admin
2) go to volto.kitconcept.com
3) create a new page (without typing in a title)
4) add a new image block (right sidebar will show the block details)
5) hit save button
-> nothing happens
-> the user is puzzled
-> you have to switch the sidebar to the "document" tab to see that there is a required field (title)

what should happen:
-> the title field indicates it is required (red border) and Volto shows a message that you have to enter a title in order to save the site
-> the save button should be disabled and show a message that the title is required (on hover)

![Add-Document](https://user-images.githubusercontent.com/632105/91281925-ec0c0280-e788-11ea-8fc5-fc16619cd19a.png)

**Comment by avoinea** [comment]
Refs #1589 and #1454

**Comment by avoinea** [comment]
@tisto Is this still the case. I think we have a toast error now.

**Comment by sneridagh** [comment]
At the moment of this writing the problem is gone as the error appears and the tab is changed to the "Document" one so the title is visible that is empty.
