### ISSUE TITLE
Volto forgets authentication when hot-reloading

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1808]
I've noticed (since forever) an annoyance that comes with developing with Volto. 

Steps to reproduce:

- start volto (`yarn start`)
- make some changes in code, wait for the hot reload to kick in (maybe make a "partial save", with incomplete code, to make React spill an error)
- now you're logged out of the website.

I've noticed a workaround: after the initial login I go and restart Volto, which makes the authentication "stick". My guess is that it's something related to this `setTimeout` [here](https://github.com/plone/volto/blob/master/src/helpers/AuthToken/AuthToken.js#L48) but I haven't really looked at the problem in a really long time.

**Comment by tisto** [comment]
Yeah. I fully agree. Victor built a Chrome plugin to auto-login into Volto to work around this. Fixing this would be fantastic.
