### ISSUE TITLE
Warning in developer console, from moment.js

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1809]
Warning triggered by src/components/manage/Widgets/DatetimeWidget.jsx:

> Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.

@nzambello

**Comment by Amit-Morade** [comment]
@avimishra18 is this issue still open?

**Comment by stevepiercy** [comment]
I think this issue may be closed by https://github.com/plone/volto/pull/3160. @tiberiuichim @sneridagh please confirm.
