### ISSUE TITLE
Navigation Depth setting from Plone is not applied

### ISSUE THREAD

**Issue by jackahl** [plone/volto#1824]
you can set the navigation depth in /controlpanel/navigation , but it is never used because volto will pull the navdepth from: https://github.com/plone/volto/blob/12dc99881c2520a22cab12ee81a8b006b4f08372/src/config/index.js#L72

**Comment by jackahl** [comment]
@tiberiuichim does this have something to do with the addon configuration you implemented?

**Comment by tiberiuichim** [comment]
@jackahl no, it was always hardcoded to 1, see https://github.com/plone/volto/pull/1546/files#diff-4c45c25c02c22e2b92b2d6d7fc2fab69L70

**Comment by jackahl** [comment]
@tiberiuichim ok, than this is something to fix in the future. Weird no one noticed earlier...

**Comment by davisagli** [comment]
This was fixed in https://github.com/plone/volto/pull/4946
