### ISSUE TITLE
Extend Video block with a preview image field

### ISSUE THREAD

**Issue by tisto** [plone/volto#1830]
Not all clients use YouTube and the ability to use a preview image for an uploaded video. It might make sense to extend the video block with an optional "preview image" field that we show in the view instead of the video.

When the user clicks on the video, the video behind the image should auto-play though. I think this is possible to set in the embed code.

@plone/volto-team opinions? Does it make sense to have this in Volto core?

**Comment by tiberiuichim** [comment]
I'm ok with this. We don't use the video block, but when embedding maps, for example, we have the same need: a custom image that can be shown instead of the real map, because of GDPR issues.

**Comment by iFlameing** [comment]
Fixed by https://github.com/plone/volto/pull/1837
