### ISSUE TITLE
Acceptance test setup: Browser runs with system language settings

### ISSUE THREAD

**Issue by tisto** [plone/volto#184]
On OS X chrome looks up the system language and uses that as a browser language. If you use the "Create WebDriver" rf keyword instead of "Open browser" you can pass the browser language:

```
Open headless browser
  ${options}=  Evaluate  sys.modules['selenium.webdriver'].ChromeOptions()  sys, selenium.webdriver
  #  Call Method  ${options}  add_argument  headless
  Call Method  ${options}  add_argument  disable-gpu
  Call Method  ${options}  add_argument  disable-web-security
  Call Method  ${options}  add_argument  window-size\=1280,1024
  Call Method  ${options}  add_argument  --lang\=en
  # Call Method  ${options}  add_argument  remote-debugging-port\=9223
  Create WebDriver  Chrome  chrome_options=${options}
```

@datakurre strangely enough, setting the browser language works for headless chrome but not if I remove the "headless" argument. Any idea how we could always force English as the browser language?

**Comment by datakurre** [comment]
@tisto No idea, sorry. That sounds like a bug in chromedriver. Is language stored in prefs.js? If so, it might be possible to set user data dir with desired prefs.js (there’s also option for just prefs, but not sure that survives seleniumlibrary indirection.

http://chromedriver.chromium.org/capabilities

**Comment by tisto** [comment]
We moved to cypress. Closing.
