### ISSUE TITLE
ResolveUID in text links is not working

### ISSUE THREAD

**Issue by tisto** [plone/volto#1850]
It seems the resolveUID functionality in text links is broken. Here is what we did:

1) create a page with an internal link
2) ZEXP the page
3) import the ZEXP in another page under a different domain
-> the page under the new domain still contains the old hard-coded domain

After some investigation, I found out that both the link resolveuid as well as the image resolveuid is not working.

**Comment by sneridagh** [comment]
Related to https://github.com/plone/plone.restapi/pull/993
