### ISSUE TITLE
Not existing file returns http code 200

### ISSUE THREAD

**Issue by TilmanJimenez** [plone/volto#1857]
A not existing file returns with code 200 eg.[https://volto.kitconcept.com/thispageprobablydoesntexist.php]( https://volto.kitconcept.com/thispageprobablydoesntexist.php)
I would expect 404. This is important for the status of a xhr for example.

**Comment by iFlameing** [comment]
@TilmanJimenez I saw what are you trying to say. You see the 200 status in the first line when you visit `https://volto.kitconcept.com/thispageprobablydoesntexist.php`  but it is the default behavior of the browser if you try to directly go to a particular link. If you see all the network log you will see a 404 xhr request from client.js.

You can find similar behavior if you go to Twitter also link: https://twitter.com/thispageprobablydoesntexist.php.

![Screenshot from 2020-10-19 18-47-00](https://user-images.githubusercontent.com/33936987/96455951-80e82500-123b-11eb-9b31-de802ae46569.png)

**Comment by iFlameing** [comment]
I think that it is clear now why we are getting this behaviour.

**Comment by TilmanJimenez** [comment]
Hey sorry on not following up in time. The problem is that running
```
let xhr = new XMLHttpRequest();
xhr.open('GET', '/thispageprobablydoesntexist.php');
xhr.send();
xhr.onload= function(){console.log(xhr.status)}
```
returns 200, while what is called by the client.js is
```
/api/thispageprobablydoesntexist.php
```
which does in fact return a 404.
I would expect the first one to return 404 as well.
