### ISSUE TITLE
Handling of validation errors messages that come as list

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1868]
![Screenshot_20201002_143045](https://user-images.githubusercontent.com/141568/94919069-76e4c900-04bc-11eb-9314-75e71d4a8e48.png)
See the screenshot, the error from the server comes as a list, it should be properly formatted.

**Comment by tiberiuichim** [comment]
@avoinea

**Comment by wesleybl** [comment]
@tiberiuichim @avelino @sneridagh I think it makes no sense to show the http response code number (400) to the end user. Do you agree?

**Comment by wesleybl** [comment]
```json
{
  "message": "[{'message': 'Invalid image file', 'field': 'preview_image', 'error': 'ValidationError'}]",
  "traceback": [
    "File \"/home/user/project/lib/python3.11/site-packages/ZPublisher/WSGIPublisher.py\", line 172, in transaction_pubevents",
    "    yield",
    "",
    "  File \"/home/user/project/lib/python3.11/site-packages/ZPublisher/WSGIPublisher.py\", line 381, in publish_module",
    "    response = _publish(request, new_mod_info)",
    "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
    "",
    "  File \"/home/user/project/lib/python3.11/site-packages/ZPublisher/WSGIPublisher.py\", line 276, in publish",
    "    result = mapply(obj,",
    "             ^^^^^^^^^^^",
    "",
    "  File \"/home/user/project/lib/python3.11/site-packages/ZPublisher/mapply.py\", line 85, in mapply",
    "    return debug(object, args, context)",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
    "",
    "  File \"/home/user/project/lib/python3.11/site-packages/ZPublisher/WSGIPublisher.py\", line 68, in call_object",
    "    return obj(*args)",
    "           ^^^^^^^^^^",
    "",
    "  File \"/home/user/project/lib/python3.11/site-packages/plone/rest/service.py\", line 22, in __call__",
    "    return self.render()",
    "           ^^^^^^^^^^^^^",
    "",
    "  File \"/home/user/project/lib/python3.11/site-packages/plone/restapi/services/__init__.py\", line 19, in render",
    "    content = self.reply()",
    "              ^^^^^^^^^^^^",
    "",
    "  File \"/home/user/project/lib/python3.11/site-packages/plone/restapi/services/content/add.py\", line 79, in reply",
    "    deserializer(validate_all=True, create=True)",
    "",
    "  File \"/home/user/project/lib/python3.11/site-packages/plone/restapi/deserializer/dxcontent.py\", line 60, in __call__",
    "    raise BadRequest(errors)"
  ],
  "type": "BadRequest"
}
```

Would we use `eval` in the `message` key to get an array from the string?

**Comment by tiberiuichim** [comment]
@wesleybl I think it should be passed down as a JSON, so that we don't need to do an eval.

**Comment by wesleybl** [comment]
@tiberiuichim do you mean `plone.restapi` already returns the message key as an array instead of a string? Wouldn't that be a big change to `plone.restapi`? Changing the interface?

Today, Volto already "extracts the array" from the message, to show the error in the correct field. See:

![download (5)](https://user-images.githubusercontent.com/3297795/216147102-a04563fc-0246-4401-92a6-28d83da26e2f.png)

See the message "Invalid image file" in the Preview image field. Re-showing "Invalid image file" in the popup seems redundant to me. We would also have to concatenate the errors from all the fields. So the lower error popup could just show "Some error occurred". This is basically what Classic Plone does. Does this look good to you?

**Comment by wesleybl** [comment]
@tiberiuichim @sneridagh @davisagli do you think it is really necessary to show the error code in the message? I don't see the need for that. This doesn't mean anything to a content manager.

**Comment by wesleybl** [comment]
> I think it should be passed down as a JSON, so that we don't need to do an eval.

@tiberiuichim  I tried using `JSON.parse` but it didn't work:

```node
> m = "[{'message': 'Invalid image file', 'field': 'preview_image', 'error': 'ValidationError'}]"
"[{'message': 'Invalid image file', 'field': 'preview_image', 'error': 'ValidationError'}]"
> JSON.parse(m);
Uncaught SyntaxError: Expected property name or '}' in JSON at position 2
```

Could we use eval?

**Comment by tiberiuichim** [comment]
@wesleybl No, in this case the error message shown should be generic, don't try to show the details. Let the website developers debug the problems, they'll know how to look into the error message returned.

**Comment by wesleybl** [comment]
@tiberiuichim the message must be generic for constraint validation errors, which are associated with fields, and are shown in the form field. In these cases, the toast should only display "There was an error."

But we also have invariant validations, which are "form validations", not associated with any specific field. Validation messages for these invariants must be displayed in toast.

To know if the error is a constraint or an invariant, we must check if we have the "key" field in the error message. Constraint errors have the field key in the error message. Then we need to parse the message to transform the "string that matches a list" into a real list.

**Comment by tiberiuichim** [comment]
@wesleybl Ideally there's an interface for the error message and the error is passed as JSON, rather then as a string.

**Comment by wesleybl** [comment]
> Ideally there's an interface for the error message and the error is passed as JSON, rather then as a string.

@tiberiuichim  the error message arrives as a string because it is converted to a string here:

https://github.com/plone/plone.rest/blob/8fdc78cd1420898d6ac954b5946f725ab63b33b3/src/plone/rest/errors.py#L60

Should we change this so that it arrives as an array?

**Comment by wesleybl** [comment]
@tiberiuichim I created the issue https://github.com/plone/plone.rest/issues/176.
