### ISSUE TITLE
Component documentation

### ISSUE THREAD

**Issue by robgietema** [plone/volto#19]
All basic components (navigation, toolbar, breadcrumbs etc) need to be documented including example usage in a style guide setup. Similar to http://react.semantic-ui.com/introduction, preferably autogenerated using tests or examples.

**Comment by tisto** [comment]
@nileshgulia1 

- check if styleguidist configuration is present in the volto repo
- make sure we can build the docs locally and document its usage
- check if all our components are included and documented in our docs
- publish the docs somewhere

**Comment by sneridagh** [comment]
Storybook progress: See #2065

**Comment by nileshgulia1** [comment]
Storybook is in core.
