### ISSUE TITLE
Folder contents should use "back" icon instead of "big x"

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1911]
The current icon is confusing. X means close, but we're not closing anything.

**Comment by tisto** [comment]
@tiberiuichim can you share a screenshot to make it more obvious what you mean?

**Comment by tiberiuichim** [comment]
![Screenshot 2020-10-17 211935](https://user-images.githubusercontent.com/141568/96350448-89ffb780-10be-11eb-9756-c8993b505315.png)

**Comment by sneridagh** [comment]
That has a reason, Albert told me so because "contents" was supposed to behave like an app-like view, not be part of the website layout. However, it seems that in Quanta he changed his mind :)

**Comment by sneridagh** [comment]
In quanta, the contents doesn't have the site layout, so this is something that we can address as low hanging fruit.

**Comment by pnicolli** [comment]
This was done already, and honestly I can't find a reference to when this has been changed at the moment.
