### ISSUE TITLE
Version overview in control panel always showing debug mode warning

### ISSUE THREAD

**Issue by achimwilde** [plone/volto#1928]
View: /controlpanel
Associated file: /src/components/manage/Controlpanels/VersionOverview.jsx

There is a formatted message that seems to be shown always (no condition):

```
 <FormattedMessage
          id="Warning Regarding debug mode"
          defaultMessage='You are running in "debug mode". This mode is intended for sites that
        are under development. This allows many configuration changes to be
        immediately visible, but will make your site run more slowly. To turn
        off debug mode, stop the server, set "debug-mode=off" in your
        buildout.cfg, re-run bin/buildout and then restart the server process.'
        />
```

To get the system information from Plone API, @system is called and the JSON response includes "debug_mode". I suggest using this data to dynamically change the above message.

Also, the message seems to address only the Plone API debug/production mode (talking about buildout.cfg and buildout), but to those not knowing about the history of this message (which was copied from Plone control panel) might think it is about a Volto debug mode (which doesn't exist AFAIK). How about changing "You are running in debug/production mode" to "Your API is running in debug/production mode"?

If you agree to my two suggestions, we would implement it, too.

**Comment by tisto** [comment]
@achimwilde that makes sense to me.

**Comment by davisagli** [comment]
Looks like this was done; there is a condition now. https://github.com/plone/volto/blob/03464c30dd342418a16bf1825fddff0dc9ff14f7/src/components/manage/Controlpanels/VersionOverview.jsx#L61
