### ISSUE TITLE
Lazy-load draftjs libraries

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1932]
There's no reason to have them in the main client bundle. I think it would save at least 150kb gzipped size.

**Comment by tiberiuichim** [comment]
- react-beautiful-dnd also needs to go. 
- react-toastify
-react-dnd-html5-backend
- moment?
- react-dropzone
- diff.js
- react-simple-code-editor
- dnd-core
- prismjs

Also, why do we load js zlib libraries?

**Comment by davisagli** [comment]
Looks like this was already done
