### ISSUE TITLE
Small screen issue with docs.voltocms.com

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#1943]
![Screenshot_20201026_115521](https://user-images.githubusercontent.com/141568/97158528-3b1ee580-1782-11eb-9c66-06f38abea1b5.png)

On smaller laptop screens the frontpage is mostly empty and there's no cues about using the left-side menu to navigate.

**Comment by stevepiercy** [comment]
This is no longer an issue, now that we are using sphinx-book-theme.
