### ISSUE TITLE
Link overlay covers the actual link text

### ISSUE THREAD

**Issue by tisto** [plone/volto#1983]
**Describe the bug**

Link overlay covers the actual link text. The editor can not for which link she chooses a link target.

**To Reproduce**

1. Go to https://volto.kitconcept.com/add?type=Document
2. Create a new document
3. Create a text with a link

**Expected behavior**

The overlay shows up just above the link text.

**Screenshots**

![Add-Document](https://user-images.githubusercontent.com/632105/98700350-63a90100-2378-11eb-9f40-731a5a5b715e.png)

**Comment by tisto** [comment]
@giuliaghisini is that something you considered when implementing the link overlay? Just wondering...

**Comment by tiberiuichim** [comment]
it's a slippery slope, I wonder if we should avoid zindexes as much as possible. @tisto: what happens when I edit richtext in the block sidebar, i try to add a link and open the sidebar? Maybe body > sidebar > overlay > link popup > objectbrowser popup, as order of zindex.

**Comment by giuliaghisini** [comment]
I think this is the correct behavior, because the user has chosen to search for the content on the site, therefore the object browser appears .. I don't think it would make sense to allow him to use the sidebar (objectbrowser) and linkwidget at the same time

**Comment by tisto** [comment]
@tiberiuichim @giuliaghisini This is not about zindex. The old link popup showed up above the link text, the new link popup covers the link. This makes it impossible for the editor to see which link she is editing when the right content browser sidebar is open. This is not about being able to edit the link while the sidebar is open.

The solution would be to move the link popup above the link, so the editor can see which link she is editing.

**Comment by giuliaghisini** [comment]
> @tiberiuichim @giuliaghisini This is not about zindex. The old link popup showed up above the link text, the new link popup covers the link. This makes it impossible for the editor to see which link she is editing when the right content browser sidebar is open. This is not about being able to edit the link while the sidebar is open.
> 
> The solution would be to move the link popup above the link, so the editor can see which link she is editing.

oh sorry, i had not understood.. yess. i agree with you @tisto. This is a thing that i've not considered when implemented the link overlay

**Comment by tisto** [comment]
All good. I guess I did not describe the problem properly everybody got it wrong at first. :)

@iFlaming will start to look into this today...

**Comment by tiberiuichim** [comment]
@tisto no, you did describe acurately, but, as always with pictures, we jumped on what we assumed was wrong based on what we saw in the picture.

**Comment by davisagli** [comment]
This is no longer a problem with the slate block.

<img width="406" alt="Screenshot 2023-02-23 at 9 45 00 AM" src="https://user-images.githubusercontent.com/49014/220987709-5c1540d2-39fb-41c8-a039-a972582ce232.png">
