### ISSUE TITLE
Pastanaga Editor: Tile borders overlap with image that is left/right aligned

### ISSUE THREAD

**Issue by tisto** [plone/volto#200]
1) Go to https://plone-react.kitconcept.io
2) Login
3) Create a new document
4) Add an image tile
4) Add a text tile after the image tile and type some paragraphs
-> The selected image tile borders overlap with the image on the left/right side
Expected behavior:
-> Show the tile borders only on the left/right side
![add document 1](https://user-images.githubusercontent.com/632105/42039329-6a929250-7aed-11e8-9e65-2be856194dd0.png)

**Comment by robgietema** [comment]
It's a floating image so you don't know where to put the border, this is how other editors works also.
