### ISSUE TITLE
Listing blocks: what's the better context to call querystring-search?

### ISSUE THREAD

**Issue by cekk** [plone/volto#2000]
**Describe the bug**

In view mode, the endpoint (@querystring-search) is called on the site root
In edit mode, the endpoint (@querystring-search) is called on the current context (the object where we are creating that block).

If we don't pass any path in the query, Plone automatically set the path as the context's navigation root.

If we have a multilanguage site, the navigation root depends on the current selected language (/it or /en).
That could bring to a difference in results when you are in edit or in view mode.

For example if you are filtering items with a keyword used by some contents in /it and others in /en, and you create a block into /it section, in edit mode you'll see only italians results but in view, you'll see all results (because the endpoint is called on site root).

What should be the correct path where to call the querystring-search?
Probably the current context, because if we call it always on the site root, we should always set some path to avoid mixed results (from different navigation roots)

**Comment by davisagli** [comment]
Currently, `@querystring-search` is requested in the current context.

There can still be a difference in results when using a relative path, because when a new page is being added, that is loaded in the context of the container. But that is a separate issue
