### ISSUE TITLE
Users and groups settings does not store role and group membership on creation or change

### ISSUE THREAD

**Issue by fredvd** [plone/volto#2009]
After installing a Volto site with the docker plone backend I tried to create a new user having the Manager role to stop using the default Plone/Zope admin/admin.  

**To Reproduce**
In a fresh installed Volto site, go to the users & groups settings, create a new user, assign the user to the Manager role or add the User to the Administrators Group.

**Expected behavior**
When I log out of Volto and try to log in with my new created user, I should be able to create and edit pages. I can't. 

Checking in the Plone backend control panel I see that the created user does not have the Manager role and/or is not added to the Administrators group.
<img width="834" alt="users and groups settings" src="https://user-images.githubusercontent.com/394784/99903125-ae087700-2cc2-11eb-92a8-0364b879088a.png">

Also, If I check the 'Manager' role in the User/role matrix in the Users and Groups settings, markinet the checkbox is also not persisted.   Setting the role through the Plone backend does show the role checked on reload in the Volto controlpanel

Volto 9.1.0
Plone 5.2.2 
Zope 4.5.1
Python 3.8.6

**Comment by nileshgulia1** [comment]
I too observed this. When I try to change the roles and try to refresh, the role doesn't seems to apply. I wrote the user and groups controlpanel way long ago, somehow didn't notice the problem. Will have a look maybe this week!

**Comment by tisto** [comment]
I'd recommend writing a failing Cypress test first, then push it on a PR to prove the problem. After this write a fix and prove with a green CI that the problem has been fixed.

**Comment by fredvd** [comment]
Fixed in other issues/PR's
