### ISSUE TITLE
Don't use Hamburgers CSS library since it is big and a very small part of it is used

### ISSUE THREAD

**Issue by silviubogan** [plone/volto#2022]
**Describe the bug**
For apps based on Volto, [this library](https://github.com/jonsuh/hamburgers), although put in a separate chunk, is automatically loaded with the front page and is pretty big.

**To Reproduce**
1. Go to a new/base Volto setup in browser
2. Open the Network DevTools tab (Performance shows this information too)
3. Click on the CSS file that is downloaded and begins with:

```css
/*!
 * Hamburgers
 * @description Tasty CSS-animated hamburgers
 * @author Jonathan Suh @jonsuh
 * @site https://jonsuh.com/hamburgers
 * @link https://github.com/jonsuh/hamburgers
 */
```

4. Note the size of this chunk (29.5 KiB - on my computer I have set it up to be gzipped, so in normal Volto it would be bigger) and how it is loaded on every page, or at least on every page that is using the mobile navigation button.

**Expected behavior**
This dependency is not needed as the animations are relatively easy to reproduce. We could use just the actual animation that is currently in use in Volto.

**Screenshots**
When the width of the viewport is lower than a specific breakpoint the hamburger menu appears:
![image](https://user-images.githubusercontent.com/198924/100360759-0cef2880-3002-11eb-8855-02849d82dfa7.png)

When clicking on it, an animation begins and at the end of it, it looks like this:
![image](https://user-images.githubusercontent.com/198924/100360893-3314c880-3002-11eb-94a9-fa01532f6efb.png)

**Software:**
 - OS: Manjaro Linux (although it is the same in all OS's supporting Chromium)
 - Browser: Chromium (although it is the same in all recent browser versions)
 - Volto Version: 9.2
 - Plone Version: N/A
 - Plone REST API Version: N/A

**Additional context**
The relevant Volto source code is:

https://github.com/plone/volto/blob/376cb3f3bb965e0eeb3ec4274edf86148c4f9a6e/src/components/theme/Navigation/Navigation.jsx#L126-L156

I will start working on this as a draft PR soon. I can take one of two approaches:

1. customize the Hamburgers menu to include just the `collapse` animation as documented [here](https://github.com/jonsuh/hamburgers)
2. copy-paste and adjust the `collapse` animation's code and give credit at the beginning of that code snippet to the Hamburgers library

I would go for (2) because it is [a short piece of code](https://github.com/jonsuh/hamburgers/blob/master/_sass/hamburgers/types/_collapse.scss).

**Comment by tiberiuichim** [comment]
@silviubogan Ok, but can you migrate the code to our less? So that we don't need to ship with scss enabled by default?

**Comment by ichim-david** [comment]
Library removed in recent versions of Volto as noticed in the Volto upgrade guide
https://6.docs.plone.org/volto/upgrade-guide/index.html#removed-hamburgers-library
