### ISSUE TITLE
Circular dependencies in Volto

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2031]
src/actions/content/content.js -> src/helpers/Content/Content.js -> src/config/index.js -> src/config/Widgets.jsx -> src/components/manage/Widgets/AlignWidget.jsx -> src/helpers/index.js -> src/helpers/AuthToken/AuthToken.js -> src/actions/index.js -> src/actions/content/content.js

src/actions/index.js -> src/actions/content/content.js -> src/helpers/Content/Content.js -> src/config/index.js -> src/config/Widgets.jsx -> src/components/manage/Widgets/AlignWidget.jsx -> src/helpers/index.js -> src/helpers/AuthToken/AuthToken.js -> src/actions/index.js

src/actions/querystringsearch/querystringsearch.js -> src/config/index.js -> src/config/Widgets.jsx -> src/components/manage/Widgets/AlignWidget.jsx -> src/helpers/index.js -> src/helpers/AuthToken/AuthToken.js -> src/actions/index.js -> src/actions/querystringsearch/querystringsearch.js

src/actions/vocabularies/vocabularies.js -> src/config/index.js -> src/config/Widgets.jsx -> src/components/manage/Widgets/AlignWidget.jsx -> src/helpers/index.js -> src/helpers/AuthToken/AuthToken.js -> src/actions/index.js -> src/actions/vocabularies/vocabularies.js

src/actions/workflow/workflow.js -> src/config/index.js -> src/config/Widgets.jsx -> src/components/manage/Widgets/AlignWidget.jsx -> src/helpers/index.js -> src/helpers/AuthToken/AuthToken.js -> src/actions/index.js -> src/actions/workflow/workflow.js

**Comment by tisto** [comment]
@tiberiuichim is there a way to automatically detect those circular dependencies? If so we could add this as a check to our CI.

**Comment by tiberiuichim** [comment]
@tisto Sorry, this ticket is a bit misleading, Victor and I are trying to see if we can revive Storybook and solving the imports problem is a must. I've added a webpack plugin that automatically detects and logs warnings about such dependencies. The current situation in Volto is such that it's difficult to avoid circular imports (for ex a widget uses a helper that needs settings, which is defined in `~/config` which bootstraps the widgets, so you have a circular import).

**Comment by tiberiuichim** [comment]
I've added the plugin integrated in Volto here: https://github.com/plone/volto/tree/circular_deps_plugin
