### ISSUE TITLE
Pastanaga Editor: Do not allow to remove title tile

### ISSUE THREAD

**Issue by tisto** [plone/volto#205]
Right now it is possible to delete both the title and the description tile. You can re-add them but I am not sure if this is the desired behavior.

**Comment by robgietema** [comment]
For now yes, we might want to add some required tiles later to the content type.

**Comment by davisagli** [comment]
-1, I’ve had clients ask for pages without a visible title before.

David Glick
(mobile)

**Comment by jackahl** [comment]
It is not possible to re-add the title and the description. That should be possible when you are able to delete it.

**Comment by tisto** [comment]
@robgietema @davisagli @sneridagh @albertcasado as discussed in Tokyo, we will remove the description tile and auto-generate the description. This leaves us with the UX problem that the user currently can delete the title tile (hit the delete icon next to the title tile) and then there is no way to get it back.

I gave a training on Volto in the last week and this was something users ran into. I would propose we remove the delete icon from the title tile for now. 

I am open to discuss the optional tile use case afterward. Though, we need a short-term solution for this UX problem IMHO.
