### ISSUE TITLE
Integrate widgets-view in core Volto as dexterity item view

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2050]
If you create a Dexterity item right now, with schema fields you won't be able to view it in an autogenerated view. The https://github.com/eea/volto-widgets-view has "view mode" for widgets, basically they can be used to render a schema and values. Maybe this + schema renderer should be integrated in core?

**Comment by davisagli** [comment]
A schema-based view for non-blocks-enabled content types was added in #3330
