### ISSUE TITLE
Re-add "show all" button to folder contents view

### ISSUE THREAD

**Issue by tisto** [plone/volto#2051]
**Is your feature request related to a problem? Please describe.**

The Plone classic folder contents view has a "show all" button. We should re-add it.

Sometimes editors want to change the order of items in folders/pages with lots of subitems. It is currently impossible to move an object across our current batch boundaries.

**Describe the solution you'd like**

Add a new button "All" that shows all items in the folder/document.

![Contents (5)](https://user-images.githubusercontent.com/632105/101601759-56297a00-39fd-11eb-9aa4-d929f6ae8149.png)

**Comment by iFlameing** [comment]
Fixed by https://github.com/plone/volto/pull/2070
