### ISSUE TITLE
Provide full-stack Docker image for evaluation, personal and development purposes

### ISSUE THREAD

**Issue by datakurre** [plone/volto#206]
I would love to have a Docker image that runs up-to-date Plone with Pastanaga UI themed plone-react frontend.

It would not need to be production quality. Just something to evaluate and play with. With your opinionated Plone content type selection.

gatsby-source-plone GSOC could use it to develop tiles support for the plugin.

Anyone could use to play with it locally and publish the results as gatsby-source-plone -powered gatsby-site.

The ugly part would be that it would run multiple processes in container. Would supervisor be suitable to run as the main process and manage the others? (It some container use designed init.) It could expose all ports to ease debugging (plone, supervisor, plone-react’s server).

**Comment by tisto** [comment]
We already have a demo site running with Pastanaga, plone-react, and plone.restapi. Not sure how @sneridagh actually did it. Maybe that is something that we could use as a starting point. I will add it to the Costa Brava sprint topics.

**Comment by sneridagh** [comment]
@datakurre @tisto The current docker image that we use only includes the Plone backend. We can take a look into and add a full fledged docker-compose with two images, the backend and the frontend. Shouldn't be hard :)

**Comment by datakurre** [comment]
I guess, docker-compose mash-up is ok.

**Comment by datakurre** [comment]
@sneridagh Any chance you could release plone-react-image at the end of Costa Brava Sprint? :)

**Comment by sneridagh** [comment]
The this time of writing, https://github.com/plone/plone-frontend is the canonical Docker image for Volto.

There is a docker-compose configuration available as reference:
https://github.com/plone/volto/blob/5ca8bba560a485190d0ff8c55e52baf8c5b6ea7c/docker-compose.yml

Also the deployment training:
https://training.plone.org/5/plone-deployment/index.html
