### ISSUE TITLE
Plone root appears as "red" in the "workflow status" hint on the Toolbar

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2066]
If the "blue" means "published" and "red" means private on the Toolbar toggle handle, then Plone's shouldn't always be red.

**Comment by tiberiuichim** [comment]
@MAX-786 The problem is a bit complex, at least to my knowledge. When I wrote this ticket, the "Dexterity-based Plone root" wasn't a thing. Plone was using the old CMF-based content classes, rather then the new Dexterity framework. So, at that time, the Plone site couldn't have a workflow state. I don't know if that is still the case. In any case, I think the fallback color could be something more subtle that doesn't "conflict" with one particular, determinate state.

**Comment by MAX-786** [comment]
> So, at that time, the Plone site couldn't have a workflow state. I don't know if that is still the case.

on Volto i don't see the workflow status indicator either...,if possible can u link any resource so i can understand this issue better. 😊Thanks!

**Comment by davisagli** [comment]
It looks like at some point this got fixed so that content types without a workflow do not show a status.
