### ISSUE TITLE
Use create-yo trampoline in documentation

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2067]
So, it appears that it's actually possible to bootstrap a Volto project "hands-free", no prerequisite installed package by running:

```
npm init yo @plone/volto
```

and this works also:

```
npm init yo @plone/volto:addon
```

So I propose that we tweak our documentation and recommend this approach as default.

**Comment by tiberiuichim** [comment]
The trick here is `npm init yo` will look for a [create-yo](https://boneskull.com/create-yo/) package, which then delegates to `@plone/volto` yo generator

**Comment by nileshgulia1** [comment]
@tiberiuichim ` npm init yo @plone/volto <project-name>` doesn't seem to succeed.
```
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:2884:
../../nan/nan_typedarray_contents.h:34:43: warning: 'GetContents' is deprecated: Use GetBackingStore. See http://crbug.com/v8/9908.
      [-Wdeprecated-declarations]
      data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                          ^
/Users/nileshgulia/Library/Caches/node-gyp/14.15.4/include/node/v8.h:5272:3: note: 'GetContents' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use GetBackingStore. See http://crbug.com/v8/9908.")
  ^
/Users/nileshgulia/Library/Caches/node-gyp/14.15.4/include/node/v8config.h:402:39: note: expanded from macro 'V8_DEPRECATE_SOON'
# define V8_DEPRECATE_SOON(message) [[deprecated(message)]]
                                      ^
1 warning generated.
info looking for cached prebuild @ /Users/nileshgulia/.npm/_prebuilds/82ff49-iltorb-v2.4.5-node-v83-darwin-x64.tar.gz
http request GET https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v83-darwin-x64.tar.gz
http 404 https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v83-darwin-x64.tar.gz
WARN install No prebuilt binaries found (target=14.15.4 runtime=node arch=x64 libc= platform=darwin)
warning ../../../../../../../package.json: No license field                                                                                                  
command not found: volto
✔ create-yo ok!
```
whereas `npm init yo @plone/volto` works as expected.

**Comment by tiberiuichim** [comment]
without the project name in the command line

**Comment by pnicolli** [comment]
`yarn create yo @plone/volto` works as well

**Comment by fredvd** [comment]
`scaffoldtest fred$ nvm use 14
Now using node v14.17.1 (npm v7.7.0)
scaffoldtest fred$ **yarn create yo @plone/volto**
yarn create v1.22.11
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-yo@2.0.0" with binaries:
      - create-yo
[################] 16/16internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'libnpx'
Require stack:
- /Users/fred/.nvm/versions/node/v14.17.1/lib/node_modules/npm/noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at resolveFileName (/Users/fred/.config/yarn/global/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/Users/fred/.config/yarn/global/node_modules/resolve-from/index.js:43:9)
    at module.exports (/Users/fred/.config/yarn/global/node_modules/resolve-from/index.js:46:47)
    at module.exports (/Users/fred/.config/yarn/global/node_modules/import-from/index.js:4:55)
    at Object.<anonymous> (/Users/fred/.config/yarn/global/node_modules/create-yo/src/create-yo.js:8:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/fred/.nvm/versions/node/v14.17.1/lib/node_modules/npm/noop.js'
  ]
}
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-yo
Arguments: @plone/volto
Directory: /Users/fred/test/scaffoldtest
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
`

`
ls -alh /usr/local/bin/create-yo
lrwxr-xr-x  1 fred  admin    67B Aug  9 20:53 /usr/local/bin/create-yo -> ../../../Users/fred/.config/yarn/global/node_modules/.bin/create-yo
Mini1:scaffoldtest fred$ which yarn
/Users/fred/.nvm/versions/node/v14.17.1/bin/yarn
`

**Comment by tiberiuichim** [comment]
I can replicate the Fred's problem on ArchLinux as well.

**Comment by tiberiuichim** [comment]
https://github.com/boneskull/create-yo/issues/4

**Comment by HillLiu** [comment]
There is a simple solution with zero dependencies, and only use node native modules.

such as...

```
npx yonpx @plone/volto volto-tutorial-project
```

**Comment by fredvd** [comment]
Breaks right away with the 'cannot find libnpx' error message.....

```
npx yonpx @plone/volto volto-tutorial-project
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'libnpx'
Require stack:
- /Users/fred/.nvm/versions/node/v16.13.1/bin/node_modules/npm/node_modules/libnpx/noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/fred/.npm/_npx/f1e212ed1c50d94c/node_modules/yonpx/src/init.js:16:34)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/fred/.nvm/versions/node/v16.13.1/bin/node_modules/npm/node_modules/libnpx/noop.js'
  ]
}
```

```
npm -g list
/Users/fred/.nvm/versions/node/v16.13.1/lib
├── corepack@0.10.0
└── npm@8.1.2

node -v
v16.13.1
```

**Comment by nileshgulia1** [comment]
> 
Hm.. works for me with node v14.x

**Comment by HillLiu** [comment]
> 

Look like node 16 change the npx invoke way, I'll help fix it.

**Comment by HillLiu** [comment]
@fredvd  quick verify on node 14 and 16, it should be resolved. 


> Breaks right away with the 'cannot find libnpx' error message.....
> 
> ```
> npx yonpx @plone/volto volto-tutorial-project
> node:internal/modules/cjs/loader:936
>   throw err;
>   ^
> 
> Error: Cannot find module 'libnpx'
> Require stack:
> - /Users/fred/.nvm/versions/node/v16.13.1/bin/node_modules/npm/node_modules/libnpx/noop.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/Users/fred/.npm/_npx/f1e212ed1c50d94c/node_modules/yonpx/src/init.js:16:34)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/Users/fred/.nvm/versions/node/v16.13.1/bin/node_modules/npm/node_modules/libnpx/noop.js'
>   ]
> }
> ```
> 
> ```
> npm -g list
> /Users/fred/.nvm/versions/node/v16.13.1/lib
> ├── corepack@0.10.0
> └── npm@8.1.2
> 
> node -v
> v16.13.1
> ```

#

**Comment by pnicolli** [comment]
This is superseded by [cookieplone](https://github.com/plone/cookieplone).
