### ISSUE TITLE
Script `yarn start:prod` does not work well

### ISSUE THREAD

**Issue by silviubogan** [plone/volto#2084]
**Describe the bug**
`$ yarn start:prod` does not work well, e.g. when loading Volto in browser, the style of the web page is not loaded.

**To Reproduce**
1. Go to 'http://localhost:3000' in Chromium
2. Wait for the page to load
3. Open DevTools console
4. See errors like these:
![image](https://user-images.githubusercontent.com/198924/102810689-d45a2900-43cc-11eb-8f90-602db07cd136.png)

**Expected behavior**
The style of the page loads well.

**Screenshots**
![image](https://user-images.githubusercontent.com/198924/102810749-ec31ad00-43cc-11eb-80c5-5f2fbbf425a3.png)

**Software:**
 - OS: Manjaro Linux
 - Browser Chromium
 - Volto Version 10.6.1
 - Plone Version 5.2.2 (5209)
 - Plone REST API Version 6.15.0

**Context**
From what I've seen, the http://localhost:3001 domain is not served.

**Comment by tiberiuichim** [comment]
@silviubogan: did you need to run "yarn build" before? See https://docs.voltocms.com/deploying/simple/

**Comment by silviubogan** [comment]
@tiberiuichim If I run `yarn i18n` then `yarn build` then `yarn start:prod`, for the last command I get this:

![image](https://user-images.githubusercontent.com/198924/102877977-3d36b500-4450-11eb-8299-06e1189a71d8.png)

**Comment by silviubogan** [comment]
@tiberiuichim The beginning of the output is available [in this gist](https://gist.github.com/silviubogan/bee33ecc54e5677579d673ad177368aa). I could not get the end into the gist for some reason.

**Comment by tiberiuichim** [comment]
I can confirm Volto no longer starts in master, neither development or production version.

**Comment by tiberiuichim** [comment]
The problem has been introduced in this commit: https://github.com/plone/volto/commit/5d1a615d4f0c00018d58527054d683872bf9db66
