### ISSUE TITLE
Spa mode is broken because of Sentry integration

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#2093]
**Describe the bug**

The build is broken because of 

```
TypeError: Cannot read property 'RAZZLE_SENTRY_DSN' of undefined
initSentry
node_modules/@plone/volto/src/sentry.js:38
  35 | }
  36 | 
  37 | if (__CLIENT__) {
> 38 |   if (window.env.RAZZLE_SENTRY_DSN) {
     | ^  39 |     if (!sentry_config) {
  40 |       sentry_config = {};
  41 |     }
```

**To Reproduce**
1) enable SPA build (renaming `public/index.html.spa` -> `public/index.html`)
2) yarn start-spa

**Expected behavior**
The build starts flawlessly

**Comment by sneridagh** [comment]
@mtoepfl ?

**Comment by sneridagh** [comment]
@mtoepfl Why did you close the issue?

**Comment by mtoepfl** [comment]
Sorry, this was not my intention. I didn't notice I did. It's too easy with GitHub mobile UI. I'm only watching Volto repo. Sorry.

**Comment by sneridagh** [comment]
No problem at all!! I guessed it might be that, but I also thought this might be fixed already or something!
Cheers!

**Comment by tiberiuichim** [comment]
Closed by https://github.com/plone/volto/pull/2094
