### ISSUE TITLE
Strange behavior with RAZZLE_INTERNAL_API_PATH variable

### ISSUE THREAD

**Issue by cekk** [plone/volto#2114]
We're trying using RAZZLE_INTERNAL_API_PATH env variable and i have a strange related behavior.

First of all: what's its main purpose?

We have the following setup:

- in restapi response we have a custom component (in @components section) with an url to a custom endpoint (let's say http://my-site/api/my-content/@custom-endpoint)
- the view of this content, in Volto, reads that url and try to get data from it

If we don't set internalApiPath, everything works fine.
If we set internalApiPath:
- if we access that page through Volto interface (so we don't use ssr), everything works fine
- if we access that page directly (or reload the page), the view tries to get @custom-endpoint not on the frontend url (http://my-site/api) but on the internalApiPath url (http://localhost:8080/Plone) and this leads to a CORS problem and we can't get that additional data

Now, i can bypass this error disabling RAZZLE_INTERNAL_API_PATH but i'd like to understand what's happening here.

Some strange things that i noticed:
- it's the client that is trying to get a resource from the api with the internal url
- if i put a console.log just before the [action dispatch](https://github.com/RedTurtle/design-volto-theme/blob/master/src/components/ItaliaTheme/View/CartellaModulisticaView/CartellaModulisticaView.jsx#L44) all links inside @contents attribute are converted with internal api path
- the GET call to the content that i see in browser's console, has the right urls in @contents attributes (and some calls later, i can see the wrong call to internal api url)

Could it be possible that when we directly access to a page, the SSR makes backend calls using internal url (maybe from [this](https://github.com/plone/volto/pull/1751) pr) to generate the html page and set the state for content with "wrong" urls and then share somehow that state with the client. That could be the reason why i see internal urls into my view on client side.

**Comment by tiberiuichim** [comment]
>if we access that page directly (or reload the page), the view tries to get @custom-endpoint not on the frontend url (http://my-site/api) but on the internalApiPath url (http://localhost:8080/Plone) and this leads to a CORS problem and we can't get that additional data

"the view" < that's where the problem is. You should use `flattenToAppURL` in api calls and actions.

**Comment by tiberiuichim** [comment]
@cekk: the content information in the redux store is "cleaned up": https://github.com/plone/volto/blob/master/src/reducers/content/content.js#L126

Also, another thing to debug, make sure that the settings are properly replicated in the server, look in the generated html for the runtime config information script.

**Comment by cekk** [comment]
damn..with flattenToAppURL it works.
I thought that it only worked with frontend api urls, but it's a change that you did in the pull request that i linked here and i missed that change :(

Ok, nevermind..i can close this issue!

Thanks
