### ISSUE TITLE
Proposal: make the /api proxy "official" and change it to insert VH rules in its proxied URLs

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2116]
**Is your feature request related to a problem? Please describe.**

We have a lot of issues in how we treat URLs and object ids across the stack. All content comes from the Plone stack with the "wrong urls" for the frontend stack and it's basically a "whack-a-mole": we have to keep fighting issues everywhere. Basically, `flattenToAppUrl` needs to be called everywhere and developers need to be aware of the issues. 

Why do we subject ourselves to this? There is a solution to be implemented, to avoid this and make the whole thing coherent.

**Describe the solution you'd like**

We can use insert VH rules from the /api proxy to make Plone publish content with proper URLs and avoid having to make sure, across the stack, that we always strip the "foreign api website" from our links.

**Additional context**

Most Plone deployments are like:

- (Stack A) HTTP frontend server -> varnish -> haproxy/loadbalancer -> Zope clients

And with Volto, there needs to be another paralel stack in front of it.

- (Stack B, variant 1) HTTP frontend server -> Volto Express server -> varnish (via internalApiPath)
- (Stack B, variant 2) HTTP frontend server -> Volto Express server -> Stack A

With my proposed change, we would remove (Stack B, v2). If direct access to the Plone site is needed (via classic interface), then a separate VH rule can be made for them.

**Comment by tisto** [comment]
I agree that we have to make Volto/REST API a first-class citizen and simplify and standardize our deployment stack. I also agree that Plone classic should be available under a different URL/domain if needed.

@jensens did some work on an explicit traverser that we could use by default:

https://github.com/plone/plone.rest/pull/113

(I am still undecided if I prefer "/api" over "/++api++" but that is a personal preference to a certain degree I guess...

**Comment by jensens** [comment]
As already said I would prefer a traverser with `++` simply because it is more explicit and IIRC in the publisher there is an abbreviation for all starting with `@` and `+` to be looked up as a view (need to lookup where it is and if this is relevant performance wise)
