### ISSUE TITLE
Pastanaga Editor: Make text float around left/right aligned images in edit mode as well

### ISSUE THREAD

**Issue by tisto** [plone/volto#215]
Right now if you make images float left/right in the edit mode, the text won't float around the image:

![pastanaga-editor-float-left-image-edit](https://user-images.githubusercontent.com/632105/42497917-2121919c-842b-11e8-96f0-95b61b231268.png)

This works in the view mode though:

![pastanaga-editor-float-image-view](https://user-images.githubusercontent.com/632105/42497920-22aceb60-842b-11e8-9bb1-d24e2222c8de.png)

**Comment by rakshitv15** [comment]
Hi I am starting with plone volto and wanted to take this issue.

**Comment by tisto** [comment]
@rakshitv15 thank you for stepping up to work on this and sorry we did not reply sooner! Unfortunately, we kind of already fixed the issue. I'd recommend going through the Volto issues that are marked as "easy" to find other tasks that are suitable for you:

https://github.com/plone/volto/labels/41%20lvl%3A%20easy

Let me know if there is anything I can do to help!

**Comment by tisto** [comment]
Fixed by @sneridagh. Closing
