### ISSUE TITLE
Default language and lang attr on the html tag.

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#216]
The default language is always EN unless the user goes to his/her personal preferences and change them. It needs to be consistent with the language set on the site or find a sensible solution for the user case in which the site is in a single language.

Maybe set it on the Plone-React settings... since getting this on the fly from the server in SSR mode is hard.

**Comment by robgietema** [comment]
Why is this hard to do on SSR? We can just fetch the setting right?

**Comment by sneridagh** [comment]
Solved in Volto 5.
