### ISSUE TITLE
Slate Editor

### ISSUE THREAD

**Issue by tisto** [plone/volto#2167]
## Slate Roadmap

* [x] Lower risk: by companies picking up Slate as editor (RedTurtle and kitconcept)
* [x] Backend (make plone.restapi support slate in addition to draftjs)
* [x] Transforms indexing in p.restapi
* [x] Transforms for resolveuid
* [x] Frontend
* [x] integrate slate into Volto core
* [ ] Migration
* [ ] Migration steps - Transforms for migration inplace?

### Features / UX
* [ ] link sidebar (external/internal links, anchor links)
* [ ] UI decide buttons, bar looking like the current one
* [ ] Plone 6 Upgrade Steps
* [ ] Sidebar - what do we want to show?
* [ ] Extensibility story
* [ ] Documentation
* [ ] Configuration
* [ ] Extensibility
* [ ] features/plugins

### Questions:

* [ ] Current Title block (one liner fixed rich text)?

**Comment by tiberiuichim** [comment]
## Slate Roadmap

- Lower risk: by companies picking up Slate as editor (RedTurtle and kitconcept)
- Backend (make plone.restapi support slate in addition to draftjs)
- Transforms indexing in p.restapi
- Transforms for resolveuid
- Frontend
- integrate slate into Volto core
- Migration
- Migration steps - Transforms for migration inplace?

Features / UX
link sidebar (external/internal links, anchor links)
UI decide buttons, bar looking like the current one
Plone 6 Upgrade Steps
Sidebar - what do we want to show?
Extensibility story
Documentation
Configuration
Extensibility
features/plugins


### Questions:
Current Title block (one liner fixed rich text)?

**Comment by tisto** [comment]
@tiberiuichim I moved your comment to the main description of the ticket. We can use a checklist there to keep track of our progress.

**Comment by ksuess** [comment]
What's the current roadmap on 'Replace draftJS with Slate editor'?
Unfortunatly Volto microsprints on Slate are not public anymore. I understand that you focus on associates. But this is on Plone 6. I do consume and contribute.

As soon as Volto Slate editor is not anymore a third party product but indeed Plone 6:
- Is the inline editor style menu still a feature? https://github.com/eea/volto-slate/issues/109
- fixed editor toolbar is skipped: yes, mywords. I convinced the customer.
- …

**Comment by tiberiuichim** [comment]
@ksuess 

- the inline style menu paragraph style should be fixed. I don't plan on removing it
- fixed editor toolbar... I'm sorry, I'm the one who messed with it. I need to revamp it. I've tried to improve the performance of the editor and the responsiveness of the toolbar and I found that the code is confusing and I've tried to simplify it. I can bring it back, but the plan for the future is to make the toolbar "fixed" all the time, using the Quanta toolbar. Probably not sooner then autumn, though, as Volto would have to ship with Quanta toolbar support. If you want, and I'm sorry about this, you can make a PR in volto-slate that brings back the fixed toolbar support and we'll merge it.

**Comment by sneridagh** [comment]
Slate is merged in Volto core since 16.0.0-alpha.15.
