### ISSUE TITLE
Pastanaga Editor: Title field is not selected when creating a new page

### ISSUE THREAD

**Issue by tisto** [plone/volto#217]
1) Create a new document via the add menu
-> The title field is not automatically selected

I think the title field should be automatically selected so the user can type in the title directly.

**Comment by kunal-mohta** [comment]
I would like to work on this issue.
As I went through the code I figured a way to implement this, but it needs accessing the DOM element with id `field-title` from the `componentDidMount` method of `Form` component.
Shall I proceed with this method? or Can there be better way to do this?
