### ISSUE TITLE
Toast "email: required input is missing" is raised when hit Cancel (X) on the password reset form

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2181]
**Describe the bug**
Toast "email: required input is missing" is raised when hit Cancel (X) on the password reset form

**To Reproduce**
1. Go to http://localhost:3000/password-reset
2. Click on 'X' to cancel
4. There's a toast popup message

**Expected behavior**
No toast

**Comment by tiberiuichim** [comment]
This also happens on the contact form.

**Comment by nileshgulia1** [comment]
Also in Register Form when you click 'save' with empty values.

**Comment by nileshgulia1** [comment]
Cannot reproduce anymore.
