### ISSUE TITLE
UX: Pastanaga Editor: No user feedback when creating a page and hitting the save button

### ISSUE THREAD

**Issue by tisto** [plone/volto#222]
1) Go to https://plone-react.kitconcept.io/add?type=Document
2) Login
3) Create a new document
4) Hit the save button without doing anything
-> Nothing happens
Expected behavior:
-> Either the save button is greyed out and can not be clicked without a title or the document is saved with an auto-generated title

**Comment by pigeonflight** [comment]
This is what I see:
![image](https://user-images.githubusercontent.com/31827/46490857-bf365700-c7ce-11e8-9a85-0a2147a60e11.png)

So at least it shows an error on attempted save.

Greying out the save button would be desirable.

**Comment by tisto** [comment]
@pigeonflight FYI: your screenshot does not show the Pastanaga editor. This screenshot has nothing to do with my originally reported issue here: https://plone-react.kitconcept.io/add?type=Document

**Comment by pigeonflight** [comment]
:) I'm clearly speaking out of ignorance.

**Comment by kunal-mohta** [comment]
I am not quite able to understand this issue. When I hit the save button without making any changes, I get the same result as @pigeonflight

**Comment by sneridagh** [comment]
https://zpl.io/VYKlwAn and https://zpl.io/aR1lrEN

The Pastanaga messages, as toasts and messages are ok, depending on the context.

**Comment by sneridagh** [comment]
<img width="393" alt="image" src="https://user-images.githubusercontent.com/486927/54524429-3ec97400-4972-11e9-8913-e62fb7f96188.png">
<img width="387" alt="image" src="https://user-images.githubusercontent.com/486927/54524443-48eb7280-4972-11e9-9fe4-b72812b6520c.png">

**Comment by sneridagh** [comment]
Related to #701

**Comment by davisagli** [comment]
Currently this shows a toast which seems fine
![Screen Shot 2022-07-27 at 9 31 47 PM](https://user-images.githubusercontent.com/49014/181421057-5b3ec0a4-c6dc-4176-9b7d-b7aa3a654cba.png)
