### ISSUE TITLE
Reset Password: Mail with link to frontend

### ISSUE THREAD

**Issue by ksuess** [plone/volto#2222]
**Describe the bug**
User triggers a password reset and gets mail. The mail has a link to reset the password, but the address is not an address of the frontend but an address  /api/

**To Reproduce**
1. go to /login
2. click on 'I forgot my password. what next?'
3. type in login or email
4. click save (wording could be changed to 'send')

**Expected behavior**
mail with link to frontend

**Software (please complete the following information):**
Volto master (Volto 12 alpha)

**Comment by tiberiuichim** [comment]
@ksuess As far as I know (though I have never tested this), kitconcept.volto has this exact same problem in mind with this: https://github.com/kitconcept/kitconcept.volto/blob/master/src/kitconcept/volto/interfaces.py#L15
