### ISSUE TITLE
Actions/Reducers have the same path in their index modules, making it impossible them

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#223]
e.g.

actions/index.jsx module:
```
...
./search/search
...
```

reducers/index.jsx module:
```
...
./search/search
...
```
so, when writing an override both paths collides, and Webpack doesn't know which one to override. This might go away when using Plone-React-app, but still it might be nice to change it.

**Comment by robgietema** [comment]
Fixed, we're doing absolute imports now.
