### ISSUE TITLE
Search page doesn't follow Plone's settings of searchable types

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2263]
The `@search` endpoint is also used in the contents view, which makes it a problem as the search now can't follow the settings.

**Comment by tisto** [comment]
@tiberiuichim this is exactly the reason why we can't make the search endpoint aware of searchable types. Devs will have different expectations on the API endpoint. I guess we have to find another solution to this issue that restricting the search endpoint (by default).

**Comment by tiberiuichim** [comment]
@tisto I'm working on adding a new parameter to the `@search` endpoint, it will be passed from Volto's /search page. Based on discussions with Victor.

**Comment by tisto** [comment]
@tiberiuichim please follow our "documentation first" approach and create a PR with the documentation before you start with the implementation.

**Comment by tiberiuichim** [comment]
@tisto Volto doesn't follow Plone's settings on what is searchable. It's a bug, not a feature.

**Comment by tiberiuichim** [comment]
@tisto: I'm not sure how a documentation-first approach would look like. We're talking about a single parameter that can be passed to an endpoint. I've started the doc here, but without an implementation is difficult to follow plone.restapi's request/response documentation approach.

https://github.com/plone/plone.restapi/pull/1081/files#diff-790a0f68740f41b97cdedd15b90946ce18061ec9f46e5fb31fc2cd7aecb8b387R167

**Comment by tisto** [comment]
@tiberiuichim that's sufficient. It basically boils down to how to name the param and document it:

https://github.com/plone/plone.restapi/pull/1081/files#diff-790a0f68740f41b97cdedd15b90946ce18061ec9f46e5fb31fc2cd7aecb8b387R167

**Comment by sneridagh** [comment]
Closing since it's implemented in #2264
