### ISSUE TITLE
Some suggestions for the generator 

### ISSUE THREAD

**Issue by anrakit** [plone/volto#2265]
Hey I just started using volto and i found some confusing stuff during the setup for a new volto project. I have some suggestions for a better setup experience.

If you want to create a new  volto-project by using the command
`npm init yo @plone/volto`
You will automatically have to answer a few questions.

1. `? Project name`
-> maybe a hint would be helpful about the restriction (no blanks, etc.)

2. `? Project description (A volto -powered Plone frontend)`
-> im not sure if this is really needed but here you simply continue by pressing enter.

3. `? Would you like to add addons? (true)`
-> should be false by default (should say: would you like to add existing Volto add-ons to your project?)

4. `? Would you like to add workspaces? (true)`
-> should be false by default (and again I'm not sure if this is even needed during the setup - we discussed that in a team and tought this could be probably removed in general.)

**Comment by avoinea** [comment]
Fixed.
