### ISSUE TITLE
Generator prompts are confusing for beginners

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2266]
Somebody just starting with Volto doesn't know what an addon or workspace is. By default the generator asks for this information.

The --addons and --workspaces flags are only useful for scripts and CI setup. My proposal is not to expose them in the prompts.

The generator should construct a Volto project perfectly fit for development: have mrs-developer integrated, and finish with several prompts with further instructions on how to go next. (create an addon, links to several chapters in the documentation, etc).

**Comment by tisto** [comment]
I fully agree. From my own experience with other systems, I can tell that fewer questions and sensible defaults are the keys to dev satisfaction. Yeoman allows to pass further options via command line, which is great. So we can assume that more experienced devs know how to handle this, we should optimize for the newby/default use case and make that experience as pleasant and straight-forward as possible.

**Comment by tisto** [comment]
Todo:

* [ ] Define target audience
* [ ] What does this particular target audience need?
* [ ] Implementent the best option for that target audience

**Comment by avoinea** [comment]
Audience:
- CI / CD (Jenkins, Github actions)
  - --no-interactive
- Docker images / containers
  - --no-interactive
- Try Volto
  - Quick up&running
- Frontend dev
  - Beginner
    - Generate initial project
    - Easily add existing add-ons to project
  - Advanced
    - Easily generate new add-ons and start working within without having to tweak `mrs.develop.json` / `package.json`
    - Add-on templates from github

**Comment by avoinea** [comment]
Fixed.
