### ISSUE TITLE
Warning message in Volto bootstrap: "Warning: forwardRef render... "

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#2305]
Warning: forwardRef render functions do not support propTypes or defaultProps. Did you accidentally pass a React component?

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/486927/112718063-e5956300-8ef0-11eb-883c-1c123ced71ab.png">

**Comment by nileshgulia1** [comment]
fixed by #2309
