### ISSUE TITLE
Sidebar main element still do not fill the whole height

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#2308]
@avoinea do you know what we changed there for it to behave different now?

![image](https://user-images.githubusercontent.com/486927/112747328-01623d00-8fb5-11eb-913a-eaa3f2a456db.png)

**Comment by sneridagh** [comment]
@avoinea it seems #2292 fixed some things but also broke others. Where it was wrong (the sshot in the PR)? Can I have a look? I think that we might need both:

```
    height: 100%;
    min-height: 100%;
```

**Comment by avoinea** [comment]
@sneridagh Indeed :disappointed: 

One solution would be to remove the `raised segments` but maybe there is a better one out there.

**Comment by sneridagh** [comment]
For quanta we should re-visit it, for sure. However, can I take a look where it fails with the height?

**Comment by avoinea** [comment]
@sneridagh It was mostly within InlineForm but I already removed the raised and segments here https://github.com/plone/volto/pull/2295/files#diff-152a160265a543b914f56865c5c6b77c87866f006303b0682d087b90e2b675daR41

Thus, I think we can revert it to `height: 100%` and then look for a better fix if it replicates elsewhere.
