### ISSUE TITLE
LinkMore in listing block as opt-in

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#2312]
**Is your feature request related to a problem? Please describe.**
Some of our clients were confused about the "link more" presence in the listing block settings.

**Describe the solution you'd like**
Could we make the ListingMore opt-in, via block setup?

**Describe alternatives you've considered**
Having to override the whole ListingBody is cumbersome :( I would prefer it doing it via config.

**Additional context**
https://github.com/plone/volto/blob/a7712629253cf21d9828bafd0fc26466142a68bc/src/components/manage/Blocks/Listing/ListingSidebar.jsx#L80-L83

/cc @giuliaghisini @nzambello @pnicolli

**Comment by nzambello** [comment]
@sneridagh I think this is done
