### ISSUE TITLE
Stop changing block id onMutateBlock

### ISSUE THREAD

**Issue by avoinea** [plone/volto#2330]
This approach generates a lot of issues when used together with DX Blocks Layout Editor.

**How to reproduce:**

* Go to DX Blocks Layout Editor on you content-type:
* Add a new text block and make it fixed, required, etc.
* Now click on the plus sign and add a new image block
* All the settings on the text field are lost

Proposed solution:
* Stop using the text uid for the new block on mutateBlock and generate new one:

https://github.com/plone/volto/blob/5daa6a128a226a3e54da05e53e33c72a0a8fe60b/src/helpers/Blocks/Blocks.js#L154

**Comment by tiberiuichim** [comment]
I don't think it will be a problem to fix it as you propose. Push a PR
