### ISSUE TITLE
Blocks in edit mode have a duplicated wrapper

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#2338]
**Describe the bug**

<img width="626" alt="Screenshot 2021-04-06 at 10 19 31" src="https://user-images.githubusercontent.com/486927/113682565-95be5500-96c3-11eb-958d-cceab836442c.png">

https://github.com/plone/volto/blob/dce52d08956d405dc7e07135164a55d8d61303d3/src/components/manage/Blocks/Block/EditBlockWrapper.jsx#L50

and

https://github.com/plone/volto/blob/c0a983cc2bf63e89709215e420b3d52a7880814e/src/components/manage/Blocks/Block/Edit.jsx#L128

**Expected behavior**
Only one wrapper is present.

**Additional context**
Cypress tests and CSS selectors are affected.

**Comment by sneridagh** [comment]
Which one is the safest to remove?

**Comment by tiberiuichim** [comment]
Edit.jsx
