### ISSUE TITLE
Moment.js is a legacy project, Temporal is coming

### ISSUE THREAD

**Issue by pnicolli** [plone/volto#2392]
Moment.js is a legacy project, it is officially been stated. ``react-dates``, which we are using, among other components we have, depends on it, and we also use it in other places.

Temporal will be the new standard, it got to Stage 3. I still have to look further into it, but I wanted to raise awareness on the subject and possibly collect some comments.
Due to this new standard, migrating to other famous libraries like ``date-fns`` is probably not a good idea at this time, so unless we find out something interesting, we might want to keep an eye on these new standard and check how the world will adapt.

One possibly interesting issue on the subject (at least the latest comments):
https://github.com/airbnb/react-dates/issues/208

**Comment by pnicolli** [comment]
@plone/volto-team we can probably close this since we base our future on `react-aria-components` which does not revolve around momentjs anymore, while Temporal is STILL stage 3 after 3 years :/

**Comment by stevepiercy** [comment]
`react-dates` requires excessive clicks to go to a specific year or month. Try picking your birthdate. Forget it! I'll just type it in. The date picker we choose should make it easy to select a year or month without all the clickety-clicks, tappity-taps, and swipe-ity-swipes.

Without question, yeet moment.js from the stack.

I could not find how to navigate to specific months and years in [`react-aria-components` DatePicker](https://react-spectrum.adobe.com/react-aria/DatePicker.html), other than using excessive clicks or keyboard entry. Did I miss something?

In any case, yes, paste a link to the issue or PR regarding the move to `react-aria-components`, then close this issue.

References:

- https://github.com/plone/volto/issues/4352
- https://github.com/plone/volto/issues/4332
- https://github.com/plone/volto/issues/4756
- https://github.com/plone/volto/issues/4204

**Comment by davisagli** [comment]
@stevepiercy The [docs for the react-aria calendar component](https://react-spectrum.adobe.com/react-aria/useCalendar.html#styled-examples) link to an example of how to add custom month/date selectors: https://codesandbox.io/p/sandbox/affectionate-rosalind-tdm323?file=%2Fsrc%2FCalendar.js

**Comment by stevepiercy** [comment]
@davisagli thanks! I updated the [PLIP's "Proposal and Implementation" section](https://github.com/plone/volto/issues/5629).
