### ISSUE TITLE
Link Integrity for Content Objects

### ISSUE THREAD

**Issue by tisto** [plone/volto#2396]
**Is your feature request related to a problem? Please describe.**

Plone Classic shows a link integrity warning when an editor deletes a page that is referenced by another page. This is an essential CMS feature that Volto currently lacks.

**Describe the solution you'd like**

* Create page "My Page"
* Create page "My Second Page" with a link to "My Page" in DraftJS
* Delete "My Page"
* After hitting the "Delete" Button, Volto shows a warning message that lists all the references this delete action would break and the option to cancel or finish the delete operation

**Comment by cekk** [comment]
related to this: https://github.com/plone/plone.restapi/pull/953

**Comment by ThomasKindermann** [comment]
@steffenri yes i worked on the frontend part in Sorrento

**Comment by davisagli** [comment]
This was added in #3317
