### ISSUE TITLE
Paste blocks to another page doesn't work

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#2448]
**Describe the bug**
When you copy some blocks (in our case one block) from a page to a new page, it doesn't paste blocks. If you look into the console you have an error 'cannot read property @type of undefined:

**To Reproduce**
1. Go to a page with some blocks (some listing blocks)
2. Hold cmd button to copy blocks, and click on a block and then to another block to enable selection 
3. Click again on the second block selected, to unselect it (because we want to copy only one block)
4. Click on copy button in toolbar
5. Go to another new page
6. Paste copied blocks
7. You see the error

This happens because the unselected block is in array of copied blocks as 'undefined'.
I also think it should be possible to copy only one block, then enable the copy functionality even just by selecting one block.

**Screenshots**
![image](https://user-images.githubusercontent.com/51911425/118230000-3e16c480-b48d-11eb-831e-6c0af4071dff.png)

**Comment by tiberiuichim** [comment]
@giuliaghisini I couldn't replicate the problem on volto.kitconcept.com.

**Comment by giuliaghisini** [comment]
@tiberiuichim i forget some details, i've updated the steps to reproduce in issue description..

**Comment by tiberiuichim** [comment]
ah, I see. I think there's a problem with the copy of a single block, probably an extra check somewhere.
