### ISSUE TITLE
Expose Plone on alternate path for volto.kitconcept.com

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2456]
We use the volto.kitconcept.com as the reference implementation. Sometimes we need to debug things (for example I somehow just broke the frontpage by applying a callout over a blockquote in the draftjs editor), but with Seamless mode it's no longer possible, as the /api path is no longer accessible.

So, can we have another entry path to Plone classic?

**Comment by sneridagh** [comment]
6.demo.plone.org is on classic deployment!
