### ISSUE TITLE
Js are not executed in Error pages

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#2461]
https://github.com/plone/volto/blob/d0d46260faa4a1a5446ab161aca64375c2fb210d/src/server.jsx#L229

Why this?

This is a problem for us, because in error pages some items (for example megamenu with dropdown) needs to be in page and working.

**Comment by tiberiuichim** [comment]
https://volto.kitconcept.com/sadasdas

![Screenshot_20210518_150501](https://user-images.githubusercontent.com/141568/118647926-8ebe5280-b7ea-11eb-99df-46e6635b26ee.png)

![Screenshot_20210518_150433](https://user-images.githubusercontent.com/141568/118647943-91b94300-b7ea-11eb-99f6-077770089bc3.png)

**Comment by tiberiuichim** [comment]
![Screenshot_20210518_150728](https://user-images.githubusercontent.com/141568/118648153-ce853a00-b7ea-11eb-8721-bad44384c152.png)

I think error pages shouldn't try to load application.

**Comment by nzambello** [comment]
I think that for a CMS would be good to have at least the navigation: if an user fell into a non existing content, he should be directed to the content he's looking for using the navigation and the footer. Going to the homepage should be the fallback I guess.

@giuliaghisini and I are planning to dig a bit into this, to see if we can have the stability and the functionality of both the situations (with and without extractScripts set to true)

**Comment by giuliaghisini** [comment]
We found that the reason why js were disabled in the error pages, was because CORS error is showing from client instead of showing the true error (on the SSR it works fine). This happens when the frontend (Volto) baseurl is different from the BE (Plone) baseurl, but if they both have the same baseurl, then the problem is not there and everything works fine.
I think the problem is therefore only in development, unless FE and BE are published with different baseurls in production.

**Comment by tiberiuichim** [comment]
I don't remember much from those changes... but if you figure out a way to make this thing work properly, I'd be very happy.

What I fear, and this is the reason why I think error pages should be as simple as possible, is that by making the error pages include too much "application code", we're risking a situation where the error page would crash.

Maybe we need to isolate parts and include "ErrorBoundaries" around our components?

**Comment by giuliaghisini** [comment]
@tisto i agree to set it in config.js file. The default will obviously remain the current one.

**Comment by giuliaghisini** [comment]
i've created this pr :https://github.com/plone/volto/pull/2465
