### ISSUE TITLE
Listing block doesn't respect Results limit

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2473]
It should function as "max results", as far as I understand, but even if I set the limit to 2, I still get all there results.

**Comment by tiberiuichim** [comment]
I think it happens only when no search criteria are defined.

**Comment by ionlizarazu** [comment]
I think is related with [this line ](https://github.com/plone/volto/blob/e432d05650ef2d1dc7856f3b6c393306a57ae964/src/components/manage/Blocks/Listing/ListingBody.jsx#L25). The limit parameter that is modified when you change data is outside of query value, so no request are launched.

**Comment by iRohitSingh** [comment]
@tiberiuichim , I am work on this issue and try to reproduce it but i am unable to do so .
Steps which i have done.
1. Created bunch of page content type.
2. Created listing blocks.
3. Checked the result limit parameters.
4. It's  working perfectly fine.

**Comment by tiberiuichim** [comment]
@iRohitSingh At some point I've restructured the "data fetching logic", now it looks like this HOC: https://github.com/plone/volto/blob/ec8ee39e602a39d943d5eb523adf6cae64507497/src/components/manage/Blocks/Listing/withQuerystringResults.jsx#L12

**Comment by davisagli** [comment]
Currently the Results Limit field is disabled when no criteria are specified (because then the block is showing folder contents, not query results)
