### ISSUE TITLE
Full SEO support

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#252]
and add ability to configure meta tags in the <head>

Maybe include a configuration item that includes them in Html helper or alternativelly using Helmet in the App component.

**Comment by robgietema** [comment]
We could add this to the config.js

**Comment by vinay72** [comment]
Configure Meta title and Meta description

Perform the following:

    Open the static module whose content items you want to configure with specific meta title and description and in the right pane, click Custom Fields for <content type>.
    For dynamic modules, navigate to Administration » Module builder, click the module and then, the content type.
    Create the following custom fields:
        Type: Search engine optimization, Meta field: Meta title.
        Type: Search engine optimization, Meta field: Meta description.

        NOTE: When you create the fields, you can make them localizable. This way, you can display different content items for different language versions.
        For more information about creating custom fields, see Create custom fields.
    Create a new content item, or edit an existing one.
    You will see the new fields.
    Fill out the Title for search engines and the Description fields.
    If you leave Title for search engines field blank, the system will automatically fill it out with the Title of the item.

    IMPORTANT: If you leave the Description field empty, Sitefinity CMS  automatically fills it out with the content of the first field after the content of the content item, regardless of whether it is a long or short text field. 
    For example, if after the news item, you have a Summary field, the Description field will be populated with the content of the Summary field. For dynamic modules, you can use Modify the backend screens of a dynamic module to change the order of the fields.

RESULT: When you open the content item in detailed view, the runtime value of these fields is used to set the page meta title and meta description tags in the <head> tag of the page. If you do not set them, the meta title is taken from the title field of the static content item or the identifier field of the dynamic content item.

**Comment by tisto** [comment]
FYI: there is https://github.com/kitconcept/kitconcept.seo which provides all the basic SEO fields (and more). I guess we would have to write and release a frontend part for this (that overrides the helmet component) or add some kind of hooks that kitconcept.seo (and possibly other extensions) can hook in.

**Comment by tiberiuichim** [comment]
I think BodyClass can be used as an example on how  to lift stuff from the child route components to the top level, together with asyncConnect they might do the job

**Comment by nzambello** [comment]
This thread covers wider aspects, but a part of this has been worked in https://github.com/plone/volto/pull/2132
