### ISSUE TITLE
ObjectListWidget doesn't pass intl to schemaExtender

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2536]
https://github.com/plone/volto/blob/d8aecf4aa0386ad784aa9021c5048c6cae92e8b5/src/components/manage/Widgets/ObjectListWidget.jsx#L179 should also pass `intl`

**Comment by 1bsilver** [comment]
Hi! I'm trying to contribute to open source, and I want a first issue. Would you mind assigning me this?

**Comment by tiberiuichim** [comment]
@1bsilver Hi Ibrahim! I'm happy to see your desire to contribute!

**Comment by 1bsilver** [comment]
Thanks @tiberiuichim! 
I pulled a request but I think I need to wait for my agreement to be verified. 
https://github.com/plone/volto/pull/2575
