### ISSUE TITLE
Update bundlesize to get rid of iltorb

### ISSUE THREAD

**Issue by ksuess** [plone/volto#2606]
yarn fails.
https://gist.github.com/ksuess/a027fbb516b9c8160db51f1d60a8c112

- current Volto 13.8.2
- Mac M1

By now we have bundlesize 0.18.0 with following dependencies (see yarn.lock)

```
bundlesize@0.18.0:
  version "0.18.0"
  resolved "https://registry.yarnpkg.com/bundlesize/-/bundlesize-0.18.0.tgz#3625520f984f503df8c3d57dd9be2b9c0df40092"
  integrity sha512-GZURr25umfYxZYZUyOlOtJRbYjAn0VfbjbnS0NBcOiF8VcjmhoEhmx8Gw4va8HeQb8j7Ra0ZltY/IeHgSHFXFw==
  dependencies:
    axios "^0.19.0"
    brotli-size "0.1.0"
```

current 'brotli-size ' exterminates iltorb. And that is what would help M1 machines to run 'yarn' without failure.

bundlisize seems to be poor maintained: see bundlesize2 and branches of bundlesize. Is there an alternative to bundlesize? https://www.npmtrends.com/size-limit-vs-bundlesize-vs-cost-of-modules-vs-bundlewatch-vs-rollup-plugin-size-snapshot-vs-rollup-plugin-sizes-vs-rollup-plugin-visualizer-vs-rollup-plugin-analyzer

Github action https://github.com/andresz1/size-limit-action
- Commenting pull requests with the comparison of Size Limit output.
- Rejecting a pull request if the cost exceeds the limit.

**Comment by tiberiuichim** [comment]
Let's try to eliminate this dependency... I see that there's difficulties in installing iltorb as it needs a binary package.

```
 yarn why iltorb                                                                                                                                  (base) 13.79h  Mon 08 Nov 2021 08:05:57 AM EET
yarn why v1.22.11
[1/4] Why do we have the module "iltorb"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "iltorb@2.4.5"
info Reasons this module exists
   - "_project_#@plone#volto#bundlesize#brotli-size" depends on it
   - Hoisted from "_project_#@plone#volto#bundlesize#brotli-size#iltorb"
info Disk size without dependencies: "6.09MB"
info Disk size with unique dependencies: "6.75MB"
info Disk size with transitive dependencies: "9.88MB"
info Number of shared dependencies: 40
Done in 0.87s.
```

**Comment by tisto** [comment]
@ksuess @tiberiuichim bundlesize is a helper library to check the bundle size. If it causes problems we should just remove it. If I understood @sneridagh correctly we can have devDependencies again...

**Comment by tisto** [comment]
@ksuess @tiberiuichim @sneridagh PR to remove bundlesize:

https://github.com/plone/volto/pull/2820

We decided to go with bundlewatch for bundle size checks anyways. So this was just a leftover...
