### ISSUE TITLE
Rename "Dexterity Content Types" to just "Content Types"

### ISSUE THREAD

**Issue by tisto** [plone/volto#2623]
**Is your feature request related to a problem? Please describe.**

It does not make any sense for Volto or Plone 6 to keep the name "Dexterity" in the control panel or anywhere else. We just have one content types framework. Archetypes is dead dead dead and not available in Plone. Nobody cares about the internal name.

**Comment by erral** [comment]
This goes in the controlpanel.xml in plone.app.dexterity and the translations of this file, should be changed there:

https://github.com/plone/plone.app.dexterity/blob/master/plone/app/dexterity/profiles/default/controlpanel.xml

**Comment by sneridagh** [comment]
Indeed, this should be done in the backend.

**Comment by davisagli** [comment]
Done in https://github.com/plone/plone.app.dexterity/pull/341
