### ISSUE TITLE
SelectWidget / ArrayWidget cache search results and on the second load they display an incomplete vocabulary

### ISSUE THREAD

**Issue by avoinea** [plone/volto#2657]
Update: Try on Chrome if Firefox doesn't show any interactions within the video playback

https://user-images.githubusercontent.com/323385/133121773-c5be5bc9-708e-478a-9e64-54795a4b336d.mp4

**Comment by avoinea** [comment]
Someone did it on purpose:

https://github.com/plone/volto/blob/ec386e1b276138e6be0730b2aea1f798af2a2a4c/src/components/manage/Widgets/SelectWidget.jsx#L308-L313

**Comment by nileshgulia1** [comment]
Not connected to this but might be good to take care also #2540
