### ISSUE TITLE
Impossible to edit a document called "history"

### ISSUE THREAD

**Issue by tisto** [plone/volto#2692]
**Describe the bug**

When an editor creates a new object with the name "history", it is impossible for the editor to edit that object.

**To Reproduce**

1. As admin
2. Go to https://volto.kitconcept.com/
2. Create a new Page with the title "History"
3. Page "https://volto.kitconcept.com/history" shows the front-page
4. Clicking on edit leads to the edit view of the front-page

**Expected behavior**

I'd expect that either the system prevents the user from creating content with reserved words (show a validation error, rename the content object automatically), or that we make this "just" work.

**Comment by tisto** [comment]
@sneridagh @plone/volto-team is there a way for editors to use reserved words like "history" in the URL? It is hard to tell clients that they can not create a page like www.mydomain.com/history. I guess the only way to solve this is to start using something like "/@@history".

**Comment by tiberiuichim** [comment]
I'm +1 on changing the builtin routes. I'd propose something like /+history, as not to clash with view names.

**Comment by pnicolli** [comment]
> I'm +1 on changing the builtin routes. I'd propose something like /+history, as not to clash with view names.

I don't understand, aren't these exactly views? Before reading your comment I would have suggested to keep ``@@`` for consistency with usuale Plone behavior, am I missing something?

**Comment by tiberiuichim** [comment]
I'm concerned that there will be confusion and inconsistency and will make it even harder to expose classic Plone views with something like https://github.com/eea/volto-middleware-vh

**Comment by tisto** [comment]
@tiberiuichim can you elaborate how exactly a frontend view @@history could clash with a backend view @@history? Don't we always have a way of telling exactly which is which?

**Comment by tiberiuichim** [comment]
In today's Volto we have a [@@images and @@download](https://github.com/plone/volto/blob/d1879d8cbdd56a4782865a052d32369bed378849/src/express-middleware/images.js#L25) proxies. They serve the Plone content 1:1, so for any `@@` view I'd expect to see the Plone backend answering for it. 

If we start prefixing our routes with `@@`, we will reach a point where, in the documentation, we'll have to say: 'this URL only works in Plone frontend', 'if you're looking for this view name in any zcml, you won't find it' and so on. Indeed, functionally the view names are the same and prefixing them similarly is enticing, but I think on long term it will cause headaches. 

There's also the possibility of clashing names and even if that probability is very low, we'll still be sharing the same URI space between two different things.

And I wonder if this argument wasn't the same when it lead to the decision of prefixing plone.rest endpoints with a single `@`.

**Comment by giuliaghisini** [comment]
@tisto i had the same problem with routes /add and /edit
i solved the problem for that routes here https://github.com/plone/volto/pull/2664
maybe you have to do the same for /history

**Comment by sneridagh** [comment]
I am a bit reluctant to change all the route names at this point, (think about existing user's bookmarks). I think the problem is much more easy to tackle, let's redefine "history" view name and call it something less "common".

This is the list of the current system routes:
https://github.com/plone/volto/blob/2b062ea2b69b4ab7bad1b2fa3c3da11a5d27c9ee/src/routes.js#L85

the others are fine, the only conflictive one is "history" indeed.

**Comment by tiberiuichim** [comment]
Indeed, that seems to be a simpler solution for now.
