### ISSUE TITLE
Some storybook pages are broken

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2695]
It seems in particular those that are "connected".

- https://docs.voltocms.com/storybook/?path=/story/internal-components-context-navigation--connected&globals=measureEnabled:false
- https://docs.voltocms.com/storybook/?path=/story/object-browser--connected&globals=measureEnabled:false (click on browse icon)

**Comment by ichim-david** [comment]
Example error response
![story-handle-controls](https://user-images.githubusercontent.com/152852/134777090-8f6c0298-d5ed-427d-a126-4da9621894e0.png)
