### ISSUE TITLE
Redirection take presendence over new content on SSR (most likely a plone.restapi issue)

### ISSUE THREAD

**Issue by tisto** [plone/volto#2765]
**To Reproduce**
1. As admin
2. Create a page under "/foo" with title "Foo"
3. Move that page to "/bar"
4. Create a new page under "/foo" with title "New Foo"
5. Go to "/foo"
6. -> you will see "Foo" (the redirected version)

**Expected behavior**

Volto will render the new page instead of following the redirect.

**Comment by davisagli** [comment]
Related to https://github.com/plone/plone.rest/pull/135

**Comment by djay** [comment]
@davisagli this is fixed with the latest restapi so can it be closed?

**Comment by davisagli** [comment]
@djay yep, thanks
