### ISSUE TITLE
Search block does not reset the pagination on filter/search refining

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#2814]
**Describe the bug**
Search block does not reset the pagination on filter/search refining, it should reset to page 1 on every search parameter refinement.

**To Reproduce**
1.- Create a search block in any content
2.- Define a search that forces the pagination to show up
3.- Navigate to another page
4.- Change the search

**Expected behavior**
The pagination should reset to page 1 once the new search is issued.

**Comment by tiberiuichim** [comment]
Fixed  by https://github.com/plone/volto/pull/2816
