### ISSUE TITLE
Default values setted in schema are not working in InlineForm

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#2851]
i've ha listing block with a variation and i've added some fields to the variation with a default value for each variation field.
But default value is not longer set. 
Debugging, i can se that onChangeField is triggered to change the default value of the field, but formData doesn't receive new value and no defaultValue is set.

**Comment by sneridagh** [comment]
We improved a bit the feature during last releases, and we had to change a bit its shape and preconditions. Which release are you using? Also, default should be the name od the field, although defaultValue is used un a couple of widgets still 😞 (like selects).

**Comment by tiberiuichim** [comment]
It's possible that applyBlockDefaults needs extension support... I don't know how I've missed it. I'm overdue with the finalization of that story anyway.

**Comment by giuliaghisini** [comment]
@sneridagh i'm using 14.0.0-alpha.32 version. Debugging fields defaultValue is correctly setted and the initial useEffect in InlineForm does what it has to do.. but onChangeField call doesn't have any effect on formData and nothing changes..

**Comment by giuliaghisini** [comment]
@sneridagh @tiberiuichim i dive into and i found that onChangeField in inlineForm triggers an onChangeBlock from ListingData.jsx and the problem is in From.jsx at line 531 where the setState have correct newFormData, but this doesn't causes a re-render of Form.jsx and so the attribute 'properties' passed to <BlocksForm> (value is the current formData in state) doesn't change..
I don't know how to fix it, but you could better understand the flow..

**Comment by tiberiuichim** [comment]
@wesleybl passing onChangeBlock to BlockDataForm is somewhat recent, and yes, it's the correct way to handle things. https://6.dev-docs.plone.org/volto/upgrade-guide/index.html#better-defaults-handling
