### ISSUE TITLE
Provide a PreviewImage component

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2867]
This sort of code, with the introduction of the preview image component, should be made a separate component.

https://github.com/plone/volto/blob/7a0ffcfcf55a4fc4bcd621a4caec676e8c50540d/src/components/manage/Blocks/Listing/SummaryTemplate.jsx#L29-L37

**Comment by ichim-david** [comment]
Component added as a pull request in https://github.com/plone/volto/pull/2888
