### ISSUE TITLE
Smart Listing Tile (Collection)

### ISSUE THREAD

**Issue by robgietema** [plone/volto#287]

**Comment by tisto** [comment]
@nileshgulia1 @sneridagh as long as we are missing the collection functionality we should remove it from the Volto UI. Can you please take care of this tomorrow?

**Comment by tisto** [comment]
@sneridagh the collection tile is one of the last large and important missing pieces. Maybe someone in Sorrento would like to have a look...

**Comment by tisto** [comment]
@sneridagh @albertcasado it would be great if we could get a rough draft of how the collection tile (and maybe the listing tile) should work and look like. I'd like to make this a priority for the Beethoven sprint next week.

**Comment by pnicolli** [comment]
WIP PR in #747
