### ISSUE TITLE
Separator-Block (Add-on)

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2879]

**Comment by tiberiuichim** [comment]
https://github.com/eea/volto-block-divider

**Comment by tisto** [comment]
https://www.npmjs.com/package/@kitconcept/volto-separator-block

![volto-separator-block](https://user-images.githubusercontent.com/632105/150323461-7423ab74-6d6f-4ceb-9585-5f302e95ccbe.png)

I guess we can close this issue. We have two add-ons available.
