### ISSUE TITLE
Headline-Block (Add-on)

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2881]

**Comment by tisto** [comment]
@tiberiuichim did you create the three tickets for button, headline, and separator add-on from the project issues that I created? The background of this list was that we plan to open-source those add-ons soonish.

**Comment by tiberiuichim** [comment]
@tisto yes, indeed, converted from the project. I was looking at them, thinking which one can be closed, as they tend to accumulate.

**Comment by tisto** [comment]
Heading Block has been published as open source:

https://www.npmjs.com/package/@kitconcept/volto-heading-block

We plan to further polish it and update the docs. Closing this ticket now.

**Comment by tiberiuichim** [comment]
@tisto Really cool, the headline block especially nice. Is there a separate repo for the two addons released? I only see links to the volto-blocks private repo.

**Comment by tisto** [comment]
@tiberiuichim that's the main culprit right now. We have one repo with all our blocks and we are in the process of open-sourcing them one by one. At the end of the process, we can publish the repo. That's not possible right now unfortunately though (just too many things in there, some are client-specific and we need to get approval from clients to open source the work they paid us to do). The client on our next big project (starting in March) offered to fund us to open source most of those blocks. If you (or anyone else) want to contribute to any of those blocks we can also find an intermediate solution until then though. I am currently working on a full inventory of our blocks, to at least have an overview of where we are and make a plan to open source them one after another.

**Comment by tisto** [comment]
@tiberiuichim oh, our list of priorities right now is mainly driven by the needs of @rioksane and the plone.org relaunch efforts (highlight teaser block) and by the blocks I showed in my keynote at ploneconf (I don't want to show stuff to people that we do not open source afterwards :)). Apart from that we will open source the most generic blocks first because they are most useful.
