### ISSUE TITLE
Listing block in "folder contents" summary view no longer shows thumbnails

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2891]
I think it's a regression introduced by https://github.com/plone/volto/pull/2731

Basically, when the listing block is working in "folder contents" mode, by not setting any query, the `items` children list are serialized as a summary, with no metadata fields included. I propose that we serialize them in plone.restapi with metadata (if possible). Otherwise, in plone.volto, include their image_field information.

**Comment by tiberiuichim** [comment]
Also related to https://github.com/plone/plone.volto/issues/33

**Comment by nileshgulia1** [comment]
should be fixed by https://github.com/plone/plone.volto/pull/20
