### ISSUE TITLE
Form Block

### ISSUE THREAD

**Issue by robgietema** [plone/volto#290]

**Comment by avoinea** [comment]
@robgietema Huh? Obsolete or it should be renamed to Form Block?!

**Comment by tisto** [comment]
@avelino this ticket is from 2018...different times :)

**Comment by sneridagh** [comment]
In 2022, https://github.com/collective/volto-form-block is candidate for core.

**Comment by davisagli** [comment]
Closing as a duplicate of #739 which has more info
