### ISSUE TITLE
Dynamic user information form and a route for it

### ISSUE THREAD

**Issue by erral** [plone/volto#2912]
Currently the User information form in Volto is directly hardcoded:

https://github.com/plone/volto/blob/master/src/components/manage/Preferences/PersonalInformation.jsx#L165

This form can easily be dynamic, linking it to a `@userschema` endpoint in plone.restapi to provide the user schema in JSONSchema format, so any change in Plone would be directly shown in Volto:

https://github.com/plone/plone.restapi/pull/707

Moreover, this form is shown directly in the toolbar which is OK for simple user-forms but when you have a big form with a lot of options it's better to show this form in a route (name it `/profile` or `/user-information`).

We have code to this (both the dynamic form and the route), this issue is to discuss if this approach is OK to integrate it in Volto.

**Comment by tiberiuichim** [comment]
+1 for integration to Volto.

**Comment by nileshgulia1** [comment]
+1. I'm also not a fan of showing user info inside the toolbar. It behaves like mobile all the time.

**Comment by tisto** [comment]
+1 to integrate it into Volto. Maybe we can have the best of both worlds. Move to a schema-generated form and have a flag in Volto that either shows the form inline (like Albert imagined and what I would consider to be the best option for the default form) or add a link instead that goes to "/profile".
