### ISSUE TITLE
Testing against Plone 6 alpha backend

### ISSUE THREAD

**Issue by fredvd** [plone/volto#2923]
@sneridagh I didn't exactly get part of the discussion during the Steering Circle  meeting from dec. 14th 2021 about Volto not testing against Plone 6.

it might be brute force and duplication, but can't we for the time being create an api6 folder that doest the same as api but following Plone6 alpha releases?

I can make a branch/PR for that.

When that works, we could extend the main makefiles and/or parameterize the backend commands to use one or the other ( api/api6). And run both tests in separate calls

It's not perfect but will probably work for now?

**Comment by tisto** [comment]
@fredvd we can test against Plone 6 in the current gh actions matrix: 

https://github.com/plone/volto/blob/master/.github/workflows/core.yml#L8

A separate "api6" folder is not necessary IMHO. I did not attend the steering circle meeting so I don't know what was discussed there...

**Comment by fredvd** [comment]
> @fredvd we can test against Plone 6 in the current gh actions matrix:

You mean it is possible to add Plone flavours there?  I jumped around throught the gh workflow, package.json and Makefile and if I understand it correctly the possible switch points to start a different backend are now in the chain:

* GH action has a matrix
* the ci:cypress:run invocation in the GH action to package.json
* package.json ci:cyprus:run  starts ci:start-api-plone 
* ci:start-api-plone runs Makefile start-acceptance-server
* Makefile start-acceptance-server starts a docker container with 'plone' at the moment, which is 5.2.(5?)

What is a good way to trickle down the GH matrix option to the docker container start?

**Comment by davisagli** [comment]
This was already added -- but seeing this made me realize we need to update to the latest release of both Plone 5 and 6, which I'm doing in #3544
