### ISSUE TITLE
Portrait/Avatar broken under Toolbar > PersonalTools panel

### ISSUE THREAD

**Issue by pigeonflight** [plone/volto#2927]
The user portrait returns as a broken link under the toolbar > personaltools.

**To Reproduce**
1.  Click on your avatar 
2. Click on 'Profile'
3. Upload a portrait 
![image](https://user-images.githubusercontent.com/31827/146381665-22b24d6e-de80-4828-8543-fffe4a0f69ca.png)

After it successfully uploads, the portrait will fail to load
For the admin user the output In the console looks like this:
```admin:1 GET http://localhost:3000/portal_memberdata/portraits/admin 404 (Not Found)```

**Expected behavior**
I expect the the portrait to load successfully and display in panel

**Software (please complete the following information):**
Volto 13.15.1
Plone 6.0.0a1
CMF 2.5.4
Zope 5.3
Python 3.9.8 (main, Nov 10 2021, 03:21:27) [GCC 8.3.0]
PIL 8.3.1 (Pillow)

**Comment by pigeonflight** [comment]
I think it relates to the Plone restapi as the api returns the broken URL when you query the @users endpoint.
see the associated acton that makes the call to the api: https://github.com/plone/volto/blob/2b062ea2b69b4ab7bad1b2fa3c3da11a5d27c9ee/src/actions/users/users.js

**Comment by giuliaghisini** [comment]
reproduced too
