### ISSUE TITLE
Vocabulary widget should allow editing the token

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2933]
One of the most frequent requests for collective.taxonomy was to be able to edit the token id. We need to have the same capability here, as well.

**Comment by ksuess** [comment]
Do you have an example, where a token needs to be edited?
The idea of this widget is to keep the token fixed to have a future proof vocabulary.

**Comment by tiberiuichim** [comment]
Maybe not "edited", but at least when adding the new terms. If this widget would allow editing the token, then we could use it in the volto-taxonomy collective.taxonomy integration. 

The idea to allow editing the token stems from the freedom that it provides: we can then create TTW vocabularies with terms matching from outside systems (for example items coming from SQL databases).

**Comment by ksuess** [comment]
Fixed with https://github.com/plone/volto/pull/2998
