### ISSUE TITLE
More options for the object browser's selectable content types

### ISSUE THREAD

**Issue by JeffersonBledsoe** [plone/volto#2993]
The object browser currently only has one way to filter the selectable content types is to set the mode to 'image', which forces you to select an image. The object browser's image mode currently works by checking `settings.imageObjects` for a list of allowed image objects. It would be useful if it were possible to apply similar restrictions to other content types, such as for use in the video block or for a file picker.

## Options
- Have various modes to support a number of various out-the-box modes.
  - This would not be useful for custom content-types unless the list of modes was adjustable, such as through a config setting.
- Have the user pass in the short name of allowed content-types to `openObjectBrowser`.

**Comment by fredvd** [comment]
IIRC I heard some Volto people speaking in Sorrento about a reworked object browser that has quicktype and other enhancements like you describe. But I'm not sure if it was already in a customer project and needs to be generalised, or if it is something from the ground up to be rebuild.  @sneridagh @pnicolli ?

**Comment by sneridagh** [comment]
Not sure if this is what you need:

https://docs.voltocms.com/blocks/editcomponent/#selectable-types

Also, notice that the widget can get customized via the shema (pass the pros you need along it). Here:

https://github.com/kitconcept/volto-blocks-grid/blob/main/src/components/Teaser/schema.js#L75

**Comment by JeffersonBledsoe** [comment]
> Not sure if this is what you need:
> 
> https://docs.voltocms.com/blocks/editcomponent/#selectable-types

My bad for not updating this issue, I found the selectableTypes key while looking through the component definition and have been using it without any issues! I missed these docs, I was expecting it to be documented in the Object browser storybook. Happy for me to PR an update to the storybook?

**Comment by tiberiuichim** [comment]
> Happy for me to PR an update to the storybook?

+1000
