### ISSUE TITLE
DateTime Widget: TypeError: `month` must be a valid moment object

### ISSUE THREAD

**Issue by arky** [plone/volto#3002]
**Describe the bug**
Date only input field results in TypeError in Firefox. 
TypeError: `month` must be a valid moment object

This is problem specific to 'Firefox 96' on gnu/Linux. Google Chrome (97.0.4692.71) doesn't reproduce this problem.

**To Reproduce**
1. Go to Volto Storybook 
2. Select Date story and toggle 'Date only' boolean  https://docs.voltocms.com/storybook/?path=/story/widgets-datetime--datetime&args=dateOnly:true&globals=measureEnabled:false;backgrounds.grid:false
3. Select a date
4. The Date Field Shows 'Invalid Date'
**Expected behavior**
A valid date needs to be return 

**Screenshots**

![image](https://user-images.githubusercontent.com/808895/150793273-ba2aab57-74e8-4d9f-ac02-2c5e11ce1d27.png)

**Software (please complete the following information):**
 - OS:  gnu/Linux Ubuntu 64bit
 - Browser Firefox Firefox 96'
 - Volto Version : 14 
 - Plone Version : 6.0.0a2 (6002)
 - Plone REST API Version : 8.16.2

**Additional context**
Complete tracelogs and other debug information can be found in this thread: 
https://community.plone.org/t/volto-date-field-month-must-be-a-valid-moment-object/14738/4

**Comment by arky** [comment]
@tiberiuichim @sneridagh I have tested this with volto (https://github.com/plone/volto/releases/tag/14.7.0) I am still able to reproduce the issue in Firefox?

**Comment by tiberiuichim** [comment]
@arky There was no work done on this, sorry. Maybe we can add a "best with Chrome" sticker at the bottom? (joking)

**Comment by arky** [comment]
@tiberiuichim My apologies, Just reading the changelog I assumed this was patched.

**Comment by tiberiuichim** [comment]
@arky there was work done on the date libraries, but it didn't touch the datetime widget (AFAIK). Looking at the changelog, that work is marked in the "Internal" sections, we would have used "Bugfix" in case it solved any issue.

**Comment by arky** [comment]
This issue is no longer reproducible in firefox. Closing this as resolved for now.
