### ISSUE TITLE
User Controlpanel: Manage user group membership

### ISSUE THREAD

**Issue by ksuess** [plone/volto#3018]
- [x] Matrix of users and groups to change membership
- [x] Change event handler with confirmation
- [x] Filter users by groups
- [x] Filter users with search
- [x] Filter groups with search
- [x] Option to show also the groups of shown users, additional to searched groups
- [x] Sort Users alphabetically
- [x] Sort Groups alphabetically
- [x] Batch editing of membership per group
- [x] Consider flags 'many users' and 'many groups'

![image](https://user-images.githubusercontent.com/1144737/167593110-3c31bce0-bc0a-410e-b329-a35fbc01d1a8.png)

**Comment by nileshgulia1** [comment]
Yes, A duplicate: https://github.com/plone/volto/issues/2710

**Comment by ksuess** [comment]
I articulated confusing. What I mean is:
- add an existing user to an existing group

![image](https://user-images.githubusercontent.com/1144737/151961988-00726d8c-ea65-4922-a4bf-a5fcadf05f2b.png)

**Comment by nileshgulia1** [comment]
@ksuess This will be the starting point (Include users data in `GET` groups call): https://github.com/plone/plone.restapi/pull/1325

**Comment by ksuess** [comment]
@nileshgulia1 Great, that you attack this!

**Comment by ksuess** [comment]
Here is my proposal for the UI of a user group membership management.
The idea is to have all users and groups under the finger tip in one view. So this matrix of users vs groups could be build with 
- a modified search block component
- with a checkbox click event handler which updates the membership. An update is confirmed with a toast.

The view can be a separate control panel or can be integrated in the existing user control panel or group control panel.
Let me know what you think!



https://user-images.githubusercontent.com/1144737/167105466-3f972b6a-bb9d-41e6-9145-8c24cd9f7a16.mov

**Comment by nileshgulia1** [comment]
@ksuess  The draft looks good. I'm okay to have a separate controlpanel named something like "membership management" placed in users and Groups segment in `/controlpanels`

**Comment by ksuess** [comment]
![image](https://user-images.githubusercontent.com/1144737/167393011-f30ad784-d9ae-4ffe-9e4f-cc1553732fea.png)
