### ISSUE TITLE
Pastanaga Editor: Inline handler for adding inbetween tiles

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#302]
![img_0880](https://user-images.githubusercontent.com/486927/48308032-9fe4d380-e59d-11e8-8844-404b17ba44ed.jpeg)

Click outside unselects all fields and it appears the (+) button below all content

Move tile toolbar to inside the tile again.

**Comment by tisto** [comment]
PR: https://github.com/plone/volto/pull/644

**Comment by sneridagh** [comment]
![image](https://user-images.githubusercontent.com/486927/54523856-c1513400-4970-11e9-8171-208e3d81edd9.png)

**Comment by sneridagh** [comment]
See https://github.com/plone/volto/issues/689.

**Comment by sneridagh** [comment]
Solved for now in desktop by using the `RETURN` key in any tile. However, we need a way to do it in mobile/touch environments.

For now, making the editor work on responsive is not a priority, since we need the Pastanaga Toolbar in place first.
