### ISSUE TITLE
Docs need meta_html values

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#3033]
On `plone6-docs` branch, the `html_meta` values are missing from every page. These values are used to improve SEO. Omitting them results in errors when building the docs with Sphinx.

Note that the values for `description` and `property=og:description` should be identical.

```
html_meta:
  "description": ""
  "property=og:description": ""
  "property=og:title": ""
  "keywords": ""
```

**Comment by ktsrivastava29** [comment]
@stevepiercy I think I can work on this issue, may I? 
Should I create a new branch for this or should I start pushing on the updates in the docs-lang branch itself?

**Comment by ktsrivastava29** [comment]
@stevepiercy as the `plone/documentation` is a separate repository, should I create a pull request in that repository after making the modifications?

**Comment by stevepiercy** [comment]
No. These changes should be made in the volto project only. The main documentation repository imports volto and plone.restapi repositories.
