### ISSUE TITLE
Docs: Remove `legacy` directory and content?

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#3034]
There is a directory `legacy` that does not appear in the sitewide navigation, and its content appears to no longer be needed. What should be done with this directory?

- https://docs.voltocms.com/legacy/introduction/
- https://docs.voltocms.com/legacy/manage/
- https://docs.voltocms.com/legacy/mosaic/
- https://docs.voltocms.com/legacy/theme/
- https://docs.voltocms.com/legacy/create_example.txt

Their presence currently causes MyST warnings such as these:

`volto/docs/source/legacy/manage.md:10: WARNING: Duplicate reference definition: COMMENT [myst.ref]`

**Comment by sneridagh** [comment]
@stevepiercy these ones can be removed safely.

**Comment by stevepiercy** [comment]
Closed by #3076
