### ISSUE TITLE
Docs: WARNING: document isn't included in any toctree

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#3036]
Here is a complete list of the Sphinx warning `WARNING: document isn't included in any toctree`.

- docs/source/cheatsheet.md
- docs/source/configuration/locking.md
- docs/source/configuration/volto-config-js.md
- docs/source/contributing/volips.md
- docs/source/developer-guidelines/design-principles.md
- docs/source/developer-guidelines/style-guide.md
- docs/source/developer-guidelines/typescript.md
- docs/source/ie11compat.md
- docs/source/index.md
- docs/source/introduction/introduction.md
- ~~docs/source/legacy/introduction.md~~
- ~~docs/source/legacy/manage.md~~
- ~~docs/source/legacy/mosaic.md~~
- ~~docs/source/legacy/theme.md~~
- docs/source/recipes/actions-reducers.md
- docs/source/recipes/environment-variables.md
- docs/source/recipes/fetch-data.md
- docs/source/releases.md
- docs/source/theming/integrate-third-party.md

I added these two in https://github.com/plone/volto/pull/3035 because they were moved around in another PR.

- docs/source/developer-guidelines/design-principles.md
- docs/source/developer-guidelines/style-guide.md

Please advise whether the remaining items should be included in the documentation, deleted, or kept around for some other reason.

See also https://github.com/plone/volto/issues/3034

**Comment by stevepiercy** [comment]
I also merged `plone6index` into `index`, and made necessary adjustments in 795a458ed760e5a5f1cb1fef0b7d9a9820d6615b

**Comment by stevepiercy** [comment]
docs/source/legacy/* was removed in https://github.com/plone/volto/pull/3076

**Comment by stevepiercy** [comment]
We're down to just 11 files to decide whether they should be included in the documentation, be deleted, or just kept around and not displayed.

```
/cheatsheet.md
/configuration/locking.md
/configuration/volto-config-js.md
/contributing/volips.md
/ie11compat.md
/introduction/introduction.md
/recipes/actions-reducers.md
/recipes/environment-variables.md
/recipes/fetch-data.md
/releases.md
/theming/integrate-third-party.md
```

Please advise. This issue is blocking #3001.

**Comment by sneridagh** [comment]
> My take on this:
> 
> * /cheatsheet.md - no?

+ 1 I always take a look at it... it's just handy to have it around.

> * /configuration/locking.md - yes

+1 

> * /configuration/volto-config-js.md - yes

+1

> * /contributing/volips.md no

Nope

> * /ie11compat.md - no? /cc @sneridagh @giuliaghisini

It's knowledge base... but certainly (hopefully) we are not going to need it anymore.

> * /introduction/introduction.md no

Nope

> * /recipes/actions-reducers.md no

Nope

> * /recipes/environment-variables.md it seems pretty recent. I think info inside it should be revisited and integrated

Yes

> * /recipes/fetch-data.md - no

Nope

> * /releases.md - It's important as a commitment declaration from the maintainers. It's important, but should be better integrated. It should be renamed to "Versioning policy"

+1 

> * /theming/integrate-third-party.md - no

Nope

**Comment by sneridagh** [comment]
https://github.com/plone/volto/pull/3084

**Comment by stevepiercy** [comment]
Closed by https://github.com/plone/volto/pull/3084
