### ISSUE TITLE
Pluggable to toolbar user menu

### ISSUE THREAD

**Issue by ksuess** [plone/volto#3040]
**Is your feature request related to a problem? Please describe.**
No problem. Feature request.

**Describe the solution you'd like**
Can add item to toolbar user menu.
![image](https://user-images.githubusercontent.com/1144737/152696940-0227eee2-1dee-4edf-82cc-3bcec75e5a6e.png)

**Describe alternatives you've considered**
skip feature.

**Additional context**
I do not understand the question.

**Comment by ksuess** [comment]
This [PR](https://github.com/plone/volto/pull/3039) was not well thought, I apologize for the noise.

I can now add a menu item to toolbar user menu, but…
This "add user menu item" should be possible to do in arbitrary add-on. So no shadowing of "View.jsx".

For a general use of "add user menu item", this topic needs more investigation.

**Comment by JeffersonBledsoe** [comment]
@ksuess I've found myself having a `Pluggables` component that is rendered via `appExtras` to avoid having to do any shadowing when wanting to configure a pluggable item and to keep everything organised:

```jsx
config.settings.appExtras = [
    ...config.settings.appExtras,
    {
      match: '',
      component: Pluggables,
    },
  ];
```

Does this fit the 'possible to do in arbitrary add-on' use-case?
