### ISSUE TITLE
Should we remove files that are common in Volto and Plone docs?

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#3043]
> @stevepiercy Should we remove files that are common in Volto and Plone docs? For instance, `cheatsheet.md` is already serving its purpose on Plone docs.

@nileshgulia1 I do not know. That should be discussed amongst the Volto team because y'all might want to keep it for the stand-alone build or move parts of it.

_Originally posted by @stevepiercy in https://github.com/plone/volto/issues/3032#issuecomment-1030914177_

**Comment by sneridagh** [comment]
If you work in the Volto docs, you won't have the full Plone docs at hand, thus, the cheatsheet will be in other repo, so my take (and personal wish) would be to keep the cheatsheet.md although, no linked.

Are there any other files that we should review?

**Comment by stevepiercy** [comment]
OK, we'll keep it. The necessary fix is to add an entry to the `toctree` directive for the files you want to keep, then add a parameter of `hidden`. That should remove the warning.

**Comment by stevepiercy** [comment]
Actually I was wrong. The correct MyST syntax is the following, placed after the `html_meta` tags:

````
```{eval-rst}
:orphan:
```
````

**Comment by stevepiercy** [comment]
This is handled in #3084. Closing.
