### ISSUE TITLE
Pastanaga Editor: No indication of links in the edit mode

### ISSUE THREAD

**Issue by tisto** [plone/volto#305]
1) Go to volto.kitconcept.com
2) Login admin:admin
3) Create a new page
4) Add some text tile
5) Select a term and add a link
-> The text will not show an underline to indicate it is a link
-> If you hit the save button the link will show up though
![volto-link-bug](https://user-images.githubusercontent.com/632105/48308191-e9cfb880-e5a1-11e8-842c-9fc685cd1f1b.png)

**Comment by tisto** [comment]
@nileshgulia1 that shouldn't be too hard to fix. Could you please have a look at it on Monday?

**Comment by rodfersou** [comment]
Well, actually it is a difficult one to deal, and maybe need to learn more about draft-js internals.

**Comment by jackahl** [comment]
I did something similar already for another project. I will take a look

**Comment by jackahl** [comment]
@tisto I cannot reproduce this issue anymore... already fixed?

**Comment by rodfersou** [comment]
@jackahl did you kit the save button?

**Comment by sneridagh** [comment]
Fixed long time ago.
