### ISSUE TITLE
GDPR and Cookie Expiration

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#3053]
Hi all, 
according to the EU law on the management of the GDPR privacy and cookies, technical cookies must have a maximum expiration of 6 months.

On Volto, we have some technical cookies with infinite or indefinite expiration, namely '**lang**', '**I18N_LANGUAGE**', '**redux_localstorage_simple_blocksClipboard**' cookies.

It is possible to change the expiration of these cookies to
6 months? 

What do you think? 

Are there any particular reasons why those cookies have an expiration date so far?

**Comment by tisto** [comment]
@giuliaghisini I agree. We should make this configurable if possible and maybe even set the default value to 6 months (though, we have to take into account that Europe is not the entire world :)).

When we created those cookies the GDPR rules weren't that clear if I recall correctly.

**Comment by pnicolli** [comment]
It would be interesting to have at least an idea of the other regulations and what they say. Of course having it configurable would be awesome, but it wouldn't solve the possible issue of having a website targeted at users from several countries. I could see at least one of our clients migrate to Volto in the next 2 years. But this is just me trying to look at my crystal ball, so who knows.

I heard, but I'm not entirely sure about this, that Japan has its own cookie/privacy law, for example.
@terapyon sorry for bringing you into this without notice, but perhaps you might have some info about this? Or maybe a pointer to where we could find these info? :D

**Comment by fredvd** [comment]
@giuliaghisini Do you have sources for this? 

> according to the EU law on the management of the GDPR privacy and cookies, technical cookies must have a maximum expiration of 6 months.

I haven heard about or learned of any generic 6 month rule for technical cookies and have been working on the technical and legal setup for an international company with many European and world wide sites, also in Italy. 

There are a number of lesser known 'extensions' of the gdpr in some EU countries or existing national pre gdpr legislation that hasn't been cleaned up yet after implementing the new privacy laws per country.  One I learned of recently is that in Belgium you're not allowed to collect anonymous statistics aldo without using any cookies: you always have to ask permission.

It's great to have the expiry dates configurable, but the 6 monthts is not a European guideline AFAIK (Italian maybe?) and if there is one I would really like to know about its source.

**Comment by giuliaghisini** [comment]
Hi Fred,
the person who deals with the legal and privacy aspects of our company, reported that data to us.
I know that in the last period the laws changes often, maybe something is changed from that time. Otherwise, the expiration time is configurable in volto now, and you can choose the time you want according to the laws of the country of your interest
