### ISSUE TITLE
Add "profile" term to Glossary

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#3071]
> @stevepiercy The add-ons install "profiles" are like the Plone Generic Setup ones. That's why we chose the naming like this.

Should we define the term "profile" in the Glossary? I think we should make it clear that a profile in Volto and a profile in `GenericSetup` are similar, but have some differences. I could create a new issue for that, so we can merge this one and move on.

_Originally posted by @stevepiercy in https://github.com/plone/volto/issues/3067#issuecomment-1041286094_

**Comment by tiberiuichim** [comment]
Maybe we should use "addon loader" and "additional addon loaders", to avoid the overlap with "profile"? @sneridagh

**Comment by sneridagh** [comment]
So, I'm ok with @tiberiuichim proposal and turns out... we already have one entry for this!

https://github.com/plone/documentation/blob/a18f60aa264b859c078eb3477ee9aa21849666ca/docs/glossary.md#L137

@stevepiercy it turns out you wrote it already, using the "add-on loader" naming. So I'm ok with this. Although I'll improve it a bit.

**Comment by sneridagh** [comment]
https://github.com/plone/documentation/pull/1185

**Comment by stevepiercy** [comment]
> So, I'm ok with @tiberiuichim proposal and turns out... we already have one entry for this!
> 
> https://github.com/plone/documentation/blob/a18f60aa264b859c078eb3477ee9aa21849666ca/docs/glossary.md#L137
> 
> @stevepiercy it turns out you wrote it already, using the "add-on loader" naming. So I'm ok with this. Although I'll improve it a bit.

Heh, it goes deeper. The documentation glossary was a merger of all the various glossaries and that from training. The one from training was a conversion from rst to md in the training repo, and before that it was a consolidation of all the glossaries: https://github.com/plone/training/blame/e55aa6b51025270db54a34781dc93e4b3abc4142/voltoaddons/about/glossary.rst#L14-L15

**Comment by stevepiercy** [comment]
Closed by https://github.com/plone/documentation/pull/1185
