### ISSUE TITLE
Add/update language in code blocks

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#3090]
There are several code blocks that lack a language for its lexer, and Pygments is not always smart enough to detect the intended language. We should state the language like so:

````
```language
sample code block in language.
```
````

See also the guidance for [choosing a lexer](https://6.dev-docs.plone.org/contributing/authors.html#choosing-a-lexer).

**Comment by ktsrivastava29** [comment]
@stevepiercy I think I can work on this; I'm thinking about going through each document and looking for places where the language isn't mentioned; is this a reasonable strategy?

**Comment by stevepiercy** [comment]
I would suggest using a regular expression across all files to find three backticks followed by a new line. Manually doing this would be too much work.
