### ISSUE TITLE
EmailWidget doesn't pass placeholder prop

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#3120]
Unlike the [TextWidget](https://github.com/plone/volto/blob/ac0602fdb3fb2cfd0c698c58a99760e74a75acf4/src/components/manage/Widgets/TextWidget.jsx#L110) the [EmailWidget doesn't pass down placeholder prop](https://github.com/plone/volto/blob/ac0602fdb3fb2cfd0c698c58a99760e74a75acf4/src/components/manage/Widgets/EmailWidget.jsx#L28-L42). This should probably be checked for all the other widgets as well.

**Comment by tiberiuichim** [comment]
Also relevant, the HTML email input element allows some other DOM props, such as pattern. None of them are passed to the input. In theory we'd want to pass down all additional props from the field definition (or maybe separate them in an inputProps object?).

**Comment by TC5022** [comment]
@avoinea are you working on this issue?
