### ISSUE TITLE
Clipped dropdown menu in Contents view

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#3124]
![image](https://user-images.githubusercontent.com/141568/157092111-f8df8b82-06ee-47b3-a803-89bd36097500.png)

**Comment by nileshgulia1** [comment]
Recently @ichim-david looked into these kinds of changes: https://github.com/plone/volto/pull/2819

**Comment by tiberiuichim** [comment]
In this case it wasn't about small window, rather just limited number of items in the folder (just 2).

**Comment by ichim-david** [comment]
Fixed by https://github.com/plone/volto/pull/3158 merging in master
