### ISSUE TITLE
Redirect https://docs.voltocms.com/ to new address

### ISSUE THREAD

**Issue by ksuess** [plone/volto#3151]
A search for "Volto documentation" still presents https://docs.voltocms.com instead of the new address.
![Volto_documentation_-_Google_Suche](https://user-images.githubusercontent.com/1144737/158337478-819ab35e-5d3d-46b2-b92d-86559c139ec1.png)
/cc @stevepiercy @rioksane

**Comment by stevepiercy** [comment]
I think as soon as redirects are set up, Google will reindex, then promote the new site.

**Comment by sneridagh** [comment]
It was done some days ago already!

**Comment by stevepiercy** [comment]
I think @ksuess meant that a search still brings up the old URL.

https://duckduckgo.com/?q=volto+documentation&atb=v318-1&ia=web

![Screen Shot 2022-03-26 at 10 38 50 AM](https://user-images.githubusercontent.com/102112/160256293-43fb0a7c-139f-4aaf-9751-4de296cd75ab.png)

Is there a separate Google Analytics or Webmaster Tools property for the old site?

**Comment by ksuess** [comment]
OK, no more https://docs.voltocms.com/ in Google results.
