### ISSUE TITLE
make clean does not work on OSX

### ISSUE THREAD

**Issue by tisto** [plone/volto#3193]
**Describe the bug**

- checkout volto repo
- run "make clean" (on OS X)

```
make clean
bash: realpath: command not found
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
bash: realpath: command not found
bash: -c: line 1: syntax error: unexpected end of file
make[1]: *** [clean-tmp-worktrees] Error 2
make: *** [clean] Error 2
```

**Comment by stevepiercy** [comment]
Would you please attempt to isolate where it fails by inserting `@echo unique error message here` at each of the steps in a make target?

Do other make targets return the same error message, e.g., `make help`?
