### ISSUE TITLE
Listing variation templates should be passed block data

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#3222]
Right now variations are not passed the whole block data, which is a shame.

**Comment by davisagli** [comment]
Is this what was added in #3518?

**Comment by tiberiuichim** [comment]
I think so, yes

**Comment by tiberiuichim** [comment]
Well, it's not generalized, only from the Search block. The Listing block should do it as well, I think

**Comment by davisagli** [comment]
Looks like it is already there for the listing block.
