### ISSUE TITLE
Missing default view of custom types with custom fields/behaviors.

### ISSUE THREAD

**Issue by jensens** [plone/volto#3259]
If one adds a custom type with custom fields or behaviors, those fields are not shown on the view in Volto.
In Plone Classic UI the fields is shown like so:

![Screenshot from 2022-04-22 11-46-54](https://user-images.githubusercontent.com/157140/164681939-2f92e113-2ae4-447b-a12e-c3df7b297458.png)

In Volto the output is missing:

![Screenshot from 2022-04-22 11-47-02](https://user-images.githubusercontent.com/157140/164681998-76b7631a-da4a-45f2-9833-ef579ad4970b.png)

**Comment by erral** [comment]
Something like Dexterity default view is missing:

https://github.com/plone/plone.dexterity/blob/master/plone/dexterity/browser/item.pt
https://github.com/plone/plone.dexterity/blob/master/plone/dexterity/browser/view.py

**Comment by ionlizarazu** [comment]
We need something like this in core:

https://github.com/eea/volto-widgets-view

**Comment by erral** [comment]
See https://github.com/plone/plone.restapi/issues/1409

**Comment by pbauer** [comment]
Fixed with https://github.com/plone/volto/pull/3330
