### ISSUE TITLE
Style Wrapper in Volto Core (e.g. for introducing background colors for blocks)

### ISSUE THREAD

**Issue by tisto** [plone/volto#3264]
**Is your feature request related to a problem? Please describe.**

At kitconcept we introduced the concept of background colors for blocks. Usually all our blocks support the option to choose from a color palette of different background colors. Here is a simple example of a text block:

![Block-Text-mit-Hintergrund](https://user-images.githubusercontent.com/632105/164692685-1fa2c770-6716-4ce5-bfbc-fade9f746548.png)

**Describe the solution you'd like**

We introduced a style wrapper that allows us to apply different styles to blocks in a re-usable way.

We believe that this is a feature that everyone else will face sooner or later in Volto and it should become part of Volto core.

**Comment by nileshgulia1** [comment]
At EEA we use [volto-block-style](https://github.com/eea/volto-block-style) as a wrapper around volto blocks. In addition to bg-colors it also supports font-size and other most useful CSS styles.

**Comment by sneridagh** [comment]
@nileshgulia1 the idea is to grab all the useful things in yours and ours and make the uber style wrapper in core.

Extensible, pluggable, etc
