### ISSUE TITLE
Too many installation docs (and other suggested improvements)

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#3289]
We have too many Volto installation docs.

- ~https://github.com/plone/volto#quick-start~ DELETED.
- ~https://github.com/plone/volto#volto-development~ DELETED.
- ~[`docs/source/getting-started/install.md`](https://6.docs.plone.org/volto/getting-started/install.html)~ DELETED.
- [Develop Volto core](https://6.docs.plone.org/volto/contributing/developing-core.html)
- ~[Install Volto for development](https://6.docs.plone.org/volto/contributing/index.html#install-volto-for-development) See https://github.com/plone/volto/issues/5556~ RESOLVED
- [Creating a new Volto project](https://6.docs.plone.org/volto/recipes/creating-project.html)
- https://github.com/plone/volto/issues/4079
- [Plone 6 Install](https://6.docs.plone.org/install/index.html)
- Trainings:
  - ~https://training.plone.org/volto/bootstrap.html~ ARCHIVED to https://2022.training.plone.org/volto/bootstrap.html
  - https://training.plone.org/voltohandson/quickstart.html
  - https://training.plone.org/voltoaddons/01-addon-basics.html#bootstrap-a-new-volto-project
  - https://training.plone.org/mastering-plone/installation.html#installing-plone-frontend
  - ~https://training.plone.org/plone_training_config/instructions.html#installing-the-frontend~ DELETED
- Others?

I would strongly advocate for one, and only one, way to install Volto for development in Plone 6.

This would make it easier to maintain installation documentation and reduce frustration of developers.

As a couple of side notes:

1. I would require, not make it optional, to use `nvm`. Alternatively, we should make a statement such as, "The Volto development team uses `nvm` for installing and managing versions of Node.js. We do not support any other node version manager or the lack of one. If you do not use `nvm`, then we assume you know what you are doing and can resolve issues on your own."
2. Provide clear paths to install Volto using either Docker or a manual installation. The current docs are not structured clearly because all headings are at the same level and not in order. The proposed version aims to provide that structure and order.
3. State "For simplicity in documentation, we use `bash` for a shell. Adjust commands according to your preferred shell flavor."
4. Specify what characters are valid in a project name for `npm init yo @plone/volto`. Letters, number, dashes, underscores, other characters?
5. Use "Install", not "Getting Started", buried under "Introduction". Elevate it.
6. Separate "Installation" from "Development" documentation. Volto (and any other core Plone package) should still have its specific documentation for development purposes, such as for running tests.

**Comment by tiberiuichim** [comment]
Thank you @stevepiercy for working on this (and all your other work on documentation)!

**Comment by ksuess** [comment]
I updated Mastering Plone Development Training two weeks before by referencing Plone 6 documentation instructions and removing any self cooked instructions. So this is at least for the frontend part OK now.
Glad that you picked up the idea to clean up the creative variety of installation instructions!

**Comment by stevepiercy** [comment]
Thanks @ksuess. I've added https://training.plone.org/5/mastering-plone/installation.html#installing-plone-frontend to the list above.

**Comment by ksuess** [comment]
> > BTW this '/5/' in the uri is confusing…
> 
> See [plone/training#581](https://github.com/plone/training/issues/581)

Oh my, another task…

**Comment by stevepiercy** [comment]
I've created a project to track all Install-related issues, [Install Docs](https://github.com/orgs/plone/projects/16).

**Comment by rileydog** [comment]
@stevepiercy  Hi, when i click on Install Docs, it goes to https://github.com/orgs/plone/projects/16  and gives a 404 error

**Comment by stevepiercy** [comment]
@rileydog oops, I opened it up to @plone/developers. Are you a member of that team?

**Comment by rileydog** [comment]
@stevepiercy   -  no I'm not part of the team

**Comment by stevepiercy** [comment]
@rileydog have you signed the Plone [Contributor Agreement](https://plone.org/foundation/contributors-agreement)?

**Comment by rileydog** [comment]
@stevepiercy  I'm not part of the team so i didn't sign the agreement.  Im not a contributor, i just found the link didn't work for me.

**Comment by stevepiercy** [comment]
@rileydog I am not an organization Owner, so I cannot make it public. I am OK with making it public, but an organization Owner would need to change its visibility, and I have no clue who that might be. @plone/plone-foundation-board any of you know? IMO all GitHub projects under the Organization should be publicly visible for transparency.

The best I can do is make the project available to members of the organization, which is @plone/developers, and have you sign the CA to become a member of that group. And of course ask someone else to change the visibility, which I have done here.

Finally, the project is merely a collection of issues across several repos in their issue trackers, so you can search for them that way.

**Comment by aclark4life** [comment]
I'm an organization owner … anyone know why it's not public, and/or if it's OK to make public?

**Comment by ericof** [comment]
As documentation and volto repositories require the contributor agreement
before any contribution is made, I would keep the project restricted to
those who signed the agreement.

**Comment by stevepiercy** [comment]
Signing the CA is still enforced when a contributor submits a PR to any Plone repo, but that has nothing to do with being able to read an issue. In fact, by allowing issues to be readable by the public is how many people become contributors, including through GSoC.

[Release Plone 6 docs](https://github.com/orgs/plone/projects/12) is already public. This [GitHub project](https://github.com/orgs/plone/projects/16) is a subset of that and is merely a collection of issues that are publicly readable in their respective repos. What needs to be kept private that is already public in separate repos?

**Comment by polyester** [comment]
There is a difference between the whole organization (which has, and will always have, private repos for things like the admin&infra team and security team) and "projects", which can have per-project settings. As long as a project (which is just a collection of issues) has issues from public repos, the project visibility can be set to "public" as well. [This does not change who can interact with it.](https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/managing-visibility-of-your-projects)

I've set the visibility of the "[Install docs](https://github.com/orgs/plone/projects/16)" and "[Release Plone 6 docs](https://github.com/orgs/plone/projects/12)" projects to "public"

**Comment by stevepiercy** [comment]
@lorstenoplo I moved your comment into a NEW issue, instead of piling on to this one.

**Comment by stevepiercy** [comment]
I'm going to close this issue, because we have resolved most of the issues and consolidated documentation into include files. Specific issues remain, but they can be addressed separately.
