### ISSUE TITLE
Toobar bottom icons are visible when toolbar is collapsed

### ISSUE THREAD

**Issue by ichim-david** [plone/volto#3293]
**Describe the bug**
The toolbar bottom icons are visible when the toolbar is collapsed.
Also the sidebar **full-size-sidenav-btn** is visible when the sidebar is collapsed

**To Reproduce**

1. Go to ['...'](https://volto.kitconcept.com/edit)
2. Click on the toolbar and the sidebar collapse buttons
5. See toolbar bottom section still visible as well as the full-size-sidenav-btn

**Expected behavior**
For those sections to be hidden

**Screenshots**
![undo-redo-buttons-with-sidebar-closed](https://user-images.githubusercontent.com/152852/166115673-5f14fb04-887f-4e9e-9702-17ce9d306377.png)

**Software (please complete the following information):**

- Volto Version [e.g. 8.5.0]
- Plone Version [e.g. 5.2.2]
- Plone REST API Version [e.g. 7.0.1]

**Additional context**

**Comment by ichim-david** [comment]
Fixed by https://github.com/plone/volto/pull/3292

**Comment by harshit-dugar** [comment]
Can I work on It
@ichim-david

**Comment by ichim-david** [comment]
@harshit-dugar  I already have a pull request opened for this issue, no further work is needed
https://github.com/plone/volto/pull/3292
