### ISSUE TITLE
Volto 15.4.x no longer supports Language Variants on the backend (en_US, nl_BE, etc.)

### ISSUE THREAD

**Issue by fredvd** [plone/volto#3297]
When you create a new API backend for a Volto site in Plone 6 Alpha 4 the  Language dropdown contains both Languages (English, Dutch) and Language Variants, like English (USA), Dutch (Belgium).  The former have codes like EN and NL, the latter are encoded with en_US and nl_BE . 

The Default selected language depends on your locale and which browser you use. Some uses with their local and browser will have a language variant selected by default. This explains why not everybody might see this issue. 

<img width="593" alt="Screenshot 2022-05-02 at 16 06 20" src="https://user-images.githubusercontent.com/394784/166247639-dbe5da99-0667-4977-8e68-667b20ee05f1.png">

Volto 15.4.1 will throw an error if you created the backedn with any Language Variant:

```
"Unhandled Rejection (Error): Cannot find module './en_US.json'
./locales lazy recursive ^./..json$/webpackAsyncContext/<
/home/Code/Plone/Plone-6/frontend/locales lazy ^/./.json$ namespace object:50"
```

This appears to be a regression, as the documentation explicitly has a language variant as an example and Plone 5.2 also has language variants enabled and listed in the Site language dropdown when you create a site.

**Comment by arky** [comment]
I have faced this issue with Plone 6a2 Backend.

**Comment by JeffersonBledsoe** [comment]
Just came to say I faced this upgrading a local development site from Volto 14.0 to 15.5. 6a2/3/4 backends all worked fine with Volto 14.

**Comment by fredvd** [comment]
Thanks for the input @JeffersonBledsoe  ! Then devs can look at the changes between 14.0 and 15.4  in Volto 

IIRC 15.0 to 15.4 were very quick iterations.

**Comment by fredvd** [comment]
@sneridagh @davisagli  I test this manully with some language variants that should not fall back to english (de-ch) for example, because the tests didn't catch this problem 2 months ago, so the tests now passing doesn't say that much.  it works correctly now. 

follow up issues:
* see if we can add a test for this regression.  Will add a new issue for that. 
* The vocabularies used in the language form field to create Plone site and the language control panel in Plone seem to be different.  The creation form has nice indented values for the variants, the control panels just lists the Main language names in full (English, Deutsch, Nederlands) and all variants as de-ch, nl-be etc.  Will add another issue as well. 

<img width="441" alt="language-variants-create-plonesite" src="https://user-images.githubusercontent.com/394784/167140685-0385a913-0c65-418a-949b-f254fa709ce5.png">
