### ISSUE TITLE
Criteria that no longer exist in a QueryWidget cause a block existing error

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#3298]
If in a listing block there's a criterion saved that somehow no longer exists, it breaks down here: https://github.com/plone/volto/blob/master/src/components/manage/Widgets/QueryWidget.jsx#L336
 
And it makes it impossible to delete / modify that block.

**Comment by tiberiuichim** [comment]
https://github.com/plone/volto/blob/18fcbfd9660c0bd9ec5e80b2ca562a04526c6f4d/src/components/manage/Widgets/QueryWidget.jsx#L336
