### ISSUE TITLE
FileView shows a link to download the file instead of downloading the file like in Classic UI

### ISSUE THREAD

**Issue by erral** [plone/volto#3306]
**Describe the bug**
Add a File in Classic UI, say /Plone/file1.pdf both logged-in and anonymous users get the file download (or rendered in the browser if it's a PDF)

In Volto we get the FileView with a link to download the file. To get this functionality in ClassicUI one needs to add /view in the URL, ex: /Plone/file1.pdf/view

Should this functionality be the same in both UIs?

**Comment by davisagli** [comment]
Closing this because #6060 has more discussion of the nuances of this question.
