### ISSUE TITLE
Unable to build the arm64 flavour of the plone/plone-frontend image because of Sentry

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#3346]
While building the arm64 version of the plone/plone-frontend:

```
#11 153.9 [5/5] Building fresh packages...
#11 159.5 error /build/node_modules/@sentry/cli: Command failed.
#11 159.5 Exit code: 1
#11 159.5 Command: node scripts/install.js
#11 159.5 Arguments:
#11 159.5 Directory: /build/node_modules/@sentry/cli
#11 159.5 Output:
#11 159.5 Error: Unable to download sentry-cli binary from https://downloads.sentry-cdn.com/sentry-cli/1.59.0/sentry-cli-Linux-arm64.
#11 159.5 Server returned 403: Forbidden.
#11 159.5 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I know it's a Sentry servers issue, but we can't rely that a third party has their thing put together always, and it's not the first time it happens.

@avoinea @tiberiuichim @pnicolli @cekk I know that you are using that extensively, but I'd like to keep it out of core... having it in the pre-add-on era was ok. Now I guess it's no sense anymore. Do you think there's something that cannot be done in a Sentry add-on? Also, if necessary we could keep a minimum integration code/entrypoints in place, but keep the bulk out. What do you think? v16 anyone? :)

**Comment by pnicolli** [comment]
I haven't checked if moving Se try to an add-on is easily doable, but I would be very happy with this change if possible.

**Comment by fredvd** [comment]
I remember having this issue as well a few months ago and the solution was to pin to a higher version of sentry-cli where the tool that runs to fetch something above also fetches the arm64 version.

The problem however was that in the package dependency some of the sentry packages are pulled in multiple times with different versioning requirements from their parents.  So I had to add an version 'override' to the main package.json of the project.

**Comment by sneridagh** [comment]
@fredvd thanks, it seems it did the trick!
