### ISSUE TITLE
razzle.config.js in project template should be easier to extend

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#3424]
Right now, if I want to tweak configuration in the generated razzle.config.js, I have to rewrite it, more or less, and this operation is not exactly trivial to newbies. 

I propose that we ship with a razzle.config.js that already has its own local modify function, so that it's easier to instruct beginners on how to extend it with custom code.

**Comment by tiberiuichim** [comment]
Example razzle.config in a project:

```
const path = require('path');
const makeLoaderFinder = require('razzle-dev-utils/makeLoaderFinder');

const babelLoaderFinder = makeLoaderFinder('babel-loader');

const jsConfig = require('./jsconfig').compilerOptions;

const pathsConfig = jsConfig.paths;
let voltoPath = './node_modules/@plone/volto';
Object.keys(pathsConfig).forEach((pkg) => {
  if (pkg === '@plone/volto') {
    voltoPath = `./${jsConfig.baseUrl}/${pathsConfig[pkg][0]}`;
  }
});

const { modifyWebpackConfig, plugins } = require(`${voltoPath}/razzle.config`);

const customModifyWebpackConfig = ({ env, webpackConfig, webpackObject }) => {
  const config = modifyWebpackConfig({
    env,
    webpackConfig,
    webpackObject,
  });
  const babelLoader = config.module.rules.find(babelLoaderFinder);
  const { include } = babelLoader;
  const corePath = path.join(
    path.dirname(require.resolve('@react-leaflet/core')),
    '..',
  );
  const esmPath = path.join(
    path.dirname(require.resolve('react-leaflet')),
    '..',
  );

  include.push(corePath);
  include.push(esmPath);
  return config;
};

module.exports = { modifyWebpackConfig: customModifyWebpackConfig, plugins };
```

**Comment by akshatgarg12** [comment]
can i work on this?

**Comment by tiberiuichim** [comment]
@akshatgarg12 Yes, please do. The idea is to change this file: https://github.com/plone/volto/blob/master/packages/generator-volto/generators/app/templates/razzle.config.js to have a really simple `customModifyWebpackConfig` (which doesn't have to do anything other then returning the unchanged config), so that, for future generated projects, its easy and obvious what they have to do. Make sure to test this file by copying and overwriting your razzle.config.js file in a Volto project you generate on your machine.
