### ISSUE TITLE
A11y : Maps Block

### ISSUE THREAD

**Issue by iRohitSingh** [plone/volto#3467]
**Describe the bug**
Frames should have a unique title attribute

**To Reproduce**

1. create "page "
2. Add two or more maps Block 
3. run "axeDevTool"
4. See error "Frames should have a unique title attribute"

**Screenshots**
![Screenshot from 2022-07-08 18-59-47](https://user-images.githubusercontent.com/61353484/178001718-efe824c9-ec9c-4b05-b641-839dce6d228d.png)

**Comment by iRohitSingh** [comment]
@tisto I can fix it by putting the data.url in the title field but it doesn't make sense for the user. any feedback how i can fix it.

I don't know how to fix it.

data.url https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d224345.83923100954!2d77.06889716447195!3d28.527582006607656!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390cfd5b347eb62d%3A0x52c2b7494e204dce!2sNew%20Delhi%2C%20Delhi!5e0!3m2!1sen!2sin!4v1657288342054!5m2!1sen!2sin

**Comment by jackahl** [comment]
https://dequeuniversity.com/rules/axe/3.5/frame-title-unique

**Comment by tisto** [comment]
Let's add a new field "alt-tag" to the maps block that can be used by the React component to generate a unique iframe title.
