### ISSUE TITLE
Pagination state to be available through redux store

### ISSUE THREAD

**Issue by JeffersonBledsoe** [plone/volto#3483]
**Is your feature request related to a problem? Please describe.**
I'm currently trying to style the Search block and I need to be able to list the current range of (e.g. `Showing results 25-50 of 73`). In order to calculate this when using pagination, I need access to the current page, but this is all stored as local state within the listing block:

https://github.com/plone/volto/blob/28db44608718fbb579a2baccd2628e9368066e02/src/components/manage/Blocks/Listing/withQuerystringResults.jsx#L40
https://github.com/plone/volto/blob/master/src/helpers/Utils/usePagination.js

It would be nice if the currently selected page were available through redux, so this calculation could be done. There may be other places this data could be useful too?
.
**Describe the solution you'd like**
When the pagination component causes a page change, for the current page to be available in the global redux store

**Comment by tiberiuichim** [comment]
@JeffersonBledsoe I presume that you're adding this as a new component? Or shadowing one of the existing Search block sub-components? My proposal would be to pass the pagination numbers to the subcomponent, from the main block. Maybe a PR is needed for that.

**Comment by JeffersonBledsoe** [comment]
> @JeffersonBledsoe I presume that you're adding this as a new component? Or shadowing one of the existing Search block sub-components? My proposal would be to pass the pagination numbers to the subcomponent, from the main block. Maybe a PR is needed for that. 

@tiberiuichim The way the Search block currently works is that it renders a listing body as a child, and it is the listing body child that has the current page as local state (in the pagination component).

Any reason this state couldn't be made available to parents, rather than passing it down (e.g. via URL querystring or redux)? I agree that moving the pagination state upwards in the tree is probably better for this specific circumstance, just trying to see if it can be a more general solution :)

**Comment by tiberiuichim** [comment]
@JeffersonBledsoe There's no reason not to move that state to the redux, my only concern is that the coresponding reducer would be complex, as it would have to namespace a specific ListingBody component.

But now, looking at the code, I think this information is already somewhat available. Looking at a querystring search endpoint, result, I see:

```
batching: {@id: "http://localhost:3000/test-search/@querystring-search",…}
@id: "http://localhost:3000/test-search/@querystring-search"
first: "http://localhost:3000/test-search/@querystring-search?b_start=0"
last: "http://localhost:3000/test-search/@querystring-search?b_start=250"
next: "http://localhost:3000/test-search/@querystring-search?b_start=50"
prev: "http://localhost:3000/test-search/@querystring-search?b_start=0"
```

So you could extract that information by doing something like https://github.com/plone/volto/blob/496d6ff101aab443fe593c602c974c58ddb7b47e/src/components/manage/Blocks/Search/hocs/withSearch.jsx#L315-L319

**Comment by JeffersonBledsoe** [comment]
This worked well, thanks! @tiberiuichim Think it's worth making a utility function for getting this information from the selector?

**Comment by tiberiuichim** [comment]
@JeffersonBledsoe No, I think special API for this is not needed.
