### ISSUE TITLE
Google fonts are not compliant with EU privacy

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#3490]
https://github.com/Semantic-Org/Semantic-UI/issues/7075

as described here Semanti-UI is not compliant with EU privacy because downloads fonts from google sending it some informations..

We are looking for a solution to not download Poppins font from google changing Semantic-UI Volto's config...

**Comment by lubber-de** [comment]
The official community fork https://fomantic-ui.com prepared that for upcoming 2.9.0 by
https://github.com/fomantic/Fomantic-UI/pull/2359

**Comment by davisagli** [comment]
Fixed by #3492 (volto 16), #3493 and #3510 (volto 15)
