### ISSUE TITLE
inline StyleMenu slate Editor

### ISSUE THREAD

**Issue by ksuess** [plone/volto#3494]
Sorry for interrupting. I think the inline StyleMenu is a funky thing that got lost and would be welcomed back not only by me. Any opinions?

_Originally posted by @ksuess in https://github.com/plone/volto/pull/3313#pullrequestreview-1045046489_

**Comment by nileshgulia1** [comment]
@ksuess I have a internal ticket for this subtask to include `slate-inline` menu in `volto` core. Did you already created an add-on? Are you working on this?

**Comment by ksuess** [comment]
need some more minutes. i'll come back to this soon with my stuff.

**Comment by nileshgulia1** [comment]
I will push my findings in a branch, will let you know.

**Comment by ksuess** [comment]
What I did is adding a custom editor button in an addon with some common tweaks. It is not generative but fix with two styles: "warning" with text color orange and "errror" with text color red.
![Nachricht_bearbeiten](https://user-images.githubusercontent.com/1144737/188071696-4ce6aa7f-b626-40d9-99da-050eca31bbcb.png)
![Nachricht_bearbeiten_and_Site_Setup](https://user-images.githubusercontent.com/1144737/188071867-8c7441c5-4d76-47a5-8c4c-66c09aba65f5.png)
With a **configurable** choice this would maybe fit in your needs:

```
export const WarningEditorSchema = {
  title: 'Marker',
  fieldsets: [
    {
      id: 'default',
      title: 'Default',
      fields: ['warning_type'],
    },
  ],
  properties: {
    warning_type: {
      title: 'Text',
      type: 'string',
      factory: 'Choice',
      choices: [
        ['warning', 'Warning'],
        ['error', 'Error'],
      ],
      default: 'warning',
    },
  },
  required: [],
};
```

This is the code, applied with `config = installWarningPlugin(config);`:

[WarningPlugin.zip](https://github.com/plone/volto/files/9475473/WarningPlugin.zip)

**Comment by ksuess** [comment]
Thank you @nileshgulia1 for resettling the style menu! I missed it, it's great.

![grafik](https://user-images.githubusercontent.com/1144737/201667869-c9f3b844-27b8-4ec3-ac21-39f957d2e05b.png)
