### ISSUE TITLE
Slate Editor: Blockquote vs Callout

### ISSUE THREAD

**Issue by tisto** [plone/volto#3498]
**Describe the bug**

The Slate editor in its default configuration currently has a quote and a blockquote option that render the exact same way. This is confusing for the users and we are wasting space in the edit view (which is especially valuable when working with small grid elements).

**To Reproduce**

1. As admin
2. Go to https://6.demo.plone.org/edit
3. Add a quote block
4. Add a blockquote block
5. Save

**Expected behavior**

Remove quote option. The difference in the HTML elements is that blockquote is a DIV element and quote is an inline element. They both render as block elements. Therefore we should remove the quote option IMHO.

**Screenshots**

<img width="1521" alt="Screenshot 2022-07-22 at 08 50 40" src="https://user-images.githubusercontent.com/632105/180381198-b46b08e0-3958-4a60-b252-73b7151e8fd7.png">

**Software (please complete the following information):**

- OS: OS X
- Browser: Chrome
- Volto Version 16.0.0-alpha.13

**Comment by stevepiercy** [comment]
I think you mean remove the "callout" option, which is represented by the megaphone icon.

![Screen Shot 2022-07-22 at 12 12 30 AM](https://user-images.githubusercontent.com/102112/180384374-e853da74-8886-49bb-b832-84dfa87d7dce.png)

![Screen Shot 2022-07-22 at 12 13 57 AM](https://user-images.githubusercontent.com/102112/180384524-71e18100-db12-4bf5-8875-ed380923d46e.png)

If so, I agree.

**Comment by tisto** [comment]
@stevepiercy yes. indeed. thanks for the clarification!

**Comment by davisagli** [comment]
Fixed in https://github.com/plone/volto/pull/3506
