### ISSUE TITLE
Slate Editor: Two table options

### ISSUE THREAD

**Issue by tisto** [plone/volto#3499]
**Describe the bug**

**To Reproduce**

1. As admin
2. Go to https://6.demo.plone.org/edit
3. Create some text in a text block and select it
4. A table option shows up
5. Choose a number of rows/columns

-> I had to try five times before something happened after choosing rows/columns
-> On the sixth time a table block showed up below the text block I was editing

**Expected behavior**

I am not sure what version I am looking at and what our intended behavior is here. My thoughts:

- we should have one way of handling tables in Plone (by default)
- if the one way is the table block, we should disable the Slate inline table feature (and make it easily addable if integrators need it)

**Screenshots**

<img width="1423" alt="Screenshot 2022-07-22 at 08 54 20" src="https://user-images.githubusercontent.com/632105/180381560-c9e8ac5f-e1ce-4e81-adc9-b4857a5e7764.png">

**Software (please complete the following information):**

- OS: OS X
- Browser: Chrome
- Volto Version 16.0.0-alpha.13

**Comment by tiberiuichim** [comment]
We should disable the Table button from the Slate toolbar.

**Comment by sneridagh** [comment]
https://6.demo.plone.org/ is Plone 6 beta 1 now and latest Volto, it does not show now.
