### ISSUE TITLE
Slate Heading buttons toolbar items should be exclusive

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#3509]
**Describe the bug**
Choosing a heading and a bold/italic is possible, and both styles are added.

**Expected behavior**
Selecting a heading should be exclusive.

**Comment by davisagli** [comment]
This is probably good to enforce most of the time, but there may be edge cases. For example in English italics are often used when writing the title of a book, so if you're writing a heading that includes a book title you would want both.

**Comment by davisagli** [comment]
> This is probably good to enforce most of the time, but there may be edge cases. For example in English italics are often used when writing the title of a book, so if you're writing a heading that includes a book title you would want both.

Ah, I see you made it configurable using `allowedHeadlineElements`. Thanks!
