### ISSUE TITLE
Change the "no results found" message of ListingBlock to something customizable

### ISSUE THREAD

**Issue by erral** [plone/volto#3552]
A client has asked us to change the "no results found" message that the ListingBlock shows when there is no results with something else like "No events found" or "No tenders found" or "There are no documents in this listing".

I think that this should be something customizable, but how?

Right now the No results message is rendered before entering the variations *dance* so there is no way to do it in a variation. But in any case does it make sense to add it in a variation? You may use this variation for Events and News but want to have different "No results found" message on each one.

On the other hand, adding yet another schema field to the ListingBlock just to add the "no results found" seems an overkill.

Opinions?

**Comment by ionlizarazu** [comment]
I would add a noResultsComponent key to the listing block configuration with the default message. This way we can modify it with a React component. I would also give the option to add a noResultsTemplate key to each variation so we can modify the message separately.

Somehow, the inital config can be something like this:

```
listing: {
    id: 'listing',
    title: 'Listing',
    icon: listBulletSVG,
    group: 'common',
    view: ViewListingBlock,
    edit: EditListingBlock,
    schema: BlockSettingsSchema,
    blockSchema: ListingBlockSchema,
    restricted: false,
    mostUsed: true,
    sidebarTab: 1,
    showLinkMore: false,
    security: {
      addPermission: [],
      view: [],
    },
    variations: [
      {
        id: 'default',
        isDefault: true,
        title: 'Default',
        template: DefaultListingBlockTemplate,
      },
      {
        id: 'imageGallery',
        title: 'Image gallery',
        template: ImageGalleryListingBlockTemplate,
        noResultsTemplate: MyImageNoResultsComponent,
      },
      {
        id: 'summary',
        title: 'Summary',
        template: SummaryListingBlockTemplate,
      },
    ],
    noResultsComponent: DefaultNoResultsComponent,
    getAsyncData: getListingBlockAsyncData,
  },
```

**Comment by tiberiuichim** [comment]
I think there should be two levels of `noResultsComponent`: a default one and one optional for each variation.

I like the idea, I wonder if we should connect it to the components registry.
