### ISSUE TITLE
User controlpanel: search by full name

### ISSUE THREAD

**Issue by ksuess** [plone/volto#3559]
by now search queries only username / id / email

**Comment by ksuess** [comment]
Will do PR with
https://github.com/plone/volto/blob/63d4d7161422d8b5b751cc2cb42827ad31c2593f/src/components/manage/Controlpanels/Users/UsersControlpanel.jsx#L138-L140

query -> search

after https://github.com/plone/volto/pull/3534 is merged.

**Comment by MdSahil-oss** [comment]
@ksuess As I observed, sorting is possible in User Controlpanel by only UserId and not possible by Email & UserName.

So, for an enhancement what would be better to use in User Controlpanel direct multiple input fields or a select input field with multiple options like UserName, UserId and Email to sort users in user Controlpanel.

**Comment by ksuess** [comment]
@MdSahil-oss It's great that you want to care for this! 
My personal opinion is that one search field is enough. But of course distinguished sort options on either id or full name would be a comfortable enhancement. Because even the switch from "query for id" to "search for id, email and full name" would be an enhancement, I vote for one single search field. But let's see what others say.

Before you start working on this, please talk to @nileshgulia1 . He is working already on the user control panel. And some coordination would spare you and him some rebasing in between.

**Comment by ksuess** [comment]
Done by #3962
