### ISSUE TITLE
Switch to use Plone 6 in tests as default in acceptance testing, 5.x with essential testing

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#3571]
Also, update/modernize the convenience buildout included in Volto repo.

**Comment by sneridagh** [comment]
@davisagli uh, I was under the assumption that I set up "essential" testing on 6 (a subset of the full suite, to improve a bit CI performance) but it seems that I refrained to do so at the last moment 😅.

Anyways, we could introduce it, so we start only to test a basic subset on Plone 5 from that moment on.

**Comment by davisagli** [comment]
This was done in #3700
