### ISSUE TITLE
Rich text editor: no tool (no function) to remove formatting for selected text

### ISSUE THREAD

**Issue by iFlameing** [plone/volto#3572]
**Describe the bug**
There is no possibility in rich text editor to remove formatting, see screenshot below

Screenshot

![image_2022-08-02_1651_no_remove_format_tool](https://user-images.githubusercontent.com/33936987/185416796-72b86c4c-7a9e-4c55-aeda-e1026a4e6cbb.png)

**Comment by iFlameing** [comment]
@tiberiuichim we want something like Gmail.


<img width="773" alt="Screenshot_2022-08-18_at_09 55 45" src="https://user-images.githubusercontent.com/33936987/185417470-39a4a9ef-5395-4fc2-b551-6ad2e8ff90af.png">
l

**Comment by tisto** [comment]
@tiberiuichim @avoinea is removing formatting in Slate a feature request that you ever encountered in your use cases? I think that would be a useful addition to Volto.

**Comment by tiberiuichim** [comment]
@tisto we have something implemented in an old PR, we could probably resurrect it. It makes sense to have that feature.

**Comment by robgietema** [comment]
https://github.com/eea/volto-slate/pull/246

**Comment by davisagli** [comment]
@robgietema Hasn't development of volto-slate moved into this repo? https://github.com/plone/volto/tree/master/packages/volto-slate

**Comment by sneridagh** [comment]
Fixed in #3596
