### ISSUE TITLE
Image Gallery listing block variation only shows 25 results

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#3589]
and there's no way to override it other than making an actual query.

**Comment by tiberiuichim** [comment]
I think there's also issues with the folder contents as listing block. No pagination (as far as I remember) and the shape of the result item in the array is different, the children are serialized with only title + id, while the querystring results are enriched with metadata. This makes the listing templates behave differently, when using more advanced templates that use additional metadata, for example to show content type or tags.

**Comment by davisagli** [comment]
A quick fix for the image gallery was merged in #3590, so I'll close this. I don't mean to ignore your comment @tiberiuichim; those sound worth further thought.
