### ISSUE TITLE
Slate Editor: can not delete bullet point after adding it by typing "- "

### ISSUE THREAD

**Issue by tisto** [plone/volto#3597]
**Describe the bug**

A bullet point item can not be deleted after it has been added by typing "- ".

**To Reproduce**

1. as admin
2. go to https://6.demo.plone.org/add?type=Document
3. Select the first text block and type "-" followed by a blank -> a bullet point occurs in slate
4. -> user can not hit delete, the "type text" label is displaced

**Expected behavior**

Bullet point lists can be deleted by hitting the delete key. Label is not displaced.

**Screenshots**

![Add-News-Item (1)](https://user-images.githubusercontent.com/632105/187398638-1a667c00-5397-4ac8-b586-51e1265f2c60.png)

**Comment by dobri1408** [comment]
I implemented a fix here https://github.com/plone/volto/pull/3612, hope is good.
