### ISSUE TITLE
Slate Editor: when hitting return on a bullet point list the cursor goes to the beginning of the item instead of creating a new text block

### ISSUE THREAD

**Issue by tisto** [plone/volto#3598]
**Describe the bug**

**To Reproduce**

1. as admin
2. go to https://6.demo.plone.org/add?type=Document
3. type "- foo"
4. hit return
5. -> cursor goes to the beginning of "foo"
6. -> no new text block is created

**Screenshots**

![Add-Document (1)](https://user-images.githubusercontent.com/632105/187400164-0daa03de-b732-404f-8f00-0a67b1e2b41f.png)

**Comment by vutkarsh01** [comment]
Not reproducible anymore, please verify this @tisto and close this

https://github.com/plone/volto/assets/43907055/2699273c-6d85-41c3-82e9-be301f09bf75

**Comment by davisagli** [comment]
Confirmed, it's working now
