### ISSUE TITLE
Slate Editor: pasting text into a bullet point list leads to a new text block

### ISSUE THREAD

**Issue by tisto** [plone/volto#3599]
**Describe the bug**

**To Reproduce**

1. as admin
2. create a new page
3. type "foo" and mark it as a bullet point list
4. hit return for a new bullet point list item
5. paste a plain text
6. -> the text hasn't been added to the bullet point list
7. -> instead the bullet point list item is gone and a new text block has been added

**Expected behavior**

**Screenshots**

Before pasting the text:

![Add-Document (2)](https://user-images.githubusercontent.com/632105/187400559-6d53199f-ffef-48d3-858a-0970385dff1d.png)

After pasting the text:

![Add-Document (3)](https://user-images.githubusercontent.com/632105/187401131-76068d7f-b3d2-455f-9edd-5ddfd0465db9.png)

**Comment by sneridagh** [comment]
Fixed by #3601
