### ISSUE TITLE
History vew uses "X hours/days ago" instead of the exact date/time

### ISSUE THREAD

**Issue by tisto** [plone/volto#3620]
**Is your feature request related to a problem? Please describe.**

- Folder contents shows exact date/time: https://6.demo.plone.org/contents
- History view uses "x hours/days ago": https://6.demo.plone.org/news/history

**Describe the solution you'd like**

Displaying date/time should be used consistently. "x hours/days ago" might make sense in social media. It doesn't make sense for the CMS use case.

**Comment by stevepiercy** [comment]
Can I just say how much I *hate* "x hours/days/minutes ago"? I want the absolute datetime always. I wish GitHub and Gitlab would changes this to display the user's datetime or UTC if not authenticated.

**Comment by erral** [comment]
This should be addressed together withClassic UI Toolbar, becuase the "2 hours ago" is present there too.

![Pantaila-argazkia 2022-09-12 08-12-20](https://user-images.githubusercontent.com/817365/189585223-aaa488e1-a704-4976-805a-931e8cd38805.png)

**Comment by tiberiuichim** [comment]
![image](https://user-images.githubusercontent.com/141568/189585810-8ed5337b-edc8-42ad-8d56-166fa477c806.png)

The relative datetimes are usually titled with the original. With Volto we have a component that does this automatically.

https://github.com/plone/volto/blob/d8b04e734b06e5d707f845da8f1d35c3dfb4875e/src/components/theme/FormattedDate/FormattedRelativeDate.jsx#L41-L43

**Comment by thet** [comment]
my2©: I‌ think the "2 hours ago" in the toolbar is ok. That allows for faster scanning as if there was a ``2022-09-15, 14:48`` instead.
We definitely should add the exact time in the title attribute.

For detail views I'm ok to not have relative dates.
