### ISSUE TITLE
Makefile: support Mac?

### ISSUE THREAD

**Issue by ksuess** [plone/volto#3642]
The following code is of course helpful, but lets Mac users with shell zsh stumble. Who is expert in _make_ and conditionalize it?

### Defensive settings for make:
#     https://tech.davis-hansson.com/p/make/
SHELL:=bash
.ONESHELL:
.SHELLFLAGS:=-xeu -o pipefail -O inherit_errexit -c
.SILENT:
.DELETE_ON_ERROR:
MAKEFLAGS+=--warn-undefined-variables
MAKEFLAGS+=--no-builtin-rules

**Comment by davisagli** [comment]
@ksuess What was the problem you ran into? We already have these lines in the Makefile, and `SHELL:=bash` ensures that the Makefile commands will be run using bash, even if the user running the command has their shell set to zsh.

**Comment by ksuess** [comment]
With an upgrade of make to 4.x I got the following error:
```
% make docs-livehtml
bash: line 0: inherit_errexit: invalid shell option name
make: *** [Makefile:123: docs-livehtml] Error 2
```
Now I upgraded bash from 3.x to 5.x. which solved by problem.

Thank you @davisagli  for caring!
