### ISSUE TITLE
email widget validation does not correctly validate email addresses

### ISSUE THREAD

**Issue by instification** [plone/volto#3663]
**Describe the bug**

The current validation for the email type widget has a simple regex that does not allow for newer types of domains, such as .name.

**To Reproduce**

1. Create a schema form with an email widget
2. Submit the form with a valid email address such as `test@domain.name`
3. You will see the error `Input must be valid email (something@domain.com)`

**Expected behavior**

The email validation should accept all valid email addresses.

**Screenshot**

<img width="935" alt="Screenshot 2022-09-21 at 09 53 43" src="https://user-images.githubusercontent.com/2558052/191460728-6752f7dd-e6a8-41c9-9f5c-2d1c16bb4f55.png">

**Additional context**
This [stackoverflow question](https://stackoverflow.com/questions/46155/how-can-i-validate-an-email-address-in-javascript) discusses the issue and provides a regex that will handle a wider array of valid email addresses.

The [current regex](https://github.com/plone/volto/blob/master/src/helpers/FormValidation/FormValidation.js#L43) is:

```
/^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/;
```

I am proposing to replace this regex with the one provided in the above stackoverflow answer to:

```
  /^(([^<>()[\]\.,;:\s@\"]+(\.[^<>()[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i;
```

**Comment by stevepiercy** [comment]
Here's an another regex for email. If it's good enough for web browsers, then it's good enough for us. If we use an HTML5 input of type email, then you probably want to use this regex to align with that.

https://github.com/Pylons/colander/blob/baa0e5ce4d9dae404d40b23ef7392f71a86b8cd8/src/colander/__init__.py#L380-L390

**Comment by instification** [comment]
Hi @stevepiercy thanks for this! I think it's a much easier to read regex.

 Here's the js compatible regex taken from the WHATWG spec:

```
/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;
```

I've updated the attached PR with this regex.

I agree that it should match with web browser standards.
