### ISSUE TITLE
Cannot resolve custom syntax module "postcss-less"

### ISSUE THREAD

**Issue by nileshgulia1** [plone/volto#3701]
**Describe the bug**
The error originates after upgrading my volto addon to run [stylelint](https://github.com/plone/volto-addon-ci/blob/master/docker-entrypoint.sh#L96) from volto-addon-ci after I run the upgrade steps in https://github.com/plone/volto/blob/master/docs/source/upgrade-guide/index.md#upgraded-to-razzle-4

**Expected behavior**
The command should run successfully.

- Volto Version: latest alpha

**Comment by davisagli** [comment]
@nileshgulia1 Can you share the full stack trace for the error so that it's possible to see where the error is happening?

postcss-less [is a dependency of @plone/volto](https://github.com/plone/volto/blob/master/package.json#L310), so it's not immediately obvious what is going wrong.

**Comment by wesleybl** [comment]
In https://github.com/plone/volto/blob/master/docs/source/upgrade-guide/index.md#upgraded-to-razzle-4 says:
```
You should also do a final step, and change the babel.config.js, removing the preset from razzle/babel to razzle
```

But `@plone/generator-volto` uses `razzle/babel`:

https://github.com/plone/volto/blob/af0a18dd8c02ce0b6c1c5c63d46164709d1ea533/packages/generator-volto/generators/addon/templates/babel.config.js#L3

Shouldn't he be `razzle`?

**Comment by nileshgulia1** [comment]
This is fixed locally.
