### ISSUE TITLE
Improve validation of IdWidget

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#3716]
This issue defines what we want the frontend to do based on what the backend allows, specifically the `and`ing of all these:

- No new lines (https://zopeschema.readthedocs.io/en/latest/fields.html#asciiline)
- Allow only 7-bit bytes characters (https://zopeschema.readthedocs.io/en/latest/fields.html#ascii)
- No characters that are illegal in URLs: `\x00-\x1F`, `\x7F`, `<`, `>`, and `&`. (https://github.com/zopefoundation/Zope/blob/d1814d0a6bddb615629b552de10e9aa5ad30a6da/src/OFS/ObjectManager.py#L81-L94)
- Not the empty string `""`. (https://github.com/zopefoundation/Zope/blob/d1814d0a6bddb615629b552de10e9aa5ad30a6da/src/OFS/ObjectManager.py#L90)
- Is not `.` or `..` (can be traversed). (https://github.com/zopefoundation/Zope/blob/d1814d0a6bddb615629b552de10e9aa5ad30a6da/src/OFS/ObjectManager.py#L98)
- Cannot start with `_`. (https://github.com/zopefoundation/Zope/blob/d1814d0a6bddb615629b552de10e9aa5ad30a6da/src/OFS/ObjectManager.py#L101)
- Cannot start with `aq_`. (https://github.com/zopefoundation/Zope/blob/d1814d0a6bddb615629b552de10e9aa5ad30a6da/src/OFS/ObjectManager.py#L105)
- Cannot end with `__`. (https://github.com/zopefoundation/Zope/blob/d1814d0a6bddb615629b552de10e9aa5ad30a6da/src/OFS/ObjectManager.py#L108)
- Cannot start with `@@` or `++`. (https://github.com/zopefoundation/Zope/blob/d1814d0a6bddb615629b552de10e9aa5ad30a6da/src/OFS/ObjectManager.py#L112)
- Cannot be `REQUEST`. (https://github.com/zopefoundation/Zope/blob/d1814d0a6bddb615629b552de10e9aa5ad30a6da/src/OFS/ObjectManager.py#L131)
- Cannot contain `/`. (https://github.com/zopefoundation/Zope/blob/d1814d0a6bddb615629b552de10e9aa5ad30a6da/src/OFS/ObjectManager.py#L133)

_Originally posted by @stevepiercy in https://github.com/plone/volto/issues/3704#issuecomment-1266373914_

**Comment by ichim-david** [comment]
Fixed by the merging of https://github.com/plone/volto/pull/4686
