### ISSUE TITLE
Remove "Creating a new Volto project" from documentation

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#3723]
https://6.docs.plone.org/volto/recipes/creating-project.html

I think we should keep a single document page (getting-started), to avoid missing out on places to update.

**Comment by stevepiercy** [comment]
The entry point is: https://6.dev-docs.plone.org/install/index.html

From there, the user can choose [containers](https://6.dev-docs.plone.org/volto/recipes/creating-project.html) or [packages using the new cookiecutter](https://6.dev-docs.plone.org/install/install-from-packages.html). Note that in the latter we refer to the page you propose to remove. As such we need to move content into the latter page before we remove this one.

**Comment by farhanakhtar24** [comment]
Hey @stevepiercy can you explain this briefly what's the issue here .

**Comment by davisagli** [comment]
This was already fixed.

**Comment by stevepiercy** [comment]
@davisagli are you sure? https://6.docs.plone.org/volto/recipes/creating-project.html

**Comment by davisagli** [comment]
Oops, it was still there after all.

This page is still a useful how-to for the scenario where someone wants to create a volto frontend project only (i.e. to use with an existing backend). I added a note in https://github.com/plone/volto/pull/5287 to try to clarify this.

**Comment by stevepiercy** [comment]
Rename this page to "Create a Volto project without a backend". Add explanation for why this might be desired, such as using your own existing backend with Classic UI, Nick, or Guillotina.
