### ISSUE TITLE
related items don't show by default

### ISSUE THREAD

**Issue by tkimnguyen** [plone/volto#3740]
on https://6.demo.plone.org/ if I edit the front page and set a related item, it does not appear in the normal view

**Comment by wesleybl** [comment]
@sneridagh related items don't show by default or is it not implemented yet?

**Comment by davisagli** [comment]
related item to this issue about related items: https://github.com/plone/volto/issues/3355

**Comment by wesleybl** [comment]
I think issue #3355 is not an impediment to implement related item listing. Related items work well with `ObjectBrowserWidget`.
