### ISSUE TITLE
Allow adding images from the site content to Hero block

### ISSUE THREAD

**Issue by rioksane** [plone/volto#3763]
As a content editor I want to use existing images from the site content on a hero block. It is possible on image or teaser block. 

See example
<img width="1371" alt="Screenshot 2022-10-14 at 16 44 32" src="https://user-images.githubusercontent.com/5127672/195876019-c0c007e0-82ae-4e05-a2ca-e291c832658b.png">

 (this is from Volto 15.5 so maybe its there in the newer one?)

**Comment by tiberiuichim** [comment]
Should be covered in https://github.com/plone/volto/pull/3386

**Comment by sneridagh** [comment]
This should be covered from an add-on, since we deprecated the Hero block in Volto 18. 
Closing for now.
