### ISSUE TITLE
Move sentry code to new Volto addon

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#3766]
We should move the sentry code to a new Volto addon.

This may be a bit trickier, but if needed, we add the required Volto hooks to be able to do this.

**Comment by tiberiuichim** [comment]
I've created a branch, started collective/volto-sentry

**Comment by sneridagh** [comment]
Removed from core. The add-on is in-progress: https://github.com/collective/volto-sentry

**Comment by pnicolli** [comment]
@sneridagh @tiberiuichim this is done and can be close afaict, or is something missing?
