### ISSUE TITLE
Include the --canary option of the generator in the documentation

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#3769]
Sometimes (Volto 16 alpha 42) we have quite a long time no stable releases that match what the rest of us are doing. So it would be a good idea to mention the --canary flag in the documentation for the `yo @plone/volto` generator

**Comment by davisagli** [comment]
It's already mentioned in https://www.npmjs.com/package/@plone/generator-volto

I guess you mean we should add it in https://github.com/plone/volto/blob/master/docs/source/getting-started/install.md#install-volto ?

**Comment by tiberiuichim** [comment]
@davisagli Yes, in the getting started
