### ISSUE TITLE
Pasting specially crafted HTML with inner `\n`  in a slate block using FF inserts spaces at the beginning and (apparently) randomly in the middle of the text

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#3802]
**Describe the bug**
If the copied HTML is crafted in a way that it contains `\n` on it, pasting in a slate block using FF inserts soft spaces at the beginning and (apparently) randomly in the middle of the text.

**To Reproduce**

1. Using FF
2. Use https://www.dlr.de/content/de/artikel/news/2022/03/20220831_intelligentes-lademanagement.html
3. Copy the text
4. Paste in a slate block 

See the initial spaces in each block, also some weird double ones in the middle.

<img width="523" alt="image" src="https://user-images.githubusercontent.com/486927/198063841-c9697ad4-ce09-4a6e-88be-f4be04aab301.png">

**Expected behavior**
The pasted content is clear of glitches.

**Comment by tiberiuichim** [comment]
Browsers are nasty.

Here's an example, you can see that a new line in a headline is visually rendered as a space:

![image](https://user-images.githubusercontent.com/141568/198226376-0c66b946-32eb-42ce-8205-7203f51a3d9a.png)

**Comment by tiberiuichim** [comment]
![image](https://user-images.githubusercontent.com/141568/198231039-b7619037-b479-47a3-bdfc-f19c7430dd8c.png)
