### ISSUE TITLE
UX: Confusing the X is used both delete (in a grid) and cancel (on a page)

### ISSUE THREAD

**Issue by djay** [plone/volto#3816]
**Describe the bug**
I'd say it makes it pretty unclear that x on a container block means delete

**To Reproduce**
make a grid. see the x

**Expected behavior**
Use a trash icon. It's consistent.

**Screenshots**
Here you can see the same x icon being used for two different purposes on the same page

<img width="980" alt="image" src="https://user-images.githubusercontent.com/41700/199159116-4a05d70f-6533-43f8-b8f1-0991bc2449d7.png">

**Comment by davisagli** [comment]
Is this about https://github.com/kitconcept/volto-blocks-grid? The grid block hasn't been added to volto core yet.

**Comment by stevepiercy** [comment]
There's also a trash can icon to the right of the block, making the `X` next to the gear icon redundant. `X` means "cancel" in my brain.

**Comment by djay** [comment]
> There's also a trash can icon to the right of the block, making the `X` next to the gear icon redundant. `X` means "cancel" in my brain.

exactly. X means cancel. 
The delete next to the gear deletes the contents rather than the whole block. Which is itself another different UX problem with that particular container block.

> Is this about https://github.com/kitconcept/volto-blocks-grid? The grid block hasn't been added to volto core yet.
fair enough. It also applies to other container blocks like accordion which also aren't in core. so hopefully the appropriate place to fix it is #3180 and the proper block in block UI once it's in core I guess.

**Comment by djay** [comment]
since this is related to grids and rows and they aren't released yet this is not a current bug
