### ISSUE TITLE
Issue on page /volto/blocks/block-style-wrapper.html enableStyling was removed in volto 16.0.0.alpha.46

### ISSUE THREAD

**Issue by avoinea** [plone/volto#3819]
enableStyling is not working anymore starting with [Volto 16.0.0-alpha.46](https://github.com/plone/volto/releases/tag/16.0.0-alpha.46)

**Comment by stevepiercy** [comment]
Transferred to `plone/volto` repo https://github.com/plone/volto/issues/3819

**Comment by davisagli** [comment]
@avoinea @stevepiercy This was done intentionally in https://github.com/plone/volto/pull/3794 and documented in the Volto upgrade guide. Is this issue about updating the training?

**Comment by davisagli** [comment]
Ah, no, I figured out this is about the mention of enableStyling that remains on https://6.dev-docs.plone.org/volto/blocks/block-style-wrapper.html

/cc @sneridagh

**Comment by sneridagh** [comment]
Uh, maybe the docs sync has failed? Eric S. Made it work during the conf sprint.

**Comment by stevepiercy** [comment]
Nope, it's b0rken. @esteele said [he would look into it](https://github.com/plone/documentation/pull/1346#issuecomment-1283013996).

I updated the submodule tips manually. Check the [build](https://github.com/plone/documentation/actions/runs/3372490711/jobs/5595981352) in about 10 minutes.

**Comment by davisagli** [comment]
The docs are up to date now.
