### ISSUE TITLE
Search block: results not updating after navigating (duplicate block id)

### ISSUE THREAD

**Issue by davisagli** [plone/volto#3826]
**Describe the bug**
If I use the search block to navigate to another page that also has a search block with the same block id, the search results are not updated.

(This is a bit of an edge case, but it happened in a project where we were initializing all containers by copying blocks from a common template, so every container's search block has the same block id.)

**To Reproduce**
1. Add a page with the title "Page A". Give it a search block with criteria to search by relative path and order by position in folder.
2. In the contents view, copy Page A and paste it inside of Page A. (This creates a second page with the same block ids.)
3. In the contents view, rename the inner Page A to page-b / Page B.
4. Open /page-a in a new tab.
5. Click the link in the search results to navigate to Page B.
6. --> expected: the search results update to show that there are no results inside Page B.
7. --> actual: the search results do not update, so they continue to show the link to Page B.

**Analysis**
Since the block id is unchanged, the existing search block view component is not replaced, and nothing triggers a new query.

Proposed solution: Set the page `@id` as a `key` on the view component. Navigating to a new page changes the `@id`, so React will not reuse the existing components. (See https://medium.com/trabe/avoiding-stateful-components-reuse-with-react-keys-2e5f6e8cc5cb for more explanation.)

**Comment by tiberiuichim** [comment]
+1 on the proposal

**Comment by davisagli** [comment]
@tiberiuichim working on it now, and already confirmed it fixes the issue. Any idea how to write a test for this?
