### ISSUE TITLE
Issue with hover toolbar when opening ObjectBrowser

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#3829]
[vokoscreenNG-2022-11-03_10-06-04.webm](https://user-images.githubusercontent.com/141568/199672484-2c3daaad-8678-4b7a-a5ce-e9f5e156eef4.webm)

Notice the toolbar disappears (in the 1st second of the video) when the object browser is opened. Then, when clicking on the non-working link of the current document, the toolbar appears at that position.

**Comment by lord2anil** [comment]
@tiberiuichim  can please check  this issue again , for me this is not happening
