### ISSUE TITLE
connect ECONNREFUSED 0.0.0.0:443

### ISSUE THREAD

**Issue by adam139** [plone/volto#3872]
**Describe the bug**
plone@LAPTOP-F9R9D7PI:~/workspace$ yo @plone/volto emc_front
Getting latest Volto version
Using latest released Volto version: 15.16.0
Retrieving Volto's yarn.lock
Error @plone/volto emc_front

connect ECONNREFUSED 0.0.0.0:443
plone@LAPTOP-F9R9D7PI:~/workspace$

**To Reproduce**

1. npm install -g yo

2. npm install -g yo @plone/generator-volto
3.  yo @plone/volto emc_front
raise error:
connect ECONNREFUSED 0.0.0.0:443

**Additional context**
why connect to localhost 443 port?

**Comment by tiberiuichim** [comment]
@adam139 I have never seen this problem.

Do you have something weird about your setup? A local npm cache? A proxy of some sort? Did you use your laptop for Javascript development, before trying this? Can you try to bootstrap a react app by following the steps here: https://reactjs.org/docs/create-a-new-react-app.html#create-react-app ?

**Comment by adam139** [comment]
1. OS:Linux LAPTOP-F9R9D7PI 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
2. nvm:nvm --version 0.39.1
3. npm: 8.19.2
4. node:node -v v16.18.1
5.  yo --version 4.3.1
6. yo Available Generators:  @plone/volto    addon
7. do not set any proxy
8. I had development React application successfully.
9. can bootstrap the app:```
Compiled successfully!

You can now view my-app in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://172.27.5.132:3000

Note that the development build is not optimized.
To create a production build, use npm run build.

webpack compiled successfully
```

**Comment by nileshgulia1** [comment]
@adam139 Could you try re-installing Node, probably using nvm? I also haven't saw this error, especially with volto-generator.

**Comment by adam139** [comment]
I use nvm re-install node.run the following commands:

1. npm install -g yo @plone/generator-volto
2.  yo @plone/volto
raise the new error:
`Getting latest Volto version
Error @plone/volto

undefined`

**Comment by nileshgulia1** [comment]
I use node `v16.13.1`, and works fine for me. It seems for you it broke after getting volto version. Can you try to make a curl in https://github.com/plone/volto/blob/67dcc0a52ade4b951ce51eac5534a3c3d8053e42/packages/generator-volto/generators/app/utils.js#L33

**Comment by davisagli** [comment]
Closing due to lack of followup.

https://community.plone.org/ is a better place to ask for support.
