### ISSUE TITLE
Github test runners need to be updated

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#3895]
![image](https://user-images.githubusercontent.com/141568/201999945-cd5c8dea-44b8-46bd-b382-ee4432350a68.png)

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by davisagli** [comment]
This was fixed as part of https://github.com/plone/volto/pull/3291
