### ISSUE TITLE
Site Administrator can't access user controlpanel

### ISSUE THREAD

**Issue by wesleybl** [plone/volto#3917]
**Describe the bug**
A user with the Site Administrator role, receives an Unauthorized error, when trying to access the user's controlpanel:

http://localhost:3000/controlpanel/users

Log:

```bash
2022-11-18 10:24:33 ERROR [Zope.SiteErrorLog:35][waitress-2] Unauthorized: http://localhost:3000/@roles
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 167, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 376, in publish_module
  Module ZPublisher.WSGIPublisher, line 255, in publish
  Module ZPublisher.BaseRequest, line 641, in traverse
  Module ZPublisher.HTTPResponse, line 1017, in unauthorized
zExceptions.unauthorized.Unauthorized: You are not authorized to access this resource.
```

**To Reproduce**

1. Create a user with the Site Administrator role
2. Logged in with this user, try to access the user's controlpanel:
http://localhost:3000/controlpanel/users

**Expected behavior**
Allow the user to access the control panel

**Software (please complete the following information):**

OS: Ubuntu 22
Browser: Chrome
Volto Version: 16.0.0-alpha.48
Plone Version 6.0.0b3
Plone REST API Version: 8.30.0

**Comment by wesleybl** [comment]
@mauritsvanrees FYI

**Comment by wesleybl** [comment]
The problem is this permission:

https://github.com/plone/plone.restapi/blob/80c0b085381dceb177b48fed34897ecd69d7efa4/src/plone/restapi/services/roles/configure.zcml#L10

@jaroel any specific reason to use this permission?

**Comment by davisagli** [comment]
I think `plone.app.controlpanel.UsersAndGroups` is the correct permission to use here.

**Comment by wesleybl** [comment]
@davisagli @jaroel @lukasgraf

We also have permission checks in the python file:

https://github.com/plone/plone.restapi/blob/f77182b5700d059b6aee0f8f0bcc7a3fa29e3696/src/plone/restapi/services/users/get.py#L149-L161

These checks were inserted in:

https://github.com/plone/plone.restapi/pull/772

Can we change these permissions?

**Comment by davisagli** [comment]
In general we should avoid using the `Manage portal` permission, and use more specific permissions. When something is protected by the `Manage portal` permission, it is difficult to change the policy and grant it to someone other than a Manager.

**Comment by wesleybl** [comment]
I think it will also be necessary to check that a Site Administrator is not able to give a Manager role to users.

@lukasgraf @sneridagh @tisto 

Is there any check in this regard in restapi?

**Comment by davisagli** [comment]
@wesleybl Excellent point. The classic UI users control panel has some checks for this (search for is_zope_manager in https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/controlpanel/browser/usergroups_usersoverview.py) that need to be duplicated for the REST API.

There's a good chance that the lack of these checks is why the control panel is restricted to the `Manage portal` permission so far.

**Comment by wesleybl** [comment]
@davisagli the way restapi deletes users is different from Plone Classic. Plone Classic uses [acl_users](https://github.com/plone/Products.CMFPlone/blob/bad7ee61597c72f165f5db979ee04efd06066d22/Products/CMFPlone/controlpanel/browser/usergroups_usersoverview.py#L246). restapi uses [portal_membership](https://github.com/plone/plone.restapi/blob/48d2569b00b4e166556b6699ce4ee086f30a2c7e/src/plone/restapi/services/users/delete.py#L42). The way restapi does it, the Site Adminstrator also needs the `Manage users` permission. When trying, I get the error:

```
{
  "message": "You need the 'Manage users' permission for the underlying User Folder.",
  "type": "Unauthorized"
}
```
Where would be the best place to give Site Administrator this permission? In `plone.restapi` itself?

**Comment by wesleybl** [comment]
@davisagli when a user who is not a Manager is creating another user, he can only assign the roles it has, see:

https://github.com/zopefoundation/Products.CMFCore/blob/c73cdf4f0fdcca4b9bb95813ade7a374282dd801/src/Products/CMFCore/utils.py#L213-L215

Volto has a functionality to assign roles to a user in its creation. So a Site Administrator who only has the Site Administrator role could only create Site Administrator or no role. But later, in the user list, he could assign other roles. This is strange, but I'm not looking to mess with this behavior. Can we keep it like this?

**Comment by wesleybl** [comment]
@davisagli @sneridagh @tisto I did the PR https://github.com/plone/plone.restapi/pull/1712 on the plone.restapi side and I'm going to do the PR on Volto, to remove options from the Site Administrator to give Manager permission. My question is whether this PR should work without the plone.restapi PR, or should I consider that the plone PR will be available? There would be fewer checks if you consider that plone.restapi is with my PR.
