### ISSUE TITLE
User add form does not highlight fields with validation error

### ISSUE THREAD

**Issue by wesleybl** [plone/volto#3918]
**Is your feature request related to a problem? Please describe.**
It only shows the text `There were some errors.`

**Describe the solution you'd like**
Show the error message in the field and highlight the field

**Additional context**
![useradd](https://user-images.githubusercontent.com/3297795/202727958-90bc799e-0c35-4abc-b42d-f569db2c736c.png)

**Comment by davisagli** [comment]
@wesleybl What is the API response in this case?

**Comment by wesleybl** [comment]
uh I can see that in master this doesn't happen:

![useradd](https://user-images.githubusercontent.com/3297795/202775502-2c53df0b-3e62-4c58-be91-2b4585169690.png)


So I'll close here.
