### ISSUE TITLE
Experimental features need to be properly documented

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#3920]
We have a few experimental features that need to be clearly marked as such, in a proper doc.

One example is Pluggables, which is still marked as experimental. Do we graduate it? If so, we should clearly document its use case and how it's supposed to be used internally in Volto.

**Comment by stevepiercy** [comment]
I think that this should be a new page in the [Configuration](https://6.dev-docs.plone.org/volto/configuration/index.html) directory, entitled Experimental Features. When they are no longer experimental, then they can be moved into the appropriate Configuration page.

@davisagli mentioned he would like to work on this, so I will assign it to him.

**Comment by davisagli** [comment]
I started this in #3942, but so far I only mentioned the add block button because it is the only one that can be controlled using `config.experimental` (and also I am not really sure what other features are considered experimental).

@tiberiuichim Should we mention Pluggables here, or just mention that it is experimental on the page about Pluggables? What other features are still experimental?

**Comment by tiberiuichim** [comment]
@davisagli Pluggables are "experimental" in the sense that at least myself I have not decided if they're a good idea or a bad idea. It bothers me that there are edge cases that make them tricky to use: by just having a component refresh, your pluggable can be overriden by whatever you wanted to override. So it can lead to bad performance and things that are hard to debug and understand. The initial goal was to make it possible to plug things into the UI without having to declare configuration for those plug points... but if things don't work out, we may have to reconsider.

At least they should be better documented, to make it obvious about their problems. For example, the `dependencies` and `order`  features are not documented.
