### ISSUE TITLE
Translate error message on add user form

### ISSUE THREAD

**Issue by wesleybl** [plone/volto#3958]
**Describe the bug**
Error messages on add user form are not translated

**To Reproduce**

1. Create a Plone site and put it in a language other than English.
2. Go to add users form
3. Fill in all fields except the password field.
4. See that the error message is in English.

**Expected behavior**
The error message must be translated.

**Screenshots**
![useradd](https://user-images.githubusercontent.com/3297795/203416397-2cc0e31b-2e8e-4e42-babb-b411a3c7cf4a.png)

**Software (please complete the following information):**

OS: Ubuntu 22
Browser: Chrome
Volto Version: 16.0.0-rc.1
Plone Version 6.0.0rc1
Plone REST API Version: 8.32.2

**Comment by wesleybl** [comment]
Does this translation have to be done in `plone.restapi`?

**Comment by davisagli** [comment]
@wesleybl It looks like some strings are not translated in https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/services/users/add.py

@erral Should they be added with the plone.restapi domain or something else?

**Comment by erral** [comment]
we have very few messages to translate in plone.restapi. The idea was to include them into plone domain, see https://github.com/collective/plone.app.locales/pull/332

I don't like adding things in plone.restapi because it is yet another package to translate, so if it was possible I would try to minimize it.

If it is not possible to create those messages outside of plone.restapi, then we have no other option

**Comment by davisagli** [comment]
@erral Hmm, I was going to agree with you, but then I remembered that plone.restapi aims to keep compatibility with Plone 5 (at least for existing features). If we move the existing messages to plone.app.locales, then they will no longer have translations in Plone 5.

I think it would be okay to add new messages to the plone domain (using the message factory from CMFPlone) and put the translations in plone.app.locales for them.

**Comment by wesleybl** [comment]
@davisagli today we only have translations of the restapi domain into German:

https://github.com/plone/plone.restapi/tree/master/src/plone/restapi/locales

And there are few terms:

https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/locales/de/LC_MESSAGES/plone.restapi.po

**Comment by erral** [comment]
I would leave them in plone.restapi domain, and when we break Plone 5 compatibility we will move them to plone domain.
