### ISSUE TITLE
Upgrade guide mentions upgrade to Cypress 10, but we're on Cypress 11

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#3979]
https://github.com/plone/volto/blob/4e619b73bda70c4b0e52a2fb48048bc11e6f0484/package.json#L256-L258

https://github.com/plone/volto/blob/4e619b73bda70c4b0e52a2fb48048bc11e6f0484/docs/source/upgrade-guide/index.md?plain=1#L350

**Comment by tiberiuichim** [comment]
Nevermind, false flag.

> Later on, the core has been upgraded to Cypress 11.
> However no changes need to be made if you already upgraded to Cypress 10.

**Comment by stevepiercy** [comment]
Actually, that wording is awkward. Was the intent, "In the future, the core will be upgraded to Cypress 11."?

**Comment by tiberiuichim** [comment]
@stevepiercy I think the upgrade should just say "Cypress has been upgraded to 11", and avoid the misdirection "cypress has been upgraded to 10... oh, wait, actually it has been upgraded to 11"
