### ISSUE TITLE
Intermitent failures in volto test runs

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#3983]
![image](https://user-images.githubusercontent.com/141568/204082327-4d803d98-f8f9-4dec-9b1a-15e300a242ed.png)

see https://github.com/plone/volto/actions/runs/3550237081/jobs/5963435992 and https://cloud.cypress.io/projects/hvviu4/runs/2822/overview/881dc552-7079-41c7-93ea-a63faca1050b/video

**Comment by wesleybl** [comment]
I haven't seen this error for a long time. It has probably already been fixed.
