### ISSUE TITLE
Documentation still references yarn classic

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#3998]
![image](https://user-images.githubusercontent.com/141568/204248535-44927825-aec3-4b14-b622-91561441cb80.png)

Screenshot from https://6.dev-docs.plone.org/volto/getting-started/install.html#yarn-nodejs-package-manager

We use Yarn 3. @sneridagh I know that we ship with [yarn as a binary release](https://github.com/plone/volto/blob/master/.yarn/releases/yarn-3.2.3.cjs), should anything be done about the documentation?

CC @stevepiercy

**Comment by stevepiercy** [comment]
Sorry for my off-topic rant for what seems a small change, but every time I look at Installation docs, I feel dismayed.

First, the Install story is incredibly complex for Plone 6, and I want to make it easier to navigate. Anything to do with Install should be carefully thought through in the context of Plone 6. The current state of all the Install docs is OK, but it has some serious flaws.

1. [Plone 6 Docs' Install says, "Look at Volto's docs"](https://6.dev-docs.plone.org/install/install-from-packages.html#pre-requisites-for-installation).
2. Volto's Install doc is deeply nested and poorly named under [Frontend](https://6.dev-docs.plone.org/volto/index.html) > [Introduction](https://6.dev-docs.plone.org/volto/getting-started/index.html) > [Getting Started](https://6.dev-docs.plone.org/volto/getting-started/install.html).
3. Volto has a [Quick Start in its README.md](https://github.com/plone/volto#quick-start) with yet another Install story.
4. We do not define the role of the person who wants to install Plone. Is it an end user, developer, contributor, sysadmin, other?
5. We do not give sufficient guidance to each of those roles to Install Plone 6.
6. Across all roles, we do not define the common bits and pieces to Install Plone 6.
7. For each role, we do not define the unique bits and pieces to Install Plone 6. These bits may be better kept in Volto docs and referenced from the Plone 6 Docs as needed.

There may be other flaws that I omitted, but these are the big ones.

Eventually I would like to have One Install Doc to Rule Them All in Plone 6 Docs, and there's been some good progress toward that goal. Before I can move this task forward, I need help to define items 4, 5, 6, and 7, even if that is only for Volto. Maybe that's where we start, with Volto leading the charge.

I recall someone told me, "I have on-boarding docs that we use for Company X. Let me check if we can share that, and get back to you." That would be a great start, but I can't remember the details.

**Comment by tiberiuichim** [comment]
I think the current situation is due to how Volto was developed, as an external product, outside of the Plone classic world. There's also kind of two types of developers now, both with concerns over their own little world: frontend (Volto) and backend (Plone).

**Comment by fredvd** [comment]
Explocit mention of needing yarn 3 is now in the installation section.  also the docs for indtalling  have been reorganised somewhat but we're not there yet
