### ISSUE TITLE
subscript and subscript should not be active at same time.

### ISSUE THREAD

**Issue by iFlameing** [plone/volto#4011]
**Describe the bug**

During the inline editing of the text block, we can't set the subscript and subscript at the same time. It should not be possible.

**To Reproduce**

1. create a page
2. Add some text in text block
3. select one text at which you want to put sub or sup script.
4. You can apply both on same element.

**Expected behavior**

Both should not be applied at same time.

**Screenshots**

**Software (please complete the following information):**

- OS: [e.g. iOS] macos
- Browser [e.g. chrome, safari] chrome
- Volto Version [e.g. 8.5.0] latest
- Plone Version [e.g. 5.2.2] latest
- Plone REST API Version [e.g. 7.0.1] latest

*

**Comment by davisagli** [comment]
Fixed in #4012 and #4042
