### ISSUE TITLE
AppExtras is still on settings, although we have a configuration registry entry for it...

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#4019]
It seems we never really made the migration :(

`config.AppExtras` is there but the one really working is: `config.settings.AppExtras`.

**Comment by tiberiuichim** [comment]
I did not knew there's an `config.AppExtras` . I think it's fan to keep it in config.settings.

**Comment by sneridagh** [comment]
Then let's remove the `config.AppExtras` :)
