### ISSUE TITLE
make start-backend-docker doesn't work

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#4022]
![image](https://user-images.githubusercontent.com/141568/205428966-1ccf348a-0565-4ae5-8c54-7f54dffdde32.png)

**Comment by davisagli** [comment]
I noticed this too. We need to avoid passing ADDONS when it is empty

**Comment by tiberiuichim** [comment]
maybe plone-backend entrypoint should be smarter about it

**Comment by davisagli** [comment]
@sneridagh had the same idea: https://github.com/plone/plone-backend/pull/102

**Comment by sneridagh** [comment]
yeah, I got bitten by this the other day too!
