### ISSUE TITLE
Input value of Serach field remains even after hitting submit button

### ISSUE THREAD

**Issue by MAX-786** [plone/volto#4028]
## Issue
When the input is given inside the search field the value remains there even if we change our routes or do editing etc. which I think does not look so good.
This video illustrates the above issue:

https://user-images.githubusercontent.com/99530996/205440822-41bf8e6b-dea0-4112-99e3-5b874f29f9cf.mp4

## Approach

1. In `plone/volto/src/components/theme/SearchWidget/SearchWidget.jsx` we can modify the handler `onSubmit()` to reset the value of the input field of the search widget.
OR
2. As proposed by tiberiuichim#7386 on discord we can replace the input field with a button that takes you to the search page just like in bbc.com.

https://user-images.githubusercontent.com/99530996/205442462-cb27c76c-0d67-48fe-aecc-e159f4c1b076.mp4

Feedback Welcome.

**Comment by tiberiuichim** [comment]
@sneridagh @tisto Would changing the behavior for the search widget work fine for you guys?

@MAX-786 Proposal 1 is the safest to implement until we hear a confirmation about changing the default behavior of the search widget. 

From my personal experience, I think having an independent search input widget causes a lot of UX problems and BBC's solution seems very much a good thing to do.

@plone/volto-team thoughts on this?

**Comment by MAX-786** [comment]
Thanks for your feedback @tiberiuichim, And for now if we are going with 1st proposal then after hearing others thoughts on this, I will move ahead and make a PR of it's looks good to everyone
