### ISSUE TITLE
Can't type spaces in rich text field with slate editor

### ISSUE THREAD

**Issue by davisagli** [plone/volto#4076]
**Describe the bug**
When using the slate editor to edit a rich text field, I am unable to type spaces at the beginning/end of a text node.

**To Reproduce**

1. Create a volto site.
2. Go to the Content Types control panel and add a new content type.
3. Edit the schema for the content type and add a Rich text field.
4. Start adding an instance of the content type. In the rich text field, try to type a sentence.

**Expected behavior**
Typing spaces should work.

**Actual behavior**
Hitting the spacebar does not add a space.

**Software (please complete the following information):**

- OS: Mac
- Browser: Firefox
- Volto Version: 16.3.0 (current master)
- Plone Version: 6.0.0rc1
- Plone REST API Version: 8.32.2

**Comment by davisagli** [comment]
@tiberiuichim @robgietema Any pointers where to look for this one?

**Comment by davisagli** [comment]
If I position the cursor in the middle of other existing non-space text, I can type a single space, but any subsequent spaces jump the cursor to the end of the field.

**Comment by tiberiuichim** [comment]
I'll take a look tomorrow.

**Comment by mauritsvanrees** [comment]
It is a problem on beta.plone.org as well, when adding a hotfix:
https://github.com/plone/plone.org/issues/35#issuecomment-1337873937
