### ISSUE TITLE
Upgrade some dependencies

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#4104]
I closed a bunch of PRs from bots:

https://github.com/plone/volto/pull/4078  [99 tag: dependencies](https://github.com/plone/volto/issues?q=is%3Apr+is%3Aopen+label%3A%2299+tag%3A+dependencies%22) Pull requests that update a dependency file[javascript](https://github.com/plone/volto/issues?q=is%3Apr+is%3Aopen+label%3Ajavascript)Pull requests that update Javascript code
#4078 opened 5 days ago by [dependabot](https://github.com/plone/volto/issues?q=is%3Apr+is%3Aopen+author%3Aapp%2Fdependabot) bot
[ 2](https://github.com/plone/volto/pull/4078)

https://github.com/plone/volto/pull/4077  [99 tag: dependencies](https://github.com/plone/volto/issues?q=is%3Apr+is%3Aopen+label%3A%2299+tag%3A+dependencies%22) Pull requests that update a dependency file[javascript](https://github.com/plone/volto/issues?q=is%3Apr+is%3Aopen+label%3Ajavascript)Pull requests that update Javascript code
#4077 opened 5 days ago by [dependabot](https://github.com/plone/volto/issues?q=is%3Apr+is%3Aopen+author%3Aapp%2Fdependabot) bot
[ 2](https://github.com/plone/volto/pull/4077)

https://github.com/plone/volto/pull/4065  [99 tag: dependencies](https://github.com/plone/volto/issues?q=is%3Apr+is%3Aopen+label%3A%2299+tag%3A+dependencies%22) Pull requests that update a dependency file[javascript](https://github.com/plone/volto/issues?q=is%3Apr+is%3Aopen+label%3Ajavascript)Pull requests that update Javascript code
#4065 opened 6 days ago by [dependabot](https://github.com/plone/volto/issues?q=is%3Apr+is%3Aopen+author%3Aapp%2Fdependabot) bot
[ 2](https://github.com/plone/volto/pull/4065)

https://github.com/plone/volto/pull/4031  [99 tag: dependencies](https://github.com/plone/volto/issues?q=is%3Apr+is%3Aopen+label%3A%2299+tag%3A+dependencies%22) Pull requests that update a dependency file[javascript](https://github.com/plone/volto/issues?q=is%3Apr+is%3Aopen+label%3Ajavascript)Pull requests that update Javascript code
#4031 opened 10 days ago by [dependabot](https://github.com/plone/volto/issues?q=is%3Apr+is%3Aopen+author%3Aapp%2Fdependabot) bot
[ 2](https://github.com/plone/volto/pull/4031)

https://github.com/plone/volto/pull/4030  [99 tag: dependencies](https://github.com/plone/volto/issues?q=is%3Apr+is%3Aopen+label%3A%2299+tag%3A+dependencies%22) Pull requests that update a dependency file[javascript](https://github.com/plone/volto/issues?q=is%3Apr+is%3Aopen+label%3Ajavascript)Pull requests that update Javascript code
#4030 opened 10 days ago by [dependabot](https://github.com/plone/volto/issues?q=is%3Apr+is%3Aopen+author%3Aapp%2Fdependabot) bot
[ 2](https://github.com/plone/volto/pull/4030)

https://github.com/plone/volto/pull/4029  [99 tag: dependencies](https://github.com/plone/volto/issues?q=is%3Apr+is%3Aopen+label%3A%2299+tag%3A+dependencies%22) Pull requests that update a dependency file[javascript](https://github.com/plone/volto/issues?q=is%3Apr+is%3Aopen+label%3Ajavascript)Pull requests that update Javascript code
#4029 opened 10 days ago by [dependabot](https://github.com/plone/volto/issues?q=is%3Apr+is%3Aopen+author%3Aapp%2Fdependabot) bot
[ 2](https://github.com/plone/volto/pull/4029)

https://github.com/plone/volto/pull/4020  [99 tag: dependencies](https://github.com/plone/volto/issues?q=is%3Apr+is%3Aopen+label%3A%2299+tag%3A+dependencies%22) Pull requests that update a dependency file[javascript](https://github.com/plone/volto/issues?q=is%3Apr+is%3Aopen+label%3Ajavascript)

**Comment by SaiRev0** [comment]
I would like to solve this issue please assign it to me

**Comment by tiberiuichim** [comment]
@SaiRev0 First, you need to be a member of the Plone Developers (sign the Contributers Agreement, etc). See the plone.org website for details

**Comment by SaiRev0** [comment]
@tiberiuichim Thanks for the information, I have emailed the pdf, so for the time being is there anything I can do other than waiting??

**Comment by tiberiuichim** [comment]
@SaiRev0 you can start working on the issue. The idea is that the bot cannot make the PRs, as it's not a member of the group. So you can make a PR that does all those minor dependency upgrades

**Comment by stevepiercy** [comment]
@SaiRev0 also review https://6.docs.plone.org/volto/developer-guidelines/contributing.html, and install Plone locally for development, if you have not yet done so.

**Comment by SaiRev0** [comment]
@stevepiercy Made a PR, please check and review it, and if it need some changes please inform me
