### ISSUE TITLE
Duplicate Text Block contents?

### ISSUE THREAD

**Issue by wesleybl** [plone/volto#4139]
**Describe the bug**
When we save a Text Block, the texts are duplicated in the json. One in a "plaintext" key and one in a "text" key. Does the Volto editor need to duplicate this text? This is bad for performance and bandwidth, as all text will be duplicated in the json response.

**To Reproduce**

1. Create a page with a text block.
2. Go to the network tab of the browser's development tool.
3. See the duplicate text in the api response json.

**Expected behavior**
No duplicate text

**Screenshots**
![Captura de tela de 2022-12-16 10-24-19](https://user-images.githubusercontent.com/3297795/208109604-051ef43c-3450-44fd-bec6-dd5743de3e5f.png)

**Software (please complete the following information):**

- Browser: Chrome
- Volto Version 6.4.0
- Plone Version 6.0.0
- Plone REST API Version 8.32.6

**Comment by davisagli** [comment]
I think the `plaintext` is currently needed for indexing the slate block contents in the SearchableText index: https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/indexers.py#L70

**Comment by tisto** [comment]
This is indeed the intended behavior.
