### ISSUE TITLE
Update redirect for https://docs.voltocms.com/ to https://6.docs.plone.org/volto on https://6.docs.plone.org/volto/

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#4148]
Update redirect for https://docs.voltocms.com/ to https://6.docs.plone.org/volto on https://6.docs.plone.org/volto/.

Requires access to configure the server or DNS that hosts voltocms.com.

Refs: https://github.com/plone/documentation/issues/1140

**Comment by vedant-z** [comment]
@stevepiercy I am willing to take this

**Comment by stevepiercy** [comment]
Sorry @vedant-z you do not have access to configure the server that hosts voltocms.com. Only someone with that access can make that configuration. I don't know who that is. @sneridagh?

**Comment by stevepiercy** [comment]
bump @sneridagh @tisto or whoever owns `voltocms.com`.

**Comment by polyester** [comment]
done, will take a bit to filter through cloudflare caching
