### ISSUE TITLE
`pathname` should be a required prop for Blocks/Block/Edit.jsx component

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#4194]
The Listing block depends on it. See for more required props: https://github.com/plone/volto/blob/master/src/components/manage/Blocks/Block/BlocksForm.jsx#L244

**Comment by KartikBudania** [comment]
Hello @tiberiuichim ,
Could you explain what exactly is the issue??
Do we need to add pathname as a required prop in Edit.jsx??

**Comment by tiberiuichim** [comment]
@KartikBudania yes, it should be marked as a required propType.

**Comment by akshatgarg12** [comment]
Can i work on this? @tiberiuichim

**Comment by tiberiuichim** [comment]
@akshatgarg12 Yes. Please see also https://6.dev-docs.plone.org/volto/developer-guidelines/contributing.html#create-a-pull-request

**Comment by akshatgarg12** [comment]
@tiberiuichim There are other props also which are not present in prop types of Edit block https://github.com/plone/volto/blob/master/src/components/manage/Blocks/Block/Edit.jsx#L42 other than pathname,  should all those be added as a required prop ?

**Comment by tiberiuichim** [comment]
@akshatgarg12 only if we know for sure that they're really required, if, for example, there's a block edit component that uses them.

**Comment by akshatgarg12** [comment]
@tiberiuichim EditDefaultBlock uses onChangeBlock and block from props, which are not present in prop types of edit block, https://github.com/plone/volto/blob/master/src/components/manage/Blocks/Block/DefaultEdit.jsx#L10, also blockConfig is used in EditBlock https://github.com/plone/volto/blob/master/src/components/manage/Blocks/Block/Edit.jsx#L69, should these also be added as required props?
