### ISSUE TITLE
YouTube videos redirect during linkcheck

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#4203]
> And there are still warnings for youtube links:

Looks like a GDPR issue. I don't see redirects in the US.

We could add youtube to the list of ignored links, or just be aware of it. There is [no open issue in Sphinx about GDPR compliance for linkcheck](https://github.com/sphinx-doc/sphinx/issues?q=linkcheck+gdpr).

Alternatively we could embed the YouTube videos with https://github.com/sphinx-contrib/youtube, as suggested by https://github.com/executablebooks/sphinx-book-theme/issues/354#issuecomment-1046319108, which would remove the links.

_Originally posted by @stevepiercy in https://github.com/plone/volto/issues/4181#issuecomment-1367878131_

**Comment by SaiRev0** [comment]
I would like to work on this issue

**Comment by stevepiercy** [comment]
@SaiRev0 the @plone/documentation-team first needs to discuss and decide how to proceed. Once that decision is made, then you are welcome to work on it. @ksuess @polyester opinions?

Meanwhile, have you signed the Plone Contributor Agreement and been able to build the docs locally? See https://6.docs.plone.org/contributing/index.html for details. Thank you!

**Comment by SaiRev0** [comment]
@stevepiercy I have filled and mailed the Agreement yesterday, but no response for it yet, and i have not setup it locally, so doing it now

**Comment by SaiRev0** [comment]
@stevepiercy Can you please explain the issue and What I have to do, Its a bit unclear

**Comment by stevepiercy** [comment]
I'm awaiting opinions of how to deal with this issue from the @plone/documentation-team. @polyester @ksuess I don't have enough experience with GDPR to have an informed opinion.

**Comment by polyester** [comment]
looks like sphinxcontrib-youtube has an easy way of setting the 'privacy mode which is a nice thing to do.
`..  youtube:: dQw4w9WgXcQ`
`   :privacy_mode:`

**Comment by stevepiercy** [comment]
Nice. I also found the PR and noted that there is a Do Not Track mode for Vimeo, in case we need it.

https://github.com/sphinx-contrib/youtube/pull/30

````md
```{eval-rst}
 .. vimeo:: 73214621
        :url_parameters: ?dnt=1
```
````

@SaiRev0 let's replace the links to the videos accordingly, and add this extension to Sphinx's `conf.py` and `requirements-docs.txt`. Then we can ask folks who are affected by the GDPR to check it.

This will also need to be applied to the main documentation repository.

**Comment by MohdAnas07** [comment]
I want to work on this issue please assign me this issue.

**Comment by ShubhamKhati** [comment]
I would like to work on this issue, can you please tell me how to get started.

**Comment by stevepiercy** [comment]
@MohdAnas07 @ShubhamKhati see my earlier comment.

> Meanwhile, have you signed the Plone Contributor Agreement and been able to build the docs locally? See https://6.docs.plone.org/contributing/index.html for details. Thank you!

See also: https://github.com/plone/documentation/issues/1452 which will be incorporated into documentation soon by me.

**Comment by stevepiercy** [comment]
@polyester would you please test this, now that https://github.com/plone/volto/pull/6486 was merged? Visit: https://volto--6486.org.readthedocs.build/tutorials/index.html

**Comment by stevepiercy** [comment]
@ksuess @polyester I think this is now fixed. Can you run `make linkcheckbroken` to verify? Sorry, I don't have a VPN in the EU to test this out. Thank you!

**Comment by polyester** [comment]
@stevepiercy currently not in the EU as well

**Comment by ksuess** [comment]
Running `make docs-linkcheckbroken` from Zurich, 
on a freshly checked out https://github.com/plone/volto/   branch `main`,
I get the following:

```
% make docs-linkcheckbroken
Symlink to Volto news created or updated.
/Users/katjasuss/Volto/volto/lib/python3.12/site-packages/sphinx/builders/linkcheck.py:86: RemovedInSphinx80Warning: The default value for 'linkcheck_report_timeouts_as_broken' will change to False in Sphinx 8, meaning that request timeouts will be reported with a new 'timeout' status, instead of as 'broken'. This is intended to provide more detail as to the failure mode. See https://github.com/sphinx-doc/sphinx/issues/11868 for details.
  warnings.warn(deprecation_msg, RemovedInSphinx80Warning, stacklevel=1)
/Users/katjasuss/Volto/volto/docs/source/news/6482.documentation: WARNING: document isn't included in any toctree
/Users/katjasuss/Volto/volto/docs/source/news/6485.bugfix: WARNING: document isn't included in any toctree
/Users/katjasuss/Volto/volto/docs/source/news/6486.documentation: WARNING: document isn't included in any toctree
/Users/katjasuss/Volto/volto/docs/source/news/6487.bugfix: WARNING: document isn't included in any toctree
( tutorials/index: line   80) redirect  https://www.youtube.com/playlist?list=PLGN9BI-OAQkQmEqf6O8jeyoFY1b2hD1uL - with Found to https://consent.youtube.com/m?continue=https%3A%2F%2Fwww.youtube.com%2Fplaylist%3Flist%3DPLGN9BI-OAQkQmEqf6O8jeyoFY1b2hD1uL%26cbrd%3D1&gl=CH&m=0&pc=yt&cm=2&hl=de&src=1
( tutorials/index: line   74) redirect  https://www.youtube.com/playlist?list=PLGN9BI-OAQkQDLQinBwdEXpebDTQCwdGi - with Found to https://consent.youtube.com/m?continue=https%3A%2F%2Fwww.youtube.com%2Fplaylist%3Flist%3DPLGN9BI-OAQkQDLQinBwdEXpebDTQCwdGi%26cbrd%3D1&gl=CH&m=0&pc=yt&cm=2&hl=de&src=1
( tutorials/index: line   57) redirect  https://www.youtube.com/playlist?list=PLGN9BI-OAQkQxqQcCZeJefMC8XlA_qv3Z - with Found to https://consent.youtube.com/m?continue=https%3A%2F%2Fwww.youtube.com%2Fplaylist%3Flist%3DPLGN9BI-OAQkQxqQcCZeJefMC8XlA_qv3Z%26cbrd%3D1&gl=CH&m=0&pc=yt&cm=2&hl=de&src=1
( tutorials/index: line   75) redirect  https://www.youtube.com/playlist?list=PLGN9BI-OAQkTJPayNdKIZ8lLDm5RVOLV3 - with Found to https://consent.youtube.com/m?continue=https%3A%2F%2Fwww.youtube.com%2Fplaylist%3Flist%3DPLGN9BI-OAQkTJPayNdKIZ8lLDm5RVOLV3%26cbrd%3D1&gl=CH&m=0&pc=yt&cm=2&hl=de&src=1
make: *** [Makefile:119: docs-linkcheckbroken] Error 1

```

**Comment by ksuess** [comment]
Can I test something else?

**Comment by kmahesh18** [comment]
❯ make docs-linkcheckbroken
Symlink to Volto news created or updated.
/home/mahesh/volto/lib64/python3.10/site-packages/sphinx/builders/linkcheck.py:86: RemovedInSphinx80Warning: The default value for 'linkcheck_report_timeouts_as_broken' will change to False in Sphinx 8, meaning that request timeouts will be reported with a new 'timeout' status, instead of as 'broken'. This is intended to provide more detail as to the failure mode. See https://github.com/sphinx-doc/sphinx/issues/11868 for details.
  warnings.warn(deprecation_msg, RemovedInSphinx80Warning, stacklevel=1)
/home/mahesh/volto/docs/source/news/6482.documentation: WARNING: document isn't included in any toctree

got this Running make docs-linkcheckbroken from Hyderabad

**Comment by stevepiercy** [comment]
> Can I test something else?

Oh, duh. My mistake, of course linkcheck won't check this directive, as there is no link for it to check.

````markdown
```{youtube} kHec4MXH8vo
:privacy_mode:
:width: 100%
```
````

@ksuess, since you're in the EU, there are two things to check.

1. Check whether the result of viewing this rendered page results in a GDPR warning (or whatever cookie stuff gets thrown at EU residents). I just pushed this page to production so it has the new rendered directive.

   https://6.docs.plone.org/volto/tutorials/index.html

   Its `iframe` has this: `src="https://www.youtube-nocookie.com/embed/kHec4MXH8vo"`.

   The following earlier PR preview has the previous `<iframe>` version, for comparison:

   https://plone6--1757.org.readthedocs.build/volto/tutorials/index.html

2. For this line:

   ```console
   ( tutorials/index: line   80) redirect  https://www.youtube.com/playlist?list=PLGN9BI-OAQkQmEqf6O8jeyoFY1b2hD1uL - with Found to https://consent.youtube.com/m?continue=https%3A%2F%2Fwww.youtube.com%2Fplaylist%3Flist%3DPLGN9BI-OAQkQmEqf6O8jeyoFY1b2hD1uL%26cbrd%3D1&gl=CH&m=0&pc=yt&cm=2&hl=de&src=1
   ```

   Can you edit the URL to:

   ```
   https://www.youtube-nocookie.com/embed/playlist?list=PLGN9BI-OAQkQmEqf6O8jeyoFY1b2hD1uL
   ```

   ...and run linkcheck to see if that one still redirects? If this test works, then we can do a global find and replace. Otherwise we'll need to leave this ticket open. I'd prefer to find a different video host that does not profit from our personal information.

Thank you!

**Comment by stevepiercy** [comment]
@kmahesh18 see https://6.docs.plone.org/volto/contributing/documentation.html#warnings-from-make-docs-commands.

**Comment by ksuess** [comment]
I am not in the EU, but Switzerland. As I see the EU cookie consent popup when visiting youtube, it makes sense that I do the tests.
![grafik](https://github.com/user-attachments/assets/27bc3427-79cf-49f7-a8fe-fb057cd2e737)


1. The embedded video is shown properly without any cookie dialog.
![grafik](https://github.com/user-attachments/assets/59a1771d-2a74-464a-8ea7-cb2fc994a20f)
It's good to use the https://www.youtube-nocookie.com/embed/kHec4MXH8vo
Even better for privacy would be to use the `https://www.youtube-nocookie.com/embed/VIDEO_ID?privacy_mode=1`
_Add the privacy_mode=1 parameter to the embed URL. This parameter further enhances privacy by ensuring YouTube doesn't store user information or track their activity while watching the embedded video._ 
See https://usercode.de/blog/how-to-embed-youtube-videos-with-maximum-privacy-gdpr-compliant#2-enable-privacy-mode
So this is the code to achieve it:

````
```{youtube} kHec4MXH8vo
:privacy_mode:
:url_parameters: ?privacy_mode=1
:width: 100%
```
````

**Comment by stevepiercy** [comment]
@ksuess thanks for the thorough testing and PR!
