### ISSUE TITLE
Fix: Update 2022 to 2023 in main page

### ISSUE THREAD

**Issue by punithnayak** [plone/volto#4205]
![Screenshot_20230101_071750](https://user-images.githubusercontent.com/110713318/210158983-32679b80-a2d3-460f-8430-48d6d8bf0cee.png)
Change the year 2022 to 2023 in the following line of the main page

"2022 - Volto Team - Plone Foundation"

**Comment by stevepiercy** [comment]
Where did you find this?

**Comment by punithnayak** [comment]
![image](https://user-images.githubusercontent.com/110713318/210159262-062bb6d1-6291-4f65-9e96-1cf318fb0ea0.png)

http://localhost:3000/

**Comment by stevepiercy** [comment]
This value is dynamically set when a site is created, as shown in:

https://github.com/plone/plone.volto/blob/2b783c96c140f35083231152270597b741c070cb/src/plone/volto/default_homepage/default.py#L239

It is not a bug.
