### ISSUE TITLE
Select widget steals focus

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#4230]
Tested on demo.plone.org, 

Volto 16.5.0
Plone 6.0.0
plone.restapi 8.32.6
CMF 2.6.0
Zope 5.7.3
Python 3.11.1 (main, Dec 8 2022, 00:19:30) [GCC 10.2.1 20210110]
PIL 9.3.0 (Pillow)
Add-ons
@plone/volto-slate 16.5.0
@kitconcept/volto-blocks-grid 5.2.0

[vokoscreenNG-2023-01-05_14-08-26.webm](https://user-images.githubusercontent.com/141568/210777044-338b6577-f744-4009-aadc-6b48d510300c.webm)

**Comment by sneridagh** [comment]
@reebalazs It seems that this is still happening under some instantiations of the select widgets. 

@avoinea as we talked during the Volto Team Meeting, could you please coordinate the efforts to fix this?
