### ISSUE TITLE
nothing can be clicked, iframe covering the page due to a react-error-overlay bug

### ISSUE THREAD

**Issue by reebalazs** [plone/volto#4242]
**Describe the bug**

In devmode, nothing is clickable on the site. This occurs due to a bug
in react-error-overlay that displays an iframe that covers the whole
page and steals the focus. At the same time, there is an error appearing
in the console:

`ReferenceError: process is not defined`

The solution is to upgrade react-error-overlay.

This issue is [referenced here](https://stackoverflow.com/questions/70368760/react-uncaught-referenceerror-process-is-not-defined). Also described in details https://github.com/facebook/create-react-app/issues/11773.

**To Reproduce**

Unknown. Just happened persistently in devmode on a site I worked on.

**Expected behavior**

Site should be clickable.

**Screenshots**

No

**Software (please complete the following information):**

- Volto Version: 16.6.0 , newest at time
- Any browser (FF or Chrome confirmed)
- Any OS

**Additional context**

No

**Comment by reebalazs** [comment]
Fixed in https://github.com/plone/volto/pull/4243

**Comment by SanjeevSingh08** [comment]
Why these issues are still opened if already fixed
