### ISSUE TITLE
Search block saving facet field label wrongly.

### ISSUE THREAD

**Issue by iRohitSingh** [plone/volto#4255]
We are directly saving the facet field label value directly to backend where as we have to only save the value and in fronted we have to generate the level.

steps to reproduce
1. create a page
2. create a search block
3. add a facet
4. select any field
5. see the response 
6. we are directly saving the label and value.

Screenshot

<img width="708" alt="imageforfield" src="https://user-images.githubusercontent.com/61353484/212354311-ecd9bbd1-e163-408b-a181-1cc6306acb6e.png">

**Comment by avoinea** [comment]
This is a generic issue of the Select widget when used with Form schema 🙈

**Comment by davisagli** [comment]
Fixed in https://github.com/plone/volto/pull/4306
