### ISSUE TITLE
contentExpand-able reducers should also be executed on the GET_CONTENT_SUCCESS action

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#4264]
**Is your feature request related to a problem? Please describe.**

It's possible to piggy-back the content load network call to load additional information, using the content expanders mechanism. The problem is that, while this works very well in practice for custom reducers, those that ship with default Volto <16.6 (current version) are less useful, as they don't get executed (they don't switch) on the `GET_CONTENT` action.

**Describe the solution you'd like**

I want them modified so that they're also aware of the `GET_CONTENT` action.

**Comment by akshatgarg12** [comment]
What would be the return state if its a sub-request , just the `initialState`?

**Comment by tiberiuichim** [comment]
@akshatgarg12 sneridagh worked on this issue in https://github.com/plone/volto/pull/4285

This issue will be closed very soon, once that PR is merged (as that is finished).
