### ISSUE TITLE
Slate json without the text node throwing error.

### ISSUE THREAD

**Issue by iFlameing** [plone/volto#4265]
screenshot of error.

![Screenshot 2023-01-17 at 8 32 54 PM](https://user-images.githubusercontent.com/33936987/212933543-dcfa006c-ff24-442c-86cf-70f6501a201d.png)

Problemtic code 

```
{
      "type": "span",
      "children": []
    
 }
     
 ```
     
     
 if someone copying and pasting from another website we might run in this type of json. During saving it doesn't give any problem but when we are saving and try to edit the page it is throwing the error.
     
     
 Schema

Blocks
 
```

{
 "2e77ee8c-2689-45b0-9dd9-fb81289e2a2e": {
  "@type": "slate",
  "plaintext": " aber auch von Fahrzeugen ausgetauscht werden.",
  "value": [
   {
    "children": [
     {
      "children": [
       {
        "text": ""
       }
      ],
      "type": "span"
     },
     {
      "children": [
       {
        "text": "aber auch von Fahrzeugen ausgetauscht"
       }
      ],
      "type": "span"
     },
     {
      "children": [
       {
        "text": "werden."
       }
      ],
      "type": "span"
     },
     {
      "type": "span",
      "children": []
     }
    ],
    "type": "p"
   }
  ]
 },
 "9e986f19-5327-47fb-9fb4-95f7ee58fbde": {
  "@type": "title"
 }
}

```

Blocks layout

```

{
 "items": [
  "9e986f19-5327-47fb-9fb4-95f7ee58fbde",
  "2e77ee8c-2689-45b0-9dd9-fb81289e2a2e"
 ]
}

````

**Comment by iFlameing** [comment]
@tiberiuichim can you guide me in the correct path to how we can handle this empty children array during the saving of page?

**Comment by tiberiuichim** [comment]
https://github.com/plone/volto/blob/master/packages/volto-slate/src/editor/extensions/insertData.js#L40

**Comment by iFlameing** [comment]
@tiberiuichim can this type of JSON be generated by migration also or it could happen only by copy-paste? I am not pretty sure how in the first place we are able to get this JSON in Plone's backend. Do you have any guesses because reading insertdata.js code and I think it is handling the null case for `spanTagDeserializer`

**Comment by davisagli** [comment]
I checked the page that @iFlameing was debugging here. I am pretty sure it came from an old version of blocks-conversion-tool and is not a bug in volto.

**Comment by iFlameing** [comment]
I am closing this since we know how it got at first place.
