### ISSUE TITLE
Grammar fix for #4260

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#4272]
I don't monitor Volto PRs closely, so I missed this error in #4260:

`Here some examples of useful ones`

s/b

`Here are some examples of useful ones`

**Comment by shubhamtalesara** [comment]
can I take this one?

**Comment by stevepiercy** [comment]
yes, please!

**Comment by shubhamtalesara** [comment]
just a min

**Comment by SanjeevSingh08** [comment]
Is this issue closed? if not i would like to take this one

**Comment by manav-06** [comment]
Hi, @stevepiercy , I would like to take this

**Comment by stevepiercy** [comment]
In the Plone organization, you do not need to ask to be assigned to or to work on an open issue. Instead please assign yourself to the issue by selecting , signaling that you are working on it, then start working on it.

Upper right corner, click the gear icon.

![Screen Shot 2023-01-22 at 12 45 38 AM](https://user-images.githubusercontent.com/102112/213907507-9c5b31fe-8826-4d47-835d-30e60c0fadf1.png)

Select your username.

![Screen Shot 2023-01-22 at 12 47 00 AM](https://user-images.githubusercontent.com/102112/213907558-7c91b493-3647-4124-8d3c-7f4b5cc3efa3.png)

Thank you!

**Comment by Amit-Morade** [comment]
@SaiRev0 are you working on this issue?

**Comment by stevepiercy** [comment]
@Amit-Morade please proceed. I consider it abandoned after a week of no response for a trivial fix, per https://github.com/plone/volto/pull/4297#issuecomment-1407550484. Thank you!

**Comment by SaiRev0** [comment]
@stevepiercy Actually I was ill for the past week so I was not able to do any work, but now I m back so I will complete this pr today Itself
