### ISSUE TITLE
Slug based linked headlines in volto-slate

### ISSUE THREAD

**Issue by nileshgulia1** [plone/volto#4298]
## Abstract

Add a anchor link target to headings(h1,h2,h3,h4) in volto-slate.

## Motivation

We often came across situations where we might want to direct a user to specific section/heading(h1,h2,h3,h4) in a page. We need an ability to create those anchors links within headings written in volto-slate. 

## Assumptions

For every new widget/block, UniversalLink component should be used for rendering links.

## Proposal & Implementation

Proposal is to display a link button when hovering on a specific heading in volto-slate hitting which creates an anchor based on slugiffied **heading title** and stored as an id attribute on an element. IMO, this is a most useful basic feature missing in a modern day CMS and quite a common solution on many sites.

Example: https://learn.microsoft.com/en-us/power-platform/alm/overview-alm#what-is-alm
` <h2 id="introduction-to-everything">Introduction to everything</h2>`

## Deliverables
- [x] link svg on hover headings
- [x] sluggified anchors based on heading title
- [x] `github-slugger` npm package
- [ ] Existing blocks toc, links?
- [ ] What about the title block?
- [ ] Css and animations on scroll
- [x] UniversalLink component now uses `react-router-hash-link`
- [ ] Cypress tests

## Risks
- Using sluggified anchors can break existing blocks such as TOC and other widgets which are based on block uids.
- What will happen to slug if headings are modified? and/or existing headings?
- Could be a potential breaking change?
- opt-in feature?

## Participants
- @tiberiuichim https://github.com/plone/volto/pull/3540
- @nileshgulia1 https://github.com/plone/volto/pull/4287

To be discussed in next @plone/volto-team meeting.

**Comment by stevepiercy** [comment]
How would you handle hover states on mobile devices without a mouse? Tap and hold?

**Comment by tiberiuichim** [comment]
@stevepiercy on mobile, the headline links should be visible directly (not hidden), similar to the way github does it.

**Comment by nileshgulia1** [comment]
For the record, this is how the current implementation looks

**mobile**:
![Screenshot 2023-01-23 at 3 05 02 PM](https://user-images.githubusercontent.com/22280901/214042337-8cdc476e-de8c-4225-8739-0fe3dc3b3375.png)

**Desktop**:
![Screenshot 2023-01-23 at 6 21 56 PM](https://user-images.githubusercontent.com/22280901/214044387-251617ec-42bc-4fe2-89a4-57013893ca3d.png)

The title block isn't a part of this feature yet as it doesn't support rich text editing. We might also need to modify https://github.com/plone/volto/blob/linkedHeadlinesRefactor/src/components/manage/Blocks/Title/Edit.jsx#L146

**Comment by rakshith6404** [comment]
I would like and am planning to contribute to this project/idea as a contributor and an aspirant of GSoC'23,

Looking forward for the solution needed and making a detailed proposal for the same is what i am planning to get going to this project,I have started to work on this issue and have some deliverables from my side which i have stated in the proposal.

As in the part of Risks @nileshgulia1 haas stated ;

> Using sluggified anchors can break existing blocks such as TOC and other widgets which are based on block uids.

I have a solution to this issue and have started writing my proposal regarding the same.

**I am looking forward for the mentors cc: @tiberiuichim @nileshgulia1 and the mentor of this Project/idea to guide me through it and also could the CCs Please guide me how to start contributing to this issue.Should i just submit the proposal when the timeline for the submission for the project starts??**

**Comment by sneridagh** [comment]
@plone/volto-team This is how Confluence is implementing it, and I kind of like it:


https://user-images.githubusercontent.com/486927/229339076-5da723da-adfa-44d2-b3b5-5d69cb603e9b.mov

**Comment by tiberiuichim** [comment]
@sneridagh can you do a test with a multiline headline? I wonder how they treat this case, if the link icon is inline with the end of the text, or at the side.

**Comment by sneridagh** [comment]
At the end of the text:

https://user-images.githubusercontent.com/486927/229340509-39bfda49-0ddb-4b05-84d7-dbfef4bf54a2.mov

**Comment by sneridagh** [comment]
Closing as completed in #3540

**Comment by tisto** [comment]
@nileshgulia1 @tiberiuichim @avoinea @sneridagh I am currently writing the roadmap for Plone 6.x and I try to include links to the documentation of a new feature. So far I only found:

https://6.docs.plone.org/volto/configuration/volto-slate/index.html
https://6.docs.plone.org/volto/configuration/volto-slate/configuration-settings.html#slate-uselinkedheadings

Is this everything we got/need?

**Comment by nileshgulia1** [comment]
@tisto That's only what I found. It would be nice to mention it in the user manual as well.

**Comment by tisto** [comment]
@nileshgulia1 could you imagine working on some user docs for this feature?

**Comment by tisto** [comment]
@nileshgulia1 any update on the docs for this feature? I just realized that we released Plone 6.1 without having docs for this new feature. cc @stevepiercy @sneridagh @plone/volto-team

**Comment by stevepiercy** [comment]
@tisto @nileshgulia1 here's the issue I opened almost one year ago, asking for docs.

https://github.com/plone/volto/issues/5755

**Comment by nileshgulia1** [comment]
@stevepiercy I opened a relevant PR: https://github.com/plone/volto/pull/6750
