### ISSUE TITLE
Volto Mail Control Panel has no "send test email and save configuration" button/option

### ISSUE THREAD

**Issue by tisto** [plone/volto#4300]
**Describe the bug**

The Plone Classic Mail Control Panel has a "send test email and save configuration" button that the Volto control panel currently lacks.

**To Reproduce**

1. As admin
2. Go to http://localhost:3000/controlpanel/mail
3. There is no button to test the email settings

**Comment by tiberiuichim** [comment]
@tisto Duplicate of #3791 ?

**Comment by tisto** [comment]
@tiberiuichim yes. sorry for the noise. closing this ticket.
