### ISSUE TITLE
Pasting something in Table Block is throwing error

### ISSUE THREAD

**Issue by iFlameing** [plone/volto#4301]
**Describe the bug**

Paste something in table block. Nothing happens because it throws a error in console.

**To Reproduce**

1. Create a page
2. Add a table block
3. Paste something in the table block

**Expected behavior**
I am able to see the pasted data.
**Screenshots
![Screenshot 2023-01-23 at 8 35 18 PM](https://user-images.githubusercontent.com/33936987/214074146-e45b8e34-7d20-4197-aa95-cc04fe0288f2.png)
**

**Software (please complete the following information):**

- OS: [e.g. iOS] ios
- Browser [e.g. chrome, safari] chrome
- Volto Version [e.g. 8.5.0] latest
- Plone Version [e.g. 5.2.2] latest
- Plone REST API Version [e.g. 7.0.1] latest

**Comment by parteekcoder** [comment]
hi I would like to take this issue

**Comment by stevepiercy** [comment]
@parteekcoder In the Plone organization, you do not need to ask to be assigned to or to work on an open issue. Instead please assign yourself to the issue by selecting your username, signaling that you are working on it, then start working on it.

Also read this: https://6.docs.plone.org/volto/developer-guidelines/contributing.html#create-a-pull-request

Upper right corner, click the gear icon.

![Screen Shot 2023-01-22 at 12 45 38 AM](https://user-images.githubusercontent.com/102112/213907507-9c5b31fe-8826-4d47-835d-30e60c0fadf1.png)

Select your username.

![Screen Shot 2023-01-22 at 12 47 00 AM](https://user-images.githubusercontent.com/102112/213907558-7c91b493-3647-4124-8d3c-7f4b5cc3efa3.png)

Thank you!

**Comment by parteekcoder** [comment]
That option is not available

**Comment by parteekcoder** [comment]
Is plone participating in GSoC this year?

**Comment by stevepiercy** [comment]
> Also read this: https://6.docs.plone.org/volto/developer-guidelines/contributing.html#create-a-pull-request

> Is plone participating in GSoC this year?

Yes. See https://plone.org/community/gsoc

**Comment by parteekcoder** [comment]
[image: Screenshot_20230124_140242.png]

so how will i assign myself , i don't have the access to do that
it is not showing any option to add username on clicking or hovering

**Comment by stevepiercy** [comment]
Do you see a link "assign yourself" near the top on the right?

![Screen Shot 2023-01-24 at 1 54 04 AM](https://user-images.githubusercontent.com/102112/214261380-6e7fa9c7-1da1-43e5-bd11-1d41a5bf29bd.png)

Please take a screenshot of what you see there and paste that here.

See also https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users
