### ISSUE TITLE
Add option to add action button to the top of the toolbar and menu button to the bottom of the toolbar.

### ISSUE THREAD

**Issue by ksuess** [plone/volto#4333]
Option to add action button to the top of the toolbar.
Option to add menu button to the bottom of the toolbar.

**Comment by geekaryan** [comment]
@ksuess Can I work on this issue..!

**Comment by ksuess** [comment]
You are welcome to contribute to any issue, @geekaryan. 
This issue is taken. You can see if an issue is taken by the linked pull request.
I'm a bit clueless which other issues to recommend. Maybe you want to write some or more words on your fields of interest on https://community.plone.org/ ?

**Comment by geekaryan** [comment]
sure.. I will represnt my thoughts there.. thank you

**Comment by stevepiercy** [comment]
@geekaryan to determine whether an issue is already being worked on, you can check whether there is a linked pull request as @ksuess mentioned or if someone is assigned to the issue.

In the Plone organization, you do not need to ask to be assigned to or to work on an open issue. Instead please assign yourself to an available issue by selecting your username, signaling that you are working on it, then start working on it.

Also read this: https://6.docs.plone.org/volto/developer-guidelines/contributing.html#create-a-pull-request

To assign yourself to an issue, in the upper right corner, click the gear icon.

![Screen Shot 2023-01-22 at 12 45 38 AM](https://user-images.githubusercontent.com/102112/213907507-9c5b31fe-8826-4d47-835d-30e60c0fadf1.png)

Select your username.

![Screen Shot 2023-01-22 at 12 47 00 AM](https://user-images.githubusercontent.com/102112/213907558-7c91b493-3647-4124-8d3c-7f4b5cc3efa3.png)

Thank you!

**Comment by geekaryan** [comment]
@stevepiercy Thanks alot for helping me out. I will assign myself a issue if I found that I am able to complete it. Again thank you ..
