### ISSUE TITLE
Listing block should never be passed folder contents, if it has a query

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#4351]

**Comment by tiberiuichim** [comment]
https://github.com/plone/volto/blob/0f84668688ce1d69030d2769d32a01d7dde28964/src/components/manage/Blocks/Listing/withQuerystringResults.jsx#L51

the ` && querystringResults?.[block]` should not be there.

**Comment by wesleybl** [comment]
If #3866 it's approved, he'll sort it out.
