### ISSUE TITLE
Button UI and Carousel play/pause

### ISSUE THREAD

**Issue by Vansh-Baghel** [plone/volto#4359]
UI issue
Button UI is really not good for a professional website. The carousel could be played infinite times, so there no point of adding pause button as a user can even go back using arrows.

**Solution**
A clear and concise description of what you want to happen.I was hoping for contribution but the code base is too weird to understand as I do not see any direct installation way or to implement CSS directly. 
Increase the padding and font-size to 1 rem in all buttons. 
**Additional context**

**_From this_** :
![before-img](https://user-images.githubusercontent.com/103327712/216763381-e026f11d-4d8c-49b4-99fe-2d96521eb57e.png)

**_To this_** :
![after-img](https://user-images.githubusercontent.com/103327712/216763394-68448762-3d26-4e26-9844-a11bef265a24.png)

**Comment by stevepiercy** [comment]
@Vansh-Baghel I don't think this is an issue with Volto, but instead the plone.org website only. Can you verify? If so, please open an issue in that repository at https://github.com/plone/plone.org.

**Comment by Vansh-Baghel** [comment]
@stevepiercy Oh you are right! In plone repository, I am not able to install the dependencies using npm install , npm install --force , yarn install. Nothing worked.

**Comment by tiberiuichim** [comment]
@Vansh-Baghel `cd frontend`

**Comment by stevepiercy** [comment]
I don't have access to transfer this issue to the proper repo. I am closing it here. @Vansh-Baghel please open a new issue in the correct repo. Thank you!

**Comment by Vansh-Baghel** [comment]
> @Vansh-Baghel `cd frontend`

Yes, I did that but it shows this after almost getting completed 

![ss1](https://user-images.githubusercontent.com/103327712/216787760-5316f5bf-8079-4aed-acec-95d73ecea143.png)

**Comment by stevepiercy** [comment]
@Vansh-Baghel for support, please post to https://community.plone.org/. 

See also
https://meta.stackoverflow.com/questions/285551/why-should-i-not-upload-images-of-code-data-errors
