### ISSUE TITLE
OK page for Volto

### ISSUE THREAD

**Issue by erral** [plone/volto#4375]
**Is your feature request related to a problem? Please describe.**
In Plone we currently have the `@@ok` view where Plone returns a simple `OK` message to signal that it is alive and thus this URL can be used in load-balancers or keep-alive services to check that the website is running.

We do not have such a feature in Volto and in some cases if the back-end is not exposed the only way to check if the website is alive is to hit the front-page or some other pages.

**Describe the solution you'd like**
I would like to have a non content route called `ok` in Volto, that renders a component that simply returns `OK` like the Plone one does. This way this URL can be added to any service checking the status of the site.

**Comment by tiberiuichim** [comment]
@erral would this be strictly nodejs level or should it also use React to render the message?

**Comment by erral** [comment]
I don't know the internals... I made some tests yesterday and I didn't manage to render just a `OK` message, all the header and the footer of the page was also rendered.

If this has to be a nodejs thing instead of a React Component, I'm fine with it.

**Comment by tiberiuichim** [comment]
@erral 

There's two routers and levels where this could be implemented.

The first is the [express router](https://github.com/plone/volto/blob/master/src/server.jsx#L78) where it could be implemented as a simple express middleware. This would be really fast, but would not use React to render the response.

The second is the [react-router level](https://github.com/plone/volto/blob/master/src/routes.js#L317), where react could be used to implement a simple component. This is potentially slower, but maybe more corect in asserting functioning status.

**Comment by erral** [comment]
I tried the second one yesterday, will try to add a PR.

**Comment by AishwaryaRavi07** [comment]
Hey, I would like to work on this issue, could you please help me understand the issue in a bit more detail?

**Comment by erral** [comment]
I think that all the details are describe abive, in the issue. If there is something you dont't understand I will be happy to answer2your questions
