### ISSUE TITLE
The Site setup… page is not responsive for small screen devices

### ISSUE THREAD

**Issue by lord2anil** [plone/volto#4484]
The Site setup… page is not responsive for mobile devices,
see video

https://user-images.githubusercontent.com/97228857/223721261-55f2bc25-9557-407c-b811-ca997a805b93.mp4

**Expected behavior**
See the Site setup page of  Plone classic ui

https://user-images.githubusercontent.com/97228857/223721650-96efd065-f8a5-4e2b-85e0-9c4aca8d0548.mp4

**Comment by stevepiercy** [comment]
Does Volto have breakpoint classes like Classic UI?

I notice that the HTML markup in Classic UI uses `<ul><li>` with Twitter Bootstrap breakpoint classes compared to Volto's `<div class="six">`.

Is there a design guide for Volto markup? That might help identify a good solution.

**Comment by lord2anil** [comment]
sir i raised a PR please have a look , https://github.com/plone/volto/pull/4487#issue-1615437800

**Comment by stevepiercy** [comment]
Thanks. GitHub user tip: in the PR, add the text "Closes #4484". Then when that PR is merged, it will automatically close this issue. You can edit your original comment, instead of adding a new comment, and it will work.
