### ISSUE TITLE
Typo found in idea list

### ISSUE THREAD

**Issue by Vansh-Baghel** [plone/volto#4491]
**Describe the bug**
There is a typing mistake in the idea list website. The Markdown link is looking like normal text. 

**To Reproduce**
Replace : (TanStack Query)[https://tanstack.com/query] 
With : [TanStack Query](https://tanstack.com/query)

Link : https://plone.org/community/gsoc/2023

**Screenshots**
![gg1](https://user-images.githubusercontent.com/103327712/224080008-0601b427-79eb-4323-b13c-d856ae25235a.png)

**Software (please complete the following information):**

- Volto Version [e.g. 8.5.0]
- Plone Version [e.g. 5.2.2]
- Plone REST API Version [e.g. 7.0.1]

**Additional context**

**Comment by AbhishekCS3459** [comment]
@Vansh-Baghel Can I go for it??

**Comment by Vansh-Baghel** [comment]
> @Vansh-Baghel I can solve this issue please assign it to me.

This part is not from this repository. We would have to wait for developers' response for it.

**Comment by stevepiercy** [comment]
Wrong repo. Please open an issue in https://github.com/plone/plone.org

**Comment by davisagli** [comment]
@stevepiercy In case you didn't know, you can transfer an issue to the correct repo using the "Transfer issue" link in the right sidebar.

**Comment by stevepiercy** [comment]
@davisagli I tried, but plone.org is not listed for some reason. Perhaps I lack sufficient access to that repo? Do you have access?
