### ISSUE TITLE
Revisit i18n story for "all in with add-ons" approach.

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#4495]
We should review the whole approach for the all-in with add-ons (no project config) approach while developing.

Issue:

If you want to override translations, we should review the order in which the add-ons translations are applied in the main project, using the i18n script.

https://github.com/plone/volto/blob/636149b2582dbb3492820b6a2f67eff53f84f967/packages/scripts/i18n.cjs#L149-L165

**Comment by tiberiuichim** [comment]
you need to follow the `getAddonDependencies`. The addons list itself is not ordered.
