### ISSUE TITLE
Unresponsive Add Page for the File, Image and Link

### ISSUE THREAD

**Issue by sudhanshu1309** [plone/volto#4506]
**The page for adding File, Image, and Link is unresponsive for mobile devices**

**To Reproduce**
This can be seen in changing the device width to 375px or similar.

**Expected behavior**
The Page should be responsive for all device widths.

**Screenshots**

**_Before_**

<img width="320" alt="Screenshot 2023-03-10 at 3 56 53 PM" src="https://user-images.githubusercontent.com/85515381/224538791-c9a77f1c-121c-4cc0-a515-6ad004d5b6b1.png">

**_After_**
<img width="320" alt="Screenshot 2023-03-12 at 2 54 55 PM" src="https://user-images.githubusercontent.com/85515381/224538810-86ea632a-dbb5-439d-a4f7-ad08cdd7692d.png">

**Software:**

- OS: any
- Browser: any

**Comment by mandliyarajendra11** [comment]
some for this - 
![Screenshot (33)](https://user-images.githubusercontent.com/119125519/224631257-085effc6-6a3f-40cf-b759-88eddefe1e44.png)

**Comment by saadkhan011** [comment]
Hi, 
  Is this issue still open Can I Work on this?
