### ISSUE TITLE
Remove `is-url` dependency

### ISSUE THREAD

**Issue by sudhanshu1309** [plone/volto#4543]
**Remove _is-url_ dependency**

A dependency can be removed by adding some regex expressions.
This library is checking for the passed URL is a correct URL or not!

My approach is to remove this dependency and add a file with same functionality by writing some regex expressions.

**Comment by davisagli** [comment]
I would not spend the effort on this unless there is a significant improvement in the size of the bundled js, or some other reason we should not use `is-url`.

**Comment by davisagli** [comment]
Closing the issue since I don't see an important reason to remove the dependency. Please reopen if you can point to a specific problem with `is-url` that needs to be addressed.
