### ISSUE TITLE
Should use location.assign rather then location.replace

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#4550]
https://github.com/plone/volto/blob/15b83f26e21b87acaf058fca0ac6016aa3b06f22/src/middleware/blacklistRoutes.js#L21

https://stackoverflow.com/questions/4505798/difference-between-window-location-assign-and-window-location-replace

**Comment by saadkhan011** [comment]
Hi tiberiuichim,
     I want to work on this issue can you assign me this issue so I can start.
Thanks

**Comment by Krishpanchal** [comment]
Hi tiberiuichim, I can work on this issue. You can assign this issue to me.
Thanks

**Comment by Darkcoder011** [comment]
i think You Don't Do that Because 
replace :- will replace the current document and replace the current History with that URL
assign:- will just cause a new document to load

@tiberiuichim

**Comment by Coder-aadarsh** [comment]
Generally location.assign is typically used to navigate to a new URL, while location.replace is used to replace the current URL with a new one.

If the goal is to allow the user to navigate to a new page while preserving the current page in their browser history, then location.assign may be more appropriate. If the goal is to replace the current page in the browser history with a new one, then location.replace may be more appropriate i guess

**Comment by tiberiuichim** [comment]
honestly, I don't understand the difference. I'm the one that wrote the original code, `window.replace()`.

What is the impact for the browser history? What's the practical difference? As far as we can say, window.replace worked fine till now.

**Comment by Darkcoder011** [comment]
the  difference is assign is used to navigate new url but the difference replace the current URL with a new one

**Comment by tiberiuichim** [comment]
@Darkcoder011 but from a practical point of view, what happens?

Because even with window.replace, the back button works in the browser. So, it it a case that the last entry from the "list of urls I've visited" is removed and replaced with the new one? And if I use assign, that doesn't happen?

**Comment by Darkcoder011** [comment]
@tiberiuichim  yes both redirect to new page .
they both do the same job but in difference manner and both have a difference 

when we use assign they can load a new page  

but when we use replace they directly replace that page 

you can see below 
for assign:-
document.location.href = 'http://frontbackend.com'; // go to  homepage
document.location.assign('http://frontbackend.com/Frontend'); // loads a new page

for replace :- 
document.location.href = 'http://frontbackend.com'; // go to  homepage
document.location.replace('http://frontbackend.com/Frontend');  // replace to another webpage

**Comment by Darkcoder011** [comment]
and in practical  point of view they both do same job but in difference manner they both have their own methods 
@tiberiuichim

**Comment by stevepiercy** [comment]
If I understand this correctly, it depends on whether you want the user to be able to use the back button or use history to go back to the immediately preceding document. Both back button and history would still work for all other locations that do not use `replace()`.

For login/logout, I would not want the user to go back. I would use [`location.replace()`](https://developer.mozilla.org/en-US/docs/Web/API/Location/replace). I might want to use this when adding, editing, or deleting content as well, and possibly throughout the entire authenticated and authorized session.

Where I don't care or I want the user to use the back button or history, I would use [`location.assign()`](https://developer.mozilla.org/en-US/docs/Web/API/Location/assign).

**Comment by djay** [comment]
@tiberiuichim I suspect this is the code responsible for updating the browser url when p.a.redirector happens on a restapi. in this case you probably don't want the the user to go back to the incorrect url old url so replace would make most sense?

**Comment by davisagli** [comment]
Replace makes sense here. Otherwise the user will get into a loop if they try to navigate back after getting redirected by this.
