### ISSUE TITLE
User control panel improvements

### ISSUE THREAD

**Issue by erral** [plone/volto#4551]
## Abstract

We need some changes in the current Volto user controlpanel to be able to handle users efficiently or at least like it can be done in ClassicUI.

## Motivation

The current user control panel in Volto requires some work to make it more user friendly. For instance it doesn't show any indication when one is searching for users, there is no way to access user information (click and see all user properties) or there is no indication on which is the user login name

## Assumptions

We need to unify the user handling UI and UX to the one existing in ClassicUI.

## Proposal & Implementation

- When "many users" is enabled the User control panel should not show the table headings, but just the search form like ClassicUI does.
- The user controlpanel should show a spinner when the search is being made and no results are present yet.
- The user listing should show not only the user fullname but also the user login name like ClassicUI does.
- The user controlpanel should link each user to a page where all user data should be shown and be modifiable if the current logged in users has the required permissions.
- When any change is done in the User/Role matrix, an indicator should mark that changes are not saved yet (as opposed to the user-group controlpanel were changes are applied immediately when they are made)

## Deliverables

New components will be prepared to handle the user data form, and changes will be made to existing components to match the requirements.

## Risks

I don't see any risks here.

**Comment by lord2anil** [comment]
Sir , Are you talking about "User Management (2023)" gsoc project or new project ??, I whould  like to take this project and i will submit a proposel soon.

**Comment by erral** [comment]
It's somehow related. I wasn't aware of that GSOC idea but it is related. Anyway I haven't found an issue about this and that's why I added it here

**Comment by erral** [comment]
Related issues:
- https://github.com/plone/volto/issues/4018
- https://github.com/plone/volto/issues/2707
