### ISSUE TITLE
Volto is unable to run on Windows

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#4564]
It seems that there's a lot of people that do development on Windows. 

The biggest problem, right now, is that it fails to run `make`.

**Comment by stevepiercy** [comment]
Developers can install WSL or use Linux in a VM. I do not want to stop using `make` for the sake of an OS that I would never run on a production web server.

I recommend that we document what OSes are and are not supported.

**Comment by Darkcoder011** [comment]
i think we want try to our compatibility  with Windows Devices because in World may developer uses Windows 

@tiberiuichim

**Comment by stevepiercy** [comment]
@Darkcoder011 although that may be true, see the discussion at https://github.com/plone/documentation/issues/1468 for why that is not going to change. If you can figure it out, great, share your experience and document it.

**Comment by Darkcoder011** [comment]
@stevepiercy  yes you are right . but i just want to say can we try to figure it out .

**Comment by stevepiercy** [comment]
@Darkcoder011 what is this "we" to which you refer? I have negative infinity interest in doing that work, except to review your pull requests to documentation. I would suggest you post to Community Forum to identify users who would want to work and collaborate on this effort.

**Comment by Darkcoder011** [comment]
Ok i will try on community forums  that someone is interest to doing that work 

Thanks !!
@stevepiercy
