### ISSUE TITLE
Changing conditional checking of object properties to optional chaining 

### ISSUE THREAD

**Issue by nilootpal** [plone/volto#4567]
While going through the volto/plone repository I found that one of the components in src/components/themes/Icon/Icon.jsx
There was conditional checking of object properties, 
`xmlns={name.attributes && name.attributes.xmlns}`
`viewBox={name.attributes && name.attributes.viewBox}`
It can be replaced with optional chaining.

**Comment by stevepiercy** [comment]
@nilootpal please post text, not images of text. See https://meta.stackoverflow.com/questions/285551/why-should-i-not-upload-images-of-code-data-errors please.

**Comment by nilootpal** [comment]
Thanks @stevepiercy for the comment and I have changed as per your advise

**Comment by saadkhan011** [comment]
Hi nilootpal,
      I want to work on this issue. Is it open?

**Comment by stevepiercy** [comment]
@saadkhan011 it is open (see the green Open indicator?). However @nilootpal did not link their PR to this issue, nor did they assign themselves to the issue, thus you would have had to search the pull requests to determine that any work had been done on the issue.

@saadkhan011 before doing any work, please read contributing guidelines and follow their instructions:
- https://6.docs.plone.org/contributing/index.html
- https://6.docs.plone.org/volto/developer-guidelines/contributing.html
