### ISSUE TITLE
Running Docker run command gives an error due to incorrect documentation.

### ISSUE THREAD

**Issue by AbhayBhan** [plone/volto#4577]
**BUG DEFINITION**
The ReadMe of Volto mentions running Volto in development mode by using docker run commands and those commands are as follows : 
For Backend,
`docker run -it --rm --name=plone -p 8080:8080 -e SITE=Plone -e PROFILES="plone.volto:default-homepage" plone/plone-backend:6.0.1`

For Frontend,
`docker run -it --rm --name=volto --link backend -p 3000:3000 -e RAZZLE_INTERNAL_API_PATH=http://backend:8080/Plone -e RAZZLE_DEV_PROXY_API_PATH=http://backend:8080/Plone plone/plone-frontend:latest`

Once the Backend Command is running, The frontend command gives an error because it mentions "--link backend" and the name of the backend container is plone, it can either run by changing the frontend code to : 

`docker run -it --rm --name=volto --link plone -p 3000:3000 -e RAZZLE_INTERNAL_API_PATH=http://backend:8080/Plone -e RAZZLE_DEV_PROXY_API_PATH=http://backend:8080/Plone plone/plone-frontend:latest`

But doing this will render the frontend useless and it won't open in the browser, The correct fix would be to the backend code to following : 

`docker run -it --rm --name=backend -p 8080:8080 -e SITE=Plone -e PROFILES="plone.volto:default-homepage" plone/plone-backend:6.0.1`

**To Reproduce**

To Reproduce the problem, run the commands as they are mentioned on this repo's readme.

**Screenshots**
![image](https://user-images.githubusercontent.com/92722300/226249880-ac9e7ccf-de1b-4187-a38d-d46e92875825.png)

**Software (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Volto Version Latest Current
- Plone Version Latest Current
- Plone REST API Version Latest Current

**Comment by stevepiercy** [comment]
@AbhayBhan Volto does not run on Windows. This is not a bug. See open PR that will soon be merged: https://github.com/plone/documentation/pull/1469.

@sneridagh I think it is time to remove installation instructions from the Volto README. There are too many install instructions, and it absolutely not maintainable. I know you wanted the README to include installation instructions. Can we just link to https://6.docs.plone.org/install/index.html?

See also:

- https://github.com/plone/volto/issues/3289
- https://github.com/plone/volto/issues/4564
- https://github.com/plone/volto/issues/3723

**Comment by AbhayBhan** [comment]
I see, I didn't know that, I am really sorry for causing an uproar. I am a GSOC aspirant for this year and I wanted to learn plone deeply, I have been trying to do so from last 3-4 days by trying to install it in my machine, Should i close this issue? and also is WSL the only way to develop on my Windows Machine?

**Comment by AbhayBhan** [comment]
Thanks Very Much! I am closing this Issue.
