### ISSUE TITLE
sitemap.xml.gz is not compressed. Not gzip format

### ISSUE THREAD

**Issue by avoinea** [plone/volto#4622]
Download https://demo.plone.org/sitemap.xml.gz

<pre>
$ gzip -d sitemap.xml.gz 
gzip: sitemap.xml.gz: not in gzip format

$ gunzip sitemap.xml.gz 
gzip: sitemap.xml.gz: not in gzip format

$ file sitemap.xml.gz 
sitemap.xml.gz: XML 1.0 document, ASCII text
</pre>

**Comment by tiberiuichim** [comment]
https://github.com/plone/volto/blob/33962f130f25a92760848c07ab59bcd13a2ef37d/src/helpers/Sitemap/Sitemap.js#L47-L49

**Comment by avoinea** [comment]
Yes. Stil I can't figure out why the output is `text/xml` instead of `gzip`.

**Comment by avoinea** [comment]
Fixed by #4663 #4678
