### ISSUE TITLE
Workflow for new contributors

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#4632]
Here's a proposed workflow for handling new contributors

1. New contributor must sign and return PCA.
2. Plone Foundation reviews PCA, and if approved, assigns the new contributor's GitHub account to the Plone GitHub Team "Contributors".
3. New contributor creates PR from their fork to the `volto` repo.
4. If step 3 occurs before steps 1 or 2, then mr-roboto claims that the agreement has not been signed. However it is possible that step 1 has been completed, but step 2 has not, so the message may be misleading. It should be clarified to say that step 2 is in process. If the contributor has done step 1, and is waiting for step 2, then when step 2 is eventually completed, the contributor should add a comment to the PR that they received notification that they have been approved and added to the Plone Contributors Team.
5. Contributor include change log entry.
6. Member of _________ (some team, Volto Core, Developers, other?) review the code changes to screen against malicious activity.
7. Member of ________ (some team) clicks "Approve and run" to run the pending workflows.
8. Member of ________ (some team) review and approve pull request.
9. If needed, update pull request branch with master. [I don't think we can do this with external forks. The contributor might need to do this.]
10. Member of ________ (some team) merge pull request.

_Originally posted by @fredvd in https://github.com/plone/volto/issues/4631#issuecomment-1492859973_

**Comment by SayanDeveloper** [comment]
```Contributor include change log entry.```

Can you pls elaborate this point?

**Comment by stevepiercy** [comment]
This is covered in https://6.docs.plone.org/volto/developer-guidelines/contributing.html#create-a-pull-request, which every good new contributor always reads, of course, right? 😉

**Comment by SayanDeveloper** [comment]
Ah, I got you 🙂

**Comment by davisagli** [comment]
Since we have now arranged for the required workflows to be able to run without access to secrets, I think we could safely remove the requirement for someone to click "Approve and run" before workflows can run on PRs coming from a fork. (in other words, remove steps 6 and 7 above). Does that sound right @fredvd?

**Comment by stevepiercy** [comment]
Earlier today when I did my test on `documentation`, I found that `stevepiercy` had to click "Approve and run" for `stevepiercy2`'s PR. Is that an organization or repository level setting?

**Comment by davisagli** [comment]
We can configure it per repository or for the entire organization. We can't remove it entirely, but we can loosen the rule to only require approval for users who are new to github:

<img width="805" alt="Screenshot 2023-04-01 at 8 01 00 PM" src="https://user-images.githubusercontent.com/49014/229328883-424705cc-cdd2-4218-a6ac-74e4f8a8e4f6.png">

**Comment by stevepiercy** [comment]
I think it is fine to loosen the requirement for the organization. Fewer barriers and things to approve means less core developer time wasted, and I have a feeling, but no evidence, that the increased risk is negligible.

With that, I would remove Step 6, and modify Step 7 as required for whatever is set for the repository.

FYI, from https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories

> ### Controlling changes from forks to workflows in public repositories
> snip
> By default, all first-time contributors require approval to run workflows.
> snip
> You can configure this behavior for a repository using the procedure below. Modifying this setting _overrides the configuration set at the organization or enterprise level_. [emphasis added]

**Comment by stevepiercy** [comment]
Much of this, if not all, has been incorporated into the latest docs: 

- [Contributing to Plone](https://6.docs.plone.org/contributing/index.html)
- [First-time contributors](https://6.docs.plone.org/contributing/first-time.html)

@fredvd @davisagli does anything need to be added, or can we close this issue?
