### ISSUE TITLE
User Management: Minor bug in counting the password character.

### ISSUE THREAD

**Issue by hritikd3** [plone/volto#4643]
**Describe the bug**
While working on user management module, I was testing the validation for the input fields, and found that there is bug in counting password character . It is returning the object directly not the userInput value .

**To Reproduce**

1. Go to 'https://volto.kitconcept.com/'
2. Click on 'login-> profile icon->site setup'
3. Scroll down to 'users section and try adding new user and check the password field validation'

**Expected behavior**
This will distract the user and create bad UX, Instead validate the input fields properly and returning in right template string will do the job.

**Screenshots**
![image](https://user-images.githubusercontent.com/86347286/229586823-dc657dff-1bab-49b3-8b8c-6634c78028b2.png)

**Software (please complete the following information):**

- Browser [chrome]
- Volto Version [e.g. 8.5.0]
- Plone Version [e.g. 5.2.2]
- Plone REST API Version [e.g. 7.0.1]

**Comment by hritikd3** [comment]
Bug while returning the password character

**Comment by RLTek** [comment]
I would be happy to work on this issue.

**Comment by hritikd3** [comment]
great to see you are interested but already I am working on this issue .

**Comment by harshlancer** [comment]
Hey @hritikd3 I was also trying to solve this issue ,but now I see your comment . Still I want to know which file are you editing to solve this issue?

**Comment by ksuess** [comment]
Boys, update Volto to current version and see the issue gone.

**Comment by stevepiercy** [comment]
@harshlancer @hritikd3 also search the issue tracker before creating a new issue to see whether your issue has been resolved. Use the issue tracker as a knowledge base. Example: https://github.com/plone/volto/issues?q=min_chars

Closing.
