### ISSUE TITLE
A querystring appearing in the URL after accessing a page with a listing/search block

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#4692]
After merging https://github.com/plone/volto/pull/4159, the site URL start to have a strange behavior, if a listing block is present, then the URL shows a querystring:

<img width="633" alt="image" src="https://user-images.githubusercontent.com/486927/231795879-8e0c81cf-a440-4d8e-98a6-336fe9d73c1b.png">

The interesting thing is that it appears everywhere once you click in another router link.

In the videos in https://github.com/plone/volto/pull/4159 it does not show, maybe something that was introduced lately in the PR?

/cc @bipoza @erral @ionlizarazu this is quite urgent, we would need to fix asap. If it's not possible, I'd better revert the change and proceed with another release.

**Comment by sneridagh** [comment]
Also, I can see that the @querystring endpoint is being hit multiple times... this is another thing that we have to make sure that doesn't happen.

**Comment by sneridagh** [comment]
@erral Thanks a lot! Let's see if we can push a fix asap! If not, let me know and we can revert and postpone it until we have a better one.

**Comment by erral** [comment]
It looks like the code under the `useEffect` in `usePagination` is run no matter the user has gone away from the page where the pagination is shown.

Somehow this `useEffect` should be deactivated (sorry if the concept is not correct) when browsing away.

**Comment by sneridagh** [comment]
@erral we just merged some fixes to the listing/search blocks in cases of two of them are present in the same page, see: 

https://github.com/plone/volto/pull/4694

Maybe now the situation is improved.

It's what I saw, the `usePagination` hook should be addressed.

**Comment by erral** [comment]
I managed to remove the querystring before this merge, so I will test it again.

Anyway I have seen something strange going on, because I removed the querystring when going to any page except the home page. I need to test my fix further.
