### ISSUE TITLE
Search block in edit mode re-queries multiple blocks with an empty search text

### ISSUE THREAD

**Issue by reebalazs** [plone/volto#4697]
There are multiple issues here. In my use case there are two search blocks in a page with multiple filter conditions. They both have a SearchableText condition as well, so we can see from the results if that condition is in effect.

These issues are in edit mode only and don't manifest in view mode.

1. First issue is that when I load the page, at first the correct results appear, but then after a delay there is a second querystring request for each block. In addition, the second block will have the SearchableText condition removed from the query, thus yielding wrong results.

2. Second issue: when I type a search query into the blocks (not in the sidebar panel, but into the search input, which replaces the SearchableText set from the sidebar), the other block also gets requeried, and although in its search input its own search query is visible, its query has the SearchableText condition removed, thus yielding wrong results.

3. A performance issue: in my experiment with 2 blocks, the `onTriggerSearch` handler is executed 24 times during the page load, although in the end it actually does 2 (or 4) searches, because of the delayed trigger of the search. However this still causes a lot of unnecessery render calls in all the components under the current component in the tree. It might also actually trigger multiple searches when timing is different than in my experiments.

I've provided a PR to fix these problems.

# Fix search block search text re-query

SearchBlockEdit calls onTriggerSearch without parameters. But
onTriggerSearch does not ignore toSearchText in case it's not specified
in the call.

If there are multiple blocks in the page, this causes the search text
of all the other block's reset and re-queried with the wrong condition.

# Performance optimize onTriggerSearch

Previous to this fix, onTriggerSearch triggered 28 times during loading
and edit page with two search blocks in it. After the fix, it's just 2
times.

The fix is that the deep comparison condition for the query also has to
be applied in withSearch.jsx. Without that, the deep comparison in
SearchBlockEdit.jsx has no effect. This is because the onTriggerSearch
function will be regenerated each time there is an identity change in
data.query anyway. So the hook guard in SearchBlockEdit will be
triggered anyway because onTriggerSearch has changed.

In addition, I personally find it better to use JSON.stringify for the
deep comparison and skip using the useDeepCompareEffect hook. This uses
dequal under the hood which is capable to compare a lot of other data
types, but with pure json data it has no advantage to a string
comparison with JSON.stringify. (That said it would also work with
useDeepCompareEffect but perhaps a bit slower.)

# Remove SearchableText from the query only if there is a searchtext

Previously, the SearchableText was removed within normalizeState, even
if there was no searchText. This is wrong, the searchText should only
replace SearchableText condition if searchText is provided.

In the edit page this caused the following, in case a SearchableText
is specified as a condition to the block:

- Upon loading the edit page
- First the search blocks were loaded with correct results
- Then a second set of query was issued, but with the SearchableText
  condition stripped out. This means that the query result was wrong.

The current fix fixes the double querying, and the faulty condition in
the second query that results in faulty results.

The current fix still does not address the fact that eventually the
searchText should be a distinct facet from SearchableText, and the two
conditions could be combined, in comparison to the current state, when
one overrides the other.

**Comment by davisagli** [comment]
@reebalazs In order for the issue to be closed automatically you have to put "Fixes #4697" in the PR description, not a comment.
