### ISSUE TITLE
Comments are displayed on the Plone Site when we set "No" to Allow discussion

### ISSUE THREAD

**Issue by wesleybl** [plone/volto#4758]
**Describe the bug**
When we edit the Plone Site and set "no" to Allow discussion, comments are displayed

**To Reproduce**

1. Open the Plone Site edit form: http://localhost:3000/edit
2. Change the Allow discussion field on the Settings tab to "No"
3. Save
4. See that comments are displayed at the bottom of the page

**Expected behavior**
Comments should not be displayed.

**Software (please complete the following information):**

- OS: Ubuntu 22
- Browser Chrome 112
- Volto Version 17.0.0-alpha.7
- Plone Version 6.0.3
- Plone REST API Version 8.36.0

**Additional context**
The Plone Site serialization returns the `allow_discussion` field with: `{'token': 'False', 'title': 'Não'}`. The condition to display or not the comments checks only if there is any value in `allow_discussion`. To see:

https://github.com/plone/volto/blob/5874160b2d72d4c85e22e2107ab12ad5412a92a6/src/components/theme/View/View.jsx#L264

Then `{'token': 'False', 'title': 'Não'}` is considered true and the comments are displayed.

The realization of other content types returns `allow_discussion` as `false`. So on other types it works as expected.

The serialization of the other types has these steps that make `allow_discussion` `false`:

https://github.com/plone/plone.restapi/blob/f90329dfe49aa483517861a610b5175d68e0b6be/src/plone/restapi/serializer/dxcontent.py#L121-L123

In the Plone Site serialization we don't have this:

https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/serializer/site.py#L48

You need to add this in the Plone Site serialization. This was added to `dxcontent.py` by @sneridagh in [#502](https://github.com/plone/plone.restapi/pull/502).

By the way. Since now the Plone Site is Dexterity, couldn't the same serializer be used?

**Comment by davisagli** [comment]
> Since now the Plone Site is Dexterity, couldn't the same serializer be used?

plone.restapi still keeps compatibility with Plone 5.2. The portal-specific serializers can be dropped in the next major release of plone.restapi.

**Comment by Harish580** [comment]
sir, I'm new to open source contribution can you please share relevant screen shots for my better understanding of the issue .Thank you

**Comment by wesleybl** [comment]
@Harish580 before contributing to Plone, you need to sign contributor agreement. See:

https://6.docs.plone.org/contributing/index.html

**Comment by Akshat2Jain** [comment]
Hey @wesleybl, I have understood the issue. This means we have to add this 
```
 result["allow_discussion"] = getMultiAdapter(
            (self.context, self.request), name="conversation_view"
        ).enabled()
```
in  https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/serializer/site.py

**Comment by Akshat2Jain** [comment]
```
def get_allow_discussion_value(context, request):
    return getMultiAdapter((context, request), name="conversation_view").enabled()
```
@wesleybl  does this look valid?

**Comment by wesleybl** [comment]
@Akshat2Jain  LGTM.

**Comment by wesleybl** [comment]
@Akshat2Jain right.

**Comment by Akshat2Jain** [comment]
Should I make pr to `plone.restapi` and on merging that pr ...this issue will get closed right?
@wesleybl

**Comment by wesleybl** [comment]
@Akshat2Jain yes. You should do a PR on `plone.restapi` and this issue will be closed. You can indicate in PR that it will fix issue from another repository.

**Comment by Sulochan-khadka** [comment]
Is this issue still unsolved?

**Comment by davisagli** [comment]
@Sulochan-khadka There is work in progress on it, as you can see from the linked issue and pull request.
