### ISSUE TITLE
Add block index to zcatalog, expose in control panel

### ISSUE THREAD

**Issue by tisto** [plone/volto#4778]
## Abstract

It is currently not possible to get an overview of which block(types) are used on which contexts. If you want to maintain a Plone site and update, delete or migrate a block type, you want to know as a developer/integrator:
* if certain blocks are in use (at all)
* where they are in use in the site
* and programmatically loop over content items with certain blocks to maybe migrate/fix them in upgrade steps

## Motivation

the immediate use is for maintenance and upgrading. But knowing where certain blocks are and being able to quickly access them, enables future applications with for example re-using or copying collection criteria in list style blocks or other 'intra context' that is invisible now from the current available indexes.

Exposing the index in a control panel could also improve the editing esperience for power editors/webmasters, so that they can look up where certain blocks are in use.  This could be a 'support congtrol panel like the Relations control panel, the proposed locking control panel and the content overview control panel
 
## Proposal & Implementation

TBD.  Would a plain KeywordIndex be enough where a unique name for each block acts as the keyword? 

## Deliverables

* KeywordIndex, upgrade step in plone.volto. 

* block usage control panel

## Risks

Adding another index will increase the index size and have some extra work on saving blocks in the block layout behavior fields. on very large sites with many different blocks on different pages this could impact performance a little bit. o.t.o.h we don't need counts for blocks, just the presence of blocks. 

When the index has to be created with an upgrade step, the upgrade could take a lot of time for very large sites.

**Comment by tisto** [comment]
@davisagli if I am not mistaken we currently do not expose this data anywhere in a control panel, correct? Therefore I'd like to re-open this PLIP and discuss how we could expose the data in the control panel. I am thinking about a view similar to what we have in the Dexterity Control Panel. A list of all blocks in Volto and the number of blocks that are currently present in your Plone site. If you click on one of the numbers you will see a list of all pages where this block is used.

Does that sound doable with the current index in place?

cc @sneridagh 

Background: we would like to present this feature at Ploneconf when talking about Plone 6.1. A zcatalog index is great but hard to present as a feature to a (partially) non-technical audience. :)

**Comment by sneridagh** [comment]
Sounds good for me, although could be more time consuming as we think.

**Comment by davisagli** [comment]
@tisto We should discuss it but I won't have time to work on it before ploneconf.

**Comment by tisto** [comment]
@davisagli @fredvd did we discuss adding the control panel and concluded that too much work would be need for this? Or do I mix this up with another control panel that I proposed? If this is something that is still on our agenda, we might want to split up this PLIP and create a separate one for the control panel.

**Comment by davisagli** [comment]
@tisto tbh, I wasn't aware of this PLIP and didn't realize that a control panel was discussed as a necessary part of this feature. It would make sense, but we haven't worked on it yet. Though, it is less of a control panel for changing settings, and more of a report about what content exists in the site.

**Comment by tisto** [comment]
@davisagli yeah. I was thinking about a simple report, like what we currently have in the Dexterity Control Panel. You can see a list of all blocks with the number of occurrences:

| #        | Block           |
|------|-------------|
| 2332 | Text Block   |
|     32 | Grid Block   |
|      3 | Table Block  |

If possible we would provide links for each block that leads the user to a full list of all URLs that contain a block:

| URL            | Block           |
|------------|-------------|
| /my-page  | Text Block   |
| /my-page  | Grid Block   |
| /my-event | Table Block  |

**Comment by sneridagh** [comment]
@tisto I would open another PLIP for the "control panel", what do you think?

**Comment by tisto** [comment]
@sneridagh yeah. We could create another PLIP for this. Maybe a good "spare" task for @jonaspiterek or @iRohitSingh in case they run out of tasks...
