### ISSUE TITLE
UI recommendation for the relation control panel

### ISSUE THREAD

**Issue by ksuess** [plone/volto#4789]
We aggreed thursday 18.05. on Irenes recommendations:
- [x] Column of sources: 20 % , maybe 25%
	- [x] Rest left aligned
- [x] Instead of plus/minus: Checkbox that toggles 'select all' and 'de-select all' of its column.
	- [x] Checkbox a little bit bolder
- [x] Group source UI (filter and adding more sources). Same for target stuff. More distance between source and target stuff.
	- [x] Add titles 'source' and 'target'

**Comment by danalvrz** [comment]
Implemented in https://github.com/plone/volto/pull/3382

**Comment by ksuess** [comment]
@danalvrz I'll work now on the checkbox instead of "plus / minus".
