### ISSUE TITLE
GitHub Web hooks

### ISSUE THREAD

**Issue by gforcada** [plone/volto#4822]
I was having a look at the webhooks in this repository and found that there are 2 hooks pointing to hub.docker.com that are failing due to some credentials having expired or something along the lines.

Is this repository still using those hooks? they have been failing for quite a while. All logged requests did fail.

**Comment by davisagli** [comment]
Those are old, from a time when the volto repository had a Dockerfile which was built by Dockerhub. These days the images are built from the plone-frontend repository using GitHub Actions. I removed the webhooks.
