### ISSUE TITLE
Preview Image does not use HTTPS

### ISSUE THREAD

**Issue by cihanandac** [plone/volto#4911]
**Describe the bug**
While testing the website I am working on with PageSpeed Insights, I realized that the pages that use preview images are getting this warning: "Does not use HTTPS". It is dropping the score for the 'Best Practices'. If the page doesn't have a preview image shown on it, then it does not have this issue.

Link for the webpage: https://rietveldschroderhuis.intk.com/nl/over/centraal-museum-rietveld
Link for the PageSpeed test: https://pagespeed.web.dev/analysis/https-rietveldschroderhuis-intk-com-nl-over-centraal-museum-rietveld/l1bq5otzia?form_factor=desktop

Link to repo (line 72) : https://github.com/cihanandac/new-RietveldSchroderhuisWebsite/blob/main/frontend/src/components/theme/Header/HeroSection.jsx

The preview image is called with the following code: 

```
<Image
  image={content.preview_image}
  width="100vw"
  height="90vh"
/>
```

**To Reproduce**

1. Go to https://pagespeed.web.dev
2. Write the link to the URL section ->  https://rietveldschroderhuis.intk.com/nl/over/centraal-museum-rietveld
3. Click on -> Analyze
4. Scroll down to 'Best Practices' section
5. See error 'Does not use HTTPS'

**Expected behavior**
Doesn't have  "Does not use HTTPS" warning and has a better score in best practices.

**Screenshots**
<img width="1481" alt="Screenshot 2023-06-23 at 13 45 19" src="https://github.com/plone/volto/assets/67173940/563d97ad-b4f5-41b3-b418-39805efee8e7">

<img width="1503" alt="Screenshot 2023-06-23 at 13 56 44" src="https://github.com/plone/volto/assets/67173940/ea26ff98-4267-4cc2-b60b-93d94bd2bc83">

**Software (please complete the following information):**

- Volto Version: 16.20.8
- Plone Version: 6.0.5
- Plone REST API Version: 8.39.1

**Comment by manoharkumarsingh** [comment]
@cihanandac  If the page doesn't have a preview image then you shouldn't render <Imgae>. I hope this will help you to fix issue

**Comment by cihanandac** [comment]
Thanks, @manoharkumarsingh. Didn't help to solve it, but I understand your point.

**Comment by avoinea** [comment]
@cihanandac You should always use `flattenToAppURL`. See [Image Block](https://github.com/plone/volto/blob/master/src/components/manage/Blocks/Image/View.jsx#L46-L56) for example.

**Comment by cihanandac** [comment]
Thanks for the tip @avoinea. This component is also using Image Block, thus it is utilizing `flattenToAppURL`. Please correct me if I am missing something here but I believe the issue is about something else.

**Comment by avoinea** [comment]
@cihanandac No, it's not. It's custom code all the way down:
- https://github.com/cihanandac/new-RietveldSchroderhuisWebsite/blob/main/frontend/src/components/theme/Header/HeroSection.jsx#L72
- https://github.com/cihanandac/new-RietveldSchroderhuisWebsite/blob/main/frontend/src/components/theme/Header/HeroSection.jsx#L4
- https://github.com/cihanandac/new-RietveldSchroderhuisWebsite/blob/main/frontend/src/components/Image/Image.jsx#L37-L45
- https://github.com/cihanandac/new-RietveldSchroderhuisWebsite/blob/main/frontend/src/components/Image/Image.jsx#L3
- https://github.com/cihanandac/new-RietveldSchroderhuisWebsite/blob/main/frontend/src/helpers/images.js#L31
-

**Comment by cihanandac** [comment]
Thank you so much again @avoinea. Looks like you are right. I don't even know how I missed this one 🤦 .
