### ISSUE TITLE
Relations-controlpanel wrongly complains about outdated plone.restapi

### ISSUE THREAD

**Issue by pbauer** [plone/volto#4925]
The controlpanel http://localhost:3000/controlpanel/relations complains: "Please upgrade to plone.restapi >= 8.35.3."
But I already use the newest version shipped with Plone 6.0.6 and Volto 17.0.0-alpha.14 in a freshly created site.

![Bildschirmfoto 2023-06-27 um 21 33 39](https://github.com/plone/volto/assets/453208/d1e7dcdf-73eb-4e20-a47f-0d28a1e95fd9)

In the same DB in classic the controlpanel http://localhost:8080/Plone/@@inspect-relations works fine.

**Comment by davisagli** [comment]
Hmm. What I see in https://github.com/plone/volto/blob/master/src/components/manage/Controlpanels/Relations/Relations.jsx is that this message is shown if `relations.stats.stats` evaluates to false in the redux state (i.e. if there was a problem loading the `/@relations` endpoint). Can you check the network tab and see what response you are getting to that request?

(For what it's worth, the API was actually added in plone.restapi 8.39.0, so the minimum version in the message is wrong.)

**Comment by pbauer** [comment]
It works now so I cannot reproduce the issue any more. I get 404's on http://localhost:3000/++api++/findstenichätsch/@search though which comes from https://github.com/plone/volto/blob/a3b066b299a515b8b97363137b47f982e4aa1881/src/components/manage/Controlpanels/Relations/RelationsListing.jsx#L196

The constraint to 40 displayed relations makes the controlpanel rather useless for my use-case (inspecting, not creating relations) so I fall back to the classic version.
