### ISSUE TITLE
Listing block stores block id in its data

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#4942]
Volto 16.20.7

Steps to reproduce:

- create a new page. Add a listing block, don't configure anything, save it.

```
    "a126360e-9408-4036-b6df-1b79a877f783": {
      "@type": "listing", 
      "block": "a126360e-9408-4036-b6df-1b79a877f783", 
      "headlineTag": "h2", 
      "query": [], 
      "variation": "default"
    }, 
```

**Comment by davisagli** [comment]
@tiberiuichim This was already fixed in volto 17 (I think in https://github.com/plone/volto/pull/4239), but not backported to volto 16 -- I assume because it's a backwards incompatible change in the block data format.

**Comment by tiberiuichim** [comment]
@davisagli Thanks! I guess I need to catch up with 3 months of Volto development :-(
