### ISSUE TITLE
Reset button in DatetimeWidget triggers form submission in Firefox

### ISSUE THREAD

**Issue by mbarde** [plone/volto#4975]
**Describe the bug**
Click on reset button (red cross) in `DatetimeWidget` triggers form submission when using Firefox.

**To Reproduce**

1. Use Firefox
2. Edit content type with Datetime-Field
3. Select date
4. Click on the reset button
5. Submit is triggered

This also happens when the Datetime-Field is in the sidebar.

**Expected behavior**
Click on reset button should only reset the Datetime-Widget and not trigger form submission.

**Software:**

- OS: Ubuntu 22.04
- Browser: Firefox (does not occur in Chrome)
- Volto Version 16.20.7
- Plone Version 6.0.4
- Plone REST API Version 8.37.0

**Possible solution**
Add `event.preventDefault()` in `onResetDates` in `DatetimeWidget.jsx`.

**Comment by Aryan8912** [comment]
Yes, I have successfully reproduced this issue. I will be working on it.

**Comment by Aryan8912** [comment]
I think this is a right way 
const DatetimeWidget = ({ value, children, className, format = 'lll' }) => {
  const lang = useSelector((state) => state.intl.locale);
  moment.locale(toBackendLang(lang));

  // Separate function to reset the DatetimeWidget
  const handleReset = (event) => {
    event.preventDefault(); // Prevent form submission
    // Implement logic to reset the DatetimeWidget state here
    // For example, set value to null or empty string to reset the widget
  };

  return value ? (
    <span className={cx(className, 'datetime', 'widget')}>
      {children
        ? children(moment(value).format(format))
        : moment(value).format(format)}
      <button onClick={handleReset}>Reset</button> {/* Reset button */}
    </span>
  ) : (
    ''
  );
};
