### ISSUE TITLE
Create new user fails if login with email is enabled

### ISSUE THREAD

**Issue by ksuess** [plone/volto#5031]
The schema of the 'user creation form' should not include the username as this is not allowed.
https://6.docs.plone.org/plone.restapi/docs/source/endpoints/users.html#create-user

Volto 16 and 17

**Comment by mehedikhan72** [comment]
Hi, @ksuess . I got to generate the bug. New as a contributor here and I will work on it and provide the updates in this thread.

**Comment by mehedikhan72** [comment]
Update: The bug is fixed. I will make a PR once my contributor agreement is signed and taken care of.
