### ISSUE TITLE
Improve UX of password reset component.

### ISSUE THREAD

**Issue by iFlameing** [plone/volto#5052]
1. Go to http://localhost:3000/passwordreset
2. Press enter without filling in the id.

You will see an error but confused regarding what should I do now.

screenshot

<img width="928" alt="Screenshot 2023-08-02 at 12 45 35 PM" src="https://github.com/plone/volto/assets/33936987/010517ca-7ff3-4f52-8dd0-baf6894dd50b">

**Comment by stevepiercy** [comment]
There is an awful lot of pink without a clearly indicated input field. It's ridiculously minimalist.

Compare to what [Bootstrap does for validation errors](https://getbootstrap.com/docs/5.3/forms/validation/#custom-styles).

![Screenshot 2023-08-02 at 4 56 57 AM](https://github.com/plone/volto/assets/102112/051900ef-a1ef-4404-b1d7-e213f38d0e7b)

**Comment by Programmer-Dost** [comment]
Can you help me find where this function and its styling is defined so that I can improve it?

**Comment by davisagli** [comment]
@Programmer-Dost This needs input from the Pastanaga theme designer before it is ready to implement a fix.

**Comment by Programmer-Dost** [comment]
So how long we'll need to wait for approval?

**Comment by stevepiercy** [comment]
One more UI issue with labels and inputs in general, I was so confused by the [PloneConf Contact form](https://2023.ploneconf.org/contact-form).

![Screenshot 2023-08-03 at 12 52 51 PM](https://github.com/plone/volto/assets/102112/742acece-4901-4bdd-924d-4288f5a8e8d7)

Although this might be obvious to long-time users of Volto with its minimalist design, it was not at all obvious to me how to fill out the form. Clicking below "Name" had no effect, and I first thought my browser crashed. I figured it out by holding down the tab key until the cursor brought focus to the HTML input, which looks nothing like a traditional HTML5 input. The minimalism of an input having only a bottom border is unfamiliar and unrecognizable. Additionally the distance between a label and its input is misleading.

**Comment by rabahalishah** [comment]
Hello guys, I want to contribute to this. Can anybody tell me how can I get started? This would be my first contribution. Anyone Please help.

**Comment by stevepiercy** [comment]
@rabahalishah see https://github.com/plone/volto/issues/5052#issuecomment-1662602885, then https://6.docs.plone.org/contributing/index.html, and finally https://6.docs.plone.org/contributing/first-time.html.

**Comment by rabahalishah** [comment]
Alright Steve, I am gonna checkout them right now. Thank you so much @stevepiercy

**Comment by davisagli** [comment]
From my perspective this should remain on hold until @sneridagh is back from vacation and can give input on the design questions.

**Comment by tisto** [comment]
We are not going to fix the Pastanaga UI UX issues regarding forms in this ticket. We are aware of the problems and this is why Quanta uses a different way to display form fields. This ticket is about to just fix the obvious flaws.

**Comment by davisagli** [comment]
@tisto I agree the scope of the discussion here goes beyond what is reasonable to fix in the short term, but it's not clear to me which specific flaws you consider obvious. Just add a margin below the "There were some errors" message, or more than that?

**Comment by sneridagh** [comment]
@davisagli @iFlameing I would add the margin below the error message, make sure it plays well with others. However it's strange that it shows up in here, and not in other forms, maybe there's a wrong/leaking CSS declaration somewhere specific to this form?

**Comment by davisagli** [comment]
Fixed in #5115
