### ISSUE TITLE
Listing blocks in duplicate pages doesn't load properly

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#5070]
**Describe the bug**
when you 'duplicate' content with blocks, the blocks are duplicated but keep their original id.
When the page loads, calls to plone are made to querystringsearch with subrequests, whose subrequest id is the block id.
If I jump to the other page, where the block ids are the same, the call to plone for the other page's block fails because in the redux state there is already a subrequest with that id, so it gets that result .

**To Reproduce**
1. I create a page A containing a list
2. I duplicate the entire page, calling it B, with the content mode copy/paste function
3. I modify the list of page B by modifying the filters
4. I display page A by refreshing
5. I see page B... it has the same contents as A
6. I refresh the correct contents to appear
7. Returning to page A now the list of B appears (it is fixed by refreshing again)

**Comment by davisagli** [comment]
@giuliaghisini I see how your solution should make sure that the subrequest ids are unique even if block ids are duplicated on different pages.

But, it also has me thinking: if I navigate from page A to B, wait 10 minutes, and then navigate back to A, wouldn't it be reasonable for me to expect the query to be fetched again? But if the old subrequest is still in the redux state, that won't happen, right? Your solution doesn't help here. So maybe a better solution would be to clear subrequests from the state when the user navigates to a different page. (Or maybe I'm missing something and that won't work or is too difficult.)

**Comment by giuliaghisini** [comment]
@davisagli what you think is correct, but.. there are situations in which having the redux state populated avoids unnecessary calls to the backend when you navigate from one page to another.. for example we have many sites where header and footer data are requested at the backend.. in these cases it is convenient to make a request to the backend only once, and not on every page change..

**Comment by pnicolli** [comment]
@davisagli afaict the query is still fetched everytime, see also the video below. I would still see possible benefits in clearing the subrequests, but maybe (depending on how the code is written) it is using old results while waiting for new results and that could have benefits too. I'm not sure about this still, but anyway I think this matter is out of the scope of this bugfix.

[Listing-1.webm](https://github.com/plone/volto/assets/14176608/578e0376-09e0-4884-9006-50db52d3b5ea)

**Comment by davisagli** [comment]
@pnicolli oh yeah, that makes sense. it wasn't preventing fetching the request, it was just causing a flash of old results while it loads
