### ISSUE TITLE
Links from within grid Blocks do not appear in links and relations view

### ISSUE THREAD

**Issue by jackahl** [plone/volto#5099]
**Describe the bug**
Internal links and references within grid Blocks (Teaser,  Image, Inline Link) are not registered as relations in the links and references View of the linked page.

**To Reproduce**

1. create 2 pages: page-a and page-b
2. add a Grid Block to page-b
3. add a teaser block within that grid block and link page-a there
4. got to /page-a/links-to-item

**Expected behavior**
page-b should appear as an item that references page-a in the links and references panel. 

**Screenshots**

![Screenshot 2023-08-16 at 13-54-16 Links and references](https://github.com/plone/volto/assets/44289551/30a8591d-b7a3-4775-96a8-01f60ac9347e)

**Software (please complete the following information):**

- OS: any
- Browser: any
- Volto Version: 17.0.0-alpha.24
- Plone Version: 6.0.5
- Plone REST API Version: 8.39.1

**Additional context**
For Blocks outside the grid all works fine. I already created cypress tests for these cases here https://github.com/plone/volto/blob/27a8419529231ec855cbc11a1fe6c9ee8be4b11f/cypress/tests/core/basic/linkIntegrityView.js

For Links from within a grid I created a failing test here: https://github.com/plone/volto/blob/27a8419529231ec855cbc11a1fe6c9ee8be4b11f/cypress/tests/core/basic/linkIntegrityView.js#L397

**Comment by jackahl** [comment]
@davisagli I assume this needs to be fixed in p.restapi, right?

**Comment by ksuess** [comment]
@davisagli enhanced the handling of subblocks in https://github.com/plone/plone.restapi/pull/1648 which is part of plone.restapi 8.41.0. An upgrade should fix your issue.

**Comment by jackahl** [comment]
@davisagli thank you will try that out and close the issue.

**Comment by jackahl** [comment]
Confirmed working with latest rest api. Closing
