### ISSUE TITLE
Event creation not respecting dates/times

### ISSUE THREAD

**Issue by obct537** [plone/volto#51]
Creating an Event with a specific date and time will result in an event being created with today's date, and time.

In the React app:
<img width="997" alt="screen shot 2017-10-22 at 2 30 40 am" src="https://user-images.githubusercontent.com/505904/31859457-f81b354a-b6d1-11e7-8182-69828197e729.png">

Inside Plone, after creation:
<img width="381" alt="screen shot 2017-10-22 at 2 32 04 am" src="https://user-images.githubusercontent.com/505904/31859459-fd187c9c-b6d1-11e7-95c6-89c588136cb5.png">

**Comment by davisagli** [comment]
This appears to be working fine these days (note that the main date fields for an Event are on the default fieldset, not the Dates fieldset which controls when an item is visible in listings and search results)
