### ISSUE TITLE
a11y - skiplink to toolbar - cms ui

### ISSUE THREAD

**Issue by Wagner3UB** [plone/volto#5117]
**Describe the bug**
When using a screen-reader, there is no easy way to enter the left toolbar without pressing dozens of times `shift` + `tab` and there is nothing warning the user that he is inside the toolbar.

**Expected behavior**
Have a clear way to arrive to the toolbar, with a proper text explain the path using a skiplink

2 main cases of use:
- When the user just arrives at the edit page and search the skiplinks to understand where he can go
- When the user finishes an update and need to go to the toolbar to save the work

**Software (please complete the following information):**

- Volto Version 17.0.0-alpha.19
- Plone Version 6.0.4

**Comment by ichim-david** [comment]
![edit-page-landmarks](https://github.com/plone/volto/assets/152852/c398798f-87a3-4b75-b048-f656504daea5)
![form-controls-rotary](https://github.com/plone/volto/assets/152852/9fa09dfa-e663-4fd0-b329-7a9cd2ec23ce)
@Wagner3UB there is a way to get to the toolbar quite easily by using either the toolbar landmark or going to the form controls and focusing on one of the buttons from the toolbar.

One thing that would be nice is when the toolbar is collapsed for the buttons besides the enlarge button to no longer be focusable, that way you go to the toolbar, hit tab and only are taken to the shrink toolbar button where you can expand it after which you have access to all of the other buttons.

**Comment by Wagner3UB** [comment]
@ichim-david Hey, thank you for the explanation. I will need to study a little more to understand the landmark behavior, but it's very interesting to know about its existence.

@JeffersonBledsoe Thank you for the help. if you're going to work on this issue, after open a PR, please link the new PR with this issue.
