### ISSUE TITLE
a11y - sharing page - search icon label - cms ui

### ISSUE THREAD

**Issue by Wagner3UB** [plone/volto#5124]
**Describe the bug**
- Search icon doesn't have label

**To Reproduce**
- inspect the icon or using a screen reader
`<button class="ui icon button"><i aria-hidden="true" class="search icon"></i></button>`

**Screenshots
<img width="1532" alt="Schermata 2023-08-24 alle 16 44 07" src="https://github.com/plone/volto/assets/60133113/50b47b55-0e9d-4335-acb4-4913da72b523">
ts**

**Software (please complete the following information):**

Volto Version 17.0.0-alpha.19
Plone Version 6.0.4

**Additional context**

**Comment by Amdadullah-Raihan** [comment]
Hello Sir, 
What do you exactly want? Do you want a level below the icon or show the label in a tooltip?
