### ISSUE TITLE
UX Feedback: Anchor Links / Slug / Linked Headline

### ISSUE THREAD

**Issue by tisto** [plone/volto#5174]
Volto 17 implements linked headlines:

- PR: https://github.com/plone/volto/pull/3540
- PLIP: https://github.com/plone/volto/issues/4298

I just document the feedback that we received from one of the UX experts from our client:

# Discoverability of the "copy anchor link" feature

- A user has no way to understand how to copy an anchor link
- Functionality to copy anchor links is exposed to viewers of the website (regular users might consider this to be a glitch or bug in the website)
- Copying UX patterns (cargo cult) is not necessarily a good idea. Especially when copying a pattern for a system for developers (GitHub/GitLab)

<img width="1466" alt="Screenshot 2023-09-12 at 08 21 53" src="https://github.com/plone/volto/assets/632105/4524be43-a1da-4a80-9227-745d36069b76">

Note Timo: Even though I know this feature from Github and GitLab, I reported a bug to my team when the new Anchor feature of Volto was introduced in one of our projects. I though it was a visual glitch or regression.

# Fragile

- There is no way for an editor to know if changing any content of a page (e.g. a headline) could break an existing anchor link (this is considered to be a KO criteria for the adoption)
- Making an anchor target explicit (anchor block) or auto-generating the anchors would not completely avoid this problem but both solutions would make it less likely that an editor breaks existing anchors

--

I am just sharing this here with the community for now and I honestly don't know which way to go without further consideration and discussions. This is a hard problem. We might want to do some more research of how other systems do it.

We (kitconcept) have a budget to implement the anchor feature in Volto 17 or in an add-on product. Our clients would be willing to pay us to Open Source the development and they want it to be Open Source. Though, they need to feature in the next few weeks and the current implementation in Volto 17 does not meet their needs.

cc @davisagli @sneridagh 

@sneridagh one question: is it possible to make the "show anchor icon on hover" feature optional or hide it from anonymous viewers? I honestly think that this is highly confusing for a public website and does not provide any useful feature for anonymous users.

# Implementation Options for setting Anchors

- Option A: editors create anchors manually
  - Option A1: editors explicitly add an anchor block, enter a unique ID for the anchor
  - Option A1: each block has an "ID" or "Anchor ID" field where editors can set the ID, independently of the actual content
- Option B: the CMS automatically generates unique anchor IDs (e.g. https://www.plone.org/about-us#s89S92)
- Option C: the CMS automatically generate anchors based on the content (e.g. "My Headline" automatically gets an ID "my-headline")

### Pros

- anchors are set explicitly so editors can see if they might break an existing anchor
- the amount of anchors is limited, so when choosing an anchor the editors see only "meaningful" anchors

### Cons

- there is no way an editor knows if they will break an existing anchor by removing an anchor
- two steps to set an anchor and link to it instead of just one (when the anchor links are automatically generated)
- option A1 only: adding an additional field to all blocks (core, open source, custom) is a lot of work and would be very fragile when we want to change it in the future

### Pros

- anchors do not break if editors change the content (at least as long as they don't remove and re-add the content)

### Cons

- the IDs that are generated are not human readable and if we use UUIDs very long

### Pros

- already implemented in Volto Core
- easy to implement

### Cons

- editors can break anchor links easily by just fixing a TYPO in a headline
- editors have no way of knowing when they will break an existing anchor link

**Comment by sneridagh** [comment]
@tisto the feature is useful also for non-logged-in users, IMHO. Same as Github/others provide it. If someone wants to copy a link to a header, how would they do it?

Yes, the feature can be disabled completely from Volto configuration.

**Comment by sneridagh** [comment]
@tisto I think the problem has much more meat than meets the eye. After reading your summary I could see lots of more potential Pros and Cons for every each of the options. I think the implications and use cases that derives from every single option are huge, and the solution and related UX is not simple, and finding a bullet proof system for managing them is not feasible.

Starting with how we are going to decide that a section has changed enough to be considered "a different one", then act properly (eg. tell user that he's going to break links, point to them, etc...), or at the contrary, how you tell that it does not so you don't generate another ID, etc...

**Comment by tisto** [comment]
@sneridagh then we need to disable this feature by default in all our projects and put our effort into an add-on instead of Volto core.

**Comment by tiberiuichim** [comment]
It's a single setting to disable them. https://github.com/plone/volto/blob/f205332d494fb99f826f9fe2afd1f2eba4a70907/packages/volto-slate/src/editor/render.jsx#L177C12-L177C24

**Comment by tisto** [comment]
@sneridagh can you elaborate on the use case for anonymous users non logged-in users? I honestly do not see this use case at all. Why would a web-based system allow copying anchor links to the clipboard? We do not have this feature for page URLs/links (because you would obviously copy the browser URL, the same works for anchor links).

**Comment by davisagli** [comment]
@tisto I use this feature all the time as an anonymous user of MDN. Example: https://developer.mozilla.org/en-US/docs/Web/CSS/z-index#values -- however, like GitHub, this is a system where the target audience is developers. I thought Wikipedia provides it too, but I remembered wrong. There probably is some truth to Mr. Harmsen's comment that it is not obvious to non-developers.

**Comment by tisto** [comment]
After discussing the current implementation with the (kitconcept) team, UX experts from our client, and editors from two different clients, and some further considerations I'd suggest the following (for now):

- disable "copy anchor link to clipboard" functionality for anonymous users of the website (this is a feature that no public website has anywhere in the world)
- keep the feature for now for logged-in users, integrators can disable it with a feature toggle
- change the wording of the notification from "Link copied to clipboard" to "Anchor link copied to the clipboard" to make it more obvious that an anchor link has been copied (again, this only works for editors that know the feature)
- fix the bug that the anchor link does not work if your headline has a special character (e.g. "Überschrift")
- disable the "copy to anchor link to clipboard" for the page title
- think about a solution for blocks that do not have text (e.g. image, maps, ...)
- consider this use case when implementing the new link widget

@sneridagh @davisagli @ericof @tiberiuichim does that sound like a reasonable plan?

**Comment by sneridagh** [comment]
- [x] disable "copy anchor link to clipboard" functionality for anonymous users of the website (this is a feature that no public website has anywhere in the world)
- [x] keep the feature for now for logged-in users, integrators can disable it with a feature toggle
- [x] change the wording of the notification from "Link copied to clipboard" to "Anchor link copied to the clipboard" to make it more obvious that an anchor link has been copied (again, this only works for editors that know the feature)
- [x] fix the bug that the anchor link does not work if your headline has a special character (e.g. "Überschrift")

Unfortunatelly this is a Chrome issue, it does works well in FF and Safari :( 

- [x] disable the "copy to anchor link to clipboard" for the page title
