### ISSUE TITLE
Sitemap does not render pages under the first level of navigation

### ISSUE THREAD

**Issue by erral** [plone/volto#5183]
**Describe the bug**
The sitemap renders just the first level of navigation

**To Reproduce**

1. Go to 'demo.plone.org'
2. Create a Page 1 in the Root of the site
3. Create a Page 2 in the root of the site
4. Create a Page 2-1 under Page 2
5. Create a Page 2-2 under Page 2
6. Go to Sitemap

**Expected behavior**
I expect to see (and the `Sitemap` component tries to render that):
- Page 1
- Page 2
  - Page 2 1
  - Page 2 2

**What I see **
- Page 1
- Page 2

![Pantaila-argazkia 2023-09-14 17-11-44](https://github.com/plone/volto/assets/817365/0f2a59a1-546c-4c9f-8a35-18d78be4521f)

**Additional context**

I see that under the hood the `@navigation` endpoint is properly called with the `expand.navigation.depth=4` value. 

Somewhere between the reducers, the value of the `items` key that holds the items under Page 2 disappear.

**Comment by Faizan711** [comment]
If anyone is not working on this issue, can I get assigned for it?
I would like to try to fix it.

**Comment by stevepiercy** [comment]
@Faizan711 please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html).

**Comment by tisto** [comment]
@erral what Volto version are you using? This is very odd since we have large sites in production where we regularly check the sitemap (e.g. https://www.dlr.de/sitemap-index.xml). @reebalazs worked on splitting the sitemap of larger sites, so maybe this is something that only occurs when the sitemap is not split?

@sneridagh @ericof it would be very helpful if we could get a demo instance with the latest Volto version up and running somewhere so that we can test those kinds of things with latest Volto (e.g. our kitconcept Volto dev instance).

**Comment by erral** [comment]
I am not talking about the sitemap.xml.gz but about the /sitemap, you can check it here: https://demo.plone.org/sitemap

The existing structure is:

- Page 1
- Page 2
 -  Page 2 1
- Page 3
 - Page 3 1
 - Page 3 2

The `@navigation` endpoint response is correct:

```json
{
  "@id": "https://demo.plone.org/@navigation", 
  "items": [
    {
      "@id": "https://demo.plone.org/page-1", 
      "description": "", 
      "items": [], 
      "review_state": "published", 
      "title": "Page 1"
    }, 
    {
      "@id": "https://demo.plone.org/page-2", 
      "description": "", 
      "items": [
        {
          "@id": "https://demo.plone.org/page-2/page-2-1", 
          "description": "", 
          "items": [], 
          "review_state": "published", 
          "title": "Page 2 1", 
          "use_view_action_in_listings": false
        }
      ], 
      "review_state": "published", 
      "title": "Page 2"
    }, 
    {
      "@id": "https://demo.plone.org/page-3", 
      "description": "", 
      "items": [
        {
          "@id": "https://demo.plone.org/page-3/page-3-1", 
          "description": "", 
          "items": [], 
          "review_state": "published", 
          "title": "Page 3 1", 
          "use_view_action_in_listings": false
        }, 
        {
          "@id": "https://demo.plone.org/page-3/page-3-2", 
          "description": "", 
          "items": [], 
          "review_state": "published", 
          "title": "Page 3 2", 
          "use_view_action_in_listings": false
        }
      ], 
      "review_state": "published", 
      "title": "Page 3"
    }
  ]
}
```

I would say that somewhere in the reducer we lose the inner items. I would say that `getRecursiveItems` loses the inner items, as if arrays in objects were not copied or something like that https://github.com/plone/volto/blob/master/src/reducers/navigation/navigation.js#L84

**Comment by erral** [comment]
We also have a large sitemap available in an older Volto version: https://www.deba.eus/eu/sitemap

**Comment by sneridagh** [comment]
@erral it has to do with the hasapiexpanders if present. I will take a look, since this code is mine.
