### ISSUE TITLE
Documentation: 'make develop' instead of 'yarn develop'

### ISSUE THREAD

**Issue by ksuess** [plone/volto#5195]
https://6.docs.plone.org/volto/addons/index.html#use-mrs-developer-to-manage-the-development-cycle

See upgrade guide https://6.docs.plone.org/volto/upgrade-guide/index.html#upgrade-to-use-yarn-3

**Comment by stevepiercy** [comment]
There's another place that might need updating. I am not familiar, so please let me know. It was for upgrading to Volto 16.

https://6.docs.plone.org/volto/upgrade-guide/index.html#upgrade-to-use-yarn-3

Step 3:

> Change your package.json scripts section:
> `-    "preinstall": "if [ -f $(pwd)/mrs.developer.json ]; then if [ -f $(pwd)/node_modules/.bin/missdev ]; then yarn develop; else yarn develop:npx; fi; fi",`

https://github.com/plone/volto/blame/59b9dc02a59dee3a82a121d4ea730643b8f9bd7c/docs/source/upgrade-guide/index.md#L512
