### ISSUE TITLE
create-addon-loader.js uses deprecated buffer api

### ISSUE THREAD

**Issue by ichim-david** [plone/volto#5198]
**Describe the bug**
For fun I wanted to see if Volto would run with bun.sh, which results in an
error from create-addon-loader.js
```
fs.writeFileSync(addonsLoaderPath, new Buffer.from(code));                                     ^
TypeError: function is not a constructor (evaluating 'new Buffer.from(code)')
```

It seems that we are using a deprecated call even when using Node 16.
https://nodejs.org/docs/latest-v16.x/api/buffer.html#new-bufferarray

**Expected behavior**
We should use Buffer.from(code) instead of new Buffer.from(code)

**Comment by meltedhyperion** [comment]
@ichim-david can I work on this?

**Comment by ichim-david** [comment]
@meltedhyperion  sure, the fix is super easy actually
https://github.com/plone/volto/blob/master/create-addons-loader.js#L108
remove the new before Buffer and then volto starts both on node and bun.sh

**Comment by meltedhyperion** [comment]
I have submitted my agreement now. When can I expect to be added to the team

**Comment by ichim-david** [comment]
@meltedhyperion  it seems @Junko-Takeguchi already took the initiative and made the change without asking for permission.
Regarding the agreement you have to check the documentation, it should be automatic but it's been quite a few years since I've signed mine and I don't know what is the latest procedure.

**Comment by meltedhyperion** [comment]
Ya.. I saw the PR, I believe the test deployment is failing due to inconsistent pipeline checks. If the issue is there till I get my access. Will make a separate PR.
@ichim-david

**Comment by stevepiercy** [comment]
@meltedhyperion @ichim-david @Junko-Takeguchi we do not grant permission to work on or assign issues. Specifically, see [Make contributions through GitHub](https://6.docs.plone.org/contributing/first-time.html#make-contributions-through-github). We cannot manage other developers' work, but request that developers collaborate and coordinate amongst themselves.

**Comment by stevepiercy** [comment]
@meltedhyperion for a timeline, see [Plone Contributors Team](https://6.docs.plone.org/contributing/first-time.html#plone-contributors-team).

**Comment by Junko-Takeguchi** [comment]
@ichim-david @stevepiercy sorry for the miscommunication, I jumped onto the issue without adding a comment, I will keep that in mind from now on.
