### ISSUE TITLE
Comment input field should be a textarea

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#5265]
https://github.com/plone/volto/blob/c71a6ca108edca42dac2171e8c521cb26b92ce2a/src/components/theme/Comments/CommentEditModal.jsx#L62

**Comment by anish-patro** [comment]
@tiberiuichim I want to work on this issue, can you please assign it to me.

**Comment by anish-patro** [comment]
@stevepiercy @tiberiuichim can you please review the PR?

**Comment by tiberiuichim** [comment]
type: "textarea" will not work. If you make a PR, please take the effort to try to understand the problem that the ticket is raising and test that the code does what you claim (to fix the issue).

No low-effort PRs, only for the sake of having a PR on your CV. Personally, I don't think we need this sort of contributions.

**Comment by anish-patro** [comment]
> type: "textarea" will not work. If you make a PR, please take the effort to try to understand the problem that the ticket is raising and test that the code does what you claim (to fix the issue).
> 
> No low-effort PRs, only for the sake of having a PR on your CV. Personally, I don't think we need this sort of contributions.

Thank you for your feedback. I apologize if my previous PR seemed low-effort; that was not my intention. I will make sure to thoroughly understand the problem and rigorously test the code before submitting any future PRs.

**Comment by Ravi-kumar9347** [comment]
Hey @tiberiuichim, this issue interest me . i would like to know if anyone working on this issue at the moment, if not please assign this issue to me.

**Comment by stevepiercy** [comment]
@Ravi-kumar9347 we do not assign issues. It is your responsibility to check for linked pull requests (I see none). See items 1 and 2 in https://6.docs.plone.org/contributing/first-time.html#things-not-to-do. That page provides other helpful guidance.

**Comment by Ravi-kumar9347** [comment]
hey , i am trying to make a PR for this issue. But it is showing the error :
ravi@ravi-Vivobook-ASUSLaptop-M6500IH-M6500IH:~/volto/volto$ git push origin textarea
ERROR: Permission to plone/volto.git denied to Ravi-kumar9347.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

can anyone help me ?

**Comment by stevepiercy** [comment]
@Ravi-kumar9347 start reading from here: https://6.docs.plone.org/contributing/first-time.html#set-up-your-environment. I think you have misconfigured item 3.
