### ISSUE TITLE
Control panel pages show title and breadcrumbs from the previous context content

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#5285]
**Describe the bug**
The breadcrumb show the "Test" title location because that was the last page that was viewed

<img width="1217" alt="Screenshot 2023-10-07 at 10 02 24" src="https://github.com/plone/volto/assets/141568/d165580d-a7b4-4854-8f9e-ad920ee70c3c">

**To Reproduce**

Go to demo.plone.org, create a new Page, save it, go to the Site Setup, notice the problematic breadcrumb

**Comment by Sejal1411** [comment]
Could you pls assign this issue to me.

**Comment by tiberiuichim** [comment]
It's fixed.
