### ISSUE TITLE
Empty link element left hanging when we hit enter at end of link.

### ISSUE THREAD

**Issue by iFlameing** [plone/volto#5291]

**Comment by ashirupgraded** [comment]
can you show any video>?

**Comment by stevepiercy** [comment]
@ashirupgraded please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html).

**Comment by sneridagh** [comment]
Fixed several weeks ago.
