### ISSUE TITLE
Search Block Facet Select values are clipped on mobile resolutions

### ISSUE THREAD

**Issue by ichim-david** [plone/volto#5315]
**Describe the bug**
When using a Facet with several values such as portal types the select values get clipped when there is not enough
space to render the entire list as there is no scrollbar

1. Go to a search block
2. Add a facet with portal type value
3. Set emulation to mobile and scroll to interact with the facet
4. See content being clipped

**Expected behavior**
Every select option should be visible and not be clipped

**Screenshots**
![values-facet-select](https://github.com/plone/volto/assets/152852/98ea44d8-062d-427d-89b8-c690d3259458)
![value-mobile](https://github.com/plone/volto/assets/152852/3fda4df2-d643-4bf2-adb9-daa9468acf48)

**Software (please complete the following information):**
- OS: [Mac OS X]
- Browser [Firefox]
- Volto Version [16.22]

**Comment by Anubhav-Chauhan3367** [comment]
Can I work on this? Please assign this issue to me. @ichim-david

**Comment by ichim-david** [comment]
@Anubhav-Chauhan3367 you are not a member of the Plone organization, and I already have a colleague working on this issue that I have added.

**Comment by stevepiercy** [comment]
@Anubhav-Chauhan3367 also please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html).

**Comment by ichim-david** [comment]
@dobri1408 the issue was incorrect as it was not because of Volto that got fixed with never versions but it happened because of another one of our addons volto-block-styles
We will have a fix to remove the offending code there in case someone uses some of our packages that are dependent on volto-block-styles
<img width="524" alt="volto-block-styles" src="https://github.com/plone/volto/assets/152852/f3b442d5-8a27-445d-95fd-f9ed5879d694">
