### ISSUE TITLE
[docs] Review and update testing and code quality commands

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#5341]
I think Volto's documentation on what commands need to be run needs to be reviewed and updated.

- [Code quality](https://6.docs.plone.org/volto/contributing/index.html#code-quality), which has links to the three pages:
- [Linting](https://6.docs.plone.org/volto/contributing/linting.html)
- [Testing](https://6.docs.plone.org/volto/contributing/testing.html)
- [Acceptance testing](https://6.docs.plone.org/volto/contributing/acceptance-tests.html)

_Originally posted by @stevepiercy in https://github.com/plone/volto/issues/5331#issuecomment-1779955840_

**Comment by kunal-511** [comment]
Please assign this issue to me i would like to work on this

**Comment by stevepiercy** [comment]
@kunal-511 please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html).

**Comment by ichim-david** [comment]
I'll try to work on this issue, I think we are too spread on all of these issues, and we need to have a page with A-Z steps on what is needed to get from bug report to pull request that is ready for review within he Contribute to Volto section

**Comment by stevepiercy** [comment]
We should also update `Makefile` with eslint and prettier commands. I had to look them up in https://github.com/plone/volto/blob/main/.github/workflows/code-analysis.yml. Relying on one's editor configuration or https://github.com/plone/volto/blob/main/.husky/pre-commit is not a great option. All those dot files at the root! I have no clue what they do in regards to code quality and linting.
