### ISSUE TITLE
[docs] "copy to clipboard"  button not copying the whole text

### ISSUE THREAD

**Issue by arujjval** [plone/volto#5345]
**Describe the bug**
In ([the install from packages page](https://6.docs.plone.org/install/install-from-packages.html)), in the section on the installation of Yarn 3, when copying the Yarn version by clicking on "copy to clipboard", it does not copy the whole text.

![section](https://github.com/plone/volto/assets/106719640/c452c768-95b8-48bf-88e3-702502613509)

what is actually copies

![actual result](https://github.com/plone/volto/assets/106719640/3654f3df-609e-4c2c-9bdc-42399070ed88)

I know it's small but still, a bug's a bug.

**Comment by stevepiercy** [comment]
Thanks for the report. It looks like there was a [change in a Sphinx extension `sphinx-copybutton`](https://sphinx-copybutton.readthedocs.io/en/latest/use.html#automatic-exclusion-of-prompts-from-the-copies) where the class `linenos` is now excluded by default, making the regex in conf.py no longer necessary. We will need to update all the other projects that use this setting.

PR incoming.

**Comment by stevepiercy** [comment]
PRs also submitted for training, volto, and plone.restapi. plone.api does not use this extension:

- https://github.com/plone/training/pull/821
- https://github.com/plone/volto/pull/5346
- https://github.com/plone/plone.restapi/pull/1725

**Comment by DhanushShettyH** [comment]
i want to work on this

**Comment by stevepiercy** [comment]
@DhanushShettyH please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html).

Moreover I already submitted a PR, as [my above comment clearly indicates](https://github.com/plone/volto/issues/5345#issuecomment-1784486473).

**Comment by stevepiercy** [comment]
Closed by https://github.com/plone/volto/pull/5346
