### ISSUE TITLE
"Edit Recurrence" button in Recurrence widget is not aligned properly

### ISSUE THREAD

**Issue by ujjwalpathaak** [plone/volto#5359]
**Describe the bug**
The "Edit Recurrence" button present in the recurrence widget while adding or editing an event is not aligned properly.

**To Reproduce**

1. Go to 'Homepage'
2. Click on 'Add'
3. Select 'Event'
4. Scroll down to 'Recurrence'
5. See error

**Expected behavior**
The button should be properly aligned with the title "Recurrence"

**Screenshots**
![image](https://github.com/plone/volto/assets/92005669/cd5c3cba-b2c9-4efc-a5e4-f519eab1c76a)

**Comment by ujjwalpathaak** [comment]
I am working on this issue

**Comment by stevepiercy** [comment]
@keshav2025 no. See the purple "Closed" icon at the top of the issue.

Also please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do).
