### ISSUE TITLE
Control panel order should be alphabetical within groups or match what is in Classic UI

### ISSUE THREAD

**Issue by tkimnguyen** [plone/volto#5374]
It would be nice to have control panels appear in some sensible order, or do I have to https://github.com/collective/collective.sortedcontrolpanels all over again?!? 😆 Don't make me... you'll regret it 🤓 

![image](https://github.com/plone/volto/assets/815418/e167476d-9ca1-492c-8b23-edeebe89274f)

**Comment by davisagli** [comment]
There's a PR which got lost in the shuffle: https://github.com/plone/volto/pull/3737

**Comment by tkimnguyen** [comment]
/me living dangerously clicking on stuff in the GitHub UI for that PR

**Comment by davisagli** [comment]
Fixed in #3737
