### ISSUE TITLE
PreviewImage does not fallback to default image.

### ISSUE THREAD

**Issue by teekuningas** [plone/volto#5379]
**Describe the bug**

The PreviewImage component used in listings does not fallback to default image.

I suspect the reason it this: 

https://github.com/plone/volto/blob/f1610c50961654b5acfb40d26452dd4d126390e2/src/components/theme/PreviewImage/PreviewImage.jsx#L19

The jsx object is probably always truthy.

**To Reproduce**

Have a summary listing with items with no lead images.

**Expected behavior**

Default images should appear if there's no lead images.

**Software (please complete the following information):**

- Volto Version [e.g. 17.4.0]
- Plone Version [e.g. 6.0.1]

**Comment by Abro0058T** [comment]
@teekuningas  can i work  on this issue ?

**Comment by stevepiercy** [comment]
@Abro0058T please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html).

**Comment by steffenri** [comment]
PR: https://github.com/plone/volto/pull/5565

**Comment by davisagli** [comment]
Fixed in #5565 

@steffenri Link a PR to an issue by putting "Fixes #5565"; then github will close the issue automatically when the PR is merged.
