### ISSUE TITLE
Remove releases.md

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#5382]
There is an orphan file that needs its content to be migrated or deleted, then the file itself removed from `docs/source/releases.md`.

**Comment by Prakhar-Shankar** [comment]
Hi, should we delete the whole `releases.md` file?

**Comment by stevepiercy** [comment]
@Prakhar-Shankar what does the issue description say?

Also please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html).
