### ISSUE TITLE
Remove cheatsheet.md

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#5383]
Much of the content in `docs/source/cheatsheet.md` already exists in Plone 6 Documentation and other resources. This file should probably be deleted, after review by the docs-reorg team.

**Comment by Amangupta7011** [comment]
please
Kindly assign me that issue.

Best Regards,
Aman gupta

**Comment by stevepiercy** [comment]
@Amangupta7011 no. See https://6.docs.plone.org/contributing/first-time.html#things-not-to-do.
