### ISSUE TITLE
Update readme to 20.x from 18.x LTS

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#5389]
We recommend 18.x LTS: https://github.com/plone/volto#supported-nodejs-versions.

> Volto runs using [Node.js](https://nodejs.org/). We recommend using the current LTS version (18.x).
> - Node.js 20: Supported since Volto 17.

Should these lines be changed to:

```markdown
Volto runs using [Node.js](https://nodejs.org/). We recommend using the current LTS version.

- Node.js 20 LTS: Supported since Volto 17.
```

_Originally posted by @stevepiercy in https://github.com/plone/documentation/pull/1574#discussion_r1386574960_

**Comment by Noobham** [comment]
Hey Buddy,
I am very new to open source . I have raised my first PR in this org .


Do I have to update in Changelog file too before raising any PR ???
Waiting for your response

**Comment by Noobham** [comment]
> @Noobham please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html). Volto is not covered by the same license as Documentation, which is another repository.

Before raising this PR , I have signed to plone contribution agreement .
Do i have to make a file ./news named 5389.documentation and write about changes that i have made ??

**Comment by stevepiercy** [comment]
@Noobham again, please read and follow every section in the links, including https://6.docs.plone.org/contributing/index.html#change-log-entry.

**Comment by Noobham** [comment]
@stevepiercy Thank you for quick response . I throughly read contribution page and made all changes required for pushing code.

But still I have left 1 failed test in my PR.
- 29 successful, 1 errored, and 3 neutral checks
1 error occurred due to
- Plone Contributors Agreement verifier.

I have already signed the contributor agreement and received confirmation mail from Plone Org.

Waiting for your Response 
Thanks.

**Comment by stevepiercy** [comment]
@Noobham you must follow the helpful advice from https://github.com/plone/volto/pull/5393#issuecomment-1808632786.
