### ISSUE TITLE
Adopt a full monorepo approach in the Volto repo

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#5411]
## Responsible Persons
Víctor Fernández de Alba (@sneridagh)

### Proposer:
Víctor Fernández de Alba (@sneridagh)

### Seconder:
Tiberiu Ichim (@tiberiuichim)
Piero Nicolli (@pnicolli)

## Abstract
Adopt a (full) monorepo approach in the Volto repo, using `pnpm` as a package manager and `Turborepo` as monorepo manager.

### The monorepo move
Over the years, we've been introducing some support packages in the Volto repo, and placing them in the `/packages` folder, but without adopting a full monorepo approach. This was motivated because of the downsides of adopting it. Moving to a monorepo approach would have been costly and a huge effort, and it would have change the shape of the project itself and the development approach used. The amount of side packages that Volto had, never justified the change. Some workarounds are in place to make it work in a half-monorepo approach, using aliases and shortcuts given by the packaging system. However, these are the packages "outside" the core code (`src` folder):

- @plone/volto-slate (internal, not released)
- @plone/scripts
- @plone/registry

and not used directly by the core:

* @plone/generator-volto
* @plone/volto-testing
* @plone/volto-coresandbox (internal)
* @plone/volto-guillotina

However, the scenario has changed in the last months, since the community is moving forward completing the transition to a true headless CMS, providing the necessary tools for this to happen.

We are introducing these strategic packages:

* @plone/registry
* @plone/client
* @plone/components
* @plone/types

and others will follow:

* @plone/nextjs
* @plone/remix
* ...

These last will be integrations, or "glue packages", needed for each framework. 

The strategic packages are shared, and the interactions between all of them will increase, as development advances.

Also, having a central place, rather than a bunch of repos, where development happens now makes more sense. This is not only for development, but also CI, local testing, and prototyping—all in one place.

```console
plone-frontend/
├─ apps/
│  ├─ plone
│  ├─ nextjs
│  ├─ remix
├─ packages/
│  ├─ volto
│  ├─ client
│  ├─ components
│  ├─ registry
│  ├─ types
│  ├─ coresandbox
│  ├─ generator-volto
│  ├─ scripts
│  ├─ tsconfig
│  ├─ volto-guillotina
│  ├─ volto-slate
│  ├─ volto-testing
├─ .gitignore
├─ package.json
├─ pnpm-workspace.yaml
├─ turbo.json
├─ tsconfig.json
```

A monorepo allow you to share effectively also the TypeScript configuration between projects. 

### `pnpm`
The motivation behind the proposal of this move is mainly technological. `npm` has been behind `yarn` in so many aspects over the years, although `npm` eventually endup improving a lot too, but the differences are still noticeable (in performance above all). Over the years, other package managers have been popping up, the most noticeable one being `pnpm`. The approach that `pnpm` uses makes very much sense. The most important one, it uses a symlinked node_modules structure as opposed to their counterparts that use a flat node_modules. It does not only boost the installation speed, and the disk space required, but gets rid of problems with hoisted packages. See [https://pnpm.io/motivation](https://pnpm.io/motivation) for more information.

Regarding managing monorepos, their implementation of "workspaces" feature is better than the others, and the integration with the sym-linked structure is more natural. 

Nowadays, `pnpm` is the tool of choice for maintaining big and complex monorepos in a lot of famous repositories. See [the examples](https://pnpm.io/workspaces#usage-examples).

Using [Turborepo](https://turbo.build/repo) (or other monorepo management tool) will also help during development and doing day to day tasks.

Having a local example of a project using Volto as a library, and use it as default way to implement Volto will also help to get a real grasp on the real way to use Volto in the "real life". Testing against that will also help to spot errors and flaws in code early. Same for the other integrations.

It will also help the integration and adoption of the strategic packages into Volto itself in the upcoming months.

## Assumptions

The premise is that we do not introduce now a big change in the way that integrators and existing projects work with Volto. The nature of the change allows that the projects can still use `yarn` and continue working the way they used to do.

The move of projects to `pnpm` should be addressed from another PLIP. Although this improvement is desireable in the short term, is not strictly needed now, but should be encourage to adopt in the near future.

## Proposal & Implementation

`pnpm` requires that all the packages have their dependencies declared explicitly in their `package.json` files. We've been relying in dependency resolving too much, and when coming to a Volto project's dependencies, we leaned far too much on this, trusting in the dependencies coming from Volto itself. Although this just worked for years for us, it prevents us from moving forward and complying with the JavaScript ecosystem.

Reorganize and move things around given the above folder structure.

Update the Github actions and CI workflows to match the new structure. Update the Towncrier check to look inside the monorepo folders.

## Deliverables

- A re-shaped Volto repository using a monorepo approach, following the folder structure showed above.
- Documentation explaining how to develop core Volto from now on, and the changes made.
- Updated convenience `Makefile` commands

## Risks
The re-shape comes with its own risks: the core developers will have to get used to the new way of doing things.

These are a summary of the changes a core developer should expect:

- Reorganising the repo - things will be placed in different folders
- Switch to use `pnpm` instead of `yarn` as package manager
- Use `Turborepo` as monorepo handling tool (although we won't be using it that much at the beginning since `pnpm` has a compelling set of tools for handling monorepos too)

Internal changes to the Volto resolution and the project will be made, and some customization features will have to be re-checked and re-tested. All semi-monorepo hacks will be renamed or removed. The Razzle build relied too much on file collocation, but this has to change to real module resolution. The add-on registry will also have to adapt. All the existing features will have to be tested properly.

## Participants

@plone/volto-team 
@plone/documentation-team

**Comment by gauravsingh94** [comment]
Hi @sneridagh, I've got some experience with monorepos( like turborepos). If it's okay with you, I'd be happy to work together to switch this project to a monorepos format. I'd really appreciate the chance to contribute to the project.

**Comment by stevepiercy** [comment]
@gauravsingh94  please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html). In particular, from https://6.docs.plone.org/contributing/first-time.html?highlight=plip#work-with-github-issues:

> Issues labeled 42 lvl: moderate, 43 lvl: complex, or 03 type: feature (plip) are not suitable for first-timers because of their complexity. Issues with these labels may take weeks to complete.

**Comment by polyester** [comment]
A question for my understanding: does this change also affect toolchains, ways of working, best practices etc for other target audiences than core developers? Like integrators, theme developers, add-on developers. If so, we need to make sure that is also reflected in documentation for those audiences.

**Comment by sneridagh** [comment]
@polyester You are right, these changes will only apply to the way of developing Volto core. 
The rest is left untouched (I'm making sure of this). The integrators can still work as before, no changes there at all. Even they can continue using `yarn`, and it still works.

We *must* document this before we push the button, so the Volto core developers have a good source of information about the changes and the way to proceed once the monorepo is in place. We should communicate properly also that the changes do NOT apply for integrators or Volto consumers, and they will have to do nothing about it **(*)**. 

The idea is also to improve the main `Makefile` so the convenience commands are still available and do what they used to do.

The changes can be summarised in:

- Reorganising the repo - things will be placed in different folders
- Switch to use `pnpm` instead of `yarn` as package manager
- Use `Turborepo` as monorepo handling tool (although we won't be using it that much at the beginning since pnpm has a compelling set of tools for handling monorepos too)

Disclaimer **(*)**: Since this changes happen inside a breaking cycle, users will have to follow the usual upgrade guide steps.

I will add this info above too.

**Comment by sneridagh** [comment]
@polyester re-reading the PLIP, I have to update things that changed during this weekend (the corroboration that there is not need to switch to `pnpm` in the existing projects.

**Comment by sneridagh** [comment]
Applied in #5409 .
