### ISSUE TITLE
YouTube video embed results to error if video url contains /live/

### ISSUE THREAD

**Issue by rioksane** [plone/volto#5416]
YouTube video embed results to error if video url contains /live/

```
Sorry, something went wrong with your request
t.url.match(...) is null
```

Tested at https://demo.plone.org

**To Reproduce**

1. Go to https://www.youtube.com/watch?v=ISdHvS6Ck3k&list=PLGN9BI-OAQkSXMXVBXLWQAQr0AF2xM_NU&index=19
2. Click on Share
3. Copy link https://www.youtube.com/live/ISdHvS6Ck3k?si=COeVakmC1lI6jQy3
4. Go to Plone 6 Volto site add a new page and add video embed block. 
5. Paste url and save page.

**Expected behavior**
Video embed should work

**Screenshots**
<img width="1160" alt="Screenshot 2023-11-20 at 19 15 00" src="https://github.com/plone/volto/assets/5127672/0a0e1086-2550-42a5-9d2a-3c5be2da3097">
<img width="995" alt="Screenshot 2023-11-20 at 19 17 50" src="https://github.com/plone/volto/assets/5127672/de2da89e-f4da-437d-9d9e-61bd8c67585b">

**Software (please complete the following information):**

- OSX
- Firefox
- Volto Version 
    plone6-demo 1.0.0
    Volto 17.5.0
    Plone 6.0.8
    plone.restapi 9.1.2
    CMF 3.2
    Zope 5.8.6
    Python 3.11.6 (main, Nov 1 2023, 14:02:22) [GCC 10.2.1 20210110]
    PIL 9.5.0 (Pillow)

**Comment by rioksane** [comment]
@ericof this is the video embed issue mentioned

**Comment by pranayjoshi** [comment]
Where is the Video embed option. I can only see the option to add page links etc.

**Comment by IshaanDasgupta** [comment]
I am working on this

**Comment by kuv2707** [comment]
Is the issue resolved?

**Comment by stevepiercy** [comment]
@IshaanDasgupta no worries. We're all learning how to improve and use GitHub features here.
