### ISSUE TITLE
Add cypress tests for the delete item modal

### ISSUE THREAD

**Issue by jackahl** [plone/volto#5428]
Currently we do not have cypress testing for the modal that pops up, when you try deleting an item that is linked somewhere else. We should create that sometime soon. I already started refactoring my code for the link integrity view to test this here: https://github.com/plone/volto/blob/delete-item-modal-cypress/cypress/tests/core/basic/delete-item-modal.js

**Comment by Molochem** [comment]
Lorem

**Comment by Nishannb** [comment]
can you assign me this issue ?

**Comment by stevepiercy** [comment]
@Nishannb please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html). We do not assign issues.

**Comment by Abro0058T** [comment]
@jackahl  can i take up this issue ? I have previously written test cases  in jest .

**Comment by stevepiercy** [comment]
@Abro0058T please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html).

You should note that @jackahl assigned @Molochem to [work on this issue](https://github.com/plone/volto/issues/5428#event-11046283655). You are welcome to work on it, but I would advise not duplicating any effort that they might have already put forth, as is explained in [First-time contributors](https://6.docs.plone.org/contributing/first-time.html).

**Comment by Abro0058T** [comment]
@Molochem please let me know if you are still working on this issue to avoid duplicating any effort .
