### ISSUE TITLE
Site Setup - User Group Membership

### ISSUE THREAD

**Issue by andreclimaco** [plone/volto#5447]
Error validating the plone.restapi version.

![Captura de tela de 2023-11-27 10-55-09](https://github.com/plone/volto/assets/1651582/d2a2fa04-28ab-499a-a1c0-12e27f2ac050)

components/manage/Controlpanels/Users/UserGroupMembershipControlPanel.jsx

line 40:42

```javascript
const can_use_group_membership_panel = systeminformation
? toNumber(systeminformation?.plone_restapi_version.slice(0, 4)) >= 8.24
: false;
```

Bug scenario:
* plone.restapi 9.2.0
	- code: **toNumber(systeminformation?.plone_restapi_version.slice(0, 4))**
	- output: **NaN**

Correction suggestion:
* plone.restapi 9.2.0
	- code: **parseFloat(systeminformation?.plone_restapi_version.slice(0, 4))**
	- output: **9.2**

**Comment by stevepiercy** [comment]
@Shibbu264 please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html). We do not assign issues.

**Comment by stevepiercy** [comment]
No problem, we're here to point you to the right path.
