### ISSUE TITLE
Broken autoformat / markup shortcuts for headings in Slate text block

### ISSUE THREAD

**Issue by mbarde** [plone/volto#5452]
**Describe the bug**

Markup shortcuts for headings (`#` for h2 or `##` for h3) in slate text blocks do not work (anymore).

**To Reproduce**

* Go to https://demo.plone.org (or any other page using Volto 17.x)
* Edit a page
* Add text block
* Enter `# new heading`
* Text still formatted as normal text, but heading icon is selected in toolbar (see screenshot)

JSON of block looks like this:

```JSON
{
  "@type": "slate",
  "plaintext": "heading",
  "value": [
   {
    "type": "p",
    "children": [
     {
      "text": "heading",
      "type": "h2"
     }
    ]
   }
  ]
 }
 ```

**Expected behavior**

Text should be formatted as heading.

JSON should like that (as opposed to above snippet):

```JSON
{
  "@type": "slate",
  "plaintext": "heading",
  "value": [
   {
    "type": "h2",
    "children": [
     {
      "text": "heading",
      "type": "h2"
     }
    ]
   }
  ]
 }
 ```

**Screenshots**

![Screenshot_2023-11-28_14-25-53](https://github.com/plone/volto/assets/4497578/72d830a1-8753-4225-ab03-7e60ffab6dd1)

**Software (please complete the following information):**

- Plone Version: 6.0.8
- Plone REST API Version: 9.1.2
- Volto Version: 17.6.0
- OS: Ubuntu 22.04
- Browser: Firefox, Google Chrome

**Comment by pranayjoshi** [comment]
The case is same in the case of Italics and every other commands

**Comment by Nishannb** [comment]
Can you please assign it to me. I found the bug.

**Comment by stevepiercy** [comment]
@Nishannb please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html). We do not assign issues.
