### ISSUE TITLE
Volto 17: Unexpected 500 Error while appending `/view` to a file URL

### ISSUE THREAD

**Issue by shogunbr** [plone/volto#5461]
**Describe the bug**
When accessing a URL to a file, appending `/view` at the end of the URL using Volto 17 results in a 500 error. 
I'm migrating an old site that have many links to files that include ""/view" on the URL. I know "/view" on Volto is not supposed to show anything, so i fixed the internal links in the migration process.
Horever when accessing those old links using Volto 16 returns a 200 response, displaying a blank page, while Volto 17 consistently triggers a 500 error.

**To Reproduce**

1. Upload a file
2. Access the URL of the file appending `/view` at the end: `http://localhost:3000/foo.pdf/view`
3. It will trigger a 500 Server Error.

**Expected behavior**
Volto 16 returns a 200 response, displaying a blank page, while Volto 17 triggers a 500 error

**Screenshots**
![image](https://github.com/plone/volto/assets/17334632/1b4bf644-47d2-4015-8930-74a20eba0a53)

**Software (please complete the following information):**

- OS: any
- Browser any
- Volto Version 17.6.1
- Plone Version 6.0.8
- Plone REST API Version 9.1.2

**Additional context**

**Comment by akshayw1** [comment]
I would like to work on this!Please assign

**Comment by sneridagh** [comment]
Closing, since it's expected and documented.
