### ISSUE TITLE
Wrong pagination on the search result page if we change the defaultPageSize setting

### ISSUE THREAD

**Issue by wesleybl** [plone/volto#5464]
**Describe the bug**
When we change the [defaultPageSize](https://github.com/plone/volto/blob/main/packages/volto/src/config/index.js#L124) setting, the search result lists 25 results per page, but the pagination follows `defaultPageSize`.

**To Reproduce**

1. Change `defaultPageSize` to 6
2. Create 26 pages with the title "Test"
3. Search for the term "Test"
4. See that 25 results are shown on the result page, but the pagination shows 5 results pages.

**Expected behavior**
Pagination shows 2 result pages.

**Screenshots**
![download (9)](https://github.com/plone/volto/assets/3297795/a965e532-9db6-491e-8637-1493a5afaf39)

**Comment by wesleybl** [comment]
Or is the ideal number of items per page in the search follow `defaultPageSize`?

**Comment by wesleybl** [comment]
@EshaanAgg I think the parameter you should pass to the api is `b_size`. Documentation about this is here:

https://plonerestapi.readthedocs.io/en/latest/usage/batching.html

**Comment by EshaanAgg** [comment]
I have opened a PR with the fix for the same, but I can't seem to get the CI/CD to pass. Are there any changes that are required on my end?

**Comment by stevepiercy** [comment]
@EshaanAgg do tests pass on your machine?

**Comment by EshaanAgg** [comment]
@stevepiercy 
I ran the test locally, and a couple of them failed, but all of them seem to be related to `api` and not the changes that I made. I used the `make test` to run the test suite.
![image](https://github.com/plone/volto/assets/96648934/11ab158c-fe3f-4fe4-bf46-60e0dbc94143)

Example of a failed test:
![image](https://github.com/plone/volto/assets/96648934/6543a1fe-8d86-4880-a626-73d0cb47ab54)

I also ran the `pnpm test` command after inspecting the workflows, and they all seem to fail with the following (most probable configuration or dependency-related) error:
![image](https://github.com/plone/volto/assets/96648934/35f569aa-cb72-480c-aac5-73d139c74de7)

**Comment by EshaanAgg** [comment]
Update: It was an error due to a broken and wrong import. Fixed it in the latest commit. Thanks!

**Comment by stevepiercy** [comment]
@EshaanAgg happy to be your [rubber  :duck:](https://rubberduckdebugging.com/).
