### ISSUE TITLE
Storybook build is broken

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#5469]
The Storybook build was recently broken, which in turn prevents Documentation from being deployed to Production.

Error message from workflow:

https://github.com/plone/documentation/actions/runs/7046392784/job/19178099347

**Comment by sneridagh** [comment]
Fixed in https://github.com/plone/documentation/pull/1585

**Comment by stevepiercy** [comment]
Superseded by https://github.com/plone/documentation/pull/1586 without a submodule update.
