### ISSUE TITLE
Addition of an Announcement Block-for Version announcement /Conference Links

### ISSUE THREAD

**Issue by ujjwaleee26** [plone/volto#5516]
An Announcement Block
There are many a times when new `Volto`/' Plone` are released . To just display as an announcement message on main website. Integration of new Announcement Block. It can contain a link to redirect to page where detailed description can be found

for example ,like this,
<img width="811" alt="Screenshot 2023-12-12 at 4 12 10 PM" src="https://github.com/plone/volto/assets/138270264/c8ad290d-a950-425e-a5e7-ae1d186a64bc">

**Comment by stevepiercy** [comment]
How would this block be different from either of the following?

- [Teaser block](https://6.docs.plone.org/volto/user-manual/blocks.html#teaser-block)
- [Hero block](https://6.docs.plone.org/volto/user-manual/blocks.html#hero-block)

**Comment by ujjwaleee26** [comment]
@stevepiercy 
**Teaser block**
- [ ]  Creates visually impactful banners or headers at the top of a page.
**Hero Block**
- [ ] It is ideal for providing a preview of content and encouraging visitors to click through to view the full content.

But **Announcement Block**
- [ ] Suitable for  displaying time-sensitive announcements or news on the main website.  A real emphasis making feature which can be used once or more on the main page to give vistors a thought that ,yeah this looks important/ or so less time for this event , lets register faster .Basically a small reminders on website only used for time-sensitive announcements.

**Comment by ujjwaleee26** [comment]
` pnpm eslint --max-warnings=0 --fix:
ESLint found too many warnings (maximum: 0).
/Users/ujjwalsinha/volto/packages/volto/src/components/index.js
  0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override`.   Its showing this

**Comment by stevepiercy** [comment]
Maybe this will help? https://6.docs.plone.org/volto/contributing/linting.html

**Comment by stevepiercy** [comment]
@ujjwaleee26 see a follow up to your community forum post, and possibly this PR which I think fixes the issue you described. @sneridagh can you verify?

- https://community.plone.org/t/could-not-find-react-redux-context-value-github-repo-issue/18338/7
- https://github.com/plone/volto/pull/5530

**Comment by sneridagh** [comment]
First of all. This block does NOT belong to the core. If you want to contribute with it, please do it as an add-on.

Second, did you try latest Volto core? I fixed it this week. We are still in an interim fixing things related with the monorepo change. This has to be with the unified ESlint config and `lint-staged`. If you need to disable it, make the commit with `--no-verify`.

**Comment by ujjwaleee26** [comment]
@sneridagh I have made commits using  `--no-verify` only .  So if commit it again with as an add-on, can I please get a review regarding my PR?

**Comment by nileshgulia1** [comment]
> @sneridagh I have made commits using  `--no-verify` only .  So if commit it again with as an add-on, can I please get a review regarding my PR?

@ujjwaleee26 The above comment means the addon will not belong to this repo. If you really think this block would be beneficial for the community you can publish it somewhere and ask for review in the community forum. If that addon proves to be super useful, it can be considered for publishing under @plone-collective. Note that "not all" addons can be published under collective.

**Comment by ujjwaleee26** [comment]
@nileshgulia1  I don't have much Idea about publishing it somewhere . I am very new to this `Volto`. I just know how to develop basic things. Is there a process or something?

**Comment by nileshgulia1** [comment]
> @nileshgulia1 I don't have much Idea about publishing it somewhere . I am very new to this `Volto`. I just know how to develop basic things. Is there a process or something?

You can publish it under npm with your name. https://docs.npmjs.com/creating-and-publishing-unscoped-public-packages

**Comment by ujjwaleee26** [comment]
@nileshgulia1  thanks, I will publish it , but does that mean I have close this PR, or I can leave it here , just for @maintainers to review, if they could, cause as first time contributor,I tried my best?

**Comment by stevepiercy** [comment]
@ujjwaleee26 that would be putting the cart before the horse. Please do publish it as an add-on, and seek support and feedback from the Community Forum. This issue tracker is focused on Volto core only. Closing.

**Comment by wesleybl** [comment]
> pnpm eslint --max-warnings=0 --fix: ESLint found too many warnings (maximum: 0). /Users/ujjwalsinha/volto/packages/volto/src/components/index.js 0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override

@sneridagh I had this same problem when trying to make a commit. Your tip worked:

> If you need to disable it, make the commit with --no-verify

Is this still an issue you are checking into?
