### ISSUE TITLE
A small typo in contributing-core.md file

### ISSUE THREAD

**Issue by ujjwaleee26** [plone/volto#5537]
the `pnp`   typo command does not work . Should be chnaged to `pnpm`
<img width="1680" alt="Screenshot 2023-12-15 at 5 46 44 PM" src="https://github.com/plone/volto/assets/138270264/1b9524e2-aa71-4759-9984-30c8c10ae91a">

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by ujjwaleee26** [comment]
I already submiited a PR for it

**Comment by aarishshahmohsin** [comment]
Ok.

**Comment by stevepiercy** [comment]
@aarishshahmohsin please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html). We do not assign issues.

**Comment by stevepiercy** [comment]
@ujjwaleee26 see https://6.docs.plone.org/contributing/first-time.html#write-code for how to avoid the problem you had with your PR.
