### ISSUE TITLE
Update documentation 

### ISSUE THREAD

**Issue by lorstenoplo** [plone/volto#5554]
## Abstract

Following the contributing guide to volto here: https://github.com/plone/volto/blob/main/CONTRIBUTING.md 
leads to an error.

The project is configured to only use pnpm for installing packages.

## Motivation

Improves developer friendliness 

## Proposal & Implementation

Please update the documentation
This page: https://6.docs.plone.org/volto/contributing/index.html#install-volto-for-development
To this : https://6.docs.plone.org/volto/contributing/developing-core.html

## Deliverables

- Volto

## Risks

None

**Comment by stevepiercy** [comment]
This is not a PLIP. It is merely an issue. Closing in favor of https://github.com/plone/volto/issues/5556
