### ISSUE TITLE
Consolidate install Volto for development docs

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#5556]
Please update the documentation.

- This section should be replaced: https://6.docs.plone.org/volto/contributing/index.html#install-volto-for-development 
- with a link to: https://6.docs.plone.org/volto/contributing/developing-core.html

By following the first one we just end up with the following error:

<img width="960" alt="image" src="https://github.com/plone/volto/assets/69671750/b915b53a-a700-461b-940a-3f734375938a">

@stevepiercy 
@sneridagh

_Originally posted by @lorstenoplo in https://github.com/plone/volto/issues/3289#issuecomment-1864207374_

**Comment by stevepiercy** [comment]
Additionally, Step 2 for Node.js appears to be incorrect. Note the version mismatch. I'm not sure how to interpret these different results.

```console
$ nvm use 20  
Now using node v20.10.0 (npm v9.8.1)

 17:39:46  stevepiercy@Steves-MacBook-Pro  ...Plone/documentation/aaa  🐍 3.10.13 3.11.5 system   6.0 ✘ ✹ 
$ node -v       

v20.6.1
```

**Comment by stevepiercy** [comment]
Also after installing pnpm with:

```shell
corepack prepare pnpm@latest --activate
```

...and checking version:

```
$ pnpm --version

8.11.0
```

Latest should be 8.12.1.

**Comment by ujjwaleee26** [comment]
@stevepiercy  I have made a pr yesterday , by combining the contributing to volto and developing volto core into a sigle doc `Developing Volto Core ` which fixes 2 issues. I am trying to change what updations you have suggested and I will push a commit soon . Can I get a review, cause this followiing of core volto documentation has been an issue  for a while now. Can you please check the deployed version, I have added backend running instructions too

**Comment by stevepiercy** [comment]
@ujjwaleee26 please do not combine two issues into one pull request. I also clarified this issue's description, and #5554 has been closed and superseded by this issue.

**Comment by stevepiercy** [comment]
[Running commands](https://6.docs.plone.org/volto/contributing/developing-core.html#running-commands) does not yield a working installation of Plone with Volto for development.

Additionally [Developing Volto](https://6.docs.plone.org/volto/contributing/developing-core.html#developing-volto) does not yield a working Volto installation.

Both are very bad for developers.

```shell
$pnpm start
<snip>
Proxying API requests from http://localhost:3000/++api++ to http://localhost:8080/Plone
🎭 Volto started at 0.0.0.0:3000 🚀
```

and visiting the URL http://localhost:3000/:

```
Connection refused
http://localhost:3000/
The backend is not responding, please check if you have started Plone, check your project's configuration object apiPath (or if you are using the internal proxy, devProxyToApiPath) or the RAZZLE_API_PATH Volto's environment variable.
```

@sneridagh @tiberiuichim this is not helpful for new developers. What can we do to improve the developer experience?

@ujjwaleee26 please wait until we get a response from the Volto team. Our instructions are incomplete, and someone with that knowledge needs to update the documentation.

**Comment by stevepiercy** [comment]
@sneridagh @tiberiuichim @davisagli we made several improvements in https://github.com/plone/volto/pull/5564 and it can be previewed at [Develop Volto core](https://deploy-preview-5564--volto.netlify.app/contributing/developing-core.html). It would be super helpful to get some careful review on these changes.
