### ISSUE TITLE
How to install just Volto?

### ISSUE THREAD

**Issue by wesleybl** [plone/volto#5559]
**Is your feature request related to a problem? Please describe.**
The `pnpm install` command installs many non-Volto dependencies.

**Describe the solution you'd like**
Is there a command that installs only Volto's dependencies?

**Comment by davisagli** [comment]
@wesleybl By default pnpm installs dependencies of all packages that are part of the monorepo. To only install the dependencies of `@plone/volto`, use the `--filter` option:

`pnpm --filter @plone/volto install`

**Comment by wesleybl** [comment]
@davisagli can we have an "installvolto" script?

**Comment by stevepiercy** [comment]
@wesleybl I am not clear why that would be useful. Can you elaborate upon your use case?

If the developer knows to read pnpm documentation, why do we need to document it or add a Makefile command in Volto?

**Comment by wesleybl** [comment]
@stevepiercy I believe most people using this repository are interested in Volto. Installing the dependencies of all packages takes much longer. Another thing is that searches become slower with so many packages. It would be nice to have a command that installs only Volto. It wouldn't be in make, but in [package.json](https://github.com/plone/volto/blob/dd933d44a7510aaa1110120c6bbbb2943844bba7/package.json#L4-L25). It would be a "shortcut", a practicality, like the other package.json scripts.

**Comment by stevepiercy** [comment]
@wesleybl that sounds reasonable to me, but I don't develop Volto. I would suggest that you join the next [Volto Team Meeting](https://discord.com/channels/786421998426521600/787308038050545666/1186627752263163944) to advocate for your feature request. Or I can reopen this issue for further discussion. Please let me know.

**Comment by stevepiercy** [comment]
@wesleybl actually, there are these bits in the documentation:

- [Running commands](https://6.docs.plone.org/volto/contributing/developing-core.html#running-commands)
- [Developing Volto](https://6.docs.plone.org/volto/contributing/developing-core.html#developing-volto)

If you can suggest how to improve that text to what you want, I think there would be no objection. However I don't think it is possible, now that Volto is a monorepo, and `packages/volto` is one of the packages that comprise Volto the product.

**Comment by davisagli** [comment]
@stevepiercy It's possible; I mentioned how to do it in my comment above. I'm not sure about adding another command to the Makefile or package.json, because the more commands we add, the harder it is to find the right one. If it becomes a common request, we can add it. @wesleybl In the meantime you can add a personal alias in your shell, if it's something you need to do often.

**Comment by ichim-david** [comment]
@wesleybl @davisagli I have to admit coming from 17.x.x and lower Volto it's really strange to go inside packages/volto, run pnpm install thinking it's the yarn install equivalent and to have remix and nextjs downloading alongside all of those extra packages that come from those libraries.

Those packages should be example packages that could be worked on but when you want to interact with Volto you don't want to have the extra actions that you didn't even think you would be asking.

I will try to have a doc pull request next week mentioning the filter install given by David in 
https://github.com/plone/volto/issues/5559#issuecomment-1866662070
making it more obvious for others like me and Wesleybl on how to get started the quickest with Volto 18 development.

**Comment by davisagli** [comment]
@ichim-david It is mentioned already here: https://6.docs.plone.org/volto/contributing/developing-core.html#running-commands

But it might make sense to also mention it here: https://6.docs.plone.org/volto/contributing/developing-core.html#set-up-the-environment

/cc @sneridagh
