### ISSUE TITLE
[docs] In develop Volto core mention using Python instead of Docker for the backend

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#5573]
We could also mention that it's possible to run the backend without Docker with `make start-backend` if you have Python installed, but that could wait to be added in a separate PR.

_Originally posted by @davisagli in https://github.com/plone/volto/pull/5564#discussion_r1435848692_

**Comment by Akshat2Jain** [comment]
is someone working on this issue or not? @stevepiercy

**Comment by stevepiercy** [comment]
@Akshat2Jain using your super power of observation, you may see that the green "Open" icon reflects its status, that no one is assigned to it, no one has claimed it, and that there are no linked open pull requests. See [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do).

**Comment by aadityaforwork** [comment]
I am working on this issue via pr #6380

**Comment by davisagli** [comment]
We removed the `start-backend` command in https://github.com/plone/volto/pull/6110. Now the volto repository only has a command to start the backend using Docker, so this issue is no longer relevant.

**Comment by aadityaforwork** [comment]
> We removed the `start-backend` command in #6110. Now the volto repository only has a command to start the backend using Docker, so this issue is no longer relevant.

okay
