### ISSUE TITLE
Improve Volto Generator

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#5577]
## Abstract

Volto generator has come a long way, and it's still using an old, unsupported version of `yo`. They have changed to ESM, so we should also move to ESM to use the latest `yo` versions. At the same time, we have identified the need to make the generator to support multiple versions of Volto, without having to rely on keeping a version matrix and a set of generator versions across Volto versions.

## Motivation

The deprecation of old versions of `yo` and the need of having a single version of the generator for all supported Volto versions.

## Assumptions

No preconditions/assumptions.

## Proposal & Implementation

Refactor the package to be ESM, use latests versions of `yo` and friends.

We need a way to save the templates for the different Volto versions, maybe in different directories? (suggestions are welcomed). Also the necessary logic and related prompts to ask for the desired Volto version to be generated.

## Deliverables

- The new `@plone/generator-volto` ESM ready, with the unified versions.
- Documentation related.
- CI tests on all supported versions to test that it does work properly (not only building and starting Volto, but also tests, linting, etc).

## Participants

Víctor Fernández de Alba (@sneridagh) - Mentor and review.
Steve Piercy (@stevepiercy) - Documentation mentor and review.

We need a champion for this one.

**Comment by stevepiercy** [comment]
I signed on for documentation mentoring and review.

**Comment by Hrittik20** [comment]
Hello @sneridagh @stevepiercy! I would like to help with this issue. Can we use "to-esm" to convert it or do you think it would be better to do it manually?

**Comment by stevepiercy** [comment]
@Hrittik20 is this what you mean? https://www.npmjs.com/package/to-esm

**Comment by Hrittik20** [comment]
@stevepiercy Yes, I think it will help us in converting JS files to ESM

**Comment by sneridagh** [comment]
@Hrittik20 No matter the process you use to get there, a thorough review of the resultant PR will follow. Also there are tests in place for it. For me, it's fine if the result is satisfactory.

Please note that this is not only about converting to ESM, I guess you read the whole spec. I estimate the work to be done in 15-20h. Please, make sure that you can stick to that commitment and you fully understand why are we doing it, what's the purpose of this package. Who is using it and why, and what is the reasoning behind this task.

**Comment by Hrittik20** [comment]
I have made "generator-volto" esm ready. Should I make a PR before working on the volto templates? Also, any advice on how I can get templates for different volto versions?

**Comment by sneridagh** [comment]
@Hrittik20 You can find them in the `16.x.x` and the `17.x.x` branches. The initial idea was to have them in separated folders.

Putting @davisagli into the loop.

**Comment by Hrittik20** [comment]
@sneridagh How about creating a 'templates' folder inside the 'generator-volto' directory, housing folders for different version templates (16 and 17)?

**Comment by sneridagh** [comment]
Closing this as completed! Cookieplone: https://6.docs.plone.org/glossary.html#term-Cookieplone
