### ISSUE TITLE
Responsiveness Issue on Plone Edit Page

### ISSUE THREAD

**Issue by singhcoder694** [plone/volto#5597]
**Describe the bug**
Clicking to Edit icon take us to a page where we can see two sides one has body and the other has various description like title, time etc. These two sides are overlapping on small screen sizes and are unable be to seen simultaneously.

**To Reproduce**

1. Go to 'Edit'
2. Change Screen Size (if on laptop/PC)
3. Overlapping issue can be seen.

**Expected behavior**
As a responsive website the bar of Description should become invisible or small on small screen size to make user experience better.

**Screenshots**
<img width="222" alt="Screenshot 2024-01-03 164928" src="https://github.com/plone/volto/assets/114601400/9b999f30-79f4-4ddc-b3f5-5b17720a0f4a">
<img width="467" alt="Screenshot 2024-01-03 164952" src="https://github.com/plone/volto/assets/114601400/0d37f9a4-ed0c-44c6-b4a6-207f35fb7e35">

**Software (please complete the following information):**

- All browsers small screen(I checked on Edge and Chrome)
- Volto (Latest Version as I installed in last month)
- Plone (Latest Version as I installed in last month)

**Additional context**
I am **new Contributor to Plone community** and would love to work on this issue as it would be an easy start for me to start contributing to Plone Community. Please assign this issue to me if you as it is important aspect of Frontend of any website.

**Comment by stevepiercy** [comment]
The sidebar has a handle represented by a light grey vertical bar (to the left of Summary in your screenshot) that you can click to close it. Click again to reopen it. I don't think this is a bug or needs fixing.

It does need to be documented in the [User Manual](https://6.docs.plone.org/volto/user-manual/index.html). It would require a new page.

**Comment by singhcoder694** [comment]
Ohh, but @stevepiercy it is so invisible for any user to see and it's positioning also seems weird... Don't you think so it should be made better ??

**Comment by stevepiercy** [comment]
See the proposed fix for that issue in https://github.com/plone/volto/pull/5431.

The original issue still needs documentation, and I'd *love* to see some of that. 😁

**Comment by singhcoder694** [comment]
Ohh got it.... Thanks for clarifications🙂
