### ISSUE TITLE
Unlocking content does not work when using the development proxy

### ISSUE THREAD

**Issue by teekuningas** [plone/volto#5602]
I am running volto in a local project, using:
```
RAZZLE_DEV_PROXY_API_PATH=http://localhost:8080/Plone yarn start
```
Upon exiting the edit view, the content fails to unlock, although it locks without issue. Investigation reveals that while actions are dispatched correctly, the DELETE request stalls at the development proxy. The issue appears to stem from the action's payload containing "{}" when force is set to false:

https://github.com/plone/volto/blob/main/packages/volto/src/actions/content/content.js#L232

Subsequently, this payload is discarded here:

https://github.com/plone/volto/blob/main/packages/volto/src/express-middleware/devproxy.js#L51

The probable cause of the hang is the discrepancy between a content-length of 2 and the absence of a body. It seems an upstream version, which the Volto code is believed to be derived from, has addressed this issue:

https://github.com/chimurai/http-proxy-middleware/pull/640

The unlocking process operates correctly when using an nginx proxy, following the Plone documentation guidelines.

This problem is likely present in the master branch; however, my Volto version is 16.21.3, so that may be a factor.

**Comment by teekuningas** [comment]
@stevepiercy,

Sorry for the trouble; it seems to work with the newest volto generated with "yo @plone/volto".

Have to start updating..

**Comment by stevepiercy** [comment]
It might be worth back porting a bugfix to 16.21.3 in a maintenance release. If you can identify where and when the fix was made, then you could submit a PR for it and you could put off upgrading to the latest Volto.

**Comment by teekuningas** [comment]
It might also be a dependency. However, given this happens only in the dev environment and is fixed in a later version, I am happy for now..
