### ISSUE TITLE
Broken markup shortcuts for bold, italic, strikethrough in Slate text block

### ISSUE THREAD

**Issue by kHAPPY2004** [plone/volto#5605]
/**Describe the bug**
Markup shortcuts for inline formating (\*\*text\*\* for bold, \*text\* for italic and \~\~text\~\~ for strikethrough) in slate text blocks do not work .

**To Reproduce**

1. Go to https://demo.plone.org/ (or any other page using Volto 17.x)
2. Edit a page
3. Add text block
4. Enter \*\*text\*\* and press space .
5. Text still formatted as normal text .

**Expected behavior**
Text should be formatted as bold.

**Software (please complete the following information):**

- OS: ubuntu
- Browser chrome
- Volto Version 18.0.0-alpha.6
- Plone Version 6.0.9

**Comment by davisagli** [comment]
@07tAnYa Please don't work on issues that already have an open PR waiting for review.

**Comment by stevepiercy** [comment]
@07tAnYa please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do).
