### ISSUE TITLE
Loading indicator (spinner) badly positioned when uploading hundreds of images via folder contents. Replace spinner with upload progress indicator (x of y files uploaded).

### ISSUE THREAD

**Issue by tisto** [plone/volto#5620]
**Describe the bug**

When a user uploads hundreds of images (e.g. the Pastanaga icons set https://github.com/plone/pastanaga-icons/tree/main/Icons) she does not see any indication that the site is uploading images in the background. For the user it seems like the site is frozen.

**To Reproduce**

1. As admin
2. Go to demo.plone.org
3. Go to folder_contents (https://demo.plone.org/icons/contents) and drag and drop the Pastanaga UI icon set
4. Click the save button (right arrow)
5. -> there is no spinner visible, the page looks frozen

**Expected behavior**

Show a spinner that shows that the site is still loading. In an ideal world, a progress indicator would show how many files have been uploaded already (e.g. 4 of 345 files have been uploaded).

**Screenshots**

![Inhalte (18)](https://github.com/plone/volto/assets/632105/58bc4224-ab81-42f7-82e0-d3b23b9f9ca4)

**Comment by Ravi-kumar9347** [comment]
@tisto i understand the problem, but can you help me in finding the exact path of file names related to the above bug

**Comment by tisto** [comment]
@Ravi-kumar9347 the filenames are irrelevant. I do not see any spinner whatsoever:

![Contents (3)](https://github.com/plone/volto/assets/632105/017e8693-0c68-494e-a4d9-8e928cc3d340)

- as admin
- go to https://demo.plone.org/icons/contents
- drag & drop the pastanaga UI icon set
- click on "next" arrow
- -> there is no spinner visible, the page looks freezed

**Comment by Ravi-kumar9347** [comment]
@tisto thank you for your information.

**Comment by ArmanKukreti** [comment]
Sir can you please help me setup the project locally. I am getting this error,please guide me
![Screenshot from 2024-01-13 13-58-08](https://github.com/plone/volto/assets/125758031/41322ba0-e7f0-4d6c-8d8e-cb40cb7740f0)

**Comment by stevepiercy** [comment]
@ArmanKukreti no. See the warning on https://6.docs.plone.org/contributing/first-time.html

**Comment by Abhishek-90** [comment]
@tisto if what @Hrittik20 is saying is correct, the work will be significantly reduced, as the new target would be to debug the issue as to why the spinner is behaving in this manner. Would like to this issue and solve it.

**Comment by Ayush-2301** [comment]
hey @Abhishek-90 , you still working on this issue . I believe maybe adding pagination would be a better option . I would like to work on it .

**Comment by sujaykadam** [comment]
@tisto Can you please assign this issue to me, I'd love to contribute to Plone and this seems like a great issue to start off with.

**Comment by stevepiercy** [comment]
@sujaykadam please read and follow [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do), [Contributing to Plone](https://6.docs.plone.org/contributing/index.html), and [Contributing to Volto](https://6.docs.plone.org/contributing/volto.html).

**Comment by sujaykadam** [comment]
@tisto I'll be working on this issue, will describe possible solutions soon to implement the best one.

**Comment by victorchrollo14** [comment]
Hey @tisto . I fixed the issue. Does this look good to make a PR.

[Screencast from 26-03-24 06:57:09 PM IST.webm](https://github.com/plone/volto/assets/89346667/c75455d3-0ad1-475b-9ded-e7a5b88df8e9)
