### ISSUE TITLE
Toolbar Menu Toggle and Outside Click Handling Bug

### ISSUE THREAD

**Issue by ravjot07** [plone/volto#5645]
When you click on a toolbar icon, the menu that pops up isn't closing properly with a second click on the same icon. It's supposed to toggle open and closed each time you click, but right now, it just stays open. Secondly, our outside click feature, which is meant to close the menu if you click anywhere else on the screen, isn't working when you click on the user button. Ideally, clicking anywhere outside the menu should close it, but currently, clicking on the user button doesn't have this effect.

**Steps to reproduce the behavior:**

- Open the application and navigate to a page where the toolbar is present.
- Click on any toolbar icon to open the corresponding menu.
- Click on the same icon again. Observe that the menu does not close as expected.
- Now, with the menu open, click on the user button. Notice that the menu remains open instead of closing.-

**Expected behavior**
The menu should toggle (open/close) when the corresponding toolbar icon is clicked.
Any click outside of the open menu, including clicks on the user button, should close the menu.

**Screen Recording **
[sidebar open closing bug.webm](https://github.com/plone/volto/assets/138920477/997b439c-0f2c-4d37-9dce-742239a07301)

**Comment by bilalshaikh292** [comment]
Is the issue still open I would like to contribute ?

**Comment by stevepiercy** [comment]
@bilalshaikh292 using your super power of observation, you may see that the green "Open" icon reflects its status, and that by virtue of its URL and the "Pull requests" tab being selected, this is a pull request, not an issue. See [GitHub docs](https://docs.github.com/). 

Also please read and follow [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do), [Contributing to Plone](https://6.docs.plone.org/contributing/index.html), and [Contributing to Volto](https://6.docs.plone.org/contributing/volto.html).

**Comment by bilalshaikh292** [comment]
Ok, I apologize for that .I will go through the contribution guideline.
