### ISSUE TITLE
No contents in the drop down arrow for selecting languages.

### ISSUE THREAD

**Issue by 07tAnYa** [plone/volto#5664]
There is no other option other than English to select for languages, still there is a drop-down arrow.

1. Visit  https://demo.plone.org/images/plone-foundation.png/edit
2. Select categorization 
3. Try to select any other language other than English from that list.
4. See the error

There are two possible solutions for this issue, either users cannot change the by-default language or there should be options for selecting the other languages too.

![Screenshot 2024-01-19 161501](https://github.com/plone/volto/assets/140234197/ebf57315-771f-490a-8011-6f85def4e974)

**Comment by stevepiercy** [comment]
@07tAnYa this is an expected behavior. The site admin needs to enable other Available Languages under the Languages Control Panel.

![Screenshot 2024-01-19 at 4 11 01 AM](https://github.com/plone/volto/assets/102112/45bc3519-c64d-4e5b-8a68-143bd7341d4a)

Admittedly our [User Manual](https://6.docs.plone.org/volto/user-manual/index.html) is weak for Plone 6 under Volto. I would accept a pull request to add some Site Admin pages, modeled after Plone 5 docs for Classic UI in [Language Settings](https://5.docs.plone.org/adapt-and-extend/config/language.html).

**Comment by 07tAnYa** [comment]
> @07tAnYa this is an expected behavior. The site admin needs to enable other Available Languages under the Languages Control Panel.
> 
> ![Screenshot 2024-01-19 at 4 11 01 AM](https://private-user-images.githubusercontent.com/102112/298061167-45bc3519-c64d-4e5b-8a68-143bd7341d4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzA0MzAsIm5iZiI6MTcwNTY3MDEzMCwicGF0aCI6Ii8xMDIxMTIvMjk4MDYxMTY3LTQ1YmMzNTE5LWM2NGQtNGU1Yi04YTY4LTE0M2JkNzM0MWQ0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxMzE1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWFhZTU5YWVkOTAwNWFkMjQ5NTI2YTJhYWUwMWNiNzg3NTA3YmQ2ZmRmYjc4MmZiNzljNmU2YTYzNWY1ZjBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Wo2lCvesOpqts1IpqY55-kw4DK8ZNNzaErOC7Z-ricE)
> 
> Admittedly our [User Manual](https://6.docs.plone.org/volto/user-manual/index.html) is weak for Plone 6 under Volto. I would accept a pull request to add some Site Admin pages, modeled after Plone 5 docs for Classic UI in [Language Settings](https://5.docs.plone.org/adapt-and-extend/config/language.html).

Sure sir.

**Comment by ash97531** [comment]
So, This issue is already resolved right??

**Comment by stevepiercy** [comment]
It is not an issue, but expected behavior. Closing.
