### ISSUE TITLE
Lodash full is loading due to dependency from plone/registry

### ISSUE THREAD

**Issue by ichim-david** [plone/volto#5672]
I believe that plone registry isn't using the webpack mechanism to use the tree shaked version of lodash.
https://github.com/plone/volto/blob/main/packages/registry/package.json#L74

running pnpm analyze shows this client bundle:
![bundle-analyze-lodash](https://github.com/plone/volto/assets/152852/2844f8d0-277b-4e54-a58d-29bcb1bf907a)

Checking the bundle stats.json through https://statoscope.tech gave us this reason for the lodash full loading:
![lodash](https://github.com/plone/volto/assets/152852/73c9737d-9456-4a8c-832e-11d3f9050314)

Lodash imports should be optimized so that we don't raise client.js bundle which is served by all Volto websites

**Comment by ichim-david** [comment]
@sneridagh I don't know how to fix this but this might interest you, it would be nice for someone with more webpack and bundling knowledge to get to the bottom of this issue.

**Comment by ravjot07** [comment]
@ichim-david PR needed to be reviewed for this issue
