### ISSUE TITLE
Links are not working

### ISSUE THREAD

**Issue by pankaj-2503** [plone/volto#5676]
**Is your feature request related to a problem? Please describe.**
When I hover on  links my cursor is not changing and these links are not working 
**Describe the solution you'd like**
![image](https://github.com/plone/volto/assets/90036864/639ea987-3bb4-47b5-887d-37f01b86dc3b)

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered
**Additional context**

**Comment by ichim-david** [comment]
@pankaj-2503 this is not a bug, it's intended behavior.
You are in the edit section and you want to be able to edit the link text without being taken to that link.
When you go to the view the links work correctly.

This is a common behavior of editing in Volto where you can't navigate the  links until you get to the view where you want to interact with links.

**Comment by b-harsh** [comment]
@pankaj-2503 @ichim-david   the links are working fine , the problem which may be considered here is : the colour of links before hovering and colour of links on hovering are almost same there is a slight colur change .

Thank you

**Comment by ichim-david** [comment]
> @pankaj-2503 @ichim-david the links are working fine , the problem which may be considered here is : the color of links before hovering and color of links on hovering are almost same there is a slight color change .
> 
> Thank you

Links are blue in color like links are in general and you get a hand pointer on hover. Read my previous comment on why links didn't work because that is the intended behavior of links on the edit interface.
