### ISSUE TITLE
Locales po files contain git merge conflicts 

### ISSUE THREAD

**Issue by ichim-david** [plone/volto#5681]
Right now it's in the fr.po but there are others in 16.x.x branch

**Comment by stevepiercy** [comment]
This commit https://github.com/plone/volto/commit/b91d69bc4b916539aeb901536dd7bfb946ddedfb shows Spanish `es` too.

**Comment by ichim-david** [comment]
@stevepiercy I think that some of the conflicts were fixed later while others were introduced later :) 
I went and checked all 3 branches that we support (main, 17.x.x and 16.x.x) and fixed all of the issues that I have found.
Thanks for the approval, this made it a faster process to then handle.
