### ISSUE TITLE
Pasting an image directly from the clipboard in a slate block triggers the creation of both a slate block and a (proper) image block.

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#5697]
**Describe the bug**
Pasting an image directly from the clipboard in a slate block triggers the creation of both a slate block and a (proper) image block.

**To Reproduce**

1. Edit any content with blocks
2. Click on an empty slate block
3. Copy an image
4. Paste directly from the clipboard into a slate block
5. Two blocks, one pure slate and an image block are created.

**Expected behavior**
Only the image block is created.

**Comment by tiberiuichim** [comment]
@sneridagh I think I've noticed this problem at some point. It needs to be fixed.

**Comment by AnshulKahar2729** [comment]
> /cc @avoinea @tiberiuichim @ichim-david Does your users not try this feature? I'm so used to do this in Gitlab/Github...

Can you attach the screenshots or recording, it will be better for understanding

**Comment by tiberiuichim** [comment]
@AnshulKahar2729 Go to Google Docs, create a new document using a template that also uses an image. From the google doc, copy everything, go to Volto to a new page, paste the clipboard. If you get two images pasted, it's a problem.

**Comment by AnshulKahar2729** [comment]
Ok, I got the problem. I tried to reproduce the problem and it happended. One more question, is it happening in all the blocks, or some specifics?

**Comment by AnshulKahar2729** [comment]
@tiberiuichim @sneridagh I try to make some changes and this is the result after that is it okay?

[Uploading Screencast from 26-01-24 02:48:21 PM IST.webm…]()

**Comment by AnshulKahar2729** [comment]
> @AnshulKahar2729 Go to Google Docs, create a new document using a template that also uses an image. From the google doc, copy everything, go to Volto to a new page, paste the clipboard. If you get two images pasted, it's a problem.

Ok, I tried doing that I got the solution too. After fixing changes, now it is rendering only one time. But, I want to make sure that my approach is correct. How can I do that, any way of discussion?

**Comment by tiberiuichim** [comment]
@AnshulKahar2729 it's concerning the integration between volto-slate and the volto blocks.

The problem is that the image slate node is not properly removed once a volto block is emitted.

https://github.com/plone/volto/blob/4bb07b9b7392879e7aed72b871f73936f2187f5c/packages/volto-slate/src/utils/volto-blocks.js#L278

https://github.com/plone/volto/blob/4bb07b9b7392879e7aed72b871f73936f2187f5c/packages/volto-slate/src/blocks/Text/index.js#L95

https://github.com/plone/volto/blob/4bb07b9b7392879e7aed72b871f73936f2187f5c/packages/volto-slate/src/editor/plugins/Image/deconstruct.js#L24-L27

Somehow the slate tree transformation is not properly done.

**Comment by AnshulKahar2729** [comment]
> once a volto block is emitted.

Ok, I will look into it

**Comment by ichim-david** [comment]
For extra context, I've tried on the demo site to paste an image and it works just fine on a Mac.
Where you have issues is when you try to paste an image from the OS clipboard

**Comment by adityaa3pathi** [comment]
Hey, @ichim-david 
Just want to ask, is this issue resolved? cause I'm not able to reproduce it in my local volto. It works just fine on Ubuntu 22.04.4 LTS.
On uploading images through HDD or from clipboard, no duplicate images are created.
