### ISSUE TITLE
Volto main lint fails when running from packages/volto instead of project root

### ISSUE THREAD

**Issue by ichim-david** [plone/volto#5714]
When I run:
pnpm lint:volto
turbo run lint --filter @plone/volto
No failures but when I cd into packages/volto and run there pnpm lint I get 2 errors
You can see the error in the following gist:
https://gist.github.com/ichim-david/1214e562abdf0fe9c6e5ee6544eca095

**Comment by sneridagh** [comment]
@ichim-david I can reproduce it also, I will take a look. We might have to polish the configs still a bit. Did you take a look already?
