### ISSUE TITLE
Suggesting addition for sign up feature

### ISSUE THREAD

**Issue by vanshdeepsingh-coder** [plone/volto#5733]
**Missing Feature:**
No sign up feature on the plone website

**Feature Suggestion i would like to add:**
I would like to add sign up feature to the plone website via firebase authentication so that user can sign up using google account.

**Here is the attached image:**

![image](https://github.com/plone/volto/assets/82263082/9a0b8d68-cc74-4f06-a905-5542c1eba5af)

**Only Admin login is Possible:**

![Screenshot from 2024-02-05 21-36-32](https://github.com/plone/volto/assets/82263082/f45df196-43ec-4a42-b460-e4e8abca5bc5)

**Comment by vanshdeepsingh-coder** [comment]
@displacedaussie can you please assign this issue to me if this is a genuine requirement for the website?

**Comment by davisagli** [comment]
Volto can use external auth providers via this addon: https://github.com/collective/volto-authomatic
