### ISSUE TITLE
Language preference not working

### ISSUE THREAD

**Issue by vanshdeepsingh-coder** [plone/volto#5734]
**Description**
In the admin panel, going to the preferences and selecting desired language ,when choosing any other language than English, changes are not being reflected.

**To Reproduce**

1. Log in to the admin panel
2. Click on the profile button on bottom left corner
3. Select preferences
4. Select language and choose your desired language

**Expected behavior**
Language of the webpage should change to the desired selected language

**What is Actually Happening**
Webpage Language is stuck to English only.

**Video**

[Screencast from 2024-02-05 22-06-53.webm](https://github.com/plone/volto/assets/82263082/caf7d393-017a-4c31-8c27-8e92f8b0f49d)

**Software**

- OS: Ubuntu 23.10
- Browser: Mozilla firefox (118.0.1 (64 bit) )
- Volto Version [e.g. 8.5.0]
- Plone Version [e.g. 5.2.2]
- Plone REST API Version [e.g. 7.0.1]

**Comment by davisagli** [comment]
@vanshdeepsingh-coder Please do not ping random people. If you don't follow our [contributor guidelines](https://6.docs.plone.org/contributing/first-time.html), you will be blocked from this organization. In particular, please read this section: https://6.docs.plone.org/contributing/first-time.html#things-not-to-do

There is already an existing proposal for how to fix this issue (https://github.com/plone/volto/issues/5507), so I will close this issue.
