### ISSUE TITLE
Duplicate content being added in plone/volto

### ISSUE THREAD

**Issue by vanshdeepsingh-coder** [plone/volto#5737]
**Description**
Duplicate content can be added to the webpage with having the exact same details.

**To Reproduce**

1. Go to home page
2. Click on contents icon on left icon bar
3. Click on the upload button
4. Upload content having the exact same details and you will see they are being perfectly added.

**Expected behavior**
Duplicate content should not be allowed to upload

**Video**

[Screencast from 2024-02-06 13-41-30.webm](https://github.com/plone/volto/assets/82263082/838630b3-3cda-4835-b129-1f8b03760b5b)

**Software**

- OS: Ubuntu (23.10)
- Browser: Mozilla Firefox (118.0.1) (64 bit)

**Comment by stevepiercy** [comment]
This is a feature request, not a bug.

I can delete a mistake, if I think it is one.

I may want to upload the same binary file to multiple locations, for example, to keep images together with text content. I also might have different files with the same filename in different local locations that I want to upload.

Plone doesn't get in the way of doing this, and I would not want this behavior to change.

**Comment by vanshdeepsingh-coder** [comment]
Understood thank you for your feedback
