### ISSUE TITLE
`pnpm test` fails on updating snapshots

### ISSUE THREAD

**Issue by ksuess** [plone/volto#5783]
Change or add a new script
"test": "pnpm --filter @plone/volto run test:ci" 
->
"test": "pnpm --filter @plone/volto run test",

**`pnpm test` exits without the chance to update a snapshot.**

**Comment by its-VinayKumar** [comment]
@ksuess Please assign me this issue. I will resolve it as soon as possible.

**Comment by stevepiercy** [comment]
@its-VinayKumar please read and follow [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do), [Contributing to Plone](https://6.docs.plone.org/contributing/index.html), and [Contributing to Volto](https://6.docs.plone.org/contributing/volto.html).

**Comment by Hrittik20** [comment]
Wouldn't updating `"test": "jest"` to `"test": "jest --updateSnapshot"` fix this issue?

**Comment by sneridagh** [comment]
@ksuess @Hrittik20 you can use:

```
pnpm test -- -u
```

**Comment by ichim-david** [comment]
@sneridagh I think it's a mistake to close this issue given the fact that we have this difference from normal commands to :ci commands
Even in packages/volto we have test and test:ci
https://github.com/plone/volto/blob/main/packages/volto/package.json#L44
For consistency, I think the action from the monorepo package should also have the same parity  and not rely on knowledge on how to  get around a broken assumption given the difference in pnpm test in the monorepo vs pnpm test in packages/volto

**Comment by sneridagh** [comment]
@ichim-david but which is the issue here? is it about the about the lack of parity, or is about issuing update command? or both?

**Comment by sneridagh** [comment]
@ichim-david https://github.com/plone/volto/pull/6051
