### ISSUE TITLE
Upgrade to Babel 7

### ISSUE THREAD

**Issue by tisto** [plone/volto#580]
I started to look into docz for our Volto docs and I ran into issues with Babel 6. Before I can proceed, we need to upgrade to Babel 6. Any pointers or anybody who can help with this?

**Comment by nileshgulia1** [comment]
@tisto We could use `babel-upgrade` tool to resolve the issue of stage preset deprecation. We can use this complete migration [guide](https://babeljs.io/docs/en/v7-migration).

**Comment by tisto** [comment]
@nileshgulia1 this is actually what I tried already. Did not work so far. Maybe you could look into this?

**Comment by sneridagh** [comment]
@tisto @nileshgulia1 as we talked already, just to write it here, let's postpone it until Razzle fully supports it and it is released.
