### ISSUE TITLE
plone.restapi Branch?

### ISSUE THREAD

**Issue by l34marr** [plone/volto#582]
It seems newnewtiles branch no longer available for plone.restapi at https://github.com/plone/volto/blob/master/api/buildout.cfg#L67

Anyway, I get this develop.cfg working with Plone 5.1.2. Hope this helpful.

https://gist.github.com/l34marr/5ecbbd8dea284a5b23c7b5f57bb0a6c2

**Comment by nileshgulia1** [comment]
@l34marr  Is it breaking your buildout?

**Comment by l34marr** [comment]
@nileshgulia1 I did refer to the api/buildout.cfg but git clone plone.restapi (master branch) into the src folder instead. It is not breaking my buildout. I just wonder why "branch=newnewtiles" used in the sample buildout.cfg.

**Comment by tisto** [comment]
@l34marr there is no need for the newtiles branch any longer. This has been merged and released. Just fire up a docker instance with:

`docker run --rm -it -p 8080:8080 kitconcept/plone.restapi:latest`
