### ISSUE TITLE
Add anchor links to discussion in a content and to each comment inside it

### ISSUE THREAD

**Issue by ericof** [plone/volto#5904]
**Is your feature request related to a problem? Please describe.**
It is not possible to link to a comment or to to discussion on a content page

**Describe the solution you'd like**
Add anchors to Discussion container and to each comment

**Comment by ericof** [comment]
@sneridagh Any recommendation about how to handle the anchors?

**Comment by sneridagh** [comment]
@ericof since they have an id, we could create the anchor already in the render component, right?

The other thing is how to copy the link. Maybe we can use a solution like the linked headlines icon...
