### ISSUE TITLE
Updating the UI

### ISSUE THREAD

**Issue by TheShiveshNetwork** [plone/volto#5907]
### Proposer: 
@TheShiveshNetwork
## Motivation
The current frontend structure is not very good. I am interested in improving the ui, and the structure of the content shown on the website.
![image](https://github.com/plone/volto/assets/84664410/2d8964a9-e284-4cf1-a611-0b9106238b58)

## Proposal & Implementation
I'll be doing UI updates in navbar, footer, home screen, login, etc.
The update will focus on improving the overall look of the website.

**Comment by stevepiercy** [comment]
@TheShiveshNetwork No. This is not how to submit a PLIP. See https://6.docs.plone.org/glossary.html#term-PLIP

This PLIP is opinionated and subjective, and lacks any consideration toward the volunteers who have contributed thousands of hours of labor to the theme. You should engage the [Plone community](https://community.plone.org/) before dismissing it wholesale as "not very good".

Additionally a PLIP is not something that a first-time contributor should submit, much less work on. Please read and follow [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do), [Contributing to Plone](https://6.docs.plone.org/contributing/index.html), and [Contributing to Volto](https://6.docs.plone.org/contributing/volto.html).
