### ISSUE TITLE
Community Forum App Icon Not Filling Correctly.

### ISSUE THREAD

**Issue by danielnabil** [plone/volto#5927]
**Issue Description:**
The image in the mobile app for the community forum does not properly fill the icon.

**To Reproduce**
1-Download The app from Google Browser

**Expected behavior**
Ensure that the Plone logo fills the icon properly across different mobile apps.

**Screenshot:**
![WhatsApp Image 2024-03-26 at 19 00 51_dd8d51e3](https://github.com/plone/plone.restapi/assets/141129283/86dada70-26d5-41d5-ba14-51a68600a047)

**Software:**
Android Version: [11]
Model Name: [Galaxy A52]

**Comment by davisagli** [comment]
This has nothing to do with volto

**Comment by danielnabil** [comment]
Thank you for your reply. I understand that this may not directly relate to Volto. Could you please guide me on which repository or project would be appropriate for addressing this issue? Any suggestions on where I should create this issue would be greatly appreciated. Thank you.

**Comment by stevepiercy** [comment]
It's under the Brand setting in the [Discourse application configuration](https://community.plone.org/admin/site_settings/category/branding). I would suggest that the original poster make their request in the [Plone Community Forum](https://community.plone.org/), and include their operating system version in their report. The images used in that configuration need padding or margin around the logos.

**Comment by danielnabil** [comment]
@stevepiercy Okay I will. Thank you.
