### ISSUE TITLE
Back button on personal tools icon in toolbar not displayed.

### ISSUE THREAD

**Issue by MostafaMagdyy** [plone/volto#5938]
**Describe the bug**
The back button on the personal tools icon in the toolbar is not displayed.

**To Reproduce**
1-In the toolbar, click the personal tools icon.
2-Note that the back button is not displayed.
3-Navigate to the volto/src/components/manage/Toolbar directory.
4-Open the PersonalTools.jsx file and observe line 79.
5-Notice that the back button should be displayed.

**Expected behavior**
The back button on the personal tools icon in the toolbar should be displayed.
![Fixed](https://github.com/plone/volto/assets/97239596/c35be26c-a287-4055-93b4-75dde96d97c5)

**Screenshots**
![Wrong](https://github.com/plone/volto/assets/97239596/6da1055b-605d-4f8c-8596-faf8c03e3aac)

**Software ():**

- OS: [Ubuntu 22]
- Browser [Microsoft edge]
- Volto Version [18.0.0-alpha.25]
- Plone Version [6.0.10]
- Plone REST API Version [9.5.0]

**Comment by MostafaMagdyy** [comment]
Hey, I tried to solve this issue after modifying the CSS for the Toolbar, and it appeared as shown in the screenshot I provided. However, when I tried to test it, I encountered an error **regarding the function unloadComponent in the volto/src/components/manage/Toolbar.jsx file.**
![Error2](https://github.com/plone/volto/assets/97239596/9d2f8a98-020c-4b7f-91ad-c09ca28b9b8c)

**Comment by MostafaMagdyy** [comment]
> Hey, I tried to solve this issue after modifying the CSS for the Toolbar, and it appeared as shown in the screenshot I provided. However, when I tried to test it, I encountered an error **regarding the function unloadComponent in the volto/src/components/manage/Toolbar.jsx file.** ![Error2](https://private-user-images.githubusercontent.com/97239596/318440391-9d2f8a98-020c-4b7f-91ad-c09ca28b9b8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzczMTIsIm5iZiI6MTcxMTk3NzAxMiwicGF0aCI6Ii85NzIzOTU5Ni8zMTg0NDAzOTEtOWQyZjhhOTgtMDIwYy00YjdmLTkxYWQtYzA5Y2EyOGI5YjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEzMTAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NWEwNGE0OWRhMmQyY2JlNWQ4YzU1M2NmNDY5YWY5ZjFhNWFhYzgwNGQ4ZWM4NjhjMTQzNjIxOGJhNjQ0MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UeiGzA80yxmJfuYKu_un1PVt5mHY55JYlfpHF4Di96M)
Previous loaded component i.e(-2) does not have hideToolbarBody property.
I tried to solve it by checking if it is undefined to set it to false, but i do not think it is the better way and i do not want to break other behaviours.
So,is there any guidance about this error?

**Comment by stevepiercy** [comment]
Why should a back button be displayed? I don't think this is a bug.

**Comment by MostafaMagdyy** [comment]
> Why should a back button be displayed? I don't think this is a bug.

It should be displayed as it already exists a button rendered with classname called back in the PersonalTools.jsx component as i said above.

**Comment by stevepiercy** [comment]
OK, I see now. It helps to provide a permalink to code, like this:

https://github.com/plone/volto/blob/13d5d60e9923af6fa45383794096f45174c47123/packages/volto/src/components/manage/Toolbar/PersonalTools.jsx#L79

What should happen when clicking the back button, if it were to be displayed? Currently clicking anywhere outside the menu hides it. I assume the same behavior would be desired, and would help with accessibility.

**Comment by ichim-david** [comment]
@stevepiercy @MostafaMagdyy this is not a bug.
The back button shows up when you have a popup opened and you need to go back.
That only happens when you click on the "Preferences" option.
When you do, you have the right css to show the back button and it works when you click it.
![personal-preferences](https://github.com/plone/volto/assets/152852/29817a73-136c-4a6b-8139-f7b141da3fcc)

**Comment by ichim-david** [comment]
> > @stevepiercy @MostafaMagdyy this is not a bug. The back button shows up when you have a popup opened and you need to go back. That only happens when you click on the "Preferences" option. When you do, you have the right css to show the back button and it works when you click it. ![personal-preferences](https://private-user-images.githubusercontent.com/152852/318474057-29817a73-136c-4a6b-8139-f7b141da3fcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5ODQ0MzAsIm5iZiI6MTcxMTk4NDEzMCwicGF0aCI6Ii8xNTI4NTIvMzE4NDc0MDU3LTI5ODE3YTczLTEzNmMtNGE2Yi04MTM5LWY3YjE0MWRhM2ZjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxNTA4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTNkOWViYWViMzFjYmQwNmM1OTQxNzFjYzg5ZjU0ODRhNzlmNGIyMTUwZTViOTBlMzBlZjVkZTViMGFiZmRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hhcy3uuwEcwCLNPMRWG4QP1F0CJTxzDNNIK1IFwLnKQ)
> 
> @ichim-david @stevepiercy this is not the same button I am talking about If you check the PersonalTools.jsx component [volto/packages/volto/src/components/manage/Toolbar/PersonalTools.jsx](https://github.com/plone/volto/blob/13d5d60e9923af6fa45383794096f45174c47123/packages/volto/src/components/manage/Toolbar/PersonalTools.jsx#L79) you will see it is rendered within header component and beside username. **Also, the button you are talking about isn't even rendered in the same component**, you'll see that the component preferences are pushed in this line [volto/packages/volto/src/components/manage/Toolbar/PersonalTools.jsx](https://github.com/plone/volto/blob/13d5d60e9923af6fa45383794096f45174c47123/packages/volto/src/components/manage/Toolbar/PersonalTools.jsx#L123) Even in the picture I provided, it takes another color, and I only changed its visibility from toolbar.less because it was non-visible. However, as you see. Thank you.

Even if it's not the same button because it's from another sub component the functionality of that back button is to go back from a sub component back to the main list and that is probably why that button is hidden and the close doesn't work. There is no point in trying to show it and close it, assume that it is done on purpose.

Also again the advice remains, it's better to add an issue and wait to get some bug confirmation and if it's worth pursuing by a core developer so that you minimize the risk of working in vain and not getting the pull request merged.

We are getting flooded with bug reports that might represent a non-issue to begin with or of low importance and again the chance for a fast turnaround and review will be slim due to limited capacity to review an already big queue of pull requests that are already opened and need to be checked or further worked on or given feedback.

There is a reason we advise new contributors to look at the tickets that have the needs help label as there the contributions are for certain wanted and needed.
