### ISSUE TITLE
no file named instance in bin directory

### ISSUE THREAD

**Issue by AnweshDas** [plone/volto#603]
As mentioned in the documentation to start volto in foreground
cd api
./bin/instance fg
is not working as there is no file named  instance in bin directory

**Comment by uwaiszaki** [comment]
@AnweshDas . What Python version are you using.

**Comment by nileshgulia1** [comment]
@AnweshDas Use correct python version. You should use `v2.7.x`.

**Comment by tisto** [comment]
@AnweshDas you have to run "bin/buildout" first. I'd recommend to use docker to start a backend for Volto:

`docker run --rm -it -p 8080:8080 kitconcept/plone.restapi:latest`
