### ISSUE TITLE
Widgets should not fake present a default value

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#6046]
https://github.com/plone/volto/blob/b1797b4c256e18e7e300f5c50d2565d2cf44699b/packages/volto/src/components/manage/Widgets/ImageSizeWidget.jsx#L60

@ichim-david  please explain the problem

**Comment by ichim-david** [comment]
@sneridagh  have a look when you have time to the comment I left above

**Comment by tiberiuichim** [comment]
https://github.com/plone/volto/blob/b1797b4c256e18e7e300f5c50d2565d2cf44699b/packages/volto/src/components/manage/Blocks/Image/schema.js#L83 this should have a default value of "l"
