### ISSUE TITLE
Error pages do not associate events with elements

### ISSUE THREAD

**Issue by wesleybl** [plone/volto#6048]
**Describe the bug**
In error pages, in production mode and rendered on the server, events are not associated with elements. This can be seen when we click on the search lupe, and it goes to a page not found:

http://localhost:3000/undefined/search?SearchableText=

In vanilla Plone this is not a problem, as we don't have many clickable elements on the page. But on sites that have more links this is a problem, since no Universal Link works.

**To Reproduce**

1. Start Volto in production mode:
```
pnpm build && pnpm --filter @plone/volto start:prod
```
2. In the Browser's address bar, type a non-existent URL. For example: http://localhost:3000/xxxxx
3. Press Enter.
4. Click on the search lupe.

**Expected behavior**
The Browser should be redirected to the search page:

http://localhost:3000/search?SearchableText= 

**Software (please complete the following information):**

- OS: Ubuntu
- Browser: Chrome
- Volto Version: 18
- Plone Version: 6.0.11

**Additional context**
In the situation described above, javascripts are not inserted into the page, causing the problem to occur.

This is because the `extractScripts` parameter is passed as `undefined` here:

https://github.com/plone/volto/blob/082e919d372a96af0ab40938375a65c6bdeb0c34/packages/volto/src/server.jsx#L289-L292

This causes this code not to be executed:

https://github.com/plone/volto/blob/0edcd8083afee783a6463a14b18d0f712cf7c25b/packages/volto/src/helpers/Html/Html.jsx#L189-L197

This has been implemented by @tiberiuichim in:

https://github.com/plone/volto/pull/1948

I think this code should be executed, regardless of whether it is in development or production mode. Is there any reason not to load scripts on error pages?

**Comment by davisagli** [comment]
@wesleybl From the PR you linked, it looks like this was done to avoid hydrating the markup returned from the server (which causes additional, unnecessary requests).

But we've also had to change this for some projects, and it seems quite bad to have it work differently in production mode only. I would support fixing this.

**Comment by wesleybl** [comment]
> From the PR you linked, it looks like this was done to avoid hydrating the markup returned from the server (which causes additional, unnecessary requests).

@davisagli maybe that was a problem at the time. But today I don't see that problem. The only extra request, when using `extractScripts` true, is the request to assemble the navigation. But this is common and occurs on all pages.

I am in favor of removing the `extractScripts` prop:

https://github.com/plone/volto/blob/0edcd8083afee783a6463a14b18d0f712cf7c25b/packages/volto/src/helpers/Html/Html.jsx#L190

Do you agree?

**Comment by tiberiuichim** [comment]
I'm +1 on getting rid of extractScripts
