### ISSUE TITLE
Getting CORS issues while opening volto.

### ISSUE THREAD

**Issue by uwaiszaki** [plone/volto#605]
![voltoerror2](https://user-images.githubusercontent.com/32809190/52292227-41f83a00-299a-11e9-99fb-1f97a96eab69.png)

**Comment by uwaiszaki** [comment]
@tisto . Please guide.

**Comment by tisto** [comment]
@uwaiszaki you have to provide more information on this. How did you set up your backend? It seems you did not properly configure your backend CORS configuration.

**Comment by uwaiszaki** [comment]
@tisto . I am following the [https://github.com/plone/volto/blob/master/README.md](readmemd) of plone volto.

**Comment by uwaiszaki** [comment]
volto/api/buildout.cfg is 
![corserrorvolto1](https://user-images.githubusercontent.com/32809190/52300784-c359c780-29ae-11e9-80f5-17a87b870087.png)
![corserrorvolto2](https://user-images.githubusercontent.com/32809190/52300789-c8b71200-29ae-11e9-8154-4f9178480c1d.png)

**Comment by nileshgulia1** [comment]
@uwaiszaki  There's still a workaround, use a browser extension for enabling `cors` header communication. https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/

**Comment by frapell** [comment]
@uwaiszaki @tisto The issue seems to be that calling /@workflow returns a 404 for the Plone site, maybe the "default page" functionality is not yet implemented in Volto?

![image](https://user-images.githubusercontent.com/851006/52657988-b2421680-2ed8-11e9-9592-63df6a527a1f.png)

**Comment by frapell** [comment]
Looks like @workflow in restapi is defined for IContentish, while the Plone Site does not provide that interface

**Comment by tisto** [comment]
@frapell the plone site root does not have a workflow, so this call returns a 404. This is a known issue that won't go away until we make the site root a dexterity object (PLIP pending). This does not affect Volto though, everything still works.

It would be nice to work around this issue in Volto but this seems hard to do according to @robgietema.

**Comment by frapell** [comment]
@tisto I have just started playing around with Volto after our last meeting, so I still need to learn about the known issues and design desitions, but I guess this would be fixed if the "default_page" functionality worked the same way it does in default Plone...

An out of the box Plone would have the "front-page" as default view of the site root, so if Volto would render that in the same way, the workflow wouldn't return a 404...

Another thing I am thinking is, would it make sense to first get the list of features for a given context, and then call workflow, breadcrumbs, and so on? (I know, totally unrelated to this Issue though)

**Comment by tisto** [comment]
@frapell we decided that we want to give the folderish approach without a default_page a try in Volto. We already added bugfixes for the @workflow issue and a workaround for the front-page issue.

**Comment by tisto** [comment]
@uwaiszaki try to use a docker backend and run:

`docker run --rm -it -p 8080:8080 kitconcept/plone.restapi:latest`
