### ISSUE TITLE
Browse button coming out of the segment in Add Image

### ISSUE THREAD

**Issue by uwaiszaki** [plone/volto#606]
![browsebuttonvoltoissue](https://user-images.githubusercontent.com/32809190/52352430-8e06b580-2a52-11e9-9046-7fdf0bf06e39.png)

**Comment by nileshgulia1** [comment]
@uwaiszaki Feel free to submit a PR!

**Comment by uwaiszaki** [comment]
@nileshgulia1 . Yeah am working on this.
