### ISSUE TITLE
Code complexity high, readability low

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#6078]
The use of ternary operators (and even multiple chained ternary operators) and deeply nested code makes this module really difficult to understand.

https://github.com/plone/volto/blob/02fb83c812012e62cd2478de73735159c43e703d/packages/volto/src/middleware/api.js#L128-L368

**Comment by draunger** [comment]
Hey @tiberiuichim can i send it's PR

**Comment by stevepiercy** [comment]
@draunger please read and follow [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do).
