### ISSUE TITLE
Markdown does not function fully anymore

### ISSUE THREAD

**Issue by Catherine358** [plone/volto#6131]
**Describe the bug**
When user tries to use markdown in volto text editor, for example to write "# Some title", "#" symbol disappears, but text stays to be usual text (p element). However in toolbar buttons text is marked as being "Title" (h2 element). Same behavior can be seen for Subtitle and block quote. Bold and italic texts do not work at all. But unordered and ordered lists do work fine.

**To Reproduce**

1. Go to Edit Mode.
2. Add text field.
3. Write "# Text"
4. Save

**Expected behavior**
Markdown works. When user types "# Title", he sees h2 element without "#" symbol instead of usual text. When user types "## Subtitle", he sees h3 element without "##" symbol instead of usual text. When user types "> some text", he sees blockquote element  without ">" symbol instead of usual text. When user types "**Text**", he sees bold text without "**" symbol. When user types "*Text*", he sees italic text without "*" symbol. 

**Screenshots**

https://github.com/plone/volto/assets/58996148/96d4cb9e-3baa-4d0e-a1fc-dc1b72808540

**Software (please complete the following information):**

- macOS
- Chrome
- Volto Version 17.16.0
- Plone 6.0.11
- plone.restapi 9.6.1

I have found this fix and maybe it is connected to it and will be fixed there #5495

**Comment by stevepiercy** [comment]
@Catherine358 #5495 resolved issue #5452, was applied to the `main` branch of Volto, and released in https://github.com/plone/volto/releases/tag/plone-slate-18.0.0-alpha.14.

It was not backported to Volto 17.

We'd accept a pull request that backports the fix to Volto 17. Would you like to contribute?

**Comment by Catherine358** [comment]
@stevepiercy Great! Thank you very much for the info :)

**Comment by ichim-david** [comment]
@Catherine358 Fixed by Volto 17.18.1 release https://github.com/plone/volto/commit/c449e1472eb579349d3a2fd57e7fda2522fc834f
