### ISSUE TITLE
Enable allow_discussion in object from Volto results in 'Constraint not satisfied' error

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#621]
```
BadRequest: [{'field': 'allow_discussion', 'message': u'Constraint not satisfied', 'error': ConstraintNotSatisfied(u'True', 'allow_discussion')}]
```

**Comment by sneridagh** [comment]
@lukasgraf issued transferred to Volto repo.

**Comment by miziodel** [comment]
restapi @vocabolaries provides for allow_discussion token and value pairs, both of which are strings:
{choices: [["True", "Yes"], ["False", "No"]], description: "Allow discussion for this content object.",…}

Volto provides the token back on patch ("True" | "False"), which in the current version of restapi is accepted as a correct value.

The error is no more there.

**Comment by sneridagh** [comment]
Fixed long time ago in the widget itself.
