### ISSUE TITLE
Unable to install Volto (on MacOS)

### ISSUE THREAD

**Issue by zopyx** [plone/volto#622]
```

(volto) ajung@ZOPYX-Macbook-Pro ~/src/volto $ nodejs  --version
v11.10.0
(volto) ajung@ZOPYX-Macbook-Pro ~/src/volto $ npm --version
6.7.0
(volto) ajung@ZOPYX-Macbook-Pro ~/src/volto $ create-volto-app myvoltoproject
/Users/ajung/src/volto/lib/node_modules/@plone/create-volto-app/volto-starter-kit

Creating myvoltoproject...

> Success! Created files for "myvoltoproject" Volto app

  Installing npm modules:
    @plone/volto

> Error! Failed to install @plone/volto, try again.
undefined

```

**Comment by zopyx** [comment]
Same error on Linux

**Comment by tisto** [comment]
Can you please try:

`nvm install 8.15.0
nvm use 8.15.0
npm install -g yarn
npm install -g @plone/create-volto-app
create-volto-app myvoltoproject
`

I just tried this on my mac and it works like a charm.

**Comment by tisto** [comment]
FYI: I just tried the same with Node 10.15.1 and everything works.

@zopyx try to delete your node_modules directory and your node cache.

**Comment by zopyx** [comment]
Using Node 10.15.1 works

**Comment by tisto** [comment]
Strange. We are still on 8.15.0 for our projects. Maybe something is screwed up with your local 8.15.0 node installation.

**Comment by zopyx** [comment]
The documentation stats Node 10.X.

Also "yarn start" does not work because it is not installed by the described steps.

You need to run "npm start" instead.

**Comment by tisto** [comment]
@zopyx fixed: https://github.com/plone/volto/commit/65a09a250c81aa4b9ec18328dda6b2a2bca1f9a9
