### ISSUE TITLE
Add towncrier files to ignore or rename `.keep` 

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#6225]
From a release on July 29, 2024, we need to either rename all towncrier fragments that we want to ignore to `.keep` or add `.gitkeep` to towncrier's new ignore configuration.

Reference: https://github.com/twisted/towncrier/pull/622

@Tishasoumya-02 I know it's not your fault but the pull request isn't green
https://github.com/plone/volto/actions/runs/10196668962/job/28207886197?pr=6147
Due to
https://github.com/twisted/towncrier/blob/trunk/src/towncrier/_builder.py#L117

try to rename package/volto/news/.gitkeep to .keep as they recognize that as something to ignore.

_Originally posted by @ichim-david in https://github.com/plone/volto/issues/6147#issuecomment-2262823508_

**Comment by ichim-david** [comment]
@stevepiercy  .gitkeep is a convention there isn't anything magical about it's naming other than to be more clear that it's for git to keep the folder from deleting if it were empty.

I opted to suggest to simply rename to .keep for plone/volto but as part as another pull request for this issue we could add .gitkeep as an ignore option to each package from the monorepo that uses towncrier.

**Comment by wesleybl** [comment]
> I think I'll make an issue and submit a PR with the suggestion

@stevepiercy Yes! `.gitkeep` is very common. It shouldn't be a problem for `towncrier`.

**Comment by stevepiercy** [comment]
Issue created at https://github.com/twisted/towncrier/issues/643 with offer to submit PR, assuming the maintainers agree.

**Comment by stevepiercy** [comment]
PR merged https://github.com/twisted/towncrier/pull/647.

Awaiting release to revert the file rename.

**Comment by stevepiercy** [comment]
Towncrier 24.8.0 was released today, and I merged the #6232.
