### ISSUE TITLE
Add Local Development Setup Instructions to README

### ISSUE THREAD

**Issue by Manancode** [plone/volto#6228]
The current README file provides comprehensive information about the Volto project, its features, and its use cases. However, it lacks detailed instructions for setting up and running the project locally. This can be a barrier for new contributors who want to contribute to the project.

**Proposed Solution:**
Add a new section to the README with detailed instructions on how to set up and run the project locally. The instructions should include steps for:

Prerequisites (Node.js, pnpm, etc.)
Forking and cloning the repository
Installing dependencies
Running the project locally
Running tests
Building the project

**Comment by Manancode** [comment]
I’ve created a pull request to address this issue . 
Review the pull request here: [PR #6229] (https://github.com/plone/volto/pull/6229#issue-2444648946)

Please let me know if there are any additional changes needed.

Thanks!

**Comment by stevepiercy** [comment]
@Manancode please read and follow [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do), [Contributing to Plone](https://6.docs.plone.org/contributing/index.html), and [Contributing to Volto](https://6.docs.plone.org/contributing/volto.html).

We document installation of Volto in the documentation, and only refer to it in the README. We do not duplicate documentation in the README.
