### ISSUE TITLE
Link content type functionality is missing

### ISSUE THREAD

**Issue by tisto** [plone/volto#624]
1) Go to https://volto.kitconcept.com/
2) Login as admin:admin
3) Create new Link content object, fill out title and link with a https link
-> Link view shows the title and an empty page
![spiegel de](https://user-images.githubusercontent.com/632105/52917551-2ae80f00-32ed-11e9-9dff-4b25607f8b54.png)

We should at least show a link in the body of the link page view.

In the future, we should implement the same functionality that standard Plone currently has. A user with editor permissions on the link sees the link with a message that the reason you see this page instead of redirecting to the target is that you are an editor that can edit the link. Anonymous users or logged in users without the editor role are redirected to the target.

**Comment by tisto** [comment]
@nileshgulia1 can you please take care of adding a simple link to the link view? Please also look into how standard Plone handles links and try to come up with a solution for that as well.

**Comment by uwaiszaki** [comment]
@tisto I have added the link in the link view. Can we write any url in this link . 
ex- https://www.google.com, but it is opening as http://localhost:3000/link-title-1/https://www.google.com instead of google.com

**Comment by uwaiszaki** [comment]
@tisto I have added the link in the link view. Can we write any url in this link . 
ex- https://www.google.com, but it is opening as http://localhost:3000/link-title-1/https://www.google.com instead of google.com

**Comment by nileshgulia1** [comment]
closed via #628
