### ISSUE TITLE
Error when testing customized Volto module in addon

### ISSUE THREAD

**Issue by wesleybl** [plone/volto#6244]
**Describe the bug**
When customizing the [FormValidation.jsx](https://github.com/plone/volto/blob/main/packages/volto/src/helpers/FormValidation/FormValidation.jsx) module and copying its tests to the addon, I receive the error below when executing the tests:
```javascript
FAIL src/addons/my.addon/src/customizations/volto/helpers/FormValidation/FormValidation.test.js
  ● Test suite failed to run

    node_modules/@plone/volto/src/helpers/FormValidation/validators.ts:1:35 - error TS7016: Could not find a declaration file for module './FormValidation'. '/home/user/git/app/node_modules/@plone/volto/src/helpers/FormValidation/FormValidation.jsx' implicitly has an 'any' type.

    1 import { validationMessage } from './FormValidation';
```

**To Reproduce**

1. Create a Volto app with an addon.
2. Create the file:

`app/src/addons/my.addon/src/customizations/volto/helpers/FormValidation/FormValidation.jsx`

And place the contents of the corresponding Volto file, replacing relative imports with absolute imports.
3. Create the file:

`app/src/addons/my.addon/src/customizations/volto/helpers/FormValidation/FormValidation.test.js`

And place the contents of the corresponding Volto file, replacing relative imports with absolute imports.
4. Run the command:
```
CI=true yarn test --no-cache
```

**Expected behavior**
The test should run without errors.

**Software (please complete the following information):**

Volto 18.0.0-alpha.42
Plone 6.0.12
plone.restapi 9.7.1
CMF 3.5
Zope 5.10
Python 3.12.3 (main, Apr 27 2024, 19:00:21) [GCC 11.4.0]
PIL 9.5.0 (Pillow)

**Additional context**
I tried creating a `FormValidation.d.ts` file but it didn't work.

**Comment by wesleybl** [comment]
If I use the full path when importing `validationMessage` in [validators.ts](https://github.com/plone/volto/blob/9f8c1e939014381f8077dca85d690a12cfc63f05/packages/volto/src/helpers/FormValidation/validators.ts#L1), the test works. The import would look like this:

```javascript
import { validationMessage } from '@plone/volto/helpers/FormValidation/FormValidation';
```
Is there another way to solve this?

**Comment by ichim-david** [comment]
> If I use the full path when importing `validationMessage` in [validators.ts](https://github.com/plone/volto/blob/9f8c1e939014381f8077dca85d690a12cfc63f05/packages/volto/src/helpers/FormValidation/validators.ts#L1), the test works. The import would look like this:
> 
> ```js
> import { validationMessage } from '@plone/volto/helpers/FormValidation/FormValidation';
> ```
> 
> Is there another way to solve this?

@wesleybl it looks like an omission or we haven't thought of such an interaction. Given that message is imported
full path I suggest we do the same with validationMessage.
Would you be willing to make a pull request with this fix but in the process also check if there are similar issues with the other validation files?

**Comment by wesleybl** [comment]
> Would you be willing to make a pull request with this fix but in the process also check if there are similar issues with the other validation files?

@ichim-david Basically, this can happen in any `.ts` file that imports relatively. Another place where this happens is here:

https://github.com/plone/volto/blob/eb611a8485457171a94409fd097906cc8ae4d16a/packages/volto/src/helpers/Blocks/cloneBlocks.ts#L3-L7

I'm going to make a PR.
