### ISSUE TITLE
Lead image of a News Item does not show up.

### ISSUE THREAD

**Issue by tisto** [plone/volto#625]
1) Go to https://volto.kitconcept.com
2) Login as admin:admin
3) Add News Item with a lead image
4) Go to the News Item view
-> You will not see the lead image
![news item 1](https://user-images.githubusercontent.com/632105/52917643-528ba700-32ee-11e9-9fc4-5b1f0a502577.png)

Network tab shows that the request for the lead image is redirected because of a permission problem:

https://volto.kitconcept.com/api/acl_users/credentials_cookie_auth/require_login?came_from=https%3A//volto.kitconcept.com/api/news-item-1/%40%40images/100476f9-7a8f-4c1d-8c80-5f2286200c35.jpeg

This is a known issue. @sneridagh anything we can do to fix this on short notice?

**Comment by tisto** [comment]
Ok, this is the good old https://github.com/plone/plone.restapi/issues/148

**Comment by uwaiszaki** [comment]
@tisto  . Can we use fetch to get image directly and use that image instead of img tag.

**Comment by sneridagh** [comment]
Yes, closing this then. @tisto Applied the workaround in the demo.
