### ISSUE TITLE
Form Validation: Problem with URL Field and empty Strings

### ISSUE THREAD

**Issue by perret123** [plone/volto#6270]
**Describe the bug**
In the latest Volto Version ("18.0.0-alpha.42") there appears to be a small problem with "empty" field validations for not required URL fields. A default value of an empty string "" gets validated (and fails) even though the field is not required. In alpha.40 this was not the case.

**To Reproduce**

Define some Field with `"widget":"url",` `default=""` and `required=False`

```py
 widget(
        "button_link",
        frontendOptions={
            "widget": "url",
        },
    )
    button_link = TextLine(
        title=_("label_button_link", default="Button link"),
        description=_(
            "help_button_link",
            default="",
        ),
        required=False,
    )
```

When trying to save a new site with such a field, it fails, validating the field and telling me that this isn't valid URL. You can disable the validation by just clicking inside the field, after that saving works.

**Expected behavior**
I expect that a value of an empty "" string is seen as empty and thus not validated for not required fields.

**Software (please complete the following information):**

- Volto Version 18.0.0-alpha.42

**Additional context**
For our case, we could just define *no* default value, so the validation works again. So this ticket is not urgent for us, but I thought it is worth mentioning this, as it is some kind of regression in compare to the previous version. If you guys don't think it is worth a patch, this is fine for us.

**Comment by stevepiercy** [comment]
@perret123 in Volto validation, is `null` or `None` the same as `""`? According to the [specification we use](https://json-schema.org/draft/2020-12/json-schema-validation#name-type), they are different, where `""` is a string type.

Perhaps we need to add a comment to the [Client side form field validation documentation](https://6.docs.plone.org/volto/configuration/validation.html) and [Upgrade Guide](https://6.docs.plone.org/volto/upgrade-guide/index.html#refactor-of-formvalidation-module)?

**Comment by perret123** [comment]
@stevepiercy 
I also don't think `null` is the same as `""` technically - but in the context of a Text-Input-Field, `""` should be considered `empty` and thus not require validation if the field is `required=False`.

I feel that adding this into the docs would just bloat the docs, or is there any use-case where it would be useful to make the differentiation between an empty field and a not filled out field? Then I could see a point in adding it, but right now, I have a hard time thinking of use-cases.

**Comment by stevepiercy** [comment]
What happens if you do `default=None`?

We don't have any examples with `default` in the docs, and I don't see it anywhere in https://github.com/plone/volto/blob/main/packages/volto/src/config/validation.ts or its other related files, so I'm not sure how to use it properly, if at all.
