### ISSUE TITLE
Update cookie* references to current Volto 18.0.0-alpha.43 release

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#6289]
With the release of Volto 18.0.0-alpha.43, we need to review and potentially update or supplement references to `cookiecutter-plone-starter`, `cookiecutter-zope-instance`, and 
[`plone/generator-volto`](https://github.com/search?q=repo%3Aplone%2Fvolto%20plone%2Fgenerator-volto&type=code) with [Cookieplone](https://github.com/plone/cookieplone).

- [ ] https://6.docs.plone.org/volto/contributing/developing-core.html

See also:
- https://github.com/plone/documentation/issues/1706
- https://github.com/plone/documentation/issues/1705
- https://github.com/plone/documentation/pull/1714

**Comment by davisagli** [comment]
Cookieplone is designed for use with Volto 18.

For earlier Volto, it's still recommended to use plone/generator-volto (if you need just a frontend) or cookiecutter-plone-starter (it also uses plone/generator-volto, but generates a full project with frontend and backend).

cookiecutter-zope-instance is still relevant; it is used by both cookiecutter-plone-starter and cookieplone to create a Zope instance to run the backend.

**Comment by stevepiercy** [comment]
@davisagli I updated the description and title of this issue with your feedback. Thank you!

**Comment by stevepiercy** [comment]
There is only one file to manage in this issue. @sneridagh @davisagli should we update it to use Cookieplone or replace its entire content with a landing page with a link or redirect to the new [Create a project with Volto (development or pre-release)](https://plone6--1714.org.readthedocs.build/install/create-project-cookieplone.html) in the PR https://github.com/plone/documentation/pull/1714?

I am in favor of maintaining a single version of a file and adding a landing page and redirect. We've done this with contributing docs for volto, plone.api, and plone.restapi.

**Comment by davisagli** [comment]
@stevepiercy Cookieplone isn't an appropriate tool for developing Volto core. It generates the scaffold for a new repository, but when you're developing Volto you don't need or want a new repository.

Most of this page should remain as is. There are a couple references to cookie* that need minor updates; I'll prepare a PR.
