### ISSUE TITLE
Edit mode `<title>` doesn't describe the name of the page but instead describes the content type

### ISSUE THREAD

**Issue by JeffersonBledsoe** [plone/volto#6308]
If you go into edit mode for a page, the `<title>` will read `Edit Page`. If you edit a news item it will read `Edit News Item`. This doesn't really give you any context about which page you are on. We should probably use something more like `Edit - [MY PAGE TITLE]`

**Comment by davisagli** [comment]
Should it update in real time as you edit the title?

**Comment by JeffersonBledsoe** [comment]
Good question! I can see equal arguments for real-time and on-save. In the case where you start editing the title and change tabs, some users might be confused if the title changes from the page they originally opened, while some could be confused if it wasn't what they were working on.
Title isn't read out via screen reader normally unless you change the page you're on.
