### ISSUE TITLE
Volto 18alpha42 doesn't build with feb'24 created cookiecutter-plone-starter template

### ISSUE THREAD

**Issue by fredvd** [plone/volto#6335]
Debugged with @sneridagh at Salamina Sprint:  the scaffolded razzle.config.js in the project frontend directory missing passing a paths variable to the WebPackConfig.  

Needs to be added to the Volto 18 upgrade guide in a separate paragraph. 

Projectless cookieplone setup doesn't have this problem anymore as most boilerplate has been removed and is pulled from the volto package now directly.

**Comment by fredvd** [comment]
@sneridagh I just created a new project with the cookiecutter-plone-starter, it downloaded the latest versionsk accepted the alpha versions,  it installed 18.0.0.a44 that was just released....

but the razzle.config.js is still placed in the frontend directory without the extra required paths attribute passed to customModifyWebpackConfig.

**Comment by fredvd** [comment]
@sneridagh Can we do something conditional on the volto version in the template here in the generator-volto package to fix the cookiecutter-plone-starter template? 

Or is this webpack public folder contents collecting universal for Volto 17 and 18? 

https://github.com/plone/volto/blob/2e03204e63cee030ca90c03f9e7a056e1c724179/packages/generator-volto/generators/app/templates/razzle.config.js#L25-L39

**Comment by sneridagh** [comment]
@fredvd https://github.com/plone/volto/releases/tag/generator-volto-9.0.0-alpha.18 
The starter should work now.
