### ISSUE TITLE
Disable VSCode's format-on-save feature for markdown

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#6354]
This should help avoid contributors accidentally reformatting (the default formatter makes changes we don't want, like converting to the wrong quotes).

Is the right location at the project root? I don't use VSCode.

See https://github.com/plone/documentation/pull/1713/

## .vscode/settings.json

```json
{
  "[markdown]": {
    "editor.formatOnSave": false
  }
}
```

**Comment by aadityaforwork** [comment]
I am working on this issue in the pull request #6357

**Comment by davisagli** [comment]
Fixed in #6357
