### ISSUE TITLE
Screen jumps when the block chooser pops up

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#6389]
**Describe the bug**
Better a video than 1000 words

https://github.com/user-attachments/assets/4f69b4e7-42c5-42f5-a1f6-cd92a819421a

**To Reproduce**

1. Edit a page with enough blocks (home)
2. Click on + add block button at the bottom of the page
3. The screen jumps to the top

**Expected behavior**
It does not jump

I've pinpointed the error to this PR: https://github.com/plone/volto/pull/5867

I am reverting it right now, we need to find a better way @iRohitSingh

**Comment by JeffersonBledsoe** [comment]
@sneridagh Is it worth closing this and re-opening the original issue if you've reverted?

**Comment by sneridagh** [comment]
Reopened: https://github.com/plone/volto/issues/5866
