### ISSUE TITLE
Introduce context on view component

### ISSUE THREAD

**Issue by ksuess** [plone/volto#6394]
**Is your feature request related to a problem? Please describe.**
Tooltips generated from a glossary should show up only on the first occurrence on a page.

**Describe the solution you'd like**
Volto provides a context of the `View` component for the case that blocks need to know about each other.

Wrap the `RenderedView` component with a context provider.

**Describe alternatives you've considered**
Hints where to hook in the collection of blocks without a change in `packages/volto/src/components/theme/View/View.jsx` are welcome. As an alternative to the wrapper with context provider, I see only the shadowing of the `View` component, which is obviously no option in an add-on.

**Additional context**
https://github.com/rohberg/volto-slate-glossary/pull/8
Per default, glossary terms are searched per slate leaf. Which leads to a tooltip on every match.

**Comment by mauritsvanrees** [comment]
For the record: I want this. :-)

**Comment by ksuess** [comment]
Closing with a solution without the need of a change request in Volto. Details in the discussion of the PR #6395.
