### ISSUE TITLE
Image has no description or it is repeated due to some typo 

### ISSUE THREAD

**Issue by SuyashShukla0007** [plone/volto#6398]
**Describe the bug**

**To Reproduce**

1. Go to 'https://demo.plone.org/content-types'
2. Scroll down to see the repition

**Expected behavior**

**Screenshots**
![Screenshot 2024-10-12 104411](https://github.com/user-attachments/assets/aa2f87fc-a983-472c-9a13-152c145501d0)

**Software (please complete the following information):**

- Volto Version [e.g. 8.5.0]
- Plone Version [e.g. 5.2.2]
- Plone REST API Version [e.g. 7.0.1]

**Additional context**

**Comment by samarsrivastav** [comment]
Hey @SuyashShukla0007  i would love to work on this issue!!

**Comment by davisagli** [comment]
This is not really an issue; there are just 2 different images in that folder. Anyone is welcome to improve the title and description of the images. The demo content is in https://github.com/plone/demo.plone.org
