### ISSUE TITLE
Medium-like image zoom on image tiles

### ISSUE THREAD

**Issue by tisto** [plone/volto#647]
I'd like to have a medium-like (www.medium.com) image zoom for Volto. I already implemented that for Gatsby, so I guess it's not that hard.

https://github.com/kitconcept/gatsby-starter-kitconcept/pull/16

I used this library:

https://rpearce.github.io/react-medium-image-zoom/

Another option might be:

https://desmonding.me/zooming/

@nileshgulia1 @ajayns is that something you could imagine to look into?

**Comment by nileshgulia1** [comment]
closed via #659
