### ISSUE TITLE
UI related

### ISSUE THREAD

**Issue by Avikambir10** [plone/volto#6474]
**Is your feature request related to a problem? Please describe.**
On home Page the text "See All content types" ...... It is not user friendly basically _it should be responsive on hovering_.

**Describe the solution you'd like**
We can make it better looking and beautiful by using **tailwind css** ..
![Screenshot 2024-11-06 192129](https://github.com/user-attachments/assets/9d4ca47a-5287-437d-9f90-57667513c568)

**Comment by mrsingh-rishi** [comment]
can I work on this ?

**Comment by davisagli** [comment]
The styles shown in your screenshot come from volto-light-theme, not volto.
