### ISSUE TITLE
there is no sign up option for new user

### ISSUE THREAD

**Issue by hetbhalani** [plone/volto#6477]
**Is your feature request related to a problem? Please describe.**
yes, new user can't sign up into your website

**Describe the solution you'd like**
add sign up feature into the website

**Describe alternatives you've considered**

**Additional context**

**Comment by aryan7778** [comment]
As per my knowledge you can directly login into the website using credentials provided on the webpage itself. 
@hetbhalani If you are referring to something else please elaborate.

**Comment by Muppasanipraneeth** [comment]
@aryan7778  would you  assign it to me I will do it

**Comment by hetbhalani** [comment]
> As per my knowledge you can directly login into the website using credentials provided on the webpage itself. @hetbhalani If you are referring to something else please elaborate.

if there is a new user who visits for the first time, there is no option to sign up

**Comment by hetbhalani** [comment]
i am new at open source so i didn't know about these things...

**Comment by stevepiercy** [comment]
For anyone considering contributing to Plone, I strongly recommend to read and follow [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do), [Contributing to Plone](https://6.docs.plone.org/contributing/index.html), and [Contributing to Volto](https://6.docs.plone.org/contributing/volto.html). 

Almost all open source software projects have contributing guidelines. Every project is different, and experienced developers know to read them before barging in to a project. This saves both the volunteer project maintainers and the potential contributor a lot of frustration and effort.

**Comment by hetbhalani** [comment]
i'am so sorry about that!

**Comment by hetbhalani** [comment]
there was a misunderstanding about the issue, its resolved...👍
