### ISSUE TITLE
Add Trainings to `tutorials/index.md`

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#6491]
We have a few new tutorials that should be added to https://6.docs.plone.org/volto/tutorials/index.html.

Wait until the latest trainings are deployed to https://training.plone.org/, so you don't have to update it twice.

- [Volto Customization for JavaScript Beginners](https://training.plone.org/volto-customization/index.html) is already present
- [Customizing Volto Light Theme](https://github.com/plone/training/pull/880) is WIP, hopefully merged soon.

**Comment by kmahesh18** [comment]
@stevepiercy I gotta work on this...

**Comment by Deathnote45** [comment]
@stevepiercy hi, can I work on this issue?

**Comment by stevepiercy** [comment]
@kmahesh18 @Deathnote45 see:

> Wait until the latest trainings are deployed to https://training.plone.org/, so you don't have to update it twice.

Meanwhile please read and follow [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do), [Contributing to Plone](https://6.docs.plone.org/contributing/index.html), and [Contributing to Volto](https://6.docs.plone.org/contributing/volto.html).

**Comment by kmahesh18** [comment]
is that pr got blocked?

**Comment by stevepiercy** [comment]
> is that pr got blocked?

No. We work at the speed of unpaid volunteers, which is typical in most open source projects.

**Comment by stevepiercy** [comment]
Closed by #6499
