### ISSUE TITLE
`is-adding-contenttype` bodyclass is dragging the querystring with it

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#6493]
@stevepiercy technically speaking it should replace all values of space with -. It's stupid that js has replace and replaceAll as such if you have more than one space only the first is replaced.
Concerning the search results I did a search and I've noticed the spaces
https://volto.demo.plone.org/search?SearchableText=News%20Page%20With%20Spaces
![search-body-classes](https://github.com/user-attachments/assets/2c32cc29-dd34-401e-8e35-e29620c6a324)

Personally, I don't understand why we would set the searchable text as body classes.
is-adding-contenttype-?searchabletext=newspage with spaces 
but maybe @sneridagh can enlighten me :)

_Originally posted by @ichim-david in https://github.com/plone/volto/issues/6487#issuecomment-2483673374_

**Comment by kaushik7kk** [comment]
Hello @sneridagh ! Is this issue yet to be fixed? If yes, could you provide any info about any specific approaches that you might have decided on? Thanks!

**Comment by stevepiercy** [comment]
@kaushik7kk please read and follow [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do), [Contributing to Plone](https://6.docs.plone.org/contributing/index.html), and [Contributing to Volto](https://6.docs.plone.org/contributing/volto.html).

Also using your super power of observation, you may see that the green "Open" icon reflects its status.

**Comment by kaushik7kk** [comment]
Noted sir @stevepiercy . My apologies. Will keep that in mind going forward. I apologise for the negligence.

**Comment by prreyanshu** [comment]
can i work on this issue ??

**Comment by stevepiercy** [comment]
@prreyanshu please read and follow [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do), [Contributing to Plone](https://6.docs.plone.org/contributing/index.html), and [Contributing to Volto](https://6.docs.plone.org/contributing/volto.html).
