### ISSUE TITLE
Improve search action to support pagination and support for p.restapi list parameters

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#650]
We need to support pagination on the search endpoint in a more explicit manner, otherwise you have to master how Plone queries work and that hurts the non-Plone developers experience.

I would create a configurable default on how many items to return on each page (in order to override p.restapi default) and a explicit parameter to get the queried page (defaulting to the initial page).

I would also improve the list parameters parsing on the action for passing the correct search for lists query to Plone.

We will have to review the way of doing queries on Plone, since for non-Plone developers, it's non-sense to follow Plone's query syntax as modern browsers can handle lists in querystrings with no problems. This is also related to #281.

**Comment by sneridagh** [comment]
In part solved by: #699

**Comment by davisagli** [comment]
Seems like this is more of a restapi issue than a volto issue.
