### ISSUE TITLE
Dominio diferente para subsite plone 

### ISSUE THREAD

**Issue by leandromontenegromachado** [plone/volto#6505]
## Abstract
I need to use a different domain for a subsite within a plone site.

## Motivation
Those responsible for the subsites do not want to use the same address as the plone site. For example:
The Planning Department, which is below the state site, does not want to use the address estado.rs.gov/planejamento. They want to use the address planejamento.rs.gov.br

## Assumptions

The Planning Department, which is below the state site, does not want to use the address estado.rs.gov/planejamento. They want to use the address planejamento.rs.gov.br

**Comment by stevepiercy** [comment]
@leandromontenegromachado this is not a [PLIP](https://6.docs.plone.org/contributing/core/plips.html). It is a support request. Please see https://plone.org/support in general for how to get support.
