### ISSUE TITLE
Improve Dockerfile

### ISSUE THREAD

**Issue by svx** [plone/volto#666]
The current Dockerfile could see (needs) some improvements :).

- Adjust order to optimize chache
- Optimze and secure how and what you copy (pinning)
- Use chained commands
- Missing labels
- Unnecessary huge
- No image pinning
- Security improvements
- The `entrypoint.sh` script is potentially dangerous and could see some improvements according to `bash`, `traps`, exits, etc

**Comment by svx** [comment]
Since we are on it :smile: 
The `.dockerignore` file could be improved, too.
This would resolve in faster, `pulls`, `pushes`, `builds` and better security.

More background info, "easy" explained: https://codefresh.io/docker-tutorial/not-ignore-dockerignore/

**Comment by sneridagh** [comment]
@svx right now it's only used for the tests to run, but we need for sure some improvements and tidy them (there is another in the api folder, that can be used as base too but very old and unmaintained). We also need one for Volto alone, probably suitable for local dev, another for a full Plone-Volto stack (I guess that with compose) with 5.1/5.2, another for Guillotina-Volto, and another for the reference_backend-Volto. So we definitely need help on the whole Docker story! We could use your expertise here for sure! :)

**Comment by sneridagh** [comment]
Removed the docker container for tests some time ago
