### ISSUE TITLE
Show the current version of Volto in the control panel view

### ISSUE THREAD

**Issue by fredvd** [plone/volto#671]
It would be handy to see somewhere on the volto.kitconcept.com demo site which version of Volto is running. The main page mentions the plone.restapi version but not the Volto release.

Another place some version information could be added is the site setup page below the control panel listings. (Like default Plone iirc)

For end-user/editor testing and bug reporting this would be nice as well, so people can test if things have been fixed in a certain version or use the demo site to test and report issues.

**Comment by tisto** [comment]
What we usually do for our client projects is deploying a version.txt on the server or display the version somewhere on the site. We should add the Volto version to the control panel.

**Comment by tisto** [comment]
@nileshgulia1 could you look into this?

**Comment by nileshgulia1** [comment]
@tisto Currently plone shows this below control panels. 
![Screenshot_2019-03-14 Plone site](https://user-images.githubusercontent.com/22280901/54333731-a073a080-4649-11e9-91dc-569f1999fe5c.png)

I will look into adding something like this.
