### ISSUE TITLE
Volto is in a non-working state when user keeps the browser open > 24h

### ISSUE THREAD

**Issue by tisto** [plone/volto#674]
Steps to reproduce:

1) Fire up Volto and log in as a user
2) Keep the browser open for > 24h (and put the computer in sleep mode)
3) Revisit Volto in the browser

-> The user will see the toolbar open but only with the three dots and the user icon. 
-> Everything else is gone.

![Welcome to Volto  (3)](https://user-images.githubusercontent.com/632105/54344264-bdf03c80-4640-11e9-9c53-e3efc29e8e10.png)

-> Browser console shows network calls with an unauthorized (HTTP 401) response:

<img width="1279" alt="Screenshot 2019-03-14 at 09 54 21" src="https://user-images.githubusercontent.com/632105/54344239-afa22080-4640-11e9-9160-f41a6b79bdce.png">

**Comment by sneridagh** [comment]
Fixed in: https://github.com/plone/volto/pull/1109

We need to test it, I'm hesitating if include it already in an alpha release.
