### ISSUE TITLE
UX: Mix up trash can and close icon (was: Volto editor first time use:  closing image popup menu remove image)

### ISSUE THREAD

**Issue by fredvd** [plone/volto#683]
The title of the issue is misleading, but it was exactly what I was thinking the first few times I accidentally deleted an image from an image row:  the X button doesn't close the popup menu, it discards the image. I really had to put effort in to 'unlearn' the urge to close the popup menu.

![close_-_discard_-_delete](https://user-images.githubusercontent.com/394784/54441247-a26a5c00-473c-11e9-9c43-34d60a9e36a0.png)

The whole row can be removed using a trashcan icon, which makes more sense. The X is also used as a discard in the save/close menu on the left (in desktop mode), which is also rather destructive if you mistake it for closing the menu, but at least it's not a popup window and the choice is a bit clearer: save or discard.

I'd really suggest using another symbol that hints to 'replace' and then switch back to the first add url/image popup.  You'd only want to delete the image to insert another one, but you can replace it when the new image/url is offered.

**Comment by tisto** [comment]
Same here. I always mix up the trash can and the close symbol.

**Comment by sneridagh** [comment]
Moved to new sidebar in Volto 4.
