### ISSUE TITLE
volto editor: item properties is a toggle button in the menu, next to action buttons

### ISSUE THREAD

**Issue by fredvd** [plone/volto#685]
I only found out by playing around that the 'middle' button to edit the properties of a page or content item is a toggle button. 

![edit-properties_toggle](https://user-images.githubusercontent.com/394784/54442332-bf079380-473e-11e9-88e7-7c6837790956.png)

I edited the properties and couldn't figure out how to go back to the edit page, I thought the only choices were now are 'save' and 'discard'. Mixing toggle and action buttons is confusing for me. 

In wysiwyg editor toolbars the 'toggle' buttons are logically grouped and separated by a divider from other 'action' or buttons doing popups.

**Comment by tisto** [comment]
We could use the back arrow. Though, that would mean an additional click for the users. I kind of prefer the current way of doing things. Maybe @albertcasado wants to weight in.

**Comment by sneridagh** [comment]
Replaced in Volto 4 with the new sidebar
