### ISSUE TITLE
Inverted typing in tile (was: Volto editor keyboard nav: Shift-tab between text tiles mixes up text insertion point)

### ISSUE THREAD

**Issue by fredvd** [plone/volto#687]
Mac OS X, Google Chrome 72.  When I press SHIFT-tab while editing the description, I jump back to the Title tile, then I can move the cursor to the right, but any characters I type will be inserted at the beginning of the title. Also the focus (grey rectangle) stays around the description.

Forward tabbing from the title into the description or a normal text tile doesn't stick the insertion point to the first character.

Grr. can't upload a small mp4 video. Will do with screenshot then :-S

![shift-tab_navigation_between_tiles](https://user-images.githubusercontent.com/394784/54445046-486d9480-4744-11e9-9349-f2f5fc4b6a62.png)

**Comment by sneridagh** [comment]
This is known and related to #187.

**Comment by tisto** [comment]
Closing as duplicate.

**Comment by sneridagh** [comment]
No longer happening, in part because the description block is not present, but the issue do not happen in either draftJS or slate.
