### ISSUE TITLE
Create a "Toast" component that overrides the "Messages" one.

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#701]
Toasts have better UX and are not intrusive. See:
https://zpl.io/aR1lrEN

or a variant on the top:
https://zpl.io/VYKlwAn

**Comment by nileshgulia1** [comment]
@sneridagh Should we completely remove/Override the Messages component to use Toast instead?
Or use some libraries like `react-toastify`?

**Comment by sneridagh** [comment]
@nileshgulia1 I've been working in this:
https://github.com/plone/volto/pull/753

It's WIP though. Hoping to be able to finish it in the sprint, you can take it over too, if you wish. Mostly it's left the CSS and replace all the messages to toasts. I would leave the messages as they are, just in case, but switch to Toasts everywhere.
