### ISSUE TITLE
Changing workflow state does not propagate to the current object

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#71]
The content store does not get the change that some actions do, like the change workflow action. We should make sure that this happens.

@robgietema what will be the best approach to do this? From the reducer? Triggering another action?

**Comment by nileshgulia1** [comment]
Hey @sneridagh , can you help me, i am getting problem in running the project locally.

**Comment by sneridagh** [comment]
This is fixed in 4.0.0.alpha.0
