### ISSUE TITLE
Exception when adding new comment

### ISSUE THREAD

**Issue by rodfersou** [plone/volto#716]
After try to add a comment for a `Document`, got this exception:
![image](https://user-images.githubusercontent.com/131209/56911639-c16e4480-6a83-11e9-95af-e977083d48bb.png)

But the comment was added without problems after the exception

**Comment by tisto** [comment]
@rodfersou can you please provide a full report on how to reproduce the issue?

**Comment by tisto** [comment]
@rodfersou the error trace seems unrelated to the comments. Can you please provide steps to reproduce? Will close this issue for now until there is more information.

**Comment by rodfersou** [comment]
@tisto maybe it is just me getting used with Volto (restart backend issue..)
but I'll try to look again soon 🙂
