### ISSUE TITLE
UX: Add Tiles Menu

### ISSUE THREAD

**Issue by tisto** [plone/volto#740]
With a growing number of tile icons it becomes harder and harder to differentiate the different tile icons. Each new tile also requires a dedicated icon. Not every team has a UX/UI designer that can create custom tile icons. Maybe we consider about moving to a Gutenberg-like approach with a popup that offers more space for showing the available tiles with a title and a description.

**Comment by tisto** [comment]
@sneridagh @albertcasado this is also something I would like us to discuss during the upcoming sprints. We have clients asking for 30-40 different tiles for projects. With that amount of tiles it will be impossible to differentiate them by icons (and being able to provide those icons). Maybe looking at Gutenberg can give us a few ideas:

![https   testgutenberg com](https://user-images.githubusercontent.com/632105/59406601-130e2c80-8daf-11e9-8cbb-72df3034a716.png)
![https   testgutenberg com (1)](https://user-images.githubusercontent.com/632105/59406597-11446900-8daf-11e9-9297-668b8ee58abb.png)

**Comment by sneridagh** [comment]
Present in volto 4
