### ISSUE TITLE
Table Block

### ISSUE THREAD

**Issue by tisto** [plone/volto#741]
Allow editors to add pre-defined tables in Volto. Not a full-fledged table editing solution but basic functionality like:

- add a table
- add a column to an existing table
- add a row to an existing table

Customizations could be integrator work.

**Comment by nileshgulia1** [comment]
@tisto Do we already have a mockup for it, or just simple semantic `<Table/>` will do?

**Comment by nileshgulia1** [comment]
Okay, we have it already :)

https://app.zeplin.io/project/5c76b54e0e8c876239917ea3/screen/5cbee0647b72a0b757dd5f7b

**Comment by tisto** [comment]
@nileshgulia1 FYI: that is not a mock of the table tile. Don't worry too much about the style yet. A very simple HTML table with the default styling is sufficient. Would you feel comfortable working on the add row/column functionality? I think this is the core of this feature.

**Comment by tisto** [comment]
@sneridagh @albertcasado this is not as high-priority as the collection/listing UX. Though, it would be nice to have a rough outline about how the user adds rows/columns (tile icons?) and removes them.

**Comment by nileshgulia1** [comment]
@sneridagh Can we somehow embed an `<Editor />` onto the tables to achieve the add rows/columns functionality, Like the ones we have with tiles?

**Comment by sneridagh** [comment]
@nileshgulia1 yes, that would be the idea. However, I'm concerned about the performance of such a component that might have X x Y editors instantiated at the same time... Maybe you can do some performance tests.

I've already talked with Albert, we will have mocks after the sprint, but the initial idea is to use an UX very similar to the "Apple Pages" table embed widget.

**Comment by sneridagh** [comment]
Done.
