### ISSUE TITLE
Effective date index is not set properly in Volto

### ISSUE THREAD

**Issue by tisto** [plone/volto#761]
Steps to reproduce:

1) login as admin
2) create a new page
3) publish the new page
4) check effective date of the new page
-> the effective date (both EffectiveDate and effective) indexes are set to None or the default value 1970

What happens in standard Plone is that if you publish an item the effective date index is set to now. We have to make sure this work similarly in Volto.

**Comment by Gomez** [comment]
Fixed with https://github.com/plone/plone.restapi/pull/761
