### ISSUE TITLE
Volto Editor: Allow new line within a text tile with SHIFT+RETURN

### ISSUE THREAD

**Issue by tisto** [plone/volto#762]
When the editor hits return she currently creates a new tile, which is fine as the default behavior. We have use-cases where the editor needs to be able to specifically add a new line (e.g. a quote tile that requires explicit CR, a grid tile where one of the text tiles used needs multiple lines, migrated content where a single text tile contains multiple paragraphs).

Lots of other editors use the keyboard shortcut SHIFT+RETURN to create a new line within the tile instead of creating a new tile. We should adopt that behavior and allow power-users to add new lines within a tile.

**Comment by sneridagh** [comment]
Done.
