### ISSUE TITLE
Deployment Docs (was: Installing Volto with zeocluster and multiple clients?)

### ISSUE THREAD

**Issue by TBCcrash2064** [plone/volto#764]
Hi,
how can I install volto with multiple clients and zeocluster?

**Comment by tisto** [comment]
@TBCcrash2064 to avoid CORS issues we usually deploy both frontend and backend under the same domain.

The frontend is deployed via NGINX under e.g. www.plone.org (Port 80 -> 8080 Plone instance, varnish, haproxy, etc).

The backend is deployed via NGINX under the same domain with an "/api" suffix, e.g. www.plone.org/api (Port 80 -> 3000 Volto default).

We run Volto via pm2 and also Plone (switching from supervisor).

Let me know if you need more info, we are happy to share our prod config. We will also document this during the Beethoven sprint in Bonn next week.

**Comment by Gomez** [comment]
More info: https://community.plone.org/t/volto-deployment-options/7458/8

**Comment by sneridagh** [comment]
https://training.plone.org/5/plone-deployment/index.html

https://6.dev-docs.plone.org/volto/deploying/index.html
