### ISSUE TITLE
Adding Google Tag Manager Snipper to <Head> and <Body>  tage

### ISSUE THREAD

**Issue by medicareamaze** [plone/volto#818]
Is there a way to add Google Tag manager  code to <Head> and <body> ?

**Comment by tisto** [comment]
@medicareamaze right now you have to customize the Volto component that defines the React helmet config. See kitconcept.seo for an example:

https://github.com/kitconcept/kitconcept.seo

Though, we are already thinking about a plugin architecture that allows plugins and integrators to inject code into the header.

**Comment by agitator** [comment]
fyi tagmanager is not only about the snippet in the header but also about being able to add data layers  which are additional snippets within the body.

For example https://developers.google.com/tag-manager/enhanced-ecommerce

We did an implementation for "old style" Plone in https://github.com/bluedynamics/bda.plone.gtm ;-)

**Comment by agitator** [comment]
... overread the second line of the title ... it's still too early 🙈

**Comment by medicareamaze** [comment]
> @medicareamaze right now you have to customize the Volto component that defines the React helmet config. See kitconcept.seo for an example:
> 
> https://github.com/kitconcept/kitconcept.seo#add-to-volto-site
> 
> Though, we are already thinking about a plugin architecture that allows plugins and integrators to inject code into the header.

Thanks Tisto! How and where in Volto/Plone, do I add the actual Javascript tag? Like the following?
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-11843XXXX-X"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-118437943-1');
</script>
```

**Comment by medicareamaze** [comment]
> ... overread the second line of the title ... it's still too early 🙈

Thanks Agitator. Right Now I'm Just trying to get my site Volto Report back site visits to Google Analytics. In Site is driven by a bot and I am managing the event logging withing the app - https://www.medicareamaze.com

**Comment by medicareamaze** [comment]
> > @medicareamaze right now you have to customize the Volto component that defines the React helmet config. See kitconcept.seo for an example:
> > https://github.com/kitconcept/kitconcept.seo#add-to-volto-site
> > Though, we are already thinking about a plugin architecture that allows plugins and integrators to inject code into the header.
> 
> Thanks @tisto How and where in Volto/Plone, do I add the actual Javascript tag? Like the following?
> 
> ```
> 
> <script async src="https://www.googletagmanager.com/gtag/js?id=UA-11843XXXX-X"></script>
> <script>
>   window.dataLayer = window.dataLayer || [];
>   function gtag(){dataLayer.push(arguments);}
>   gtag('js', new Date());
> 
>   gtag('config', 'UA-11843XXXX');
> </script>
> ```

I figured this out. I site visits are now hitting Google analytics and  I also see the Meta Description Appear in the <Head>. Thanks! For those of you who have a problem with this - This ishow I did ita nd it works

`<Helmet>
      {/* other stuff... */}

      {/* Global site tag (gtag.js) - Google Analytics  */}
      <script async src=`https://www.googletagmanager.com/gtag/js?id=${googleAnalyticsId}`></script>
      <script>
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', ${googleAnalyticsId});
        `}
      </script>
</Helmet>`
