### ISSUE TITLE
Custom View for front-page?

### ISSUE THREAD

**Issue by TBCcrash2064** [plone/volto#830]
is it possible to set a custom view for the front-page/home?
I've created a custom view from the training (https://training.plone.org/5/volto/custom-views.html) and tried to set this as default view for the front-page. I can assign this to any sub-page in my volto installation but not for the front-page. I also tried to set the view via ZMI (/Plone/front-page/manage_propertiesForm) but nothing happens. Next step I tried was to add a new page, assign the new view and set it with "Select a content item as default" (/select_default_view).. but I still get the "Welcome to Volto!"...

**Comment by tisto** [comment]
@TBCcrash2064 there is a PLIP to make the Plone Site Root a Dexterity object with a custom view. This will come with Plone 6. Though, this does not help you today. 

What we do as a workaround so far is that we create a "Homepage" Dexterity content type that we put in the portal root. Then we register a Volto view on that type that shows up by default on the  portal root.

The code for this is in our kitconcept.voltodemo package. Here is how we set up the homepage content object in the portal root:

https://github.com/kitconcept/kitconcept.voltodemo/blob/75111a19dd874d95b6f985cdad1f088fbeff001c/src/kitconcept/voltodemo/setuphandlers.py

**Comment by sneridagh** [comment]
The PLIP has been merged some time ago, and available in Plone 6. For Plone 5 there has been a workaround since some years ago.
