### ISSUE TITLE
About Semantic UI

### ISSUE THREAD

**Issue by pnicolli** [plone/volto#841]
I am studying volto and semantic ui more deeply in these days, since we are actively considering to (and very likely to) use volto for our next Plone projects.

While considering some issues (mainly with using other css imported from other libraries) I stumbled upon the fact that semantic-ui is basically not developed anymore (while the react bindings still are).
https://github.com/Semantic-Org/Semantic-UI/issues/6109
https://github.com/Semantic-Org/Semantic-UI/issues/6858

Is this something that we should be worried about? What do you think?

**Comment by prudho** [comment]
Hello, you should take a look at [Fomantic-UI](https://fomantic-ui.com/), the community driven Semantic's fork. It's compatible with Semantic, has a lot of bug fixes and new functionalities, and an active development and community 😉

**Comment by tisto** [comment]
I think we discussed this so I will close the issue. We stick to semantic UI for now and allow using other libs.
