### ISSUE TITLE
Workflow state indicator always shows private state (even though the state is public)

### ISSUE THREAD

**Issue by steffenri** [plone/volto#844]
Plone 5.2 / Python 3 / Volto master branch.

Steps to reproduce:

1) Checkout Volto master branch latest
2) Create a new page 
3) publish the page
-> expected behavior: page is public, state indicator shows green color
-> actual behavior: page is public, but state indicator doesnt change (stays red) ; that doesnt change after page reload either
![bugreport](https://user-images.githubusercontent.com/54619639/63865077-437a6580-c9b1-11e9-8d66-45e7cbb25484.png)

**Comment by sneridagh** [comment]
This was fixed some time ago
