### ISSUE TITLE
Sidebar should show save/cancel on control panels

### ISSUE THREAD

**Issue by tisto** [plone/volto#850]
Volto master branch.

1) Login as admin
2) Go to any control panel
-> save/cancel will show up at the bottom of the page. for consistency those controls should be in the sidebar.

![Navigation](https://user-images.githubusercontent.com/632105/64050413-3e1b4780-cb78-11e9-982a-daafcbfc4998.png)

**Comment by avoinea** [comment]
Fixed by #1347
