### ISSUE TITLE
Example sites missing

### ISSUE THREAD

**Issue by miohtama** [plone/volto#853]
The README does not mention any publicly accessible Volto sites. I would be good to have examples of production deployments.

**Comment by nileshgulia1** [comment]
@miohtama I know of https://www.zeelandia.de

**Comment by tisto** [comment]
@miohtama good point. Has been on my todo list for quite a while now. Will add it.

**Comment by tisto** [comment]
@miohtama fixed: https://github.com/plone/volto/pull/936
