### ISSUE TITLE
If I add a document with id containing 'edit' or 'add' something goes bad

### ISSUE THREAD

**Issue by nzambello** [plone/volto#870]
Hi guys,
I discovered that having an object with ID containing 'add' or 'edit', something goes wrong and the page goes broken.
I think the problem is about routes or views and the handling of the strings like '/edit' while detecting current view.
There are some RegExp and some strings, I think we'll just need a singular way to do so to handle these cases correctly (adding '^' at the end of the regexp or confront strings differently).

<img width="1031" alt="Schermata 2019-09-19 alle 18 28 04" src="https://user-images.githubusercontent.com/21101435/65262745-4af1e200-db0b-11e9-960d-27290f7b4557.png">

**Comment by nzambello** [comment]
\cc @tisto @sneridagh @robgietema

**Comment by tisto** [comment]
@nzambello I guess this was kind of expected. I am not a React Router expert but I guess this might be hard to avoid if we allow to name content with "reserved words". The only idea I have to fix this is to prevent users to use those IDs. We could come up with a list or reserved IDs and then prevent the usage either in Volto or even plone.restapi.

**Comment by nzambello** [comment]
IMHO the deal would be to protect "reserved words" like "add" or "edit", but we cannot have a blocking behaviour with a title like "editorial", "editing" or "addicting".
I don't know well how this is implemented between Volto and plone.restapi, but we should handle this in some way, shouldn't we?

I only know that in Volto there are some lists as constants handling routes (but out of routing machinery).

**Comment by nzambello** [comment]
Seems to be solved right now. I'm not able to reproduce this now.

**Comment by nzambello** [comment]
I confirm this is resolved.
I guess in e0e77e7976f82d2c13b443ae6020e77233bfd4cc

**Comment by nzambello** [comment]
@plone/volto-team this is resolved as it doesn't break, but we still have issues

https://volto.kitconcept.com/editing-with-volto-is-a-bless (if not already reset)
<img width="1308" alt="Schermata 2021-09-14 alle 14 31 20" src="https://user-images.githubusercontent.com/21101435/133258063-c08a9b92-f65f-45ce-afdf-9c7f5d9974a4.png">

**Comment by nzambello** [comment]
The problem is in `isCmsUI`:
https://github.com/plone/volto/blob/288cf2f3cdc6ce410a58777b8477b2cd5f8b8de8/src/helpers/Url/Url.js#L124

**Comment by nzambello** [comment]
I added some tests on this: https://regexr.com/65joa
Replacing in `nonContentRoutes` add/edit routes with `/.*\/add$/` etc I get it right (indeed, tests in regexr are passing).
It works with the tests but when I navigate it goes to the route.
Furthermore, if I use my test on "add", then going to "/edit" will get me editing the parent.

**Comment by nzambello** [comment]
I also tried to change only `isCmsUi` (leaving nonContentRoutes as it is, to have other things working) like:

```js
export const isCmsUi = memoize((currentPathname) => {
  const { settings } = config;
  const fullPath = currentPathname.replace(/\?.*$/, '');
  // WARNING:
  // not working properly for paths like /editors or similar
  // because the regexp test does not take that into account
  // https://github.com/plone/volto/issues/870
  return settings.nonContentRoutes.reduce((acc, route) => {
    const parsedRoute = route.test ? route : new RegExp(`.*/${route}$`);
    const isCmsRoute = parsedRoute.test(`/${fullPath}`);
    console.log(`isCmsRoute: ${isCmsRoute} - ${parsedRoute} - ${fullPath}`);
    return acc || isCmsRoute;
  }, false);
});
```
but it doesn't change, it works even worse.
