### ISSUE TITLE
Folder contents form action buttons are still old style.

### ISSUE THREAD

**Issue by sneridagh** [plone/volto#873]

**Comment by avimishra18** [comment]
Hi @sneridagh, is this issue still open? If yes can you elaborate more, I wanted to fix it.

**Comment by sneridagh** [comment]
The "good ones" are the ones in the Form actions. I made a PR recently fixing them in the modals:

https://github.com/plone/volto/pull/3127/files#diff-f8d7da2fa5c3e731812e84a768fc5f8553f4672539679155f79a48b9c2bcaf4bR297

If you want to make a pass and assess that all are correct, it would be great. They should have the same shape than in the Modal.

**Comment by davisagli** [comment]
The ones in folder contents look right to me.
