### ISSUE TITLE
Link content type

### ISSUE THREAD

**Issue by tisto** [plone/volto#877]
The basic Link content type is implemented as well as the basic functionality:

1) Editors can see the link content object
2) Anonymous users are directly redirected to the link target

This works fine. Though, there are a few things that do not work yet:

1) Add an inline link to the body text of a page and link to an existing link object
-> An anonymous user will be redirected to the link content object, not directly to the link target

Other use cases are described here:

https://github.com/plone/volto/pull/976

@cekk is this something you could image to work on during the sprint? We also just found out that this kind of functionality does not work for file content object either.

**Comment by cekk** [comment]
Yep, i could work on it during the sprint (if we discuss before on how to implement my doubts on #976).

Actually i have also an another important (for us) task where i'd like to work on (see volto channel on slack), so we need to decide the priority

**Comment by davisagli** [comment]
This basically works now.
