### ISSUE TITLE
Controlpanel titles are not translated

### ISSUE THREAD

**Issue by jackahl** [plone/volto#878]
The titles of most elements are not translated to the set language because only English is set as available language in the backend.
![Screenshot_2019-09-20 Plone site](https://user-images.githubusercontent.com/44289551/65325752-f94f6300-dbaf-11e9-9e42-e92330751946.png)
If you set it manually, the titles for "moderate comments" and "users and groups" are not translated.
![Screenshot_2019-09-20 Seiteneinstellungen](https://user-images.githubusercontent.com/44289551/65325986-a6c27680-dbb0-11e9-94ed-72228bd2f2da.png)
They are both from the first get request. 
![controlpanelRequest](https://user-images.githubusercontent.com/44289551/65326161-1a648380-dbb1-11e9-9860-c13fe8810a01.png)

**Comment by sneridagh** [comment]
Now they are:

<img width="973" alt="image" src="https://user-images.githubusercontent.com/486927/204151708-3224217b-c61a-4e84-8535-113691696813.png">
