### ISSUE TITLE
unable to uncheck checkboxes 

### ISSUE THREAD

**Issue by steffenri** [plone/volto#888]
in volto if you try to uncheck checkboxes, its not working
its only not working graphically because if you reload the page the box is unchecked

go to https://volto.kitconcept.dev
create a new page
enable versioning
save
edit and try to disable versioning
-> issue occurs
-> the other way around its working so checking works just fine

**Comment by steffenri** [comment]
seems like this problem occurs on every checkbox on the site

**Comment by sneridagh** [comment]
@steffenri Thanks! This one was a hidden huge one! Fixed, ready to merge when green.

/cc @tisto
