### ISSUE TITLE
Upgrade to React Router 4

### ISSUE THREAD

**Issue by robgietema** [plone/volto#9]
Waiting on compatibly with `redux-connect` (https://github.com/makeomatic/redux-connect/issues/107).

**Comment by nileshgulia1** [comment]
Here is a list of the things we’ll need to do to migrate: 

- Change `react-router` to `react-router-dom`
-    Use Specialized Router Components
-   Add `<Switch>` to List of Routes
-    Add `exact` to Routes
-   Replace Nested Routes By Routes In Child Components
-    Replace `<IndexRoute>` by a regular `<Route>`
-    Replace the `params` props by `match.params`
-    Parse The Query String ourselves.
-    Replace `onEnter` with `componentWillMount`? Don't know about it though.
-    Redo Redux Integration

**Comment by robgietema** [comment]
Fixed in master.
