### ISSUE TITLE
Sidebar should not keep the collapsed state (was:Sidebar does not open in local builds)

### ISSUE THREAD

**Issue by jackahl** [plone/volto#903]
Tested on Ubuntu 18.04.3 LTS.
Steps to reproduce:
1. create a local build of volto
2. Open it on localhost:3000
3. Open edit view.
Behaviour: Metadata sidebar does not open. The sidebar-container keeps the collapsed class.

**Comment by MAX-786** [comment]
I have an approach to fix this but before, I would like to ask a question first :
Do we need `sidebar` always expanded whenever the `Edit` component is mounted?

Then, we can simply do this by setting `sidebar_expanded` to true in Cookies whenever the `Edit` component is Unmounted.

**Comment by jackahl** [comment]
Hey @MAX-786, I am quite certain this has been resolved by now. At least I could not reproduce it. Thank you for your proposed solution anyways!

I will close the issue.
