### ISSUE TITLE
Rename Tiles to Blocks

### ISSUE THREAD

**Issue by tisto** [plone/volto#907]
This was something we discussed in the Volto team for quite a while already and we finally came to the conclusion that we should rename tiles to blocks. Tiles make lots of sense in a Mosaic or a fixed grid system. Though, the Volto editor is more flexible than that and oriented more towards responsive, single-column designs. Therefore we think block is more appropriate.

Other pro arguments are that Wordpress is using blocks in Gutenberg, the German translation for Tiles ("Kachel") is misleading, and we differentiate what we are doing from Mosaic.

We should do the renaming ASAP since this will be a breaking change.

@sneridagh something for Volto 4?

**Comment by tisto** [comment]
@sneridagh this is done, right? Or is there anything left to do?

**Comment by sneridagh** [comment]
It's completely done.
