### ISSUE TITLE
Referential integrity in blocks

### ISSUE THREAD

**Issue by jaroel** [plone/volto#934]
ie. a teaser block references a page.
Do we want to prevent deleting the target page, remove the link from the blocks, or something else?

**Comment by tisto** [comment]
@jaroel first step is to add resolveUID support for blocks in plone.restapi, then we can build the Volto part.

**Comment by jaroel** [comment]
Refs https://github.com/plone/plone.restapi/pull/820

**Comment by sneridagh** [comment]
Working for smart fields (url and href) using p.restapi resolve uid transform since 7.0.0a6, and can be enabled for others.
