### ISSUE TITLE
Turn Volto into a PWA

### ISSUE THREAD

**Issue by tisto** [plone/volto#937]
- Add the basic manifest.json and neccessary boilerplate
- Add an application shell for better loading experience

**Comment by iFlameing** [comment]
@tisto How I can update the snapshot test because it is failing. Due that I am unable to make the pull request. I tried `jest --updateSnapshot -u` but it is not updating.

**Comment by tisto** [comment]
Duplicate of https://github.com/plone/volto/issues/68. Closing.
