### ISSUE TITLE
Registration does not work

### ISSUE THREAD

**Issue by tisto** [plone/volto#941]
We currently show a registration link on Volto which does not work. The frontend does not take into account the settings of the Plone backend regarding registration.

The quick fix would be to just remove or comment out the registration link.

The real solution is to check the Plone settings regarding registration via the plone.restapi and then show the registration link conditionally.

Though, then registration still won't work since the backend does not know about the frontend URL. See https://github.com/plone/volto/issues/588 for reference.

**Comment by frapell** [comment]
@tisto @sneridagh I have commited my improvements from the sprint to the self-registration-improvements branch, it is still missing tests, and it still missing the actual registration when the person submits the form, but the form will respect the site config.

It needs the https://github.com/plone/plone.restapi/tree/globals-endpoint branch which includes the `@globals` endpoint

**Comment by nileshgulia1** [comment]
@frapell Are you still working on this issue?

**Comment by frapell** [comment]
@nileshgulia1 I have not made any progress on this nor the restapi branch, feel free to continue with it if you wish to...

**Comment by KIET7UKE** [comment]
Is this issue still open? I wanna work on this @frapell

**Comment by frapell** [comment]
@KIET7UKE I haven't made any progress on this, nor I know if it is still an issue... @sneridagh ?

**Comment by KIET7UKE** [comment]
@frapell umm okay

**Comment by sneridagh** [comment]
@KIET7UKE Since you want to work on this, maybe you can investigate and tell us which is the current state? TBH, after 4 years it is hard to tell. That's why it's still open. It would help a lot to know.

**Comment by KIET7UKE** [comment]
@sneridagh Yes, I'm interested to work on this. Let's see what I can do. I'll ask for your help when I got stuck. Thanks

**Comment by tkimnguyen** [comment]
seriously? 😞 is there a simpler solution?
