### ISSUE TITLE
Searchable Blocks

### ISSUE THREAD

**Issue by ksuess** [plone/volto#959]
I assume including block text, converted to plain text, in SearchableText index would do this?

**Comment by mck9** [comment]
This would be great, as it will make the plone search more usable

**Comment by luca-bellenghi** [comment]
@tisto 
do you already have someone working on it? Otherwise I need this functionality in a project and I can work on it

**Comment by tisto** [comment]
@luca-bellenghi not yet. I started to look into it briefly. It would be great if you would want to work on it. 

We basically need to write a block-indexer that looks into the "blocks" field and extracts the text from the draftjs text field and indexes that in Plone.

**Comment by tisto** [comment]
@luca-bellenghi if you want to discuss this via slack or a hangout just ping me. I am available in the next days and happy to help!

**Comment by luca-bellenghi** [comment]
@tisto thank's.
Hope we'll talk about it as soon as I can work on it. I will also discuss it with @pnicolli, i work with him and the implementation will be done in one of our projects
