### ISSUE TITLE
Favor React Testing Library tests instead of snapshot tests in core (was: Adopt React Testing Library?)

### ISSUE THREAD

**Issue by tisto** [plone/volto#972]
@pnicolli adopted React Testing Library (https://github.com/testing-library/react-testing-library) in his lazy loading PR (https://github.com/plone/volto/pull/967). I also looked into it and it seems a good choice. Opinions @sneridagh @robgietema?

**Comment by pnicolli** [comment]
For the sake of completeness, I also added this with the same PR: https://github.com/testing-library/cypress-testing-library

**Comment by pnicolli** [comment]
cypress-testing-library has been removed for incompatibilities. The react part is there for now. It's probably worth mentioning that it's now featured by default inside the new CRA templates, which is probably a good sign.

**Comment by sneridagh** [comment]
Already using it in several tests in Volto itself, it should be the choice for new tests and prioritise them instead of snapshot tests.

**Comment by tisto** [comment]
Approved.
