### ISSUE TITLE
Translations broken on RequestPasswordReset.jsx

### ISSUE THREAD

**Issue by fredvd** [plone/volto#979]
After backend functionality to change the frontend domain URL in password reset mails is in place I want to improve the password reset form in the frontend.  

First issue is that the translations are not working, see screenshot. Comparing code with Login.jsx, I see that RequestPasswordReset js now using the schema parameter to the semantic ui Form compontent, but more elaborate forms like Login.jsx are more tailor made with specific Form elements also from semantic ui.

The translations are working fine on Login.jsx in the same session, when I compare both jsx files/forms I cannot see any difference or obvious errors. I tried locally to remodel the RequestPasswordReset.js after Login.jsx, but then also translations are broken. 

What I want to fix in RequestPasswordReset is 
* we now request for an e-mail id, but the backend only supports users at the moment afacs.
* If no user is found th form fails silently. Add a toast popup. Yes this can provide 'user id' polling, but this now also possible over restapi and in default Plone. 

Questions
----------

* What is wrong currently in RequestPasswordReset.jsx? 
* Is Login.jsx setup of the form the 'better' preferred way to be more verbose? 

<img width="453" alt="Login" src="https://user-images.githubusercontent.com/394784/67949892-e4231680-fbe8-11e9-8842-f2d525b1262a.png">
<img width="703" alt="Password_reset" src="https://user-images.githubusercontent.com/394784/67949893-e4bbad00-fbe8-11e9-8403-b026ca9ef3c9.png">

**Comment by davisagli** [comment]
These days the translations work and the form asks for login name rather than email. We shouldn't provide feedback about whether the user exists for security reasons.
