### ISSUE TITLE
Failed to install @plone/volto, try again

### ISSUE THREAD

**Issue by mck9** [plone/volto#980]
Installation fails with:

```
marek@MONO ~/dev/kobra> create-volto-app my2-volto-app
/home/marek/.nvm/versions/node/v12.13.0/lib/node_modules/@plone/create-volto-app/volto-starter-kit

Creating my2-volto-app...

> Success! Created files for "my2-volto-app" Volto app

  Installing npm modules:
    @plone/volto

> Error! Failed to install @plone/volto, try again.
undefined
```

marek@MONO ~/dev/kobra> yarn -v
1.19.1
marek@MONO ~/dev/kobra> node -v
v12.13.0
marek@MONO ~/dev/kobra> npm -v
6.12.0

**Comment by fredvd** [comment]
Node 12 has as far as I know only been added recently in the latest volto 4 alpha's. 

You could try to install create-volto-app with Node 10, or install the alpha version, which will scaffold a volto 4 alpha app

**Comment by mck9** [comment]
I upgraded the app according to https://docs.voltocms.com/upgrade-guide/
that worked. The section in the README could be fixed, as the prerequisites (https://github.com/plone/volto#prerequisites) don't match the install section (https://github.com/plone/volto#create-volto-app)

btw. what is the way to install a fresh volto 4.0.0 app without using create-volto-app?
