### ISSUE TITLE
Display "All content" shows empty page

### ISSUE THREAD

**Issue by mck9** [plone/volto#984]
volto 3.2.7 / Plone 5.1.6
volto 4.0.0-alpha.10 / Plone 5.2

**Comment by yasharthrai** [comment]
Please assign me this issue.

**Comment by stevepiercy** [comment]
@yasharthrai we do not assign issues. See https://6.docs.plone.org/volto/developer-guidelines/contributing.html and https://6.docs.plone.org/contributing/index.html for guidance. Thank you! This comment and yours well be deleted.

**Comment by davisagli** [comment]
Volto doesn't support the "all content" view, and it comes with the content types that use it disabled.
