### ISSUE TITLE
"Related Items" Widget (was: List of "Related Items" shows UUIDs)

### ISSUE THREAD

**Issue by mck9** [plone/volto#985]
volto 3.2.7 / Plone 5.1.6
volto 4.0.0-alpha.10 / Plone 5.2

This is somehow unusable without the paths and titles

![Bildschirmfoto_2019-11-01_13-47-27](https://user-images.githubusercontent.com/375845/68025950-77724f80-fcae-11e9-9472-110c232ef6f7.png)

**Comment by sneridagh** [comment]
Fixed in #1209.
