### ISSUE TITLE
"Allow discussion" shows empty dropdown / no input possible

### ISSUE THREAD

**Issue by mck9** [plone/volto#988]
It should show "No value/Yes/No". 

No input is possible, instead on every keypress in the "Allow discussion" field a request is made to the server:
http://localhost:8080/Plone/@vocabularies/http://localhost:8080/Plone/@sources/allow_discussion?b_start=0&q=yesddeffewf

volto 3.2.7
Plone 5.1.6

**Comment by tisto** [comment]
@mck9 would it be possible for you to test with Volto master branch or the latest releases Volto 4.0.0-* and Plone 5.2? We fixed a lot of issues in the last months and refactored quite a bit.

It would be great if bug reports always contain "steps to reproduce" and a screenshot.

**Comment by mck9** [comment]
Yes, I can do that.

**Comment by mck9** [comment]
The dropdown is empty in volto 4.0.0-alpha.10:

![Bildschirmfoto_2019-11-01_13-38-58](https://user-images.githubusercontent.com/375845/68025567-72f96700-fcad-11e9-93f6-170c0bcaabdb.png)

It should have the same entries like in Plone backend:

![Bildschirmfoto_2019-11-01_13-41-00](https://user-images.githubusercontent.com/375845/68025601-8c9aae80-fcad-11e9-8e70-903df17341a5.png)

**Comment by tisto** [comment]
@mck9 thank you!

**Comment by sneridagh** [comment]
@mck9 I can see it working in a31. Take into account that the value is overriden by the global Plone site setting. This is done by p.restapi, so if you set it to "yes", and the global is "no", then it will be reset to "no".

**Comment by sneridagh** [comment]
<img width="466" alt="image" src="https://user-images.githubusercontent.com/486927/73124531-d3dac780-3f9c-11ea-819d-9f6dba7b6a9a.png">

**Comment by tisto** [comment]
"No value" should actually be called "inherit" (from the global discussion setting). Though, we never really fixed that in standard Plone.
