### ISSUE TITLE
User should not be able to delete title block

### ISSUE THREAD

**Issue by mck9** [plone/volto#989]
If a user deletes the title or description block from an item there is no way to recreate them.

volto 3.2.7

**Comment by tisto** [comment]
The description block has been removed in Volto 4 (current master). The title block can indeed be deleted which shouldn't be the case.

**Comment by mck9** [comment]
This looks ok to me on 4.0.0-alpha.10:
![Bildschirmfoto_2019-11-01_13-35-50](https://user-images.githubusercontent.com/375845/68025212-91129780-fcac-11e9-940f-3c66cc9c585a.png)

**Comment by pnicolli** [comment]
I can confirm this is no longer the case in the current master and latest alpha releases, I think it can be closed @tisto
