### ISSUE TITLE
Toolbar-more popup hides dropdown entries

### ISSUE THREAD

**Issue by mck9** [plone/volto#990]
The entries of the view dropdown are not fully shown, as the toolbar menu popup hides them:

![Bildschirmfoto_2019-11-01_13-58-29](https://user-images.githubusercontent.com/375845/68026486-2ebb9600-fcb0-11e9-96fb-8d547283c9df.png)

volto 4.0.0-alpha.10 / Plone 5.2

**Comment by sneridagh** [comment]
I fixed that some weeks ago.
