### ISSUE TITLE
Home page is empty / can't edit content of homepage

### ISSUE THREAD

**Issue by mck9** [plone/volto#991]
volto 4.0.0-alpha.10 / Plone 5.2

The edit button is missing on home page. Also the home page is empty.
The Plone site was created on a new system without customizations. 

![Bildschirmfoto_2019-11-01_14-19-29](https://user-images.githubusercontent.com/375845/68027507-df2a9980-fcb2-11e9-8119-669cfc895ef6.png)

**Comment by sneridagh** [comment]
@mck9 I recomend you to use the Plone 5.2 build that is provided with Volto (`api` folder). You can build it by `make build-backend`. There are some customizations (like the one that enables blocks in the root) that are only available if a small hack is enabled on the site root. This hack is now provided by the package `kitconcept.voltodemo`, but in the future Plone 6 root object will be based on dexterity, so it will have the `Blocks` behavior on it.

You can add and install the `kitconcept.voltodemo` package in your own buildout if you want to.

I will document what `kitconcept.voltodemo` does more thoroughly to explain this points.

**Comment by sneridagh** [comment]
@mck9 I forgot to mention that the `api` folder with the buildout that I mentioned is on Volto repo. It would have been easier for you if such `api` folder was provided in the project that `create-volto-app` is creating?

**Comment by mck9** [comment]
@sneridagh Thanks! 
I used the `api` buildout. Since I want to use multiple languages, I added p.a.m and created the two language folders (dexterity types!) and enabled `blocks` on them. Now I get the edit button, but can't add content to the page, as there are no input fields available. Still wondering what goes wrong.

btw: The menu links are also somehow broken. is p.a.m supported?

**Comment by sneridagh** [comment]
@mck9 not in full yet. So no language switcher, nor language menu tools. It's high on the wish list though.

You can't edit anything because the language root folders are created programatically and the contain no default blocks (as opposed when you create them via Volto). Agreed that there should be a way to create at least the title and first text block if blocks are enabled on the content but no default blocks on them.

**Comment by sneridagh** [comment]
Created #993

**Comment by mck9** [comment]
@sneridagh Great, that helped. I copied the blocks of a newly created page. Now I can edit the homepage.

**Comment by mck9** [comment]
@sneridagh I close this as #993 is a more general solution.
