### ISSUE TITLE
[Documentation] Pastanaga icons and related Pastanaga icon font (was: Brand icons: how to use)

### ISSUE THREAD

**Issue by giuliaghisini** [plone/volto#999]
I'm not able to use brand icons on site. Only if I set @icon:'default' in theme.config, but this changes all icons in pastanaga editor.
In themes/default/elements/icon.variables I found some variable that defines where brand icons are located. I tried to override this variables in my site but nothing... 
How can i use brand-icons on my site?

**Comment by sneridagh** [comment]
Sorry for the late reply, probably you've already figured it out, writing this for documentation purposes.
In the beginning, before the Pastanaga icon system existed, a font from the Pastanaga icons was built

https://github.com/plone/pastanaga-theme/tree/master/src/fonts

and added in Volto (former Plone-React). But not all icons in SemanticUI were updated see:

https://github.com/plone/volto/blob/master/theme/themes/pastanaga/elements/icon.overrides

So, might be that some icons are not updated (the bin code), so you need to look into the original built font and related CSS, then update the CSS in Volto (make a PR) (or in your project).

However, the use of the font is discouraged, and will be deprecated from Volto eventually.

Changing the title of the issue for document this properly.
